ezsystems/ezplatform-admin-ui

src/bundle/Resources/public/js/scripts/admin.location.view.js

Renamed Sub Items List module prop name from startingLocationId to parentLocationId

Renamed Sub Items List module prop name from startingLocationId to parentLocationId

---

src/bundle/Resources/public/js/scripts/fieldType/eztext.js

**Jira ticket:** https://jira.ez.no/browse/EZP-27890

EZP-27890: As a Editor, I want to edit a Text Block field type with the new UI guidelines

---

.php_cs
bootstrap.php
composer.json
phpunit.xml
src/bundle/Controller/LocationController.php
src/lib/EventListener/SystemInfoTabGroupListener.php
src/lib/Form/Data/Content/Location/ContentLocationRemoveData.php
src/lib/Form/Data/Trash/TrashEmptyData.php
src/lib/Form/Data/Trash/TrashItemRestoreData.php
src/lib/Form/Data/UiFormData.php
src/lib/Form/Type/Policy/PolicyChoiceType.php
src/lib/Service/ContentTypeService.php
src/lib/Tests/EventListener/SystemInfoTabGroupListenerTest.php
src/lib/UI/Config/Aggregator.php

> https://jira.ez.no/browse/EZP-27938

EZP-27938: Add missing ez-support-tools dependency, tests and perform cleanup in SystemInfoTabGroupListener

---

.php_cs
bootstrap.php
composer.json
phpunit.xml
src/bundle/Controller/ContentTypeController.php
src/bundle/Controller/LocationController.php
src/bundle/ParamConverter/ContentTypeDraftParamConverter.php
src/bundle/ParamConverter/ContentTypeGroupParamConverter.php
src/bundle/ParamConverter/ContentTypeParamConverter.php
src/bundle/ParamConverter/LanguageParamConverter.php
src/bundle/ParamConverter/PolicyParamConverter.php
src/bundle/ParamConverter/RoleAssignmentParamConverter.php
src/bundle/ParamConverter/RoleParamConverter.php
src/bundle/Resources/config/services.yml
src/lib/EventListener/RequestListener.php
src/lib/Form/Data/Content/Location/ContentLocationRemoveData.php
src/lib/Form/Data/Trash/TrashEmptyData.php
src/lib/Form/Data/Trash/TrashItemRestoreData.php
src/lib/Form/Data/UiFormData.php
src/lib/Form/Type/Policy/PolicyChoiceType.php
src/lib/Form/Type/Section/SectionChoiceType.php
src/lib/Form/Type/Trash/TrashItemChoiceType.php
src/lib/Service/ContentTypeService.php
src/lib/Service/PathService.php
src/lib/Tests/EventListener/RequestListenerTest.php
src/lib/UI/Config/Aggregator.php
src/lib/UI/Value/Content/VersionInfo.php

> https://jira.ez.no/browse/EZP-27938

EZP-27938: Add tests and perform cleanup in RequestListener

---

src/bundle/Resources/public/js/scripts/admin.role_assignment.add.js
src/bundle/Resources/public/js/scripts/admin.section.list.js
src/bundle/Resources/public/js/scripts/admin.trash.list.js
src/bundle/Resources/public/js/scripts/udw/browse.js
src/bundle/Resources/public/js/scripts/udw/copy.js
src/bundle/Resources/public/js/scripts/udw/locations.tab.js
src/bundle/Resources/public/js/scripts/udw/move.js
src/bundle/Resources/public/js/scripts/udw/swap.js

https://jira.ez.no/browse/EZP-28129
Requires: https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/13

EZP-28129: UDW is not loading Media location

---

src/bundle/Resources/public/js/scripts/admin.section.list.js
src/bundle/Resources/public/js/scripts/admin.trash.list.js
src/bundle/Resources/public/js/scripts/udw/copy.js
src/bundle/Resources/public/js/scripts/udw/locations.tab.js
src/bundle/Resources/public/js/scripts/udw/move.js
src/bundle/Resources/public/js/scripts/udw/swap.js
src/bundle/Resources/views/admin/trash/list.html.twig
src/bundle/Resources/views/content/locationview.html.twig
src/bundle/Resources/views/content/modal_location_trash.html.twig
src/bundle/Resources/views/content/tab/locations/panel_swap.html.twig
src/bundle/Resources/views/content/tab/locations/tab.html.twig
src/bundle/Resources/views/content/tab/translations.html.twig
src/bundle/Resources/views/content/tab/versions/tab.html.twig

> JIRA: https://jira.ez.no/browse/EZP-28191
After PR #27 all forms became broken due to removed form action in `FormFactory`. This PR adds `action` HTML attribute to all affected forms.

EZP-28191: UI actions form are not working due to missing `action` attribute

---

src/lib/Form/Type/Trash/TrashItemChoiceType.php

**JIRA**: https://jira.ez.no/browse/EZP-28163

EZP-28163: 500 Internal Server Error on admin/trash/list

---

src/lib/Form/Factory/FormFactory.php

JIRA: https://jira.ez.no/browse/EZP-28193

EZP-28193: Remove translation without selection causes internal sever error

---

src/bundle/Controller/VersionController.php
src/lib/Form/Factory/FormFactory.php
src/lib/Tab/LocationView/VersionsTab.php

> JIRA: https://jira.ez.no/browse/EZP-28194
This PR fixes Remove version button in Location View / Version tab.

EZP-28194: Cannot remove Archived or Draft version

---

src/bundle/Controller/RoleAssignmentController.php
src/lib/Form/Factory/FormFactory.php

JIRA: https://jira.ez.no/browse/EZP-28195

EZP-28195: Cannot open Roles list because of Internal Server Error

---

src/bundle/Controller/LanguageController.php

JIRA: https://jira.ez.no/browse/EZP-28197

EZP-28197: Can't edit language because of Internal Server Error

---

src/bundle/Resources/views/admin/section/list.html.twig
src/bundle/Resources/views/admin/section/view.html.twig

JIRA: https://jira.ez.no/browse/EZP-28198

EZP-28198: Can't assign content to section

---

.travis.yml
src/lib/Form/DataMapper/SectionUpdateMapper.php
src/lib/Tests/Form/DataMapper/SelectionUpdateMapperTest.php

**TODO**:
- ~Execute behat tests~ *// follow up for later so we can move forward with enabling unit tests*

[Travis] Created config executing unit tests

---

src/bundle/Resources/public/js/scripts/admin.contenttype.selection.js
src/bundle/Resources/views/admin/content_type/create.html.twig
src/bundle/Resources/views/admin/content_type/edit.html.twig

**Jira ticket:** https://jira.ez.no/browse/EZP-28206

EZP-28206: As an Administrator, I want to add options to the ezselection FieldType in ContentType

---

src/bundle/Controller/ContentViewController.php
src/bundle/Controller/LocationController.php
src/bundle/Resources/config/routing.yml
src/bundle/Resources/public/scss/_tables.scss
src/bundle/Resources/translations/content_type.en.xliff
src/bundle/Resources/translations/location.en.xliff
src/bundle/Resources/views/content/tab/details.html.twig
src/bundle/Resources/views/parts/table_header.html.twig
src/lib/Form/Data/Location/LocationUpdateData.php
src/lib/Form/Factory/FormFactory.php
src/lib/Form/Type/ContentType/SortFieldChoiceType.php
src/lib/Form/Type/ContentType/SortOrderChoiceType.php
src/lib/Form/Type/Location/LocationUpdateType.php
src/lib/Tab/LocationView/DetailsTab.php

> https://jira.ez.no/browse/EZP-27974
For a specific location, the editor can define the sort order of the sub-items.

EZP-27974: Default sort parameter for sub-items table in the Detail content view tab

---

src/bundle/Resources/translations/locationview.en.xliff
src/bundle/Resources/views/content/tab/details.html.twig

> https://jira.ez.no/browse/EZP-27974
Added missing translation.

EZP-27974: Sort parameter for sub-items table in the Detail content view tab.

---

src/bundle/Resources/config/services/service_aliases.yml
src/bundle/Resources/translations/locationview.en.xliff
src/bundle/Resources/views/content/tab/details.html.twig
src/lib/Tab/LocationView/DetailsTab.php
src/lib/UI/Dataset/DatasetFactory.php
src/lib/UI/Dataset/ObjectStatesDataset.php
src/lib/UI/Value/ObjectState/ObjectState.php
src/lib/UI/Value/ValueFactory.php

JIRA: https://jira.ez.no/browse/EZP-28217
This adds a tab to view the content object state

EZP-28217: Add Object State tab to location view

---

src/bundle/Resources/translations/locationview.en.xliff

EZP-27974: Default sort parameter for sub-items table in the Detail content view tab.

---

src/bundle/Resources/translations/content.en.xliff
src/bundle/Resources/translations/content_type.en.xliff
src/bundle/Resources/translations/dashboard.en.xliff
src/bundle/Resources/translations/ezrepoforms_role.en.xliff
src/bundle/Resources/translations/fieldview.en.xliff
src/bundle/Resources/translations/forms.en.xliff
src/bundle/Resources/translations/language.en.xliff
src/bundle/Resources/translations/location.en.xliff
src/bundle/Resources/translations/locationview.en.xliff
src/bundle/Resources/translations/menu.en.xliff
src/bundle/Resources/translations/messages.en.xliff
src/bundle/Resources/translations/role.en.xliff
src/bundle/Resources/translations/search.en.xliff
src/bundle/Resources/translations/section.en.xliff
src/bundle/Resources/translations/systeminfo.en.xliff
src/bundle/Resources/translations/translation.en.xliff
src/bundle/Resources/translations/trash.en.xliff
src/bundle/Resources/translations/version.en.xliff

Deleted reference ad timestamp.

fix: Update translations

---

src/bundle/Resources/public/js/scripts/fieldType/ezdate.js
src/bundle/Resources/public/scss/_general.scss
src/bundle/Resources/views/content/form_fields.html.twig
src/bundle/Resources/views/fieldtypes/ezdate.html.twig

> JIRA: https://jira.ez.no/browse/EZP-27902
> Requires: https://github.com/ezsystems/repository-forms/pull/170
**THINGS DONE:**

EZP-27902: As an Editor, I want to edit a Date field type with the new UI guidelines

---

src/bundle/Controller/ContentController.php
src/bundle/Resources/config/routing.yml
src/bundle/Resources/public/js/scripts/admin.location.set.js
src/bundle/Resources/public/js/scripts/admin.location.update.js
src/bundle/Resources/translations/content.en.xliff
src/bundle/Resources/views/content/locationview.html.twig
src/bundle/Resources/views/content/tab/locations/tab.html.twig
src/lib/Form/Data/Content/Location/ContentMainLocationUpdateData.php
src/lib/Form/DataMapper/ContentMainLocationUpdateMapper.php
src/lib/Form/Factory/FormFactory.php
src/lib/Form/Type/Content/Location/ContentMainLocationUpdateType.php
src/lib/Tab/LocationView/LocationsTab.php

> https://jira.ez.no/browse/EZP-27974
The main location will be displayed at the top of the list and rest of the locations underneath the main.

EZP-28094: Set the main location of a content item

---

src/bundle/EventListener/RequestAttributesListener.php

Fix for deleted `locationId` in listener. There is still a bug with route generated in breadcrumb.

EZP-27974: Fix for deleted `locationId` in listener.

---

src/bundle/Resources/public/js/scripts/fieldType/ezdate.js
src/bundle/Resources/public/js/scripts/fieldType/ezdatetime.js
src/bundle/Resources/public/js/scripts/fieldType/eztime.js

https://jira.ez.no/browse/EZP-28244
There's still a know issue with the eztime fieldtype. It's a backend issue.

EZP-28244: Difference between time/date in edit and preview mode

---

src/bundle/Resources/views/admin/role_assignment/add.html.twig
src/bundle/Resources/views/admin/search/list.html.twig
src/bundle/Resources/views/admin/search/search.html.twig
src/bundle/Resources/views/admin/section/list.html.twig
src/bundle/Resources/views/admin/section/view.html.twig
src/bundle/Resources/views/admin/trash/list.html.twig
src/bundle/Resources/views/content/locationview.html.twig
src/bundle/Resources/views/dashboard/dashboard.html.twig
src/bundle/Resources/views/layout.html.twig

**Jira ticket:** https://jira.ez.no/browse/EZP-28291
The container for UDW was missing in content edit.
Note: Open UDW should be tested in entire application on this branch

EZP-28291: Cannot embed content in richText

---

src/bundle/Resources/public/js/scripts/fieldType/ezcountry.js

https://jira.ez.no/browse/EZP-27900

EZP-27900: As an Editor, I want to edit a Country field type

---

src/bundle/Controller/LocationController.php
src/bundle/Controller/TranslationController.php
src/bundle/Controller/VersionController.php

| Tickets       | https://jira.ez.no/browse/EZP-28324
After perform any action on content tab, user should be redirected to proper tab.

EZP-27052: Added redirect to current tab after performing actions

---

src/bundle/Controller/SearchController.php
src/bundle/Resources/config/ezplatform_default_settings.yml
src/bundle/Resources/config/services/controllers.yml
src/bundle/Resources/views/admin/search/search.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-28331
Improved search pagination based on PagerfantaBundle.

EZP-28331: Improved search pagination based on PagerfantaBundle

---

src/bundle/Controller/LocationController.php
src/bundle/Controller/TranslationController.php
src/bundle/Controller/VersionController.php
src/lib/Tab/LocationView/LocationsTab.php
src/lib/Tab/LocationView/TranslationsTab.php
src/lib/Tab/LocationView/VersionsTab.php

| Tickets       | https://jira.ez.no/browse/EZP-28324
| Tests pass?   |no
After perform unsuccessful action on content tab, user should be redirected to proper tab.

EZP-27052: Added redirect to current tab after performing actions 

---

src/bundle/Resources/public/js/scripts/admin.user.menu.js
src/bundle/Resources/views/layout.html.twig

Fix undefined fos and addEventListener on undefined

---

src/bundle/DependencyInjection/Compiler/ComponentPass.php
src/bundle/EzPlatformAdminUiBundle.php
src/bundle/Resources/config/services.yml
src/bundle/Resources/config/services/components.yml
src/bundle/Resources/config/services/dashboard.yml
src/bundle/Resources/config/services/tabs.yml
src/bundle/Resources/views/component/link.html.twig
src/bundle/Resources/views/component/script.html.twig
src/bundle/Resources/views/dashboard/block/all.html.twig
src/bundle/Resources/views/dashboard/block/me.html.twig
src/bundle/Resources/views/dashboard/dashboard.html.twig
src/bundle/Resources/views/layout.html.twig
src/bundle/Templating/Twig/ComponentExtension.php
src/lib/Component/LinkComponent.php
src/lib/Component/Registry.php
src/lib/Component/Renderable.php
src/lib/Component/ScriptComponent.php
src/lib/Component/TwigComponent.php

- Extensibility: https://github.com/ezsystems/ezplatform-admin-ui/pull/94/commits/5e0f2071c18d8d90ebecca8928a09d3c81c24ad4
- Dashboard: https://github.com/ezsystems/ezplatform-admin-ui/pull/94/commits/2201b1333d98b218518d33ad2380667d33e9f06f
- CSS & JS: https://github.com/ezsystems/ezplatform-admin-ui/pull/94/commits/818a5bae8403b6f30bcdafaa576b3ad50a2fbd02

EZP-28344: Twig template extensibility via Components (Dashboard, CSS & JS)

---

src/bundle/Resources/config/routing.yml
src/bundle/Resources/config/services.yml
src/bundle/Resources/public/js/scripts/admin.location.change_language.js
src/bundle/Resources/translations/locationview.en.xliff
src/bundle/Resources/translations/messages.en.xliff
src/bundle/Resources/translations/section.en.xliff
src/bundle/Resources/views/content/locationview.html.twig
src/bundle/Resources/views/content/tab/content.html.twig
src/lib/EventListener/RequestAttributesListener.php
src/lib/Tab/LocationView/ContentTab.php

| Tickets       | https://jira.ez.no/browse/EZP-27533
This PR add language switcher for the available translations of the content item.

EZP-27533: Switch to another translation in the Main content view tab

---

src/bundle/Resources/public/js/scripts/fieldType/base/base-file-field.js

| Tickets       | https://jira.ez.no/browse/EZP-28372

EZP-28372: Cannot preview content when editing

---

src/bundle/Resources/public/js/scripts/fieldType/ezdate.js
src/bundle/Resources/public/js/scripts/fieldType/ezdatetime.js
src/bundle/Resources/public/js/scripts/fieldType/eztime.js

| Tickets       | https://jira.ez.no/browse/EZP-28252

EZP-28252: As an Editor, I want to see validation error when required, but empty, field loses focus

---

src/bundle/Resources/config/services/components.yml
src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
src/bundle/Resources/views/content/content_edit/content_create.html.twig
src/bundle/Resources/views/content/content_edit/content_edit.html.twig
src/bundle/Resources/views/content/content_edit/content_edit_base.html.twig
src/bundle/Resources/views/parts/menu/sidebar_base.html.twig
src/bundle/Resources/views/parts/menu/top_menu_base.html.twig
src/lib/Component/TwigComponent.php

| Tickets       | https://jira.ez.no/browse/EZP-28348

EZP-28348: Allow extra template rendering for menu items (top & side)

---

src/bundle/Resources/config/services/menu.yml
src/bundle/Resources/public/scss/_card.scss
src/bundle/Resources/translations/forms.en.xliff
src/bundle/Resources/translations/menu.en.xliff
src/bundle/Resources/translations/role.en.xliff
src/bundle/Resources/views/admin/policy/add.html.twig
src/bundle/Resources/views/admin/policy/base.html.twig
src/bundle/Resources/views/admin/policy/edit.html.twig
src/lib/Menu/Admin/Role/PolicyCreateRightSidebarBuilder.php
src/lib/Menu/Admin/Role/PolicyEditRightSidebarBuilder.php
src/lib/Menu/Event/ConfigureMenuEvent.php

| Tickets       | https://jira.ez.no/browse/EZP-28420
EZP-28420: Design improvements for Policy create and edit actions in Admin Panel

EZP-28420: Design improvements for Policy create and edit actions in Admin Panel

---

src/bundle/Resources/views/layout.html.twig

Remove duplicate msg `invalidFileSize`

---

src/bundle/Resources/public/scss/_user-menu.scss
src/bundle/Resources/views/parts/menu/user_menu.html.twig
src/bundle/Resources/views/parts/navigation.html.twig

| Tickets       | https://jira.ez.no/browse/EZEE-1776

EZEE-1776: As a v2 editor I want to be notified and view notifications in my user menu

---

src/lib/Tab/Dashboard/MyDraftsTab.php

| Tickets       | https://jira.ez.no/browse/EZP-28482

EZP-28482: Wrong order of My Drafts items on Dashboard

---

src/bundle/Resources/config/services.yml
src/bundle/Resources/views/content/content_edit/content_edit.html.twig
src/lib/RepositoryForms/View/ViewParametersListener.php

| Tickets       | https://jira.ez.no/browse/EZP-28421

EZP-28421: Cannot edit draft which isn't attached to tree

---

src/bundle/Resources/public/scss/_buttons.scss

| Tickets       | [EZP-27730](https://jira.ez.no/browse/EZP-27730)
- Updated buttons' opacity based on design specifications.

EZP-27730: Buttons improvement opacity updated

---

src/bundle/Resources/public/scss/_mixins.scss

| Tickets       | https://jira.ez.no/browse/EZP-28356

EZP-28356: Improved Visibility switcher style

---

src/bundle/Controller/RoleAssignmentController.php
src/bundle/Resources/config/services/menu.yml
src/bundle/Resources/public/scss/_card.scss
src/bundle/Resources/translations/menu.en.xliff
src/bundle/Resources/views/admin/role_assignment/base.html.twig
src/bundle/Resources/views/admin/role_assignment/create.html.twig
src/lib/Menu/Admin/Role/RoleAssignmentCreateRightSidebarBuilder.php
src/lib/Menu/Event/ConfigureMenuEvent.php

| Tickets       | https://jira.ez.no/browse/EZP-28450
Design improvements for Role Assignment create action

EZP-28451: Design improvements for Role Assignment create action

---

src/bundle/Resources/config/services/menu.yml
src/bundle/Resources/public/scss/_tables.scss
src/bundle/Resources/translations/language.en.xliff
src/bundle/Resources/translations/menu.en.xliff
src/bundle/Resources/views/admin/language/base.html.twig
src/bundle/Resources/views/admin/language/create.html.twig
src/bundle/Resources/views/admin/language/delete_confirmation_modal.html.twig
src/bundle/Resources/views/admin/language/edit.html.twig
src/bundle/Resources/views/admin/language/view.html.twig
src/lib/Menu/Admin/Language/LanguageCreateRightSidebarBuilder.php
src/lib/Menu/Admin/Language/LanguageEditRightSidebarBuilder.php
src/lib/Menu/Event/ConfigureMenuEvent.php

| Tickets       | https://jira.ez.no/browse/EZP-28465
Design improvements for Languages create, edit and detail views

EZP-28465: Design improvements for Languages create, edit and detail views

---

src/bundle/Controller/LanguageController.php
src/bundle/Resources/config/routing.yml
src/bundle/Resources/public/js/scripts/admin.language.list.js
src/bundle/Resources/translations/forms.en.xliff
src/bundle/Resources/translations/language.en.xliff
src/bundle/Resources/views/admin/language/list.html.twig
src/lib/Form/Data/Language/LanguagesDeleteData.php
src/lib/Form/Factory/FormFactory.php
src/lib/Form/Type/Language/LanguagesDeleteType.php

| Tickets       | https://jira.ez.no/browse/EZP-28462
Design improvements for Languages list in Admin Panel

EZP-28462: Design improvements for Languages list

---

.eslintrc.json
src/bundle/Resources/public/js/scripts/fieldType/ezobjectrelationlist.js
src/bundle/Resources/public/scss/_icons.scss
src/bundle/Resources/public/scss/ezplatform.scss
src/bundle/Resources/public/scss/fieldType/_ezobjectrelationlist.scss
src/bundle/Resources/translations/ezrepoforms_content.en.xliff
src/bundle/Resources/views/content/form_fields.html.twig
src/bundle/Resources/views/fieldtypes/ezobjectrelation.html.twig
src/bundle/Resources/views/fieldtypes/ezobjectrelationlist.html.twig
src/bundle/Resources/views/fieldtypes/relation_base.html.twig
src/bundle/Resources/views/layout.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-28250
**Sub tasks:**
**Requires:**
- https://github.com/ezsystems/ezpublish-kernel/pull/2178
- https://github.com/ezsystems/repository-forms/pull/183
- https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/26

EZP-28250: As an editor, I want to edit a RelationList field type

---

src/bundle/Resources/public/scss/ezplatform-bootstrap.scss

| Tickets       | https://jira.ez.no/browse/EZP-28494

EZP-28494: Cannot compile css with hardcopy

---

src/bundle/Resources/public/js/scripts/admin.contenttype.relation.default.location.js
src/bundle/Resources/public/js/scripts/fieldType/ezobjectrelationlist.js
src/bundle/Resources/views/admin/content_type/edit.html.twig
src/bundle/Resources/views/fieldtypes/relation_base.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-28497
**Requires:**
- https://github.com/ezsystems/repository-forms/pull/186
**Bugfixes for:**

EZP-28497: RelationList field type issues

---

src/bundle/Resources/views/admin/role_assignment/create.html.twig
src/lib/Menu/Admin/Role/RoleAssignmentCreateRightSidebarBuilder.php

on assignment page
| Tickets       | https://jira.ez.no/browse/EZP-28484

EZP-28484: redirect user to role view after discarding changes

---

src/bundle/Resources/public/js/scripts/fieldType/ezauthor.js
src/bundle/Resources/public/js/scripts/fieldType/ezemail.js
src/bundle/Resources/public/js/scripts/fieldType/ezurl.js
src/bundle/Resources/public/scss/fieldType/_base-field.scss

| Tickets       | https://jira.ez.no/browse/EZP-28178

EZP-28178: Validation alert for non-required fields

---

src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js
src/bundle/Resources/views/layout.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-28415

EZP-28415: [MapLocation] No validation of value range for longitude and latitude fields

---

src/bundle/Resources/public/scss/ezplatform-bootstrap.scss

| Tickets       | https://jira.ez.no/browse/EZP-28511
https://github.com/ezsystems/ezplatform/pull/237

EZP-28511: Cannot use assetic:watch

---

src/bundle/Resources/public/js/scripts/fieldType/ezmedia.js
src/bundle/Resources/public/scss/fieldType/_base-field.scss
src/bundle/Resources/public/scss/fieldType/_ezmedia.scss

| Tickets       | https://jira.ez.no/browse/EZP-28320

EZP-28320: Inconsistency in validation of empty media field

---

src/bundle/Controller/SectionController.php
src/bundle/Resources/config/routing.yml
src/bundle/Resources/public/js/scripts/admin.section.view.js
src/bundle/Resources/views/admin/section/list.html.twig
src/bundle/Resources/views/admin/section/view.html.twig
src/lib/Form/Data/Section/SectionsDeleteData.php
src/lib/Form/Factory/FormFactory.php
src/lib/Form/Type/Section/SectionsDeleteType.php

| Tickets       | https://jira.ez.no/browse/EZP-28509
Design improvements for Section list

EZP-28509: Design improvements for Section list

---

src/lib/Menu/Admin/Role/PolicyCreateRightSidebarBuilder.php
src/lib/Menu/Admin/Role/RoleAssignmentCreateRightSidebarBuilder.php
src/lib/Menu/Admin/Role/RoleCreateRightSidebarBuilder.php
src/lib/Menu/SectionCreateRightSidebarBuilder.php

| Tickets       | https://jira.ez.no/browse/EZP-28516
Fix icons for create button in right menu

EZP-28516: Fix icons for create button in right menu

---

src/bundle/Resources/public/js/scripts/fieldType/ezrichtext.js
src/bundle/Resources/public/scss/fieldType/_ezrichtext.scss

| Tickets       | https://jira.ez.no/browse/EZP-28518

EZP-28518: Richtext field is not validated at all

---

src/bundle/Controller/ContentTypeController.php
src/bundle/Resources/config/routing.yml
src/bundle/Resources/views/admin/content_type/list.html.twig
src/lib/Form/Data/ContentType/ContentTypesDeleteData.php
src/lib/Form/Factory/FormFactory.php
src/lib/Form/Type/ContentType/ContentTypesDeleteType.php

| Tickets       | https://jira.ez.no/browse/EZP-28540
Design improvements for Content Type list

EZP-28540: Design improvements for Content Type list

---

src/bundle/Controller/ContentController.php

| Tickets       | https://jira.ez.no/browse/EZP-28558

EZP-28558: Editing draft should not show notification about creating draft

---

src/bundle/Resources/config/services/menu.yml
src/bundle/Resources/public/scss/_buttons.scss
src/bundle/Resources/public/scss/_card.scss
src/bundle/Resources/public/scss/_icons.scss
src/bundle/Resources/translations/content_type.en.xliff
src/bundle/Resources/translations/menu.en.xliff
src/bundle/Resources/translations/section.en.xliff
src/bundle/Resources/views/admin/base.html.twig
src/bundle/Resources/views/admin/content_type/create.html.twig
src/bundle/Resources/views/admin/content_type/edit.html.twig
src/bundle/Resources/views/admin/content_type/view.html.twig
src/lib/Menu/Admin/ContentType/ContentTypeCreateRightSidebarBuilder.php
src/lib/Menu/Admin/ContentType/ContentTypeEditRightSidebarBuilder.php
src/lib/Menu/Event/ConfigureMenuEvent.php

| Tickets       | https://jira.ez.no/browse/EZP-28545
Design improvements for Content Type create, edit and view

EZP-28545: Design improvements for Content Type create and edit

---

src/lib/Tests/Form/DataTransformer/LocationsTransformerTest.php

Unit tests were broken in #170

Fixes unit tests (LocationsTransformer Test)

---

src/bundle/Controller/LinkManagerController.php
src/bundle/Resources/config/routing.yml
src/bundle/Resources/config/services.yml
src/bundle/Resources/config/services/menu.yml
src/bundle/Resources/config/services/service_aliases.yml
src/bundle/Resources/public/js/scripts/admin.linkmanager.list.js
src/bundle/Resources/public/scss/_general.scss
src/bundle/Resources/public/scss/_tables.scss
src/bundle/Resources/translations/linkmanager.en.xlf
src/bundle/Resources/translations/menu.en.xliff
src/bundle/Resources/views/link_manager/edit.html.twig
src/bundle/Resources/views/link_manager/list.html.twig
src/bundle/Resources/views/link_manager/view.html.twig
src/lib/Form/Data/Location/LocationUpdateData.php
src/lib/Form/Factory/FormFactory.php
src/lib/Menu/Event/ConfigureMenuEvent.php
src/lib/Menu/MainMenuBuilder.php
src/lib/Menu/URLEditRightSidebarBuilder.php

| Tickets       | https://jira.ez.no/browse/EZP-28495
| Bug fix?      | no 
This PR contains UI implementation for link management.
Requires the following PRs to be merged first:
* https://github.com/ezsystems/repository-forms/pull/185 
* https://github.com/ezsystems/ezpublish-kernel/pull/2183

EZP-28495: As Editor I want UI for external links management

---

src/lib/Menu/MainMenuBuilder.php

Fixed active sub-items form Link Manager menu

Fixed active sub-items form Link Manager menu

---

src/bundle/Resources/translations/content_type.en.xliff
src/bundle/Resources/translations/forms.en.xliff
src/bundle/Resources/translations/messages.en.xliff
src/bundle/Resources/translations/role.en.xliff
src/bundle/Resources/translations/section.en.xliff
src/bundle/Resources/views/admin/bulk_delete_confirmation_modal.html.twig
src/bundle/Resources/views/admin/content_type/delete_confirmation_modal.html.twig
src/bundle/Resources/views/admin/content_type/edit.html.twig
src/bundle/Resources/views/admin/content_type/list.html.twig
src/bundle/Resources/views/admin/content_type_group/list.html.twig
src/bundle/Resources/views/admin/language/delete_confirmation_modal.html.twig
src/bundle/Resources/views/admin/language/list.html.twig
src/bundle/Resources/views/admin/policy/list.html.twig
src/bundle/Resources/views/admin/role/list.html.twig
src/bundle/Resources/views/admin/role_assignment/list.html.twig
src/bundle/Resources/views/admin/section/list.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-28563
Added modal with deleting confirmation in Admin tab

EZP-28563: Added modal with deleting confirmation in Admin tab

---

src/bundle/Resources/public/scss/_general.scss

| Tickets       | https://jira.ez.no/browse/EZP-28566

EZP-28566: Dashboard heading missaligned

---

src/bundle/Resources/views/Security/login.html.twig
src/bundle/Resources/views/admin/content_type/view.html.twig
src/bundle/Resources/views/admin/content_type_group/list.html.twig
src/bundle/Resources/views/admin/content_type_group/view.html.twig
src/bundle/Resources/views/admin/language/list.html.twig
src/bundle/Resources/views/admin/language/view.html.twig
src/bundle/Resources/views/admin/role/list.html.twig
src/bundle/Resources/views/admin/role/view.html.twig
src/bundle/Resources/views/admin/search/list.html.twig
src/bundle/Resources/views/admin/search/search.html.twig
src/bundle/Resources/views/admin/section/list.html.twig
src/bundle/Resources/views/admin/section/view.html.twig
src/bundle/Resources/views/admin/systeminfo/info.html.twig
src/bundle/Resources/views/admin/trash/list.html.twig
src/bundle/Resources/views/content/content_edit/content_create.html.twig
src/bundle/Resources/views/content/content_edit/content_edit.html.twig
src/bundle/Resources/views/content/content_edit/content_edit_base.html.twig
src/bundle/Resources/views/content/content_edit/user_create.html.twig
src/bundle/Resources/views/content/content_preview.html.twig
src/bundle/Resources/views/content/locationview.html.twig
src/bundle/Resources/views/content/tab/versions/tab.html.twig
src/bundle/Resources/views/content/tab/versions/table.html.twig
src/bundle/Resources/views/dashboard/dashboard.html.twig
src/bundle/Resources/views/layout.html.twig
src/bundle/Resources/views/link_manager/list.html.twig
src/bundle/Resources/views/link_manager/view.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-28559
Fixed block names in twig templates to snake_case

EZP-28559: Fixed block names in twig templates to snake_case

---

src/bundle/Resources/public/scss/_forms.scss
src/bundle/Resources/public/scss/_mixins.scss
src/bundle/Resources/public/scss/fieldType/_base-preview.scss
src/bundle/Resources/public/scss/fieldType/_ezauthor.scss
src/bundle/Resources/public/scss/fieldType/_ezgmaplocation.scss
src/bundle/Resources/public/scss/fieldType/_ezkeyword.scss
src/bundle/Resources/public/scss/fieldType/_ezmedia.scss
src/bundle/Resources/public/scss/fieldType/_ezobjectrelationlist.scss
src/bundle/Resources/public/scss/fieldType/_ezselection.scss

| Tickets       | [EZP-28543](https://jira.ez.no/browse/EZP-28543)
- Improved size of icons within buttons in Editing view;
- Styled colors of interactions based on design specifications;

EZP-28543: Editing view styling of buttons and form fields

---

src/bundle/Resources/public/scss/_notifications.scss

| Tickets       | https://jira.ez.no/browse/EZP-27911

EZP-27911: Notification system

---

src/bundle/Resources/public/js/scripts/fieldType/ezmedia.js

| Tickets       | https://jira.ez.no/browse/EZP-28578

EZP-28578: User can't publish content item with ezmedia

---

src/bundle/Resources/views/content/tab/locations/panel_swap.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-28583
Design improvements for Swap location

EZP-28583: Design improvements for Swap location

---

src/bundle/Resources/public/js/scripts/fieldType/ezauthor.js

| Tickets       | https://jira.ez.no/browse/EZP-28557

EZP-28557: User is not able to remove added author

---

src/bundle/Resources/public/scss/_tables.scss
src/bundle/Resources/views/content/tab/details.html.twig
src/bundle/Resources/views/content/tab/locations/panel_swap.html.twig

Fix border top in location swap and set order

---

src/bundle/Resources/views/content/content_edit/user_edit.html.twig

fix: Missing X button on User edit page

---

src/bundle/Resources/public/js/scripts/fieldType/ezselection.js
src/bundle/Resources/views/fieldtypes/ezselection.html.twig

Fix creating user

---

src/lib/Menu/MainMenuBuilder.php

| Tickets       | https://jira.ez.no/browse/EZP-28553

EZP-28553: Hides top menu section when no children items are added

---

src/bundle/Resources/public/scss/_general.scss
src/bundle/Resources/public/scss/_preview.scss

Fixed content preview action buttons in Safari

---

src/bundle/Resources/public/js/scripts/fieldType/ezauthor.js

| Tickets       | https://jira.ez.no/browse/EZP-28530

EZP-28530: Wrong validation message for e-mail in ezauthor

---

src/bundle/Resources/translations/linkmanager.en.xliff
src/bundle/Resources/translations/menu.en.xliff
src/lib/Menu/MainMenuBuilder.php

| Tickets       | https://jira.ez.no/browse/EZP-28602
Fix translations in Link Manager

EZP-28602: Fix translations in Link Manager

---

src/bundle/Controller/ContentTypeController.php
src/bundle/ParamConverter/ContentTypeDraftParamConverter.php
src/bundle/ParamConverter/ContentTypeParamConverter.php
src/bundle/Resources/config/routing.yml
src/bundle/Resources/config/services.yml
src/bundle/Resources/config/services/form_processors.yml
src/bundle/Resources/views/admin/content_type/edit.html.twig
src/lib/Menu/Admin/ContentType/ContentTypeEditRightSidebarBuilder.php
src/lib/Menu/MainMenuBuilder.php
src/lib/RepositoryForms/Form/Processor/ContentType/ContentTypeDiscardChangesFormProcessor.php

| Tickets       | https://jira.ez.no/browse/EZP-28597

EZP-28597: When editing CT draft is edited instead of published version

---

src/bundle/Resources/public/js/scripts/fieldType/ezselection.js

| Tickets       | https://jira.ez.no/browse/EZP-28606

EZP-28606: Another option is added in edit mode of ezselection

---

src/bundle/Controller/SectionController.php
src/bundle/Controller/TrashController.php
src/bundle/DependencyInjection/Configuration/Parser/Pagination.php
src/bundle/EzPlatformAdminUiBundle.php
src/bundle/Resources/config/ezplatform_default_settings.yml
src/bundle/Resources/config/services/controllers.yml
src/bundle/Resources/translations/language.en.xliff
src/bundle/Resources/translations/messages.en.xliff
src/bundle/Resources/translations/section.en.xliff
src/bundle/Resources/views/admin/section/list.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-28608
Added pagination to the Sections list

EZP-28608: Add pagination to the Sections list

---

src/bundle/Resources/views/admin/policy/list.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-28610

 EZP-28610: Edit button on unrestricted policy */* should be disabled

---

src/bundle/Resources/public/js/scripts/admin.limitation.pick.js
src/bundle/Resources/views/admin/policy/edit.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-28536

EZP-28536: It's not possible to specify Locations/Subtree of locations for Limitations of Policies

---

.travis.yml
.travis/prepare_ezplatform.sh
behat_suites.yml
composer.json

| Question      | Answer |
| ------------- | --- |
| Tickets       | [EZP-28375](https://jira.ez.no/browse/EZP-28375) |
| Bug fix?      | no |
| New feature?  | yes |
| BC breaks?    | no |
| Tests pass?   | yes! |
| Doc needed?   | no |
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE) |
This PR enables running behat tests in dockerized environment on Travis CI.

EZP-28375: [Travis] Enabled running Behat tests

---

src/bundle/Controller/LanguageController.php
src/bundle/DependencyInjection/Configuration/Parser/Pagination.php
src/bundle/Resources/config/ezplatform_default_settings.yml
src/bundle/Resources/config/services/controllers.yml
src/bundle/Resources/translations/language.en.xliff
src/bundle/Resources/views/admin/language/list.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-28609
Added pagination to the Languages list

EZP-28609: Add pagination to the Languages list

---

src/bundle/Controller/RoleController.php
src/bundle/DependencyInjection/Configuration/Parser/Pagination.php
src/bundle/Resources/config/ezplatform_default_settings.yml
src/bundle/Resources/config/services/controllers.yml
src/bundle/Resources/translations/role.en.xliff
src/bundle/Resources/views/admin/role/list.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-28611
Added pagination to the Roles list

EZP-28609: Add pagination to the Roles list

---

src/bundle/Controller/DashboardController.php
src/bundle/Resources/config/routing.yml
src/bundle/Resources/views/dashboard/dashboard.html.twig
src/bundle/Resources/views/dashboard/tab/all_content.html.twig
src/bundle/Resources/views/dashboard/tab/all_media.html.twig
src/bundle/Resources/views/dashboard/tab/my_content.html.twig
src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig
src/bundle/Resources/views/dashboard/tab/my_media.html.twig

fix: Dashboard edit now leads to Draft Edit instead of Draft Create

---

src/bundle/Resources/translations/validators.en.xliff
src/bundle/Resources/views/layout.html.twig

fix: Missing translations for JS validators

---

src/bundle/Resources/public/scss/_main-nav.scss
src/bundle/Resources/public/scss/_notifications.scss
src/bundle/Resources/public/scss/_tabs.scss
src/bundle/Resources/views/parts/navigation.html.twig

Fix button in notifications, menu height, ez-active to active

---

src/bundle/Resources/public/scss/_forms.scss

| Tickets       | https://jira.ez.no/browse/EZP-28641

EZP-28641: Checkboxes are not at the same level than other elements

---

src/lib/Menu/Voter/LocationVoter.php

fix: Improve LocationVoter to be fail proof

---

src/bundle/Resources/public/js/scripts/fieldType/ezmedia.js

| Tickets       | https://jira.ez.no/browse/EZP-28644

EZP-28644: [ezmedia] Validation alert for width and height

---

src/bundle/Resources/views/admin/search/search.html.twig
src/bundle/Resources/views/admin/trash/list.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-28642
Design improvements for Search and Trash pagination

EZP-28642: Design improvements for Search and Trash pagination

---

src/bundle/Resources/public/scss/_mixins.scss

Fix min-width in visibility switcher

---

src/bundle/Resources/public/scss/fieldType/_ezobjectrelationlist.scss

| Tickets       | https://jira.ez.no/browse/EZP-28652

EZP-28652: [ezobjectrelation] Buttons are misaligned in content view

---

src/bundle/Resources/public/js/scripts/fieldType/ezobjectrelationlist.js
src/bundle/Resources/public/scss/fieldType/_ezobjectrelationlist.scss
src/bundle/Resources/views/fieldtypes/relation_base.html.twig

Fixed relations field type header buttons styling

---

src/bundle/Resources/public/js/scripts/admin.contenttype.relation.default.location.js

| Tickets       | https://jira.ez.no/browse/EZP-28654

EZP-28654: UDW in ezobjectrelationlist field definition edit should use starting location configured in config

---

src/bundle/Resources/public/scss/_general.scss

Fix visible date input in content translate

---

src/bundle/Controller/PolicyController.php
src/bundle/Resources/views/admin/policy/list.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-28635

EZP-28635: Make sure policies without limitationTypes are not editable

---

src/bundle/Resources/public/js/scripts/udw/move.js

| Tickets       |https://jira.ez.no/browse/EZP-28639

EZP-28639: [UDW] GUI allows you to try to move content item to another content item which is not a container

---

src/bundle/Resources/views/Security/login.html.twig
src/bundle/Resources/views/layout.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-28365

EZP-28365: Browser console error on login page (Uncaught SyntaxError)

---

src/bundle/Controller/ContentViewController.php
src/bundle/DependencyInjection/Configuration/Parser/Pagination.php
src/bundle/Resources/config/ezplatform_default_settings.yml
src/bundle/Resources/config/services/controllers.yml
src/bundle/Resources/views/content/locationview.html.twig
src/bundle/Resources/views/content/tab/versions/tab.html.twig
src/lib/Tab/LocationView/VersionsTab.php

| Tickets       | https://jira.ez.no/browse/EZP-28661
Add pagination to the Draft under edit

EZP-28661: Add pagination to the Draft under edit

---

src/bundle/Resources/views/content/locationview.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-28662
| Bug fix?      |yes
In breadcrumb change link to _ezpublishLocation

EZP-28662: In breadcrumb change link to _ezpublishLocation

---

src/bundle/Resources/public/js/scripts/admin.location.view.js

| Tickets       | https://jira.ez.no/browse/EZP-28659
**Requires:**
- https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/47

EZP-28659: Add proper links to locations to sub items pagination

---

src/lib/Tab/Dashboard/MyDraftsTab.php

| Tickets       | [EZP-28668](https://jira.ez.no/browse/EZP-28668)
| Tests pass?   | hopefully
This PR implements a workaround hiding from My Drafts tab Drafts that belong to trashed Content Item.

EZP-28668: Ignored Drafts for Trashed Content Item in My Drafts Tab

---

src/bundle/Resources/public/js/scripts/fieldType/ezuser.js

| Tickets       | https://jira.ez.no/browse/EZP-28648

EZP-28648: Incorrect validation when changing user password

---

src/bundle/Resources/public/js/scripts/udw/locations.tab.js

| Tickets       | https://jira.ez.no/browse/EZP-28672

EZP-28672: Add location allows item which is not a container to have sub-items

---

src/bundle/Resources/views/Security/login.html.twig

Fix closing body tag

---

src/bundle/Resources/public/js/scripts/fieldType/ezrichtext.js

| Tickets       | https://jira.ez.no/browse/EZP-28700

EZP-28700: Editor won't accept <br> tags in headers

---

src/bundle/Resources/views/admin/role/edit.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-28735
Fixed style for edit mode of Role.

EZP-28735: Style is not applied to edit mode of Role

---

src/bundle/Resources/views/parts/navigation.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-28733

EZP-28733: Make main menu content aware

---

src/bundle/ParamConverter/ContentParamConverter.php
src/bundle/ParamConverter/ContentTypeDraftParamConverter.php
src/bundle/ParamConverter/ContentTypeGroupParamConverter.php
src/bundle/ParamConverter/ContentTypeParamConverter.php
src/bundle/ParamConverter/LanguageParamConverter.php
src/bundle/ParamConverter/PolicyParamConverter.php
src/bundle/ParamConverter/RoleAssignmentParamConverter.php
src/bundle/ParamConverter/RoleParamConverter.php
src/bundle/ParamConverter/SectionParamConverter.php
src/bundle/ParamConverter/VersionInfoParamConverter.php
src/bundle/Tests/ParamConverter/AbstractParamConverterTest.php
src/bundle/Tests/ParamConverter/ContentParamConverterTest.php
src/bundle/Tests/ParamConverter/ContentTypeDraftParamConverterTest.php
src/bundle/Tests/ParamConverter/ContentTypeGroupParamConverterTest.php
src/bundle/Tests/ParamConverter/ContentTypeParamConverterTest.php
src/bundle/Tests/ParamConverter/LanguageParamConverterTest.php
src/bundle/Tests/ParamConverter/PolicyParamConverterTest.php
src/bundle/Tests/ParamConverter/RoleAssignmentParamConverterTest.php
src/bundle/Tests/ParamConverter/RoleParamConverterTest.php
src/bundle/Tests/ParamConverter/SectionParamConverterTest.php
src/bundle/Tests/ParamConverter/VersionInfoParamConverterTest.php

| Tickets       | https://jira.ez.no/browse/EZP-28717
Add unit tests to ParamConverters

EZP-28717: Add unit tests to ParamConverters

---

src/bundle/Controller/SearchController.php

| Tickets       | https://jira.ez.no/browse/EZP-28744
Search in admin ui does not return hidden content

EZP-28744: Search in admin ui does not return hidden content

---

src/bundle/Resources/translations/locationview.en.xliff
src/bundle/Resources/views/content/tab/details.html.twig
src/bundle/Resources/views/content/tab/versions/table.html.twig
src/lib/Specification/UserExists.php
src/lib/Specification/UserSpecification.php
src/lib/Tab/Dashboard/PagerContentToDataMapper.php
src/lib/Tab/LocationView/DetailsTab.php
src/lib/UI/Value/ValueFactory.php

| Tickets       | https://jira.ez.no/browse/EZP-28755
This PR fixes error 500 if any content version was created by a user that doesn't exist anymore. Also affect "Everyone Content and Media" in Dashboard.

EZP-28755: Error 500 if any content version was created by a user that doesn't exist anymore

---

src/bundle/Controller/ContentViewController.php
src/bundle/Controller/PolicyController.php
src/bundle/ParamConverter/ContentTypeParamConverter.php
src/bundle/Resources/config/services.yml
src/bundle/Resources/config/services/controllers.yml
src/bundle/Resources/config/services/tabs/locationview.yml
src/bundle/Resources/translations/ezrepoforms_role.en.xliff
src/bundle/Resources/translations/role.en.xliff
src/bundle/Resources/views/content/locationview.html.twig
src/bundle/Resources/views/content/tab/content.html.twig
src/bundle/Tests/ParamConverter/ContentTypeParamConverterTest.php
src/lib/Form/Type/Policy/PolicyUpdateType.php
src/lib/Tab/LocationView/ContentTab.php

fix: Unify a langauge displayed across Admin aplication

---

src/bundle/Resources/public/scss/_extra-actions.scss

| Tickets       | https://jira.ez.no/browse/EZP-28776

[EZP-28776] Harmonize hover & active states for creating and editing content

---

src/bundle/Resources/views/content/form_fields.html.twig
src/bundle/Resources/views/form_fields.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-28797

EZP-28797: Can type letters into float fieldtype

---

src/bundle/Controller/UserProfile/UserPasswordChangeController.php
src/bundle/Resources/config/routing.yml
src/bundle/Resources/config/services.yml
src/bundle/Resources/config/services/menu.yml
src/bundle/Resources/config/services/validators.yml
src/bundle/Resources/public/js/scripts/user_password.change.js
src/bundle/Resources/public/scss/_forms.scss
src/bundle/Resources/translations/forms.en.xliff
src/bundle/Resources/translations/menu.en.xliff
src/bundle/Resources/translations/messages.en.xliff
src/bundle/Resources/translations/user_change_password.en.xliff
src/bundle/Resources/translations/validators.en.xliff
src/bundle/Resources/views/user-profile/change_user_password.html.twig
src/bundle/Resources/views/user-profile/form_fields.html.twig
src/lib/Form/Data/User/UserPasswordChangeData.php
src/lib/Form/Factory/FormFactory.php
src/lib/Form/Type/User/UserPasswordChangeType.php
src/lib/Menu/Event/ConfigureMenuEvent.php
src/lib/Menu/UserMenuBuilder.php
src/lib/Menu/UserPasswordChangeRightSidebarBuilder.php
src/lib/Tests/Validator/Constraint/UserPasswordTest.php
src/lib/Tests/Validator/Constraint/UserPasswordValidatorTest.php
src/lib/Validator/Constraints/UserPassword.php
src/lib/Validator/Constraints/UserPasswordValidator.php

| Tickets       | https://jira.ez.no/browse/EZP-28791
As a user I want to change password

EZP-28791: As a user I want to change password

---

features/ContentTypeGroup.feature
features/Languages.feature
src/lib/Behat/BusinessContext/AdministrationContext.php
src/lib/Behat/BusinessContext/NotificationContext.php
src/lib/Behat/BusinessContext/UpdateContext.php
src/lib/Behat/PageElement/AdminList.php
src/lib/Behat/PageElement/Breadcrumb.php
src/lib/Behat/PageElement/Dialog.php
src/lib/Behat/PageElement/Notification.php
src/lib/Behat/PageElement/RightMenu.php
src/lib/Behat/PageElement/UpdateForm.php
src/lib/Behat/PageElement/UpperMenu.php
src/lib/Behat/PageObject/ContentStructurePage.php
src/lib/Behat/PageObject/ContentTypeGroupsPage.php
src/lib/Behat/PageObject/ContentTypePage.php
src/lib/Behat/PageObject/DashboardPage.php
src/lib/Behat/PageObject/LanguagePage.php
src/lib/Behat/PageObject/LanguagesPage.php
src/lib/Behat/PageObject/LoginPage.php
src/lib/Behat/PageObject/Page.php
src/lib/Behat/PageObject/PageObjectFactory.php
src/lib/Behat/PageObject/UpdateItemPage.php

| Tickets       | https://jira.ez.no/browse/EZP-28171

EZP-28171 Behat Covering of Languages

---

src/lib/Behat/BusinessContext/ContentViewContext.php
src/lib/Behat/PageElement/UpdateForm.php

Fixing bugs introduced by previous EZP-28171 PR.

EZP-28171 Behat Covering of Languages - follow-up

---

src/bundle/Resources/views/layout.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-28877
**IMPORTANT:**
All existing Universal Discovery module instances should be tested, just in case it suddenly breaks (but it shouldn't).

EZP-28877: As a developer I would like to inject custom tabs configuration into the Universal Discovery module instance

---

src/lib/Behat/PageObject/ContentStructurePage.php
src/lib/Behat/PageObject/ContentTypeGroupPage.php
src/lib/Behat/PageObject/ContentTypeGroupsPage.php
src/lib/Behat/PageObject/ContentTypePage.php
src/lib/Behat/PageObject/DashboardPage.php
src/lib/Behat/PageObject/LanguagePage.php
src/lib/Behat/PageObject/LanguagesPage.php
src/lib/Behat/PageObject/Page.php

EZP-28171 Behat Covering of Languages - move title locator to variable

---

src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-28880

EZP-28880: Needless <> for ezauthor in view mode

---

src/bundle/Resources/public/scss/_extra-actions.scss
src/bundle/Resources/views/form_fields.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-28887

EZP-28887: Unexpected radio buttons in the content type selector and language selector

---

src/bundle/Resources/views/Security/login.html.twig

EZP-26238: eZPlatform login screen redirecting to the link the user entered initially

---

src/bundle/Controller/UrlAliasController.php
src/bundle/Resources/config/routing.yml
src/bundle/Resources/config/services.yml
src/bundle/Resources/public/js/scripts/admin.location.add.custom_url.js
src/bundle/Resources/public/scss/_custom.scss
src/bundle/Resources/public/scss/_general.scss
src/bundle/Resources/public/scss/_mixins.scss
src/bundle/Resources/public/scss/_modals.scss
src/bundle/Resources/public/scss/ezplatform.scss
src/bundle/Resources/public/scss/fieldType/edit/_base-preview.scss
src/bundle/Resources/translations/content_url.en.xliff
src/bundle/Resources/translations/locationview.en.xliff
src/bundle/Resources/translations/messages.en.xliff
src/bundle/Resources/translations/validators.en.xliff
src/bundle/Resources/views/content/locationview.html.twig
src/bundle/Resources/views/content/tab/url/checkbox.html.twig
src/bundle/Resources/views/content/tab/url/modal_add_custom_url.html.twig
src/bundle/Resources/views/content/tab/urls.html.twig
src/lib/Form/Data/Content/CustomUrl/CustomUrlAddData.php
src/lib/Form/EventListener/AddLanguageFieldBasedOnContentListener.php
src/lib/Form/EventListener/BuildPathFromRootListener.php
src/lib/Form/Factory/FormFactory.php
src/lib/Form/Type/Content/CustomUrl/CustomUrlAddType.php
src/lib/Tab/LocationView/UrlsTab.php

| Tickets       | https://jira.ez.no/browse/EZP-27840
Adding option to add custom urls for content in AdminUi.
~~Implement https://jira.ez.no/browse/EZP-20469~~

EZP-27840: As an Editor, I want to create a custom URL alias for a content item

---

src/bundle/Resources/config/default_parameters.yml
src/bundle/Resources/config/views.yml

| Tickets       | https://jira.ez.no/browse/EZP-28920
| Requires | https://github.com/ezsystems/repository-forms/pull/215

EZP-28920: Configure content edit view in AdminUI

---

src/bundle/Resources/views/parts/menu/top_menu.html.twig
src/bundle/Resources/views/parts/menu/top_menu_2nd_level.html.twig

Jira Ticket: [EZP-28928](https://jira.ez.no/browse/EZP-28928)

Fixing and adding support for custom linkAttribute classes

---

src/bundle/Controller/Controller.php
src/bundle/Controller/UrlAliasController.php
src/bundle/Resources/config/routing.yml
src/bundle/Resources/translations/content_url.en.xliff
src/bundle/Resources/translations/messages.en.xliff
src/bundle/Resources/views/content/tab/url/modal_add_custom_url.html.twig
src/bundle/Resources/views/content/tab/urls.html.twig
src/lib/Form/Data/Content/CustomUrl/CustomUrlRemoveData.php
src/lib/Form/EventListener/AddLanguageFieldBasedOnContentListener.php
src/lib/Form/EventListener/BuildPathFromRootListener.php
src/lib/Form/Factory/FormFactory.php
src/lib/Form/Type/Content/CustomUrl/CustomUrlAddType.php
src/lib/Form/Type/Content/CustomUrl/CustomUrlRemoveType.php
src/lib/Tab/LocationView/UrlsTab.php
src/lib/UI/Dataset/CustomUrlsDataset.php
src/lib/UI/Dataset/DatasetFactory.php
src/lib/UI/Value/Content/UrlAlias.php
src/lib/UI/Value/ValueFactory.php

| Tickets       | https://jira.ez.no/browse/EZP-27536
Relevant commit:
https://github.com/ViniTou/ezplatform-admin-ui/commit/ca36b73170e760fc9e67e17588d101d069331759
This needs to be rebased after https://github.com/ezsystems/ezplatform-admin-ui/pull/363 is merged.

EZP-27536: As a Editor I want to delete a URL alias in the URL alias tab

---

src/bundle/Resources/public/js/scripts/fieldType/base/base-file-field.js
src/bundle/Resources/views/fieldtypes/edit/binary_base.html.twig
src/bundle/Resources/views/fieldtypes/edit/ezmedia.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-28894

EZP-28894: Cannot publish Content Object with Image field type

---

src/lib/Tab/LocationView/RelationsTab.php

fix: Invalid policy results in Exception

---

src/bundle/Controller/SearchController.php
src/bundle/Resources/public/js/scripts/admin.search.filters.js
src/bundle/Resources/public/scss/_content-type-selector.scss
src/bundle/Resources/public/scss/_filters.scss
src/bundle/Resources/public/scss/_modals.scss
src/bundle/Resources/public/scss/ezplatform.scss
src/bundle/Resources/translations/messages.en.xliff
src/bundle/Resources/translations/search.en.xliff
src/bundle/Resources/views/admin/search/search.html.twig
src/bundle/Resources/views/admin/search/search_form.html.twig
src/bundle/Resources/views/form_fields.html.twig
src/lib/Form/Data/Search/SearchData.php
src/lib/Form/DataTransformer/DateIntervalTransformer.php
src/lib/Form/Type/Search/DateIntervalType.php
src/lib/Form/Type/Search/SearchType.php

| Tickets       | https://jira.ez.no/browse/EZP-28937
Simplified filtered search filter by Content Type, Section, Modified and Created dates.

EZP-28937: Simplified filtered search

---

src/bundle/Controller/User/UserForgotPasswordController.php
src/bundle/DependencyInjection/Configuration/Parser/Security.php
src/bundle/EzPlatformAdminUiBundle.php
src/bundle/Resources/config/ezplatform_default_settings.yml
src/bundle/Resources/config/routing.yml
src/bundle/Resources/config/services.yml
src/bundle/Resources/public/scss/_login.scss
src/bundle/Resources/translations/forms.en.xliff
src/bundle/Resources/translations/messages.en.xliff
src/bundle/Resources/translations/validators.en.xliff
src/bundle/Resources/views/Security/base.html.twig
src/bundle/Resources/views/Security/forgot_user_password/index.html.twig
src/bundle/Resources/views/Security/forgot_user_password/success.html.twig
src/bundle/Resources/views/Security/forgot_user_password/with_login.html.twig
src/bundle/Resources/views/Security/form_fields.html.twig
src/bundle/Resources/views/Security/login.html.twig
src/bundle/Resources/views/Security/mail/forgot_user_password.html.twig
src/bundle/Resources/views/Security/reset_user_password/index.html.twig
src/bundle/Resources/views/Security/reset_user_password/invalid_link.html.twig
src/bundle/Resources/views/Security/reset_user_password/success.html.twig
src/lib/Form/Data/User/UserPasswordForgotData.php
src/lib/Form/Data/User/UserPasswordForgotWithLoginData.php
src/lib/Form/Data/User/UserPasswordResetData.php
src/lib/Form/Factory/FormFactory.php
src/lib/Form/Type/User/UserPasswordForgotType.php
src/lib/Form/Type/User/UserPasswordForgotWithLoginType.php
src/lib/Form/Type/User/UserPasswordResetType.php

| Tickets       | https://jira.ez.no/browse/EZP-28792
| Dependencies | ezsystems/ezpublish-kernel#2270
As an editor, I want to reset my forgotten password in Admin U.I.

EZP-28792: As an editor, I want to reset my forgotten password in Admin U.I.

---

src/lib/Tests/RepositoryForms/Form/Processor/PreviewFormProcessorTest.php

| Tickets       | https://jira.ez.no/browse/EZP-28314
Broken by PR: https://github.com/ezsystems/ezplatform-admin-ui/pull/371

EZP-28314: Fix invalid Test case

---

src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js

| Tickets       | https://jira.ez.no/browse/EZP-28931

EZP-28931: Large values in Longitude of Map location

---

behat_suites.yml
features/ContentTypeGroup.feature
features/Roles.feature
src/lib/Behat/BusinessContext/AdministrationContext.php
src/lib/Behat/BusinessContext/ContentTypeContext.php
src/lib/Behat/BusinessContext/ContentViewContext.php
src/lib/Behat/BusinessContext/RolesContext.php
src/lib/Behat/BusinessContext/UpdateContext.php
src/lib/Behat/Helper/UtilityContext.php
src/lib/Behat/PageElement/AdminList.php
src/lib/Behat/PageElement/Dialog.php
src/lib/Behat/PageElement/DoubleHeaderTable.php
src/lib/Behat/PageElement/ElementFactory.php
src/lib/Behat/PageElement/LinkedListTable.php
src/lib/Behat/PageElement/NavLinkTabs.php
src/lib/Behat/PageElement/SimpleListTable.php
src/lib/Behat/PageElement/SimpleTable.php
src/lib/Behat/PageElement/Table.php
src/lib/Behat/PageElement/UniversalDiscoveryWidget.php
src/lib/Behat/PageElement/UpdateForm.php
src/lib/Behat/PageElement/VerticalOrientedTable.php
src/lib/Behat/PageObject/ContentTypeGroupPage.php
src/lib/Behat/PageObject/ContentTypeGroupsPage.php
src/lib/Behat/PageObject/ContentTypePage.php
src/lib/Behat/PageObject/LanguagesPage.php
src/lib/Behat/PageObject/PageObjectFactory.php
src/lib/Behat/PageObject/RolePage.php
src/lib/Behat/PageObject/RolesPage.php

EZP-28170 Behat Covering of Roles

---

src/bundle/Resources/public/scss/_modals.scss
src/bundle/Resources/views/content/modal_draft_conflict.html.twig

| Tickets       | [EZP-28922](https://jira.ez.no/browse/EZP-28922)
- Updated Draft Conflict modal based on design consistency requirements for modals throughout the application.

EZP-28922: Modal Draft Conflict design consistency update

---

src/bundle/Resources/public/js/scripts/fieldType/base/base-field.js
src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js

| Tickets       | https://jira.ez.no/browse/EZP-28859
In fact, this PR doesn't fix the backend issue. It improves the frontend validation before publishing the content.

EZP-28859: Bad request after filling one coordinate from ezmaplocation

---

src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js

The followup of #392 
Removed the dead code.
| Bug fix?      | ?

EZP-28859: Bad request after filling one coordinate from ezmaplocation - obsolete code removal

---

src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js

| Tickets       | https://jira.ez.no/browse/EZP-28941

EZP-28941: OpenStreetMaps does not load over a secure HTTPS connection

---

src/bundle/Resources/config/views.yml
src/bundle/Resources/public/scss/_card.scss
src/bundle/Resources/public/scss/_forms.scss
src/bundle/Resources/views/admin/content_type/create.html.twig
src/bundle/Resources/views/admin/content_type/edit.html.twig
src/bundle/Resources/views/admin/content_type/field_types.html.twig
src/bundle/Resources/views/admin/role_assignment/create.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-28954

EZP-28954: Label is one line below checkbox/radiobutton

---

src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js
src/bundle/Resources/public/scss/fieldType/edit/_ezgmaplocation.scss

| Tickets       | https://jira.ez.no/browse/EZP-28416
**IMPORTANT!**
We are not able to detect whether a given address matches the coordinates correctly. The only thing we can do is to check if in case of address input is filled whether the coordinate fields are also filled.

EZP-28416: [MapLocation] Problem with Address field

---

src/bundle/Resources/public/scss/_mixins.scss
src/bundle/Resources/views/content/tab/url/checkbox.html.twig
src/lib/Form/EventListener/BuildPathFromRootListener.php
src/lib/Form/EventListener/DisableSiteRootCheckboxIfRootLocationListener.php
src/lib/Form/Type/Content/CustomUrl/CustomUrlAddType.php

| Tickets       | https://jira.ez.no/browse/EZP-28968?
Disable url alias creation under root path for root locations.

EZP-28968: Error when creating URL alias at root level

---

src/bundle/Resources/public/scss/_modals.scss

| Tickets       | [EZP-28984](https://jira.ez.no/browse/EZP-28984)
- Updated Search filters modals based on design harmonization for modals throughout the application.

EZP-28984: Search filters modals design update

---

src/bundle/Resources/views/admin/content_type/field_types.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-28974

EZP-28974: Misaligned label of "Default value/Multiple choice" checkbox

---

src/bundle/Controller/ContentController.php
src/bundle/Resources/translations/content_edit.en.xliff
src/bundle/Resources/views/content/content_edit/content_edit.html.twig
src/bundle/Resources/views/content/content_preview.html.twig
src/lib/Component/Content/PreviewUnavailableTwigComponent.php
src/lib/Menu/ContentEditRightSidebarBuilder.php
src/lib/RepositoryForms/Form/Processor/PreviewFormProcessor.php
src/lib/RepositoryForms/View/ViewParametersListener.php
src/lib/Siteaccess/SiteaccessResolver.php
src/lib/Tests/RepositoryForms/Form/Processor/PreviewFormProcessorTest.php
src/lib/Tests/RepositoryForms/View/ViewParametersListenerTest.php

| Tickets       | https://jira.ez.no/browse/EZP-28939
| Requires | https://github.com/ezsystems/repository-forms/pull/227

EZP-28939: Internal Server Error when saving unpublished Draft

---

src/bundle/Resources/config/services/form_processors.yml
src/bundle/Resources/translations/content_edit.en.xliff
src/lib/RepositoryForms/Form/Processor/ContentEditNotificationFormProcessor.php

| Tickets       | https://jira.ez.no/browse/EZEE-1907

EZEE-1907: Missing notification after publishing/sending for review/publishing in the future

---

behat_suites.yml
features/ContentType.feature
features/ContentTypeGroup.feature
features/Languages.feature
features/Roles.feature
features/Sections.feature
src/lib/Behat/BusinessContext/AdministrationContext.php
src/lib/Behat/BusinessContext/SectionsContext.php
src/lib/Behat/BusinessContext/UDWContext.php
src/lib/Behat/PageElement/AdminList.php
src/lib/Behat/PageElement/Dialog.php
src/lib/Behat/PageElement/SimpleTable.php
src/lib/Behat/PageElement/Table.php
src/lib/Behat/PageElement/UniversalDiscoveryWidget.php
src/lib/Behat/PageElement/UpperMenu.php
src/lib/Behat/PageObject/ContentTypeGroupsPage.php
src/lib/Behat/PageObject/ContentTypePage.php
src/lib/Behat/PageObject/LanguagesPage.php
src/lib/Behat/PageObject/PageObjectFactory.php
src/lib/Behat/PageObject/RolePage.php
src/lib/Behat/PageObject/RolesPage.php
src/lib/Behat/PageObject/SectionPage.php
src/lib/Behat/PageObject/SectionsPage.php

| Tickets       | [EZP-28169](https://jira.ez.no/browse/EZP-28169)
13 tests that covers Admin -> Sections

EZP-28169 - Behat Covering of Sections

---

behat_suites.yml
features/SystemInfo.feature
src/lib/Behat/BusinessContext/SystemInfoContext.php
src/lib/Behat/PageElement/AdminList.php
src/lib/Behat/PageElement/ElementFactory.php
src/lib/Behat/PageElement/SimpleTable.php
src/lib/Behat/PageElement/SystemInfoTable.php
src/lib/Behat/PageObject/PageObjectFactory.php
src/lib/Behat/PageObject/SystemInfoPage.php

| Tickets       | [EZP-28168](https://jira.ez.no/browse/EZP-28168)
5 tests that covers Admin -> System Information

EZP-28168 - Behat Covering of SystemInfo

---

src/bundle/Resources/public/js/scripts/udw/copy.js
src/bundle/Resources/public/js/scripts/udw/move.js

| Tickets       | https://jira.ez.no/browse/EZP-27961

EZP-27961: Copying a content item - Restrict a user from selecting a non-container location in the UDW component

---

src/bundle/Controller/SystemInfoController.php

| Tickets       | https://jira.ez.no/browse/EZP-28862

EZP-28862: Require an explicit permission for the System Info route

---

src/bundle/Controller/TrashController.php
src/bundle/Resources/config/routing.yml
src/bundle/Resources/public/js/scripts/admin.trash.list.js
src/bundle/Resources/translations/content_type.en.xliff
src/bundle/Resources/translations/messages.en.xliff
src/bundle/Resources/translations/trash.en.xliff
src/bundle/Resources/views/admin/trash/list.html.twig
src/lib/Form/Data/Trash/TrashItemDeleteData.php
src/lib/Form/Factory/FormFactory.php
src/lib/Form/Type/Trash/TrashItemDeleteType.php

| Tickets       | https://jira.ez.no/browse/EZP-29049
There is no way to delete a single item (or multiple items) in the trash. There is only one button: Empty trash.

EZP-29049: As a user, I want to delete a single item in the trash.

---

features/ContentType.feature
src/bundle/Resources/translations/content_type.en.xliff
src/bundle/Resources/views/admin/content_type/view.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-29068

EZP-29068: [Content Types] Regression - missing PR #422 with label in consistencies fix

---

src/bundle/Controller/SearchController.php
src/bundle/DependencyInjection/Configuration/Parser/UserIdentifier.php
src/bundle/EzPlatformAdminUiBundle.php
src/bundle/Resources/config/ezplatform_default_settings.yml
src/bundle/Resources/config/services/controllers.yml
src/bundle/Resources/public/js/scripts/admin.search.filters.js
src/bundle/Resources/public/scss/_filters.scss
src/bundle/Resources/translations/search.en.xliff
src/bundle/Resources/views/admin/search/search_form.html.twig
src/lib/Form/Data/Search/SearchData.php
src/lib/Form/DataTransformer/UserTransformer.php
src/lib/Form/Type/Search/SearchType.php
src/lib/Form/Type/User/UserType.php
src/lib/Tests/Form/DataTransformer/UserTransformerTest.php

| Tickets       | https://jira.ez.no/browse/EZP-28059
This PR allow to search/filter for a content item by entering the name of the creator

EZP-28059: As an Editor, I want to search/filter for a content item by entering the name of the creator

---

src/bundle/Resources/translations/content_type.en.xliff
src/bundle/Resources/views/admin/content_type/list.html.twig
src/bundle/Resources/views/admin/content_type/macros.html.twig
src/bundle/Resources/views/admin/content_type/view.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-29070

EZP-29070: Add edit button on content type view.

---

src/bundle/Controller/ContentViewController.php
src/bundle/DependencyInjection/Configuration/Parser/Pagination.php
src/bundle/DependencyInjection/Configuration/Parser/UserGroupIdentifier.php
src/bundle/EzPlatformAdminUiBundle.php
src/bundle/Resources/config/ezplatform_default_settings.yml
src/bundle/Resources/config/services.yml
src/bundle/Resources/config/services/controllers.yml
src/bundle/Resources/config/services/tabs/locationview.yml
src/bundle/Resources/translations/locationview.en.xliff
src/bundle/Resources/translations/role.en.xliff
src/bundle/Resources/views/content/locationview.html.twig
src/bundle/Resources/views/content/tab/roles/limitation_values.html.twig
src/bundle/Resources/views/content/tab/roles/tab.html.twig
src/bundle/Resources/views/content/tab/roles/table.html.twig
src/bundle/Templating/Twig/TabExtension.php
src/lib/EventListener/SystemInfoTabGroupListener.php
src/lib/Specification/ContentType/ContentTypeIsUser.php
src/lib/Specification/ContentType/ContentTypeIsUserGroup.php
src/lib/Tab/ConditionalTabInterface.php
src/lib/Tab/Event/Subscriber/ConditionalTabSubscriber.php
src/lib/Tab/Event/TabEvents.php
src/lib/Tab/LocationView/RolesTab.php
src/lib/Tests/EventListener/SystemInfoTabGroupListenerTest.php
src/lib/UI/Dataset/DatasetFactory.php
src/lib/UI/Dataset/RolesDataset.php
src/lib/UI/Value/User/Role.php
src/lib/UI/Value/ValueFactory.php

| Tickets       | https://jira.ez.no/browse/EZP-29066
As a website administrator, I want to see the roles assigned to a user or user group

EZP-29066: As a website administrator, I want to see the roles assigned to a user or user group

---

src/bundle/Controller/ContentViewController.php
src/bundle/DependencyInjection/Configuration/Parser/Pagination.php
src/bundle/Resources/config/ezplatform_default_settings.yml
src/bundle/Resources/config/services/controllers.yml
src/bundle/Resources/config/services/tabs/locationview.yml
src/bundle/Resources/translations/locationview.en.xliff
src/bundle/Resources/translations/policy.en.xliff
src/bundle/Resources/views/content/locationview.html.twig
src/bundle/Resources/views/content/tab/policies/limitation_values.html.twig
src/bundle/Resources/views/content/tab/policies/tab.html.twig
src/bundle/Resources/views/content/tab/policies/table.html.twig
src/lib/Tab/LocationView/PoliciesTab.php
src/lib/UI/Dataset/DatasetFactory.php
src/lib/UI/Dataset/PoliciesDataset.php
src/lib/UI/Value/User/Policy.php
src/lib/UI/Value/ValueFactory.php

| Tickets       | https://jira.ez.no/browse/EZP-29067

EZP-29067: As a website administrator, I want to see the policies assigned to a user or user group

---

src/lib/UI/Value/ValueFactory.php

| Tickets       | https://jira.ez.no/browse/EZP-29020

EZP-29020: Cannot access content menu tabs when state assign policy is set

---

src/bundle/Resources/views/content/content_preview.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-28806

EZP-28806: As a developer I want to define the SiteAccess name

---

.travis.yml

| Tickets       | https://jira.ez.no/browse/EZP-29107
| New feature?  | to Travis
Running AdminUI tests on Varnish, follow-up to https://github.com/ezsystems/StudioUIBundle/pull/898

EZP-29107: Run tests on Varnish

---

src/bundle/Resources/public/scss/fieldType/preview/_ezimage.scss
src/bundle/Resources/translations/fieldtypes_preview.en.xliff
src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-29036

EZP-29036: As an Editor, I want useful information about the Image field type in Content View mode

---

src/bundle/Resources/config/services.yml
src/lib/EventListener/MenuPermissionsListener.php
src/lib/Menu/MainMenuBuilder.php
src/lib/Tests/Menu/MainMenuBuilerTest.php

| Tickets       | https://jira.ez.no/browse/EZP-29133

EZP-29133: Implement permission to access Admin Panel

---

src/bundle/Controller/SectionController.php
src/bundle/Resources/views/admin/section/assigned_content.html.twig
src/bundle/Resources/views/admin/section/list.html.twig
src/bundle/Resources/views/admin/section/view.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-29099
For now this PR implement permissions policy 'Section/Assign' without UDW.

EZP-29099: Implement permissions for Section management in Admin Panel

---

src/bundle/Controller/BookmarkController.php
src/bundle/Resources/config/ezplatform_default_settings.yml
src/bundle/Resources/config/routing.yml
src/bundle/Resources/config/services/controllers.yml
src/bundle/Resources/translations/bookmark.en.xliff
src/bundle/Resources/translations/menu.en.xliff
src/bundle/Resources/views/admin/bookmark/list.html.twig
src/bundle/Resources/views/form_fields.html.twig
src/lib/Form/Data/Bookmark/BookmarkRemoveData.php
src/lib/Form/Factory/FormFactory.php
src/lib/Form/Type/Bookmark/BookmarkRemoveType.php
src/lib/Menu/LeftSidebarBuilder.php
src/lib/Menu/UserMenuBuilder.php
src/lib/UI/Dataset/BookmarksDataset.php
src/lib/UI/Dataset/DatasetFactory.php
src/lib/UI/Value/Location/Bookmark.php
src/lib/UI/Value/ValueFactory.php

| Tickets       | https://jira.ez.no/browse/EZP-28837
Valid commit:
https://github.com/ezsystems/ezplatform-admin-ui/pull/473/commits/ed3a5b3e916a8941f508ae072184de1b68f02a3a

EZP-28837: As an editor I want to access to my bookmarks

---

src/lib/Tab/LocationView/VersionsTab.php

| Tickets       | https://jira.ez.no/browse/EZP-29212
It is needed to check Version tab visibility with limitation.

EZP-29212: Error 500 when user doen't have Content/versionread policy

---

src/bundle/Controller/PolicyController.php
src/bundle/Controller/RoleAssignmentController.php
src/bundle/Controller/RoleController.php
src/bundle/Resources/views/admin/policy/list.html.twig
src/bundle/Resources/views/admin/role/list.html.twig
src/bundle/Resources/views/admin/role_assignment/list.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-29216
| Doc needed?  |no

EZP-29216: Implement permissions for Role management in Admin Panel

---

src/bundle/Resources/views/content/content_edit/content_create.html.twig
src/lib/Menu/ContentCreateRightSidebarBuilder.php
src/lib/Menu/ContentEditRightSidebarBuilder.php

| Tickets       | https://jira.ez.no/browse/EZP-29214

EZP-29214: Error 403 after trying to publish CI without Content/Publish or Content/Edit policies

---

src/bundle/Resources/config/services/ui_config/common.yml
src/bundle/Resources/public/js/scripts/admin.location.view.js
src/bundle/Resources/views/content/locationview.html.twig
src/lib/UI/Config/Provider/Module/SubItemsList.php
src/lib/UI/Module/Subitems/ContentViewParameterSupplier.php

| Tickets       | https://jira.ez.no/browse/EZP-29154
Associated with: https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/65
Number of sub-items could be changed in `src/bundle/Resources/config/ezplatform_default_settings.yml:26`

EZP-29154: As a developer, I want to configure the number of sub-items displayed in the sub-items list

---

src/bundle/Resources/public/scss/_mixins.scss
src/bundle/Resources/public/scss/fieldType/edit/_base-preview.scss
src/bundle/Resources/public/scss/fieldType/edit/_ezgmaplocation.scss

Reorganized SCSS mixins and moved all of them to one file

---

src/lib/Behat/PageElement/Notification.php

[Behat] Wait until notification is closed

---

src/bundle/Controller/ContentViewController.php
src/bundle/DependencyInjection/Configuration/Parser/Pagination.php
src/bundle/Resources/config/ezplatform_default_settings.yml
src/bundle/Resources/config/services/controllers.yml
src/bundle/Resources/views/content/tab/policies/tab.html.twig
src/bundle/Resources/views/content/tab/roles/tab.html.twig
src/bundle/Resources/views/content/tab/urls.html.twig
src/bundle/Resources/views/content/tab/versions/tab.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-29259
This PR also add pagination limit parameters for system url and custom url lists.

EZP-29259: Fix pagination for content displayed by route _ez_content_view

---

src/bundle/Resources/views/parts/navigation.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-29295

EZP-29295: Second level of main menu has no context passed

---

src/lib/Behat/PageElement/Fields/DateAndTime.php
src/lib/Behat/PageElement/Fields/Time.php

Followup for fixing issue with setting value in time field.

EZP-28171-followup fixing time field issue

---

.prettierrc
src/bundle/Resources/public/js/scripts/admin.content.edit.js

| Tickets       | https://jira.ez.no/browse/EZP-29309
It should be tested with: https://github.com/ezsystems/ezplatform-page-builder/pull/76
Otherwise, it's purely developer's feature.

EZP-29309: Validators with errors not exposed on the frontend

---

src/bundle/Resources/views/content/tab/locations/panel_swap.html.twig
src/bundle/Resources/views/content/tab/locations/tab.html.twig
src/lib/Tab/LocationView/LocationsTab.php

| Tickets       | https://jira.ez.no/browse/EZP-29312

EZP-29312: Implement permissions for Swap Location in Locations tab

---

src/bundle/Resources/views/content/tab/versions/table.html.twig
src/lib/UI/Value/Content/VersionInfo.php
src/lib/UI/Value/ValueFactory.php

| Tickets       | https://jira.ez.no/browse/EZP-29313

EZP-29313: Implement permissions for Version remove in Versions tab

---

src/bundle/Resources/views/layout.html.twig

| Tickets       | https://jira.ez.no/browse/EZEE-2121

EZEE-2121: Added header block in page layout

---

src/bundle/Resources/public/js/scripts/admin.picker.js
src/bundle/Resources/public/scss/_picker.scss
src/bundle/Resources/public/scss/ezplatform.scss
src/bundle/Resources/views/admin/search/search.html.twig
src/bundle/Resources/views/content/content_edit/parts/javascripts.html.twig
src/bundle/Resources/views/content/content_edit/parts/stylesheets.html.twig
src/bundle/Resources/views/form_fields.html.twig
src/bundle/Resources/views/layout.html.twig
src/lib/Form/DataTransformer/DateTimePickerTransformer.php
src/lib/Form/Type/DateTimePickerType.php

| Tickets       | https://jira.ez.no/browse/EZEE-2110

EZEE-2110: Implement logic to hide/show blocks based on visibility dates

---

src/bundle/Resources/public/scss/_dashboard.scss

| Tickets       | [EZP-29243](https://jira.ez.no/browse/EZP-29243)
- Updated styling of create button in dashboard (icon was too close to text)

[EZP-29243] Update styling of create button in dashboard

---

src/bundle/Controller/TrashController.php
src/bundle/Resources/views/admin/trash/list.html.twig
src/lib/Menu/LeftSidebarBuilder.php

| Tickets       | https://jira.ez.no/browse/EZP-29203

EZP-29203: Implement permissions for Trash

---

src/bundle/Resources/public/scss/_extra-actions.scss

| Tickets       | https://jira.ez.no/browse/EZP-28805

EZP-28805: Inconsistency for Publish later container - Date & Time input is almost invisible

---

src/lib/Tests/Form/DataTransformer/LocationsTransformerTest.php

| Tickets       | https://jira.ez.no/browse/EZP-29337

EZP-29337: Fix LocationsTransformerTest unit test

---

src/bundle/Resources/public/scss/_notifications.scss

| Tickets       | https://jira.ez.no/browse/EZP-29180
Changed styling of notifications. 
**Changes closely related with:** https://github.com/ezsystems/ezplatform-admin-ui/pull/539

EZP-29180: Update styling of notifications

---

src/bundle/Resources/config/services.yml
src/lib/EventListener/RequestLocaleListener.php

| Tickets       | https://jira.ez.no/browse/EZP-29322
Refers to https://github.com/ezsystems/ezpublish-kernel/pull/2361

EZP-29322: As an editor I want to use translated Admin panel

---

src/bundle/Controller/ContentViewController.php

| Tickets       | https://jira.ez.no/browse/EZP-29342

EZP-29342: Deleting related object for ezobjectrelations field throws error 500

---

src/bundle/Resources/public/scss/fieldType/edit/_ezrichtext.scss

| Tickets       | https://jira.ez.no/browse/EZP-29357
**Before**
**After**

EZP-29375: Add style for blockquote in RichText

---

src/lib/Behat/PageElement/UniversalDiscoveryWidget.php

| Tickets       | https://jira.ez.no/browse/EZP-29278
Descreased the time spent waiting of UDW to disappear - 5 sec was too long and notifications started to disappear too.

EZP-29278: Wait max 2 seconds for UDW to disaapear

---

features/ContentCreation.feature
features/ContentTypeFields.feature
src/lib/Behat/BusinessContext/ContentUpdateContext.php
src/lib/Behat/BusinessContext/ContentViewContext.php
src/lib/Behat/BusinessContext/NavigationContext.php
src/lib/Behat/PageElement/ContentField.php
src/lib/Behat/PageElement/DateAndTimePopup.php
src/lib/Behat/PageElement/Fields/Checkbox.php
src/lib/Behat/PageElement/Fields/ContentRelationMultiple.php
src/lib/Behat/PageElement/Fields/ContentRelationSingle.php
src/lib/Behat/PageElement/Fields/Date.php
src/lib/Behat/PageElement/Fields/DateAndTime.php
src/lib/Behat/PageElement/Fields/RichText.php
src/lib/Behat/PageElement/Fields/Time.php
src/lib/Behat/PageElement/PlatformElementFactory.php
src/lib/Behat/PageElement/Tables/ContentRelationTable.php
src/lib/Behat/PageElement/Tables/SubItemsTable.php
src/lib/Behat/PageObject/ContentItemPage.php

As a QA
I want to cover with tests ez-fields (all usable except of media, binary and image) within the area of basic management of content edition
To increase the detection of errors in this area

EZP-29275 As a QA I want to cover scenarios of testing fields editing in content management

---

.prettierrc
src/bundle/Resources/public/scss/_custom.scss
src/bundle/Resources/public/scss/_general.scss
src/bundle/Resources/public/scss/ezplatform.scss
src/bundle/Resources/public/scss/functions/_calculate.rem.scss

| Tickets       | https://jira.ez.no/browse/EZP-29426

EZP-29426: As a frontend developer I would like to convert size in pixels to rems with a function

---

src/bundle/Controller/BookmarkController.php
src/lib/Pagination/Pagerfanta/BookmarkAdapter.php
src/lib/UI/Dataset/BookmarksDataset.php

| Tickets       | https://jira.ez.no/browse/EZP-29446

EZP-29446: Broken pagination in Bookmarks list when is more than 25 elements

---

src/lib/Behat/PageElement/UniversalDiscoveryWidget.php

| Tickets       | Part of  https://jira.ez.no/browse/EZP-29187, https://jira.ez.no/browse/EZP-29182
https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/94 changed the way items are selected in UDW - there is no longer a "Select content" button, but individual "add" buttons for each UDW item if UDW is in multiselect mode. For single mode, there is no "select content" button - selecting and confirming is enough. This PR adjust tests for that fact.

EZP-29182/EZP-29187: Adjust tests for UDW selection changes

---

src/bundle/Resources/views/admin/content_type/list.html.twig
src/bundle/Resources/views/admin/search/search_table_row.html.twig
src/bundle/Resources/views/dashboard/tab/all_content.html.twig
src/bundle/Resources/views/dashboard/tab/all_media.html.twig
src/bundle/Resources/views/dashboard/tab/my_content.html.twig
src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig
src/bundle/Resources/views/dashboard/tab/my_media.html.twig
src/bundle/Resources/views/link_manager/list.html.twig
src/bundle/Resources/views/link_manager/view.html.twig

| Tickets       | https://jira.ez.no/browse/EZEE-2016
Fixes date format.

EZEE-2016: Fix date/time format on Dashboard & Link manager

---

src/bundle/Resources/public/scss/_general.scss

Added the utility class for preventing scroll

---

behat_suites.yml
features/ContentCreation.feature
src/lib/Behat/BusinessContext/ContentUpdateContext.php
src/lib/Behat/BusinessContext/ContentViewContext.php
src/lib/Behat/Helper/EzEnvironmentConstants.php
src/lib/Behat/Helper/PlatformEnvironmentConstants.php
src/lib/Behat/PageElement/ElementFactory.php
src/lib/Behat/PageObject/PageObjectFactory.php

| Tickets       | [EZP-29143](https://jira.ez.no/browse/EZP-29143)
Testing reusability of admin-ui tests with demo environments.

EZP-29143 run test features on Demo version without changing feature files

---

src/bundle/Templating/Twig/UserPreferencesGlobalExtension.php
src/lib/UserSetting/Setting/Timezone.php

| Tickets       | https://jira.ez.no/browse/EZP-29582

EZP-29582: Lazy loading for UserPreferencesGlobalExtension

---

src/lib/Behat/Helper/Environment.php

Name of this service was changed between v2.1 and v2.2. This PR is just the update for behat tests.

EZEE-2304 - installer service name update

---

src/bundle/Resources/public/js/scripts/admin.location.change.language.js
src/bundle/Resources/public/scss/_tables.scss
src/bundle/Resources/views/admin/content_type/view.html.twig
src/bundle/Resources/views/admin/systeminfo/composer.html.twig
src/bundle/Resources/views/admin/systeminfo/database.html.twig
src/bundle/Resources/views/admin/systeminfo/hardware.html.twig
src/bundle/Resources/views/admin/systeminfo/php.html.twig
src/bundle/Resources/views/admin/systeminfo/symfony_kernel.html.twig
src/bundle/Resources/views/content/locationview.html.twig
src/bundle/Resources/views/link_manager/view.html.twig
src/bundle/Templating/Twig/TabExtension.php

| Tickets       | https://jira.ez.no/browse/EZEE-2206
This changes are needed to 
- allow to fetch pagination parameters from the request and set them as parameters available for SubmissionTab
- add support to more than one language switcher
see [https://github.com/ezsystems/ezplatform-form-builder/pull/36](https://github.com/ezsystems/ezplatform-form-builder/pull/36)

EZEE-2206: As an editor I want to view the form submissions

---

src/bundle/Resources/config/services/ui_config/common.yml
src/bundle/Resources/public/js/scripts/admin.format.date.js
src/bundle/Resources/public/js/scripts/helpers/timezone.helper.js
src/bundle/Resources/views/admin/content_type/list.html.twig
src/bundle/Resources/views/admin/search/search_table_row.html.twig
src/bundle/Resources/views/content/content_edit/content_edit.html.twig
src/bundle/Resources/views/content/content_edit/user_edit.html.twig
src/bundle/Resources/views/content/tab/details.html.twig
src/bundle/Resources/views/content/tab/versions/table.html.twig
src/bundle/Resources/views/dashboard/tab/all_content.html.twig
src/bundle/Resources/views/dashboard/tab/all_media.html.twig
src/bundle/Resources/views/dashboard/tab/my_content.html.twig
src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig
src/bundle/Resources/views/dashboard/tab/my_media.html.twig
src/bundle/Resources/views/fieldtypes/edit/relation_base.html.twig
src/bundle/Resources/views/layout.html.twig
src/bundle/Resources/views/link_manager/list.html.twig
src/bundle/Resources/views/link_manager/view.html.twig
src/bundle/Resources/views/user/settings/list.html.twig
src/lib/UI/Config/Provider/DateFormat.php
src/lib/UI/Config/Provider/Timezone.php

| Tickets       | https://jira.ez.no/browse/EZP-29579
| Tests pass?   | yes?

EZP-29579 As an Editor, I want to see dates in preferred timezone

---

src/bundle/Resources/public/js/scripts/core/custom.dropdown.js

CustomDropdown class: fixed item selection

---

src/bundle/Resources/views/fieldtypes/preview/ezobjectrelationlist_row.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-29670

EZP-29670: Date for Single and Multiple relation is not updated with the user settings timezone

---

src/bundle/Resources/translations/ezrepoforms_content_type.en.xliff
src/bundle/Resources/translations/ezrepoforms_role.en.xliff
src/bundle/Resources/views/Limitation/null_limitation_values.html.twig
src/bundle/Resources/views/Limitation/udw_limitation_value.html.twig
src/bundle/Resources/views/admin/content_type/field_types.html.twig

[i18n] Added missing UI translations

---

src/bundle/Resources/public/scss/_admin.section-view.scss
src/bundle/Resources/public/scss/_extra-actions.scss
src/bundle/Resources/public/scss/_login.scss
src/bundle/Resources/public/scss/core/_custom.dropdown.scss
src/bundle/Resources/public/scss/ezplatform-bootstrap.scss
src/bundle/Resources/public/scss/ezplatform.scss

| Tickets       | https://jira.ez.no/browse/EZP-29672

EZP-29672: Missing spacing between form fields

---

src/bundle/Resources/public/scss/_admin.content-type-view.scss
src/bundle/Resources/public/scss/ezplatform.scss

| Tickets       | https://jira.ez.no/browse/EZP-29654

EZP-29654: No margin at the bottom of the page on Safari

---

src/bundle/Controller/ContentViewController.php
src/bundle/Controller/Location/TrashLocationWithAssetController.php
src/bundle/Resources/config/routing.yml
src/bundle/Resources/config/services.yml
src/bundle/Resources/public/js/scripts/button.state.radio.toggle.js
src/bundle/Resources/public/scss/_buttons.scss
src/bundle/Resources/public/scss/_forms.scss
src/bundle/Resources/public/scss/_modals.scss
src/bundle/Resources/translations/forms.en.xliff
src/bundle/Resources/translations/messages.en.xliff
src/bundle/Resources/views/content/locationview.html.twig
src/bundle/Resources/views/content/modal_location_trash_with_asset.html.twig
src/bundle/Resources/views/content/modal_location_trash_with_single_asset.html.twig
src/lib/Form/Data/Location/LocationTrashWithAssetData.php
src/lib/Form/Factory/FormFactory.php
src/lib/Form/Type/Location/LocationTrashWithAssetType.php
src/lib/Menu/ContentRightSidebarBuilder.php
src/lib/Specification/Content/ContentHaveAssetRelation.php
src/lib/Specification/Content/ContentHaveUniqueRelation.php
src/lib/Validator/Constraints/LocationHaveUniqueAssetRelation.php
src/lib/Validator/Constraints/LocationHaveUniqueAssetRelationValidator.php

| Tickets       | https://jira.ez.no/browse/EZP-29408
Built on current implementation in: https://github.com/ezsystems/ezplatform-admin-ui/pull/580 and in https://github.com/ezsystems/ezpublish-kernel/pull/2409

EZP-29408: As an editor I want to delete a content item with an image asset field

---

src/bundle/Resources/public/js/scripts/fieldType/base/base-field.js
src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js
src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss

| Tickets       | https://jira.ez.no/browse/EZP-29688
Implemented new behaviour on field type validation while trying to publish a content item. It differs from regular validation while typing incorrect data in fields. Thanks to this approach it will be easier to implement: https://jira.ez.no/browse/EZP-29679

EZP-29688: eZ Map Location fieldtype validation error message is not displaying correctly

---

src/bundle/Resources/views/notifications/notification_row.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-29620
| Bug fix?      | yes/

EZP-29620: Date is not changed on Notifications pop-up

---

src/bundle/Resources/config/universal_discovery_widget.yml
src/bundle/Resources/views/admin/content_type/field_types.html.twig
src/bundle/Resources/views/fieldtypes/edit/relation_base.html.twig
src/lib/UniversalDiscovery/Event/Subscriber/ObjectRelationStartingLocationId.php

| Tickets       | https://jira.ez.no/browse/EZP-29682

EZP-29682: Cannot set default Location for objectrelationlist

---

src/bundle/Resources/views/admin/systeminfo/composer.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-29623

EZP-29623: Fix System Information / Composer isn't covered on timezone change

---

src/lib/Behat/Helper/EzEnvironmentConstants.php

| Tickets       | [EZEE-2304](https://jira.ez.no/browse/EZEE-2304)
As a QA
I'd like to adjust the tests from the date-based-publisher and flex-workflow to let us run test features on Enterprise-Demo, without changes in feature files or steps code, and to configure this tests to run in nightly builds
To improve QA processes for EE-demo environments.
Related PRs:
https://github.com/ezsystems/ezplatform-ee-demo/pull/77
https://github.com/ezsystems/ezplatform-page-builder/pull/176
https://github.com/ezsystems/flex-workflow/pull/115 …

EZEE-2304 As a QA I want to run DBP and FXW test features on Enterprise Demo

---

features/ContentTypeFields.feature
src/bundle/Resources/translations/fieldtypes_preview.en.xliff
src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig
src/lib/Behat/PageElement/Fields/EmailAddress.php
src/lib/Behat/PageElement/Fields/EzFieldElement.php

| Tickets       | https://jira.ez.no/browse/EZP-29684
- [https://github.com/ezsystems/ezpublish-kernel/pull/2461](https://github.com/ezsystems/ezpublish-kernel/pull/2461)
- [https://github.com/ezsystems/repository-forms/pull/255](https://github.com/ezsystems/repository-forms/pull/255)

EZP-29684: Remove the hyphen from the "E-mail" in whole application

---

src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-29624

EZP-29624: Value in ezdatetime field is not changed

---

src/bundle/Resources/public/js/scripts/admin.notifications.modal.js

| Tickets       | https://jira.ez.no/browse/EZP-29663

EZP-29663: Login page redirects to notifications/count

---

src/bundle/Resources/public/js/scripts/fieldType/base/base-field.js
src/bundle/Resources/public/scss/_mixins.scss
src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss

| Tickets       | https://jira.ez.no/browse/EZEE-2490

EZEE-2490: Update BaseField validator to handle custom elements definition

---

src/bundle/Resources/views/Security/login.html.twig

Using the bundle in a spanish project, where I need to show this message in spanish

Add twig filter to translate error message

---

src/bundle/Controller/ContentViewController.php

| Tickets       | https://jira.ez.no/browse/EZP-29715
| Bug fix?      | yes/

EZP-29715: Javascript error with ez platform 2.3. maybe related to the new ezimageasset fieldtype

---

features/ContentType.feature
features/ContentTypeGroup.feature
features/Languages.feature
features/ObjectStates.feature
features/Roles.feature
features/Sections.feature
src/lib/Behat/BusinessContext/AdministrationContext.php
src/lib/Behat/BusinessContext/NotificationContext.php
src/lib/Behat/PageElement/AdminList.php

Adds pagination handling for administration pages. Changes in notifications were obligatory because new notification covers over the pagination section with `Next` button, which causes errors.

EZP-29712 Run nightly Behat tests on demo metarepos

---

src/lib/Behat/PageElement/Tables/SimpleTable.php
src/lib/Behat/PageObject/SectionPage.php

| Tickets       | [EZP-29712](https://jira.ez.no/browse/EZP-29712)
Adds pagination handling in `Admin->Sections`

EZP-29712 Run nightly Behat tests on demo metarepos - pagination in sections

---

src/bundle/DependencyInjection/Configuration/Parser/Module/UniversalDiscoveryWidget.php

| Tickets       | https://jira.ez.no/browse/EZP-29730

EZP-29730: Cannot add UDW configuration from YAML file located in other bundle

---

src/bundle/Resources/public/scss/_buttons.scss
src/bundle/Resources/public/scss/_general.scss
src/bundle/Resources/public/scss/_icons.scss

You have to test the look of:
- images in the image field type,
- images in the image asset field type,
- button icons in AlloyEditor UI

CSS coding standard fixes

---

src/bundle/Controller/BulkOperation/BulkOperationController.php
src/bundle/Resources/config/routing.yml
src/bundle/Resources/config/services.yml
src/bundle/Resources/config/services/rest.yml
src/lib/EventListener/ApiRequestListener.php
src/lib/REST/Input/Parser/BulkOperation.php
src/lib/REST/Input/Parser/Operation.php
src/lib/REST/Output/ValueObjectVisitor/BulkOperationResponse.php
src/lib/REST/Value/BulkOperation.php
src/lib/REST/Value/BulkOperationResponse.php
src/lib/REST/Value/Operation.php
src/lib/REST/Value/OperationResponse.php

| Tickets       | https://jira.ez.no/browse/EZP-29713
Proposed solution creates API endpoint that in a payload can accept all structured requests made to any kernel api endpoint. `content` parameter must be properly escaped xml or json string. Keys name are not connected anyhow to type of operations i.e. you can name them however you want as long as there are unique.
```
POST http://localhost:8080/admin/api/bulk
Cache-Control: no-cache
Content-Type: application/vnd.ez.api.BulkOperation+json
Accept: …
```

EZP-29713: As an Editor, I want to Move multiple content items at a time

---

src/bundle/Resources/public/js/scripts/admin.location.view.js
src/bundle/Resources/views/content/locationview.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-28067 https://jira.ez.no/browse/EZP-29713
Needed for https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/107
As discussed: https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/107#discussion_r228430123
**Should be merged after:** https://github.com/ezsystems/ezplatform-admin-ui/pull/691
Why another PR? Because features in https://github.com/ezsystems/ezplatform-admin-ui/pull/691 are very generic and support generic bulk. This ticket and …

EZP-28067; EZP-29713: Implement bulk delete, bulk move - pass udwConfig to Sub-items

---

src/bundle/Resources/public/js/scripts/button.content.edit.js

| Tickets       | https://jira.ez.no/browse/EZP-29702

EZP-29702: Can't create new draft due to lack of language code in URL

---

src/bundle/Controller/DashboardController.php
src/bundle/Resources/translations/dashboard.en.xliff
src/bundle/Resources/translations/menu.en.xliff
src/bundle/Resources/views/dashboard/dashboard.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-29793

EZP-29793: Implement permissions for the Create button on the dashboard

---

src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js
src/bundle/Resources/views/fieldtypes/edit/ezgmaplocation.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-29728

EZP-29728: Longitude validation appears when user try to publish after editing

---

src/bundle/Resources/config/services/menu.yml
src/lib/Menu/Admin/ReorderMenuListener.php

| Tickets       | https://jira.ez.no/browse/EZP-29171
Adds priority to series of menu listeners to build it in correct order.
https://github.com/ezsystems/ezplatform-form-builder/pull/105
https://github.com/ezsystems/ezplatform-page-builder/pull/251

EZP-29171: Update Navbar menu items order

---

src/bundle/Resources/public/js/scripts/core/custom.dropdown.js
src/bundle/Resources/public/scss/core/_custom.dropdown.scss

| Tickets       | https://jira.ez.no/browse/EZP-29828

EZP-29828: Custom Dropdown improvements

---

src/bundle/Resources/public/scss/_icons.scss
src/bundle/Resources/public/scss/_preview.scss

| Tickets       | [EZP-29827](https://jira.ez.no/browse/EZP-29827)

EZP-29827: Harmonized Preview Switcher in Content Section Editing view

---

src/lib/Behat/BusinessContext/NavigationContext.php

| Tickets       | [EZEE-1674](https://jira.ez.no/browse/EZEE-1674)
Adding step that goes to the subitem of current item.

EZEE-1674 Create a spike of Form Builder scenarios for v2 - new navigation step

---

src/bundle/Resources/translations/forms.en.xliff
src/bundle/Resources/translations/search.en.xliff

Added missing translations

---

src/lib/Behat/PageElement/AdminList.php
src/lib/Behat/PageElement/Pagination.php
src/lib/Behat/PageElement/PlatformElementFactory.php
src/lib/Behat/PageElement/Tables/SubItemsTable.php

| Tickets       | http://jira.ez.no/browse/EZP-29714
Required by https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/112

EZP-29714: Adjust tests for pagination in Subitems list

---

src/bundle/Resources/public/js/scripts/core/custom.dropdown.js

| Tickets       | https://jira.ez.no/browse/EZP-29854
It's hardly testable in eZ Platform. Requires customizing the template of a field that implements custom dropdown feature.

EZP-29854: Cannot remove a selected item from custom dropdown

---

src/bundle/Resources/translations/forms.en.xliff
src/bundle/Resources/translations/search.en.xliff

Reverts ezsystems/ezplatform-admin-ui#729

Revert "Added missing translations"

---

src/bundle/Controller/ContentViewController.php

| Tickets       | https://jira.ez.no/browse/EZP-29855 

EZP-29855: Expose `pages` query param in Location View / Versions tab for implementing custom pagination

---

src/bundle/Resources/views/content/content_edit/content_create.html.twig
src/lib/RepositoryForms/View/ViewParametersListener.php
src/lib/Tests/RepositoryForms/View/ViewParametersListenerTest.php

| Tickets       | https://jira.ez.no/browse/EZP-29856

EZP-29856: Expose form's data ContentCreateStruct in content create view

---

src/lib/Behat/PageElement/Notification.php

Fixing a problem with steps not keeping up with the disappearing notification

---

composer.json
src/lib/Behat/Helper/TableNodeExtension.php
src/lib/Behat/PageElement/DateAndTimePopup.php
src/lib/Behat/PageElement/ElementFactory.php
src/lib/Behat/PageObject/FolderPreview.php
src/lib/Behat/PageObject/PageObjectFactory.php
src/lib/Behat/PageObject/PreviewPage.php
src/lib/Tests/Behat/ExtendedTableNodeTest.php

| Tickets       |https://jira.ez.no/browse/EZEE-2305
Things done:
1) Page and Element Factories are not only created once, instead of every time
2) Added a utility class for easier handling of Behat TableNodes (in order to run Unit Tests Behat had to be added to dev section fo composer.json).

EZEE-2305: Port PageBuilder tests to demo

---

src/bundle/Resources/public/scss/core/_custom.dropdown.scss

| Tickets       | https://jira.ez.no/browse/EZP-29863

EZP-29863: Exclamation mark is misaligned for Selection validation

---

src/bundle/Controller/User/UserForgotPasswordController.php
src/bundle/Controller/UserProfile/UserPasswordChangeController.php
src/bundle/Resources/views/admin/content_type/field_types.html.twig
src/lib/Form/Factory/FormFactory.php
src/lib/Form/Type/User/UserPasswordChangeType.php
src/lib/Form/Type/User/UserPasswordResetType.php

| Tickets       | https://jira.ez.no/browse/EZP-29122
:exclamation:  **Depends on https://github.com/ezsystems/ezpublish-kernel/pull/2482 and https://github.com/ezsystems/repository-forms/pull/262**

EZP-29122: As a developer, I want to configure password policies in ezuser

---

src/lib/Tests/Form/DataTransformer/LocationsTransformerTest.php

Fixed LocationsTransformerTest::testReverseTransformWithIds (v1.3)

---

src/bundle/Resources/public/js/scripts/fieldType/ezauthor.js

| Tickets       | https://jira.ez.no/browse/EZP-29738

EZP-29738: Triple validation message for invalid email address

---

src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
src/lib/Behat/PageElement/Fields/RichText.php

| Tickets       | https://jira.ez.no/browse/EZP-29877

EZP-29877: Custom tags and nested table focus issue

---

src/bundle/Resources/views/admin/content_type/tab/translations.html.twig
src/bundle/Resources/views/content/tab/translations/tab.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-29911

EZP-29911: Incorrect action attribute value in the translation remove form for content

---

src/lib/Tests/EventListener/RequestLocaleListenerTest.php

| Tickets       | https://jira.ez.no/browse/EZP-29923

EZP-29923: Add unit tests to RequestLocaleListener

---

src/bundle/Resources/translations/content_type.en.xliff
src/bundle/Resources/translations/forms.en.xliff
src/bundle/Resources/translations/locationview.en.xliff
src/bundle/Resources/translations/messages.en.xliff

JIRA: - 
This PR updates xliff files.

Updated translation files

---

src/bundle/Resources/public/scss/_general.scss

| Tickets       | https://jira.ez.no/browse/EZP-29913

EZP-29913: Missing disabled look and feel for some of the fields when translating Content Type

---

src/bundle/Resources/public/scss/_custom.scss
src/bundle/Resources/public/scss/_icons.scss
src/bundle/Resources/views/layout.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-29993

EZP-29993: As the eZ Platform developer I would like to use Sass compiler in the Admin UI modules styles

---

src/bundle/Controller/ContentOnTheFlyController.php

| Tickets       | [EZP-30001](https://jira.ez.no/browse/EZP-30001)

EZP 30001 : Limiting "Content\Create" to Section disables "Create" button in COTF

---

src/lib/Tests/Form/DataTransformer/LocationsTransformerTest.php

Unit tests fix ported from https://github.com/ezsystems/ezplatform-admin-ui/pull/755

Fix ported to 2.2 to prevent tests from failing

---

src/bundle/Resources/public/scss/_buttons.scss
src/bundle/Resources/public/scss/_icons.scss
src/bundle/Resources/public/scss/_main-row.scss
src/bundle/Resources/public/scss/ezplatform.scss
src/bundle/Resources/views/admin/base.html.twig
src/bundle/Resources/views/admin/bookmark/list.html.twig
src/bundle/Resources/views/admin/content_draft/list.html.twig
src/bundle/Resources/views/admin/content_type_group/base.html.twig
src/bundle/Resources/views/admin/language/base.html.twig
src/bundle/Resources/views/admin/object_state/base.html.twig
src/bundle/Resources/views/admin/object_state_group/base.html.twig
src/bundle/Resources/views/admin/policy/base.html.twig
src/bundle/Resources/views/admin/role/base.html.twig
src/bundle/Resources/views/admin/role_assignment/base.html.twig
src/bundle/Resources/views/admin/search/search.html.twig
src/bundle/Resources/views/admin/section/base.html.twig
src/bundle/Resources/views/admin/trash/list.html.twig
src/bundle/Resources/views/content/content_edit/content_create_draft.html.twig
src/bundle/Resources/views/content/content_edit/content_edit_base.html.twig
src/bundle/Resources/views/content/locationview.html.twig
src/bundle/Resources/views/dashboard/dashboard.html.twig
src/bundle/Resources/views/layout.html.twig
src/bundle/Resources/views/parts/tab/content_type.html.twig
src/lib/Behat/PageElement/Fields/Selection.php

| Tickets       | [EZP-29168](https://jira.ez.no/browse/EZP-29168)

EZP-29168: Side and Context Menu bars styling improvements

---

src/bundle/Resources/views/admin/section/create.html.twig
src/bundle/Resources/views/admin/section/update.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-30058
| Bug fix?      |  yes

EZP-30058: Swapped name and identifier fields in Section form

---

src/bundle/Resources/public/scss/_view-content.scss

| Tickets       | https://jira.ez.no/browse/EZP-30069

EZP-30069: As an editor I would like to change manually the width of content tree panel

---

src/bundle/Resources/views/fieldtypes/edit/ezmedia.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-29857
previous:
https://github.com/ezsystems/ezplatform-admin-ui/pull/735
adminUI:
https://github.com/ezsystems/repository-forms/pull/276

EZP-29857: Unable to upload audio to Media field type

---

src/bundle/Templating/Twig/PathStringExtension.php
src/lib/Form/Type/Location/LocationTrashContainerType.php
src/lib/Validator/Constraints/LocationHasChildrenValidator.php

| Tickets       | https://jira.ez.no/browse/EZP-30093
PR fixes typehints for API to avoid autowire issues.

Change to typehint for API to avoid autowire issues

---

src/bundle/Controller/ContentController.php
src/bundle/Controller/ContentTypeController.php
src/bundle/Controller/ContentTypeGroupController.php
src/bundle/Controller/LanguageController.php
src/bundle/Controller/LocationController.php
src/bundle/Controller/PolicyController.php
src/bundle/Controller/RoleAssignmentController.php
src/bundle/Controller/SectionController.php
src/bundle/Controller/TranslationController.php

| Tickets       | [https://jira.ez.no/browse/EZP-30088](https://jira.ez.no/browse/EZP-30088)

EZP-30088: Remove isValid check if a form is handled by submitHandler

---

src/lib/Behat/BusinessContext/ContentViewContext.php
src/lib/Behat/PageElement/DraftConflictDialog.php
src/lib/Behat/PageElement/PlatformElementFactory.php
src/lib/Behat/PageElement/Tables/ContentRelationTable.php
src/lib/Behat/PageElement/Tables/DraftConflictTable.php
src/lib/Behat/PageElement/Tables/IconLinkedListTable.php
src/lib/Behat/PageElement/Tables/LinkedListTable.php
src/lib/Behat/PageElement/Tables/SimpleListTable.php
src/lib/Behat/PageElement/Tables/SystemInfoTable.php
src/lib/Behat/PageElement/Tables/Table.php
src/lib/Behat/PageElement/Tables/TrashTable.php
src/lib/Behat/PageObject/ContentTypeGroupPage.php

| Tickets       | [EZP-29999](https://jira.ez.no/browse/EZP-29999)
followup to PR https://github.com/ezsystems/ezplatform-admin-ui/pull/805 with the fix for behat tests

EZP-29999 behat tests followup

---

src/bundle/Resources/public/scss/_main-row.scss
src/bundle/Resources/views/errors/403.html.twig
src/bundle/Resources/views/errors/404.html.twig
src/bundle/Resources/views/errors/error.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-30125

EZP-30125: Error page is displayed with right sidebar

---

src/bundle/Resources/views/content/content_edit/content_create.html.twig
src/lib/RepositoryForms/View/ViewParametersListener.php
src/lib/Tests/RepositoryForms/View/ViewParametersListenerTest.php

https://github.com/ezsystems/ezplatform-admin-ui/pull/734 backported for https://github.com/ezsystems/date-based-publisher/pull/90 for eZ Platform 2.3.

[Backported] EZP-29856: Expose form's data ContentCreateStruct in content create view

---

src/bundle/Resources/public/js/scripts/admin.location.content.tree.js
src/bundle/Resources/views/content/locationview.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-30066

EZP-30066: As an editor I would like to see current location marked as selected in the content tree

---

src/bundle/Resources/encore/ez.js.config.js
src/bundle/Resources/public/js/scripts/admin.form.autosubmit.js
src/bundle/Resources/translations/object_state.en.xliff
src/bundle/Resources/views/content/tab/details.html.twig
src/lib/Form/Type/ObjectState/ContentObjectStateUpdateType.php

| Tickets       | [EZP-30100](https://jira.ez.no/browse/EZP-30100)
- autosubmit forms mechanism
- autosubmit object state form

EZP-30100: As an Editor I want to change Object States with dropdowns instead of Set buttons

---

src/bundle/Resources/config/services/rest.yml

| Tickets       | https://jira.ez.no/browse/EZP-30065
Followup to #854 which got merged with a bug.

EZP-30065: Fixed service definitions for ContentTree Input Parsers

---

src/bundle/Resources/views/admin/bookmark/list.html.twig
src/bundle/Resources/views/admin/content_draft/list.html.twig
src/bundle/Resources/views/admin/content_type/list.html.twig
src/bundle/Resources/views/admin/search/search_table_row.html.twig
src/bundle/Resources/views/admin/trash/list.html.twig
src/bundle/Resources/views/dashboard/tab/all_content.html.twig
src/bundle/Resources/views/dashboard/tab/all_media.html.twig
src/bundle/Resources/views/dashboard/tab/my_content.html.twig
src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig
src/bundle/Resources/views/dashboard/tab/my_media.html.twig
src/bundle/Resources/views/form_fields.html.twig

| Tickets       | [EZP-30174](https://jira.ez.no/browse/EZP-30174)

EZP-30174: Styled Content Type icons in Admin UI

---

src/bundle/Resources/public/js/scripts/admin.location.content.tree.js
src/bundle/Resources/public/scss/_view-content.scss
src/bundle/Resources/views/content/locationview.html.twig

| Tickets       |  https://jira.ez.no/browse/EZP-30072

EZP-30072: As an editor I would like to see the content tree state restored after reloading a page

---

src/bundle/Resources/views/content/locationview.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-30209

EZP-30209: Expose logged User ID to ContentTree

---

src/bundle/Resources/translations/content.en.xliff
src/bundle/Resources/translations/locationview.en.xliff
src/bundle/Resources/translations/menu.en.xliff
src/bundle/Resources/translations/messages.en.xliff

Updated translations

---

src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js

| Tickets       | https://jira.ez.no/browse/EZP-30241

EZP-30241: Characters counter does not work when formatted style is used

---

src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-inlinecustomtag-update.js

| Tickets       | https://jira.ez.no/browse/EZP-30287

EZP-30287: Cannot add inline custom tag to table

---

src/lib/RepositoryForms/Data/ContentTranslationData.php
src/lib/Tests/RepositoryForms/Data/Mapper/ContentTranslationMapperTest.php

| Tickets       | [EZP-30297](EZP-30297)
- [] Coding standards (`$ composer fix-cs`)

EZP-30297: Error when I try to add a translation for a user object - fix tests

---

src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/base.js

| Tickets       | https://jira.ez.no/browse/EZP-30291

EZP-30291: Console error when adding link inside inline custom tag

---

src/bundle/Resources/config/universal_discovery_widget.yml
src/bundle/Templating/Twig/UniversalDiscoveryExtension.php

| Tickets       | https://jira.ez.no/browse/EZP-30310
This PR goes along with https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/160

EZEE-30310: SearchLimit UDW: UDW search limit configuration in YAML

---

src/bundle/Resources/public/scss/_user-menu.scss

| Tickets       | https://jira.ez.no/browse/EZP-30308

EZP-30308: User menu changes width depending on user name length

---

src/bundle/Resources/public/js/alloyeditor/src/toolbars/ez-add.js
src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js

| Tickets       | https://jira.ez.no/browse/EZP-30176

EZP-30176: Anchor icon changes position in table

---

features/ContentTypeFields.feature

| Tickets       | [EZP-29291](https://jira.ez.no/browse/EZP-29291)

EZP-29291 remove "EZP-29291-excluded" tag

---

src/lib/UI/Module/ContentTree/NodeFactory.php

| Tickets       | https://jira.ez.no/browse/EZP-30230

EZP-30230: [Content tree] Inconsistency when displaying hidden content items

---

src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js

| Tickets       | https://jira.ez.no/browse/EZP-30206

EZP-30206: Anchor icon is displayed even if anchor is not saved

---

src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/base.js

| Tickets       | https://jira.ez.no/browse/EZP-30286

EZP-30286: Inline custom tag toolbar skips when moving cursor outside RTE

---

src/bundle/Resources/public/scss/_custom-tag.scss

| Tickets       | https://jira.ez.no/browse/EZP-30288

EZP-30288: Inline custom tag does not work with formatted style

---

src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-anchoredit.js
src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
src/bundle/Resources/public/scss/_mixins.scss

| Tickets       | https://jira.ez.no/browse/EZP-30178

EZP-30178: Extra spaces added after placing anchor when formatted style is used

---

src/bundle/Resources/public/js/scripts/admin.location.visibility.js

| Tickets       | https://jira.ez.no/browse/EZP-30312
**Requires: https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/169**

EZP-30312: Refresh Content Tree on location visibility change

---

src/bundle/Resources/public/scss/_icons.scss
src/bundle/Resources/public/scss/fieldType/edit/_ezgmaplocation.scss
src/bundle/Resources/public/scss/fieldType/edit/_ezkeyword.scss
src/bundle/Resources/public/scss/fieldType/edit/_ezobjectrelationlist.scss
src/bundle/Resources/views/fieldtypes/edit/ezgmaplocation.html.twig
src/bundle/Resources/views/fieldtypes/edit/relation_base.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-30163

EZP-30163: Icons are not aligned with other elements

---

src/bundle/Resources/config/bazinga_js_translation.yml

| Tickets       | https://jira.ez.no/browse/EZP-30326
| Bug fix?      | -
I need _tips_ translations for: https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/168

EZP-30326: Expose search domain translations to the frontend

---

src/bundle/Resources/public/js/scripts/fieldType/base/base-preview-field.js

| Tickets       | https://jira.ez.no/browse/EZP-30329

EZP-30329: [Chrome] Drag and drop does not work for ezfile, ezmedia, ezimage

---

src/bundle/Controller/ContentViewController.php
src/bundle/Resources/translations/locationview.en.xliff
src/bundle/Resources/views/content/locationview.html.twig
src/bundle/Resources/views/content/tab/locations/tab.html.twig
src/lib/Tab/LocationView/LocationsTab.php

| Tickets       | https://jira.ez.no/browse/EZP-30229 (Alternative approach)

EZP-30229: Unlock Location visibility on hidden content

---

src/bundle/Resources/views/admin/content_type/field_types.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-30362
https://github.com/ezsystems/repository-forms/pull/286

EZP-30362: Hidden default location in Relation List field type crashes Content Type editing

---

src/bundle/Resources/public/js/scripts/admin.notifications.js
src/bundle/Resources/public/js/scripts/helpers/notification.helper.js

| Tickets       | https://jira.ez.no/browse/EZP-30346
https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/170

EZP-30346: Broken notifications with html

---

src/lib/UI/Config/Provider/FieldType/RichText/AlloyEditor.php

Aligned code style with php-cs-fixer rules

---

src/bundle/Resources/config/universal_discovery_widget.yml

| Tickets       | https://jira.ez.no/browse/EZP-30154

EZP-30154: Decouple Content on the Fly from browse & search by default

---

src/bundle/Controller/ContentViewController.php

| Tickets       | https://jira.ez.no/browse/EZP-30375

EZP-30375: User is unable to go to Content structure without Content/Reverserelatedlist

---

src/lib/EventListener/RequestAttributesListener.php

| Tickets       | https://jira.ez.no/browse/EZP-30367
https://github.com/ezsystems/ezpublish-kernel/pull/2590
I have no slightest idea where this could fail.
also related to:
https://github.com/ezsystems/ezplatform-admin-ui/pull/79

EZP-30367: Error: `Location cannot be displayed as it is flagged as invisible.`

---

features/ContentCreation.feature
features/Sections.feature
src/lib/Behat/BusinessContext/ContentViewContext.php

| Tickets       | https://jira.ez.no/browse/EZEE-2747

EZEE-2747 Implement minimal test coverage for Copy subtree

---

src/bundle/Resources/views/layout.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-30399

EZP-30399: Fix lang attribute on <html> element

---

src/lib/Behat/PageElement/DateAndTimePopup.php

| Tickets       | https://jira.ez.no/browse/EZEE-2736
Callback waiting for the date set in date picker.

EZEE-2736 [Travis][Behat] Non-deterministic errors in Form- and Page-Builders

---

.travis.yml

| New feature?  | n/a
Adding a CS job that runs for every PR and after every merge, something that we've discussed on Slack yesterday.

Add php-cs-fixer Travis job

---

.travis.yml
behat_suites.yml
composer.json

https://jira.ez.no/browse/EZP-30098

EZP-30098 [Travis] Implement solution for running tests in threads based on fastest 

---

.travis.yml

https://jira.ez.no/browse/EZP-30098

Ezp 30098 feature sort script improvement

---

src/bundle/Controller/ContentViewController.php

More in this ticket: https://jira.ez.no/browse/EZP-30471

EZP-30471: Sending Relation to trash will crash Relating Content view in Back Office

---

features/Roles.feature
src/bundle/Resources/config/services/universal_discovery_widget.yml
src/bundle/Resources/config/universal_discovery_widget.yml
src/bundle/Resources/public/js/scripts/admin.role_assignment.add.js
src/bundle/Resources/public/scss/_tag.scss
src/bundle/Resources/translations/role.en.xliff
src/bundle/Resources/views/admin/role_assignment/create.html.twig
src/bundle/Resources/views/admin/role_assignment/create_tag_list_item.html.twig
src/lib/Behat/BusinessContext/RolesContext.php
src/lib/Behat/PageElement/AdminUpdateForm.php
src/lib/Behat/PageObject/RolePage.php
src/lib/Form/DataTransformer/UserCollectionTransformer.php
src/lib/Form/DataTransformer/UserGroupCollectionTransformer.php
src/lib/Form/Type/Role/RoleAssignmentCreateType.php
src/lib/Form/Type/User/UserCollectionType.php
src/lib/Form/Type/User/UserGroupCollectionType.php
src/lib/UI/Config/Provider/FieldType/RichText/AlloyEditor.php
src/lib/UniversalDiscovery/Event/Subscriber/UserSelectionAllowedContentTypes.php

| Tickets       | https://jira.ez.no/browse/EZP-30022

EZP-30022: UDW widget for selecting user/groups when assigning roles

---

src/lib/Behat/Helper/Hooks.php

Don't merge, contains TMP commit.
Example how we could access browser logs in tests, output:
```
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Content type 'Test Content TypeFAILURE' updated.'
+'Content type 'Test Content Type' updated.'
│
│  http://web/assets/ezplatform/build/ezplatform-admin-ui-layout-js.js 0:7119 "Test error"http://web/assets/ezplatform/build/ezplatform-admin-ui-layout-js.js 0:7119 "Test error"
│
└─ @AfterStep # EzSystems\EzPlatformAdminUi\Behat\Helper\Hooks::getBrowserLogAfterFailedStep()
```
Any ideas/suggestions are welcome.
*Notes:* 
1) I don't think it's possible to get a better output (without `echo`) without writing our extension for this - not sure if it's worth it.
2) I've went for AfterStep because this will show the console log …

EZP-30489: Get console logs in failed tests

---

src/lib/Behat/Helper/UtilityContext.php
src/lib/Behat/PageElement/Notification.php
src/lib/Behat/PageElement/UniversalDiscoveryWidget.php

https://jira.ez.no/browse/EZP-30098

EZP-30098 fixes in waiting for notification and udw multiselect 

---

features/ContentCreation.feature
features/ContentManagement.feature

This PR divide `ContentManagement.feature` into `ContentCreation.feature` with creation, edition and preview, and `ContentManagement.feature` with moving and copying.

Workaround for the problem with ezsystems/ezplatform Travis builds timeouts

---

features/ContentType.feature

| Tickets       | https://jira.ez.no/browse/EZP-30400

EZP-30400: Fixed typo in Content Type Behat tests

---

src/bundle/Resources/public/js/scripts/admin.notifications.js
src/bundle/Resources/public/js/scripts/helpers/notification.helper.js
src/lib/Notification/FlashBagNotificationHandler.php

| Tickets       | https://jira.ez.no/browse/EZP-30396

EZP-30396: Unify bootstrap labels for danger/error

---

features/Trash.feature
src/lib/Behat/BusinessContext/ContentViewContext.php
src/lib/Behat/BusinessContext/DashboardContext.php
src/lib/Behat/BusinessContext/ObjectStatesContext.php
src/lib/Behat/BusinessContext/TrashContext.php
src/lib/Behat/PageElement/AdminList.php
src/lib/Behat/PageElement/Fields/ContentRelationSingle.php
src/lib/Behat/PageElement/Tables/LinkedListTable.php
src/lib/Behat/PageElement/Tables/SubItemsTable.php
src/lib/Behat/PageElement/Tables/Table.php
src/lib/Behat/PageElement/Tables/TrashTable.php
src/lib/Behat/PageObject/TrashPage.php

| Tickets       | https://jira.ez.no/browse/EZP-30449
Implementation of tests for 4 main scenarios for trash: empty trash, delete, restore and restore element under new parent location.

EZP-30499 Implement minimal test coverage for Trash

---

.travis.yml
behat_suites.yml
features/ContentTypeFields.feature

| Tickets       | https://jira.ez.no/browse/EZP-30315
Reorganizing `.travis.yml` file, introducing `ezbehat` script usage, and extending UDW timeouts (due to some test issues).
Related PRs:
https://github.com/ezsystems/BehatBundle/pull/77
https://github.com/ezsystems/ezplatform-page-builder/pull/344
https://github.com/ezsystems/ezplatform-form-builder/pull/162

EZP-30315 [Travis] Standarize and clean up travis configurations across the repositories

---

src/bundle/Resources/views/content/tab/translations/modal_add_translation.html.twig
src/bundle/Resources/views/content/tab/translations/tab.html.twig
src/bundle/Resources/views/content/tab/translations/translation_add_form_fields.html.twig

| Tickets       | [EZP-30456](https://jira.ez.no/browse/EZP-30456)
Removes deprecated views

EZP 30456: Remove deprecated views

---

composer.json
features/SystemInfo.feature
src/bundle/Controller/BulkOperation/BulkOperationController.php
src/bundle/Controller/Content/ContentTreeController.php
src/bundle/Controller/UniversalDiscoveryController.php
src/lib/REST/Input/Parser/BulkOperation.php
src/lib/REST/Input/Parser/ContentTree/LoadSubtreeRequest.php
src/lib/REST/Input/Parser/ContentTree/LoadSubtreeRequestNode.php
src/lib/REST/Input/Parser/Operation.php
src/lib/REST/Output/ValueObjectVisitor/BulkOperationResponse.php
src/lib/REST/Output/ValueObjectVisitor/ContentTree/Node.php
src/lib/REST/Output/ValueObjectVisitor/ContentTree/Root.php
src/lib/REST/Value/BulkOperation.php
src/lib/REST/Value/BulkOperationResponse.php
src/lib/REST/Value/ContentTree/LoadSubtreeRequest.php
src/lib/REST/Value/ContentTree/LoadSubtreeRequestNode.php
src/lib/REST/Value/ContentTree/Node.php
src/lib/REST/Value/ContentTree/Root.php
src/lib/REST/Value/Operation.php
src/lib/REST/Value/OperationResponse.php
src/lib/Tests/Util/FieldDefinitionGroupsUtilTest.php
src/lib/UI/Config/Provider/SortFieldMappings.php
src/lib/UI/Config/Provider/SortOrderMappings.php
src/lib/UI/Module/Subitems/ContentViewParameterSupplier.php
src/lib/UI/Module/Subitems/ValueObjectVisitor/SubitemsList.php
src/lib/UI/Module/Subitems/ValueObjectVisitor/SubitemsRow.php
src/lib/UI/Module/Subitems/Values/ContentTypeRemoteIdList.php
src/lib/UI/Module/Subitems/Values/SubitemsList.php
src/lib/UI/Module/Subitems/Values/SubitemsRow.php

> JIRA: https://jira.ez.no/browse/EZP-28034
Extract RestBundle and Common namespace to new package.
https://github.com/ezsystems/ezpublish-kernel/pull/2630
https://github.com/ezsystems/ezplatform-rest

EZP-28034: Refactored to use EzPlatformRestBundle

---

src/bundle/ParamConverter/ContentParamConverter.php
src/bundle/ParamConverter/PolicyParamConverter.php
src/bundle/Tests/ParamConverter/ContentParamConverterTest.php
src/bundle/Tests/ParamConverter/ContentTypeDraftParamConverterTest.php
src/bundle/Tests/ParamConverter/ContentTypeGroupParamConverterTest.php
src/bundle/Tests/ParamConverter/ContentTypeParamConverterTest.php
src/bundle/Tests/ParamConverter/LanguageParamConverterTest.php
src/bundle/Tests/ParamConverter/PolicyParamConverterTest.php
src/bundle/Tests/ParamConverter/RoleAssignmentParamConverterTest.php
src/bundle/Tests/ParamConverter/RoleParamConverterTest.php
src/bundle/Tests/ParamConverter/SectionParamConverterTest.php
src/bundle/Tests/ParamConverter/VersionInfoParamConverterTest.php

Applied fixes for tests after suggestions from Infection framework

---

src/bundle/Resources/views/themes/admin/ui/search/list.html.twig

Fixes a typo in a template path

fixes a typo in a template path

---

src/bundle/Resources/config/ezplatform_default_settings.yaml

| Tickets       | [EZP-30654](https://jira.ez.no/browse/EZP-30654)
Fixes paths

EZP-30654: User settings/change password/Forgot password doesn't work

---

src/lib/Notification/TranslatableNotificationHandler.php
src/lib/Notification/TranslatableNotificationHandlerInterface.php

| Tickets       | [EZP-30660](https://jira.ez.no/browse/EZP-30660)
fixes changing password

EZP-30660: Cannot change password

---

src/lib/Behat/Helper/Hooks.php

| Tickets       | https://jira.ez.no/browse/EZP-30642
| New feature?  | for Travis
Requires: https://github.com/ezsystems/ezplatform/pull/413
Displaying the first 10 entries from application error log when a test fails. This is the same approach as in browser console logs - for me it's good to start small and test on Travis how it behaves 😄 
Example from my local tests (when logging level has been set to debug:)
```
Scenario: Trash can be emptied                      # vendor/ezsystems/ezplatform-admin-ui/features/test.feature:7
Given I click on the left menu bar …
```

EZP-30642 display app logs

---

src/lib/Form/SubmitHandler.php

| Tickets       | https://jira.ez.no/browse/EZP-30686
Currently when an exception is thrown while form submission handling, there is no way to see error details: 
This PR adds error logging to `\EzSystems\EzPlatformAdminUi\Form\SubmitHandler`:

EZP-30686: Added errors logging in the form submission handler

---

src/lib/View/Builder/ContentTranslateViewBuilder.php

| Tickets       | https://jira.ez.no/browse/EZP-30653

EZP-30653: User is unable to add translation to the item

---

src/bundle/DependencyInjection/Configuration/Parser/SubtreePath.php
src/bundle/EzPlatformAdminUiBundle.php
src/bundle/Resources/config/services.yml
src/bundle/Resources/config/services/dashboard.yml
src/bundle/Resources/config/services/query_types.yaml
src/lib/QueryType/ContentSubtreeQueryType.php
src/lib/QueryType/MediaSubtreeQueryType.php
src/lib/QueryType/SubtreeQueryType.php
src/lib/Tab/Dashboard/EveryoneContentTab.php
src/lib/Tab/Dashboard/EveryoneMediaTab.php
src/lib/Tab/Dashboard/MyContentTab.php
src/lib/Tab/Dashboard/MyMediaTab.php
src/lib/Tab/Dashboard/SubtreeQuery.php

| Tickets       | https://jira.ez.no/browse/EZP-30695
Related PR:
- https://github.com/ezsystems/ezplatform/pull/418

EZP-30695: Remove hardcoded subtree paths in Admin UI

---

src/bundle/Resources/public/scss/fieldType/edit/_base-preview.scss
src/bundle/Resources/public/scss/fieldType/edit/_ezimageasset.scss

| Tickets       | https://jira.ez.no/browse/EZP-30649

EZP-30649: Browse field for image/media/file field types

---

src/lib/UI/Config/Provider/UserContentTypes.php

| Tickets       | https://jira.ez.no/browse/EZP-30128
use interface to properly autowire class for ezPlatform 3.0 (compatible with 2.5).

EZP-30128: Fix autowiring for eZPlatform 3.0

---

src/bundle/Templating/Twig/ComponentExtension.php
src/bundle/Templating/Twig/ContentTypeIconExtension.php
src/bundle/Templating/Twig/PathStringExtension.php
src/bundle/Templating/Twig/TabExtension.php
src/bundle/Templating/Twig/UiConfigExtension.php
src/bundle/Templating/Twig/UniversalDiscoveryExtension.php

Update Twig namespaces

---

src/bundle/Controller/ContentTypeController.php

| Tickets       | https://jira.ez.no/browse/EZP-30724
fixed message

EZP-30724: Fixed message displayed when content type is locked

---

src/bundle/Resources/views/Security/mail/forgot_user_password.html.twig

Fixed unclosed element "a" in forgot user password e-mail template

---

src/bundle/Resources/public/js/scripts/admin.format.date.js
src/bundle/Resources/public/js/scripts/helpers/timezone.helper.js

JIRA: https://jira.ez.no/browse/EZP-30792
Removes deprecated functions.

EZP-30792: Remove deprecated functions in JS

---

src/bundle/Resources/config/services/views.yaml

| Tickets       | https://jira.ez.no/browse/EZP-30880
| Requires | https://github.com/ezsystems/ezpublish-kernel/pull/2745

EZP-30880: Aligned MatcherFactory service definition with Kernel changes

---

src/bundle/Resources/public/scss/_buttons.scss

| Tickets       | https://jira.ez.no/browse/EZP-30788

EZP-30788: Harmonize Confirm button in widgets

---

src/bundle/Resources/public/js/scripts/admin.notifications.modal.js

| Tickets       | https://jira.ez.no/browse/EZP-30786

EZP-30786: 'Cannot update notifications count' notification message

---

src/bundle/Resources/public/js/scripts/button.state.checkbox.toggle.js

| Tickets       | https://jira.ez.no/browse/EZP-30916

EZP-30916: Delete content confirmation modal - button stays disabled

---

src/bundle/Controller/LanguageController.php
src/lib/EventListener/ContentTranslateViewFilterParametersListener.php
src/lib/Tab/LocationView/ContentTab.php
src/lib/UI/Config/Provider/DateFormat.php
src/lib/UI/Module/Subitems/ContentViewParameterSupplier.php

| Tickets       | https://jira.ez.no/browse/EZP-30902

EZP-30902: Remove deprecated view parameters

---

src/lib/Menu/Admin/Role/RoleAssignmentCreateRightSidebarBuilder.php
src/lib/Menu/UserSetting/UserSettingUpdateRightSidebarBuilder.php

| Tickets       | https://jira.ez.no/browse/EZP-30787

EZP-30787: Change icon in Save button when in Admin panel User settings

---

.php_cs
composer.json

This change is needed to perform tests on travis with php 7.3

Bumped php-cs-fixer to ~2.15.3 and adjusted its configuration

---

src/lib/Form/Factory/FormFactory.php

Remove incorrect service annotation

Minor fix of PHPDoc

---

src/bundle/Resources/config/services.yml
src/bundle/Resources/translations/fieldtypes_preview.en.xliff
src/bundle/Resources/translations/messages.en.xliff
src/bundle/Resources/views/Security/error/credentials_expired.html.twig
src/bundle/Resources/views/admin/content_type/field_types.html.twig
src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig
src/lib/EventListener/CredentialsExpirationWarningListener.php
src/lib/EventListener/CredentialsExpiredListener.php

| Tickets       | [EZP-30797](https://jira.ez.no/browse/EZP-30797)
| Doc needed?   | -
Information about expired credentials in the backoffice: 
Password expiration warning after login into backoffice
New settings in ezuser field type
Password expiration info in the ezuser field type preview
Information about expired credentials in the frontend siteaccess

EZP-30797: As an administrator, I want to configure a password expiration for users

---

src/bundle/Resources/public/scss/_modals.scss
src/bundle/Resources/translations/messages.en.xliff
src/bundle/Resources/views/content/modal_content_hide_confirmation.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-30491

EZP-30491: Design fix for "Conflict when hiding content item" modal

---

src/bundle/Resources/public/scss/_admin.content-type-view.scss
src/bundle/Resources/public/scss/_general.scss
src/bundle/Resources/public/scss/ezplatform.scss

| Tickets       | https://jira.ez.no/browse/EZP-30946

EZP-30946: Empty space under sidebar menu

---

src/bundle/Resources/public/scss/_modals.scss
src/bundle/Resources/translations/messages.en.xliff
src/bundle/Resources/views/content/modal_location_trash_container.html.twig
src/bundle/Resources/views/content/modal_location_trash_with_asset.html.twig
src/bundle/Resources/views/content/modal_location_trash_with_single_asset.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-29973

EZP-29973: Deleting content modal inconsistency

---

src/bundle/Resources/public/js/scripts/admin.user.menu.js
src/bundle/Resources/public/scss/_icons.scss
src/bundle/Resources/public/scss/_notifications-menu.scss
src/bundle/Resources/public/scss/_user-menu.scss
src/bundle/Resources/views/themes/admin/ui/menu/user_menu.html.twig
src/lib/Menu/UserMenuBuilder.php

| Tickets       | https://jira.ez.no/browse/EZP-29618
*Related PR: https://github.com/ezsystems/ezplatform-user/pull/46*
Before             |  After
:-------------------------:|:-------------------------:

EZP-29618: Update user menu order and add icons

---

.travis.yml
behat_suites.yml
features/personas/SubtreeEditor.feature
src/lib/Behat/BusinessContext/ContentViewContext.php
src/lib/Behat/BusinessContext/NavigationContext.php
src/lib/Behat/BusinessContext/RightMenuContext.php
src/lib/Behat/BusinessContext/UDWContext.php
src/lib/Behat/PageElement/RightMenu.php
src/lib/Behat/PageElement/UpperMenu.php
src/lib/Behat/PageObject/ContentItemPage.php

[DON'T MERGE] Test merge 1.5 -> master

---

src/bundle/Resources/config/services/components.yaml
src/bundle/Resources/config/services/dashboard.yaml
src/bundle/Resources/config/services/tabs.yaml
src/bundle/Resources/config/services/tabs/content_type.yaml
src/bundle/Resources/config/services/tabs/locationview.yaml
src/bundle/Resources/config/services/tabs/systeminfo.yaml
src/bundle/Resources/views/themes/admin/content/location_view.html.twig
src/bundle/Resources/views/themes/admin/content_type/index.html.twig
src/bundle/Resources/views/themes/admin/system_info/info.html.twig
src/bundle/Resources/views/themes/admin/ui/dashboard/block/all.html.twig
src/bundle/Resources/views/themes/admin/ui/dashboard/block/me.html.twig
src/lib/Component/TabsComponent.php

| Tickets       | https://jira.ez.no/browse/EZP-30843

EZP-30843: Tabs rendering moved to Components

---

src/bundle/Resources/views/themes/admin/content/draft/draft_list.html.twig

| Tickets       |  N/A
| Tests pass?   | TBD
This was introduced by https://github.com/ezsystems/ezplatform-admin-ui/commit/f4675f49917693f5ac07c2411e8116fc649f78aa

Fix regression in draft_list.html.twig

---

src/bundle/Resources/views/admin/content_type/field_types.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-30983
| Requires    | https://github.com/ezsystems/ezpublish-kernel/pull/2788 and https://github.com/ezsystems/repository-forms/pull/319

EZP-30983: As an Administrator, I want prevent users from reusing old password

---

src/bundle/Resources/config/views.yaml
src/bundle/Resources/views/themes/admin/content_type/content_type_group/index.html.twig
src/bundle/Resources/views/themes/admin/object_state/object_state_group/view.html.twig
src/bundle/Resources/views/themes/admin/section/view.html.twig
src/bundle/Resources/views/themes/admin/user/role/index.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-30819
Followup to #1051

EZP-30819: Replace deprecated controller syntax

---

features/personas/SubtreeEditor.feature
features/standard/Authentication.feature
src/lib/Behat/BusinessContext/AuthenticationContext.php
src/lib/Behat/BusinessContext/NavigationContext.php
src/lib/Behat/BusinessContext/UserNotificationContext.php
src/lib/Behat/PageElement/PlatformElementFactory.php
src/lib/Behat/PageElement/Tables/SimpleTable.php
src/lib/Behat/PageElement/UpperMenu.php
src/lib/Behat/PageElement/UserNotificationPopup.php
src/lib/Behat/PageObject/DashboardPage.php

JIRA: https://jira.ez.no/browse/EZEE-2899
Related PRs:
https://github.com/ezsystems/ezplatform-page-builder/pull/412
https://github.com/ezsystems/ezplatform-ee/pull/112
https://github.com/ezsystems/ezplatform-workflow/pull/79
This PR:
- adds handling of User notification sections
- changes simple table so that I could use it with Workflow tables in Admin panel
- allows to switch tabs on Dashboard page

Add workflow scenarios

---

src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js

| Tickets       | https://jira.ez.no/browse/EZP-30859
Note: 
This but is valid for bold, italic, underline, superscript, subscript, strike.

EZP-30859: Cannot remove formatting after publication in RTE

---

src/lib/Form/DataTransformer/TrashItemTransformer.php

| **JIRA issue**     | [EZP-31093](https://jira.ez.no/browse/EZP-31093)
| **Target version** |  `master` 
Fixed https://github.com/ezsystems/ezpublish-kernel/pull/2851#pullrequestreview-312507417.

EZP-31093: Introduced strict types for TrashService

---

.php_cs
composer.json
src/bundle/Controller/ContentOnTheFlyController.php
src/lib/Behat/PageElement/AdminUpdateForm.php
src/lib/Behat/PageElement/ContentUpdateForm.php
src/lib/Component/LinkComponent.php
src/lib/Component/ScriptComponent.php
src/lib/Form/Data/Location/LocationUpdateData.php
src/lib/Form/Data/Section/SectionCreateData.php
src/lib/Form/Data/Section/SectionUpdateData.php
src/lib/Form/Factory/FormFactory.php

| Tickets       | https://jira.ez.no/browse/EZP-31108

EZP-31108: Fixed code-style according to the rules from ezplatform-code-style

---

src/lib/Form/DataTransformer/ContentTypeGroupTransformer.php
src/lib/Tests/Form/DataTransformer/ContentTypeGroupTransformerTest.php

| **JIRA issue**     | [EZP-31103](https://jira.ez.no/browse/EZP-31103)
| **Target version** | `master`
| **BC breaks**      | no
| **Doc needed**     | no
Fixed https://github.com/ezsystems/ezpublish-kernel/pull/2856#pullrequestreview-317524259

EZP-31103: Introduced strict types for ContentTypeService

---

.php_cs

| Tickets       | https://jira.ez.no/browse/EZP-31008

EZP-31008: Changed to code style from EzPlatformInternalConfigFactory

---

src/lib/FieldType/Mapper/AuthorFormMapper.php
src/lib/FieldType/Mapper/DateFormMapper.php
src/lib/FieldType/Mapper/DateTimeFormMapper.php
src/lib/FieldType/Mapper/MediaFormMapper.php
src/lib/FieldType/Mapper/TimeFormMapper.php
src/lib/Form/Type/ContentType/ContentTypeEditType.php

| Tickets       | https://jira.ez.no/browse/EZP-31108

EZP-31108: Fixed invalid code-style

---

src/bundle/Resources/public/js/alloyeditor/src/plugins/ez-custom-tag.js
src/bundle/Resources/public/js/alloyeditor/src/widgets/ez-custom-tag-base.js
src/bundle/Resources/public/js/alloyeditor/src/widgets/ez-embed-base.js

| Tickets       | https://jira.ez.no/browse/EZP-31058
Note for QA:
Fixed for custom tags, inline custom tags, embed, embed-image, embed-inline

EZP-31058: No new line can be inserted in RTE below custom tags

---

src/lib/Behat/PageElement/Fields/RichText.php

| Tickets       |  https://jira.ez.no/browse/EZEE-2915

EZEE-2915: Implement minimal test coverage for Richtext block in Page Builder

---

src/lib/Behat/PageElement/Fields/RichText.php

[DON'T MERGE] Test richtext merge

---

src/bundle/Controller/ContentController.php

| Tickets       | https://jira.ez.no/browse/EZP-30936
Kernel PR with new method signature
https://github.com/ezsystems/ezpublish-kernel/pull/2875

EZP-30936 Editing Content with a Translation after adding a required field to ContentType will fail with an error

---

src/lib/Form/Extension/HelpMultilineMessageExtension.php

| Tickets       | https://jira.ez.no/browse/EZP-30985

Fix deprecation in HelpMultilineMessageExtension

---

src/lib/Behat/Helper/UtilityContext.php
src/lib/Behat/PageObject/AdminUpdateItemPage.php
src/lib/Behat/PageObject/ContentItemPage.php
src/lib/Behat/PageObject/ContentPreviewPage.php
src/lib/Behat/PageObject/ContentTypeGroupPage.php
src/lib/Behat/PageObject/ContentTypeGroupsPage.php
src/lib/Behat/PageObject/ContentTypePage.php
src/lib/Behat/PageObject/ContentUpdateItemPage.php
src/lib/Behat/PageObject/DashboardPage.php
src/lib/Behat/PageObject/LanguagePage.php
src/lib/Behat/PageObject/LanguagesPage.php
src/lib/Behat/PageObject/LoginPage.php
src/lib/Behat/PageObject/ObjectStateGroupPage.php
src/lib/Behat/PageObject/ObjectStateGroupsPage.php
src/lib/Behat/PageObject/ObjectStatePage.php
src/lib/Behat/PageObject/Page.php
src/lib/Behat/PageObject/RolePage.php
src/lib/Behat/PageObject/RolesPage.php
src/lib/Behat/PageObject/SectionPage.php
src/lib/Behat/PageObject/SectionsPage.php
src/lib/Behat/PageObject/SystemInfoPage.php
src/lib/Behat/PageObject/TrashPage.php

| Tickets       | [EZP-29112](https://jira.ez.no/browse/EZP-29112)
TODO before merge:

EZP-29112 Implement scenarios for Site Access matching

---

src/lib/Behat/Helper/UtilityContext.php

| Tickets       | https://jira.ez.no/browse/EZP-29112

EZP-29112 Implement scenarios for Studio site access matching - followup fix

---

src/bundle/DependencyInjection/Compiler/FieldTypeFormMapperDispatcherPass.php
src/bundle/DependencyInjection/Compiler/LimitationFormMapperPass.php
src/bundle/DependencyInjection/Compiler/LimitationValueMapperPass.php
src/lib/Form/DataTransformer/DateIntervalToArrayTransformer.php
src/lib/Form/DataTransformer/FieldType/AbstractBinaryBaseTransformer.php
src/lib/Form/DataTransformer/FieldType/DateTimeValueTransformer.php
src/lib/Form/DataTransformer/FieldType/DateValueTransformer.php
src/lib/Form/DataTransformer/FieldType/ImageAssetValueTransformer.php
src/lib/Form/DataTransformer/FieldType/TimeValueTransformer.php
src/lib/Form/Processor/ContentType/ContentTypeFormProcessor.php
src/lib/Limitation/Mapper/ContentTypeLimitationMapper.php
src/lib/Limitation/Mapper/LanguageLimitationMapper.php
src/lib/Limitation/Mapper/ObjectStateLimitationMapper.php
src/lib/Limitation/Mapper/SectionLimitationMapper.php
src/lib/Limitation/Templating/LimitationBlockRenderer.php
src/lib/Tests/Limitation/Mapper/ContentTypeLimitationMapperTest.php
src/lib/Tests/Limitation/Mapper/LanguageTypeLimitationMapperTest.php
src/lib/Tests/Limitation/Mapper/ObjectStateLimitationMapperTest.php
src/lib/Tests/Limitation/Mapper/SectionLimitationMapperTest.php

| Tickets       | https://jira.ez.no/browse/EZP-31021

EZP-31021: Merged repository-forms exception & command messages refactoring

---

src/bundle/Resources/public/scss/_add-to-bookmarks.scss

| Tickets       | https://jira.ez.no/browse/EZP-31184
Removed white background from active bookmark icon in Content Structure.

EZP-31184: Removed background from active bookmark icon

---

src/bundle/Resources/config/services/forms.yaml
src/bundle/Resources/translations/content_type.en.xliff
src/bundle/Resources/views/themes/admin/content_type/edit.html.twig
src/lib/EventListener/PopulateFieldDefinitionData.php
src/lib/Form/Type/FieldDefinition/FieldDefinitionType.php

| Tickets       | https://jira.ez.no/browse/EZP-30882

EZP-30882: As a developer I want to use custom Field Type as Content thumbnail

---

src/lib/Form/Processor/ContentType/ContentTypeFormProcessor.php
src/lib/Specification/ContentType/ContentTypeIsUser.php
src/lib/Util/FieldDefinitionGroupsUtil.php

| **JIRA issue**     | [EZP-31078](https://jira.ez.no/browse/EZP-31078)
| **Bug/Improvement**| no
| **New feature**    | yes
| **Target version** |  `master`
Adapted `ezplatform-admin-ui` to changes introduced in https://github.com/ezsystems/ezpublish-kernel/pull/2839

EZP-31078: Enhanced Content Type Value Object

---

src/bundle/ParamConverter/ContentTypeGroupParamConverter.php
src/bundle/ParamConverter/ContentTypeParamConverter.php
src/bundle/ParamConverter/PolicyParamConverter.php
src/bundle/ParamConverter/RoleAssignmentParamConverter.php
src/bundle/ParamConverter/RoleParamConverter.php
src/bundle/ParamConverter/SectionParamConverter.php
src/bundle/Tests/ParamConverter/ContentTypeGroupParamConverterTest.php
src/bundle/Tests/ParamConverter/ContentTypeParamConverterTest.php
src/bundle/Tests/ParamConverter/PolicyParamConverterTest.php
src/bundle/Tests/ParamConverter/RoleAssignmentParamConverterTest.php
src/bundle/Tests/ParamConverter/RoleParamConverterTest.php
src/bundle/Tests/ParamConverter/SectionParamConverterTest.php
src/lib/Form/DataTransformer/SectionsTransformer.php
src/lib/Tests/Form/Data/FormMapper/ContentTranslationMapperTest.php
src/lib/Tests/Form/DataTransformer/SectionsTransformerTest.php
src/lib/Tests/Form/Processor/ContentTypeFormProcessorTest.php
src/lib/Tests/Limitation/Mapper/ContentTypeLimitationMapperTest.php
src/lib/Tests/Limitation/Mapper/LanguageTypeLimitationMapperTest.php
src/lib/Tests/Limitation/Mapper/ObjectStateLimitationMapperTest.php
src/lib/Tests/Limitation/Mapper/SectionLimitationMapperTest.php
src/lib/Tests/Specification/ContentType/ContentTypeIsUserTest.php

Fixed broken unit tests

---

src/lib/FieldType/FieldDefinitionFormMapperInterface.php
src/lib/Form/Data/FieldDefinitionData.php
src/lib/Limitation/LimitationFormMapperInterface.php
src/lib/Limitation/LimitationFormMapperRegistryInterface.php
src/lib/Limitation/LimitationValueMapperInterface.php
src/lib/Limitation/LimitationValueMapperRegistryInterface.php

| Tickets       | https://jira.ez.no/browse/EZP-31204

EZP-31204: Provided backwards compatibility layer in repository-forms package

---

src/bundle/Resources/public/js/scripts/admin.content.edit.js

| Tickets       | https://jira.ez.no/browse/EZP-31205
Disabled sending form (new content) by hitting enter by added event.preventDefault()

EZP-31205: Disabled sending form by hitting enter key (new content)

---

src/bundle/Controller/UniversalDiscoveryController.php

| Tests pass?   | ?
Workaround to be able to load location with id = 1 by the limited user in UDW. Related CI build https://travis-ci.org/ezsystems/ezplatform-admin-ui/builds/628651352?utm_source=slack&utm_medium=notification

Temporary load root location in UDW via sudo

---

src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-image-link.js

| Tickets       | [EZP-31245](https://jira.ez.no/browse/EZP-31245)

EZP-31245: Editing link in paragraph containing more lines ends up with JS error

---

src/bundle/Resources/public/js/scripts/admin.picker.js

| Tickets       | https://jira.ez.no/browse/EZEE-2853
Added using preferred date format in scheduler.
Also: https://github.com/ezsystems/ezplatform-page-builder/pull/469

EZEE-2853: Fixed using preferedded date in scheduler

---

src/bundle/Resources/views/admin/trash/list.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-29550

EZP-29550: Added display inactive trash icon on a empty trash list

---

src/bundle/Resources/public/scss/_tables.scss
src/bundle/Resources/views/themes/admin/content/tab/locations/tab.html.twig
src/bundle/Resources/views/themes/admin/content/tab/translations/tab.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31250
Set text alignment in tables as top

EZP-31250: Set text alignment in tables as top

---

src/bundle/Resources/config/universal_discovery_widget.yaml

| Tickets       | https://jira.ez.no/browse/EZEE-2956

EZEE-2956: Auto confirm is not enabled in UDW for Embed block

---

src/bundle/Resources/public/scss/_badges.scss
src/bundle/Resources/public/scss/ezplatform.scss

| Tickets       | https://jira.ez.no/browse/EZP-31148
Added badge class for other components.
Changes:
https://github.com/ezsystems/ezplatform-page-builder/pull/461
https://github.com/ezsystems/date-based-publisher/pull/145
https://github.com/ezsystems/ezplatform-workflow/pull/101
https://github.com/ezsystems/ez-support-tools/pull/45

EZP-31148: Harmonize Badges by adding them as new UI component

---

src/bundle/Resources/public/scss/_general.scss

| Tickets       | https://jira.ez.no/browse/EZP-30860
Added blockqoute formatting for field preview

EZP-30860: Added blockqoute formatting for field preview

---

src/bundle/Resources/public/scss/_notifications-modal.scss

| Tickets       | https://jira.ez.no/browse/EZP-29955

EZP-29955: Added outline: none; for [X] button in notifications popup

---

src/bundle/Resources/public/js/scripts/admin.search.filters.js

| Tickets       | https://jira.ez.no/browse/EZP-30403
Formated date using ez.helpers.timezone (Content -> Content structure ->Search)

EZP-30403: Formated date on search content site using ez.helpers.timezone

---

src/bundle/Resources/views/themes/admin/ui/tab/location_view.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31322

EZP-31322: Fixed padding for tabs

---

src/bundle/Resources/public/scss/_custom-tag.scss

| Tickets       | https://jira.ez.no/browse/EZP-30850
Changed float to margin for custom tag

EZP-30850: Changed float to margin for custom tag

---

src/bundle/Resources/views/themes/admin/content/tab/versions/table.html.twig

| Tickets       |  [EZP-31182](https://jira.ez.no/browse/EZP-31182) 
https://github.com/ezsystems/ezplatform-content-comparison/pull/10

EZP-31182: As an Editor I want to access Version compare from the versions table

---

src/bundle/Controller/UniversalDiscoveryController.php
src/bundle/Resources/config/services/query_types.yaml
src/lib/QueryType/LocationPathQueryType.php

| Tickets       | https://jira.ez.no/browse/EZP-31261

EZP-31261: Rebuild endpoints to use proper root location per configuration

---

src/bundle/Resources/public/js/scripts/fieldType/ezdatetime.js
src/bundle/Resources/public/scss/_mixins.scss
src/lib/Behat/PageElement/Fields/DateAndTime.php

| Tickets       | https://jira.ez.no/browse/EZP-30908
Changed date format (formatShortDateTime) for datetime input like in PR https://github.com/ezsystems/ezplatform-page-builder/pull/469

EZP-30908: Changed date format for datetime input when we create article

---

src/bundle/Resources/public/scss/_content-tree.scss

| Tickets       | https://jira.ez.no/browse/EZP-31314

EZP-31314: Added transition to animation open/close for content tree

---

src/lib/Behat/PageElement/Fields/DateAndTime.php

Changing back change from https://github.com/ezsystems/ezplatform-admin-ui/commit/b45b208e94a0410090fd2b8531d8a23524ed070f

Changed back to previous typehint in constructor

---

src/bundle/Resources/translations/forms.en.xliff
src/bundle/Resources/views/admin/policy/list.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-30009

EZP-30009: Added missing translations on Admin -> Roles

---

src/lib/Behat/PageElement/Fields/MapLocation.php
src/lib/Behat/PageElement/Fields/Matrix.php
src/lib/Behat/PageElement/Fields/URL.php

Follow up to https://github.com/ezsystems/ezplatform-admin-ui/pull/1208
When merging upstream I didn't resolve all conflicts properly, this PR fixes that.

[Behat] Fixed invalid selectors for fieldtypes

---

src/bundle/Resources/public/js/scripts/admin.format.date.js

| Tickets       | https://jira.ez.no/browse/EZP-30575
| BC breaks?    | yno
Changed regex to match only repeatable chars for formatICU

EZP-30575: Fixed parsing date format in formatICU

---

src/bundle/Resources/public/scss/_breadcrumb.scss
src/bundle/Resources/public/scss/_content-edit.scss
src/bundle/Resources/public/scss/_field-group.scss
src/bundle/Resources/public/scss/_header.scss
src/bundle/Resources/public/scss/_notifications-modal.scss
src/bundle/Resources/public/scss/_page-title.scss
src/bundle/Resources/public/scss/_tables.scss
src/bundle/Resources/views/admin/bookmark/list.html.twig
src/bundle/Resources/views/admin/content_draft/draft_list.html.twig
src/bundle/Resources/views/admin/content_draft/list.html.twig
src/bundle/Resources/views/admin/content_type/list.html.twig
src/bundle/Resources/views/admin/search/search_table_row.html.twig
src/bundle/Resources/views/admin/trash/list.html.twig
src/bundle/Resources/views/content/content_edit/content_edit.html.twig
src/bundle/Resources/views/dashboard/tab/all_content.html.twig
src/bundle/Resources/views/dashboard/tab/all_media.html.twig
src/bundle/Resources/views/dashboard/tab/my_content.html.twig
src/bundle/Resources/views/dashboard/tab/my_draft_list.html.twig
src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig
src/bundle/Resources/views/dashboard/tab/my_media.html.twig
src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig
src/bundle/Resources/views/parts/breadcrumbs.html.twig
src/bundle/Resources/views/parts/page_title.html.twig
src/bundle/Resources/views/parts/table_header.html.twig

| Tickets       |https://jira.ez.no/browse/EZP-30761
Added ellipsize to strings in admin ui
Also:
https://github.com/ezsystems/ezplatform-workflow/pull/102
https://github.com/ezsystems/date-based-publisher/pull/147

EZP-30761: added ellipsize to strings

---

src/bundle/Controller/LocationController.php
src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-anchoredit.js
src/bundle/Resources/public/scss/_alloyeditor-anchor-edit.scss
src/bundle/Resources/translations/alloy_editor.en.xliff

| Tickets       | https://jira.ez.no/browse/EZP-30485
Changed selector so it accepts all valid ids

EZP-30485: Fix to invalid anchor name

---

src/bundle/Resources/public/scss/_content-edit.scss
src/bundle/Resources/public/scss/_main-row.scss
src/bundle/Resources/views/themes/admin/content/create/create.html.twig
src/bundle/Resources/views/themes/admin/content/edit/base.html.twig
src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
src/bundle/Resources/views/themes/admin/user/create.html.twig
src/bundle/Resources/views/themes/admin/user/edit.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31381

EZP-31381: Fixed z-index overlay covers when deleting items

---

src/bundle/Resources/views/form_fields.html.twig

| Tickets       | [EZEE-2933](https://jira.ez.no/browse/EZEE-2933)

EZEE-2933: Changed structure html to correct for alloyEditor

---

src/bundle/Resources/encore/ez.js.config.js
src/bundle/Resources/public/js/scripts/admin.content.tree.js
src/bundle/Resources/public/js/scripts/helpers/user.helper.js
src/bundle/Resources/views/themes/admin/ui/layout.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31382
Moved userId to to meta data

EZP-31382: As a Developer, I want to have access to userId in JS scripts

---

src/bundle/Resources/encore/ez.js.config.js
src/bundle/Resources/translations/edit_translation_button.en.xliff
src/bundle/Resources/views/dashboard/macros.html.twig
src/bundle/Resources/views/parts/edit_translation_button.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31397
**Screenshot**
Note:
The base branch has to change after this is merged: https://github.com/ezsystems/ezplatform-admin-ui/pull/1223

EZP-31397: As an Editor, I want to select language when editing content from the dashboard

---

src/bundle/Resources/public/scss/_filters.scss
src/bundle/Resources/views/themes/admin/ui/search/form.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-29950

EZP-29950: Changed styles of creator on the search tab

---

src/lib/Tab/LocationView/RelationsTab.php

| Tickets       | [EZP-31395](https://jira.ez.no/browse/EZP-31395)

EZP-31395: Fixed permission check for rev. relation list in Relations tab

---

src/bundle/Resources/public/scss/_icons.scss

| Tickets       | https://jira.ez.no/browse/EZEE-2971
Added dark icon color

EZEE-2971: Added dark icon color

---

src/bundle/Resources/config/universal_discovery_widget.yaml
src/lib/Behat/BusinessContext/ContentViewContext.php
src/lib/Behat/PageElement/UniversalDiscoveryWidget.php

| Tickets       | https://jira.ez.no/browse/EZP-31416

EZP-31416: Remove selection bar on the right from UDW (Browse)

---

src/bundle/Resources/views/themes/admin/ui/page_title.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31407

EZP-31407: Removed title from header

---

src/bundle/Resources/translations/forms.en.xliff

Added missing translation messages for Site Factory policies

---

src/lib/Validator/Constraints/UserPasswordValidator.php

###JIRA: https://jira.ez.no/browse/EZP-31079

EZP-31079: Replaced loadUserByCredentials witch checkUserChredentials

---

src/lib/Event/ContentOnTheFlyEvents.php
src/lib/Event/UserOnTheFlyEvents.php

| Tickets       | https://jira.ez.no/browse/EZEE-2982
Change after late Code Review

EZEE-2982: Made event names explicit, without concatenation

---

src/bundle/Resources/config/services.yaml
src/bundle/Resources/config/services/ui_config/common.yaml
src/bundle/Resources/translations/time_diff.en.xliff
src/bundle/Templating/Twig/TimeDiffExtension.php
src/lib/UI/Service/DateTimeFormatter.php
src/lib/UI/Service/DateTimeFormatterInterface.php

| Tickets       | https://jira.ez.no/browse/EZP-31494

EZP-31494: Added time diff filter for twig

---

src/bundle/Resources/views/themes/admin/ui/menu/top_menu_2nd_level.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31491
Added possibility to add icon to top menu entry

EZP-31491: As a developer, I want to add icon to top menu entry

---

src/lib/Form/DataTransformer/LocationTransformer.php
src/lib/Form/EventListener/BuildPathFromRootListener.php
src/lib/Form/Type/Content/Translation/TranslationAddType.php

| **JIRA issue**     | [EZP-31448](https://jira.ez.no/browse/EZP-31448)
| **Target version** |  `master`

EZP-31448: Introduced strict types for LocationService

---

src/lib/UI/Value/User/Policy.php
src/lib/UI/Value/User/Role.php

| **JIRA issue**     | [EZP-31482](https://jira.ez.no/browse/EZP-31482)
| **Target version** | `master`

EZP-31482: Introduce strict types for FieldType & VO

---

src/bundle/Tests/Templating/Twig/LimitationMock.php
src/lib/Tests/EventListener/SetViewParametersListenerTest.php
src/lib/Tests/Form/Data/FormMapper/ContentTranslationMapperTest.php
src/lib/Tests/Form/DataTransformer/LocationsTransformerTest.php
src/lib/Tests/Validator/Constraint/UserPasswordValidatorTest.php

Adjusted unit tests to recent changes

---

src/bundle/Resources/views/themes/admin/ui/search/form.html.twig

Fixed search in case when user doesn't have section/view permission

---

composer.json
src/bundle/Tests/Templating/Twig/FieldEditRenderingExtensionTest.php
src/bundle/Tests/Templating/Twig/LimitationValueRenderingExtensionTest.php
src/lib/Menu/MainMenuBuilder.php
src/lib/Tests/Form/Data/FormMapper/ContentTypeDraftMapperTest.php
src/lib/Tests/Menu/MainMenuBuilerTest.php
src/lib/Validator/Constraints/LocationIsWithinCopySubtreeLimitValidator.php

To unblock CI on pending PRs.
Production code fixes:
- `src/lib/Menu/MainMenuBuilder.php` for easier mocking in tests
- `src/lib/Validator/Constraints/LocationIsWithinCopySubtreeLimitValidator.php` - missing type cast

Fixed outstanding type-casting and test mocking issues

---

composer.json
features/standard/SystemInfo.feature

| Tickets       | https://jira.ez.no/browse/EZP-31007
| Tests pass?   | [yes](https://travis-ci.org/github/ezsystems/ezplatform-admin-ui/builds/664916181?utm_source=github_status&utm_medium=notification)
See ezsystems/ezplatform#510

EZP-31007: Replaced ezpublish-kernel with ezplatform-kernel

---

src/bundle/Resources/translations/dashboard.en.xliff

| Tickets       | https://jira.ez.no/browse/EZP-31504

EZP-31504: Fixed missing translation for eZ version on Dashboard

---

src/lib/Form/DataTransformer/ContentTransformer.php

| Tickets       | https://jira.ez.no/browse/EZP-31508

EZP-31508: Fixed changing content main translation

---

src/bundle/Resources/views/themes/admin/ui/on_the_fly/edit_on_the_fly.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31488

EZP-31488: Wrong header when editing on the fly

---

src/bundle/Resources/public/scss/_modals.scss

| Tickets       | https://jira.ez.no/browse/EZP-31467
Changed whitespace to initial from nowrap

EZP-31467: Delete draft message is misaligned 

---

src/lib/UniversalDiscovery/Event/Subscriber/ContentCreate.php

| Tickets       | https://jira.ez.no/browse/EZP-31270

EZP-31270: Fixed access to Back Office when user has CT Limitation on content create

---

src/bundle/Resources/public/scss/_filters.scss
src/bundle/Resources/views/themes/admin/ui/search/form.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31447
added extra wrapper for position absolute

EZP-31447: Remove button in search criteria for 'creator' field is not displayed propertly

---

src/lib/Form/DataTransformer/UserTransformer.php

| Tickets       | https://jira.ez.no/browse/EZEE-3052

EZEE-3052: Casted string id from form to int

---

src/bundle/Resources/translations/content_type.en.xliff
src/lib/FieldType/Mapper/UserAccountFormMapper.php

| Tickets       | https://jira.ez.no/browse/EZP-31079
Requires: https://github.com/ezsystems/ezplatform-kernel/pull/3

EZP-31079: Provided validation for email uniqueness and login pattern

---

src/bundle/Resources/views/themes/admin/content/tab/content.html.twig
src/lib/EventListener/RequestAttributesListener.php

| Tickets       | https://jira.ez.no/browse/EZP-31490
Route added here:
https://github.com/ezsystems/ezpublish-kernel/pull/3005

EZP-31490: Used new translation specific content route

---

src/bundle/Resources/public/js/scripts/fieldType/ezobjectrelationlist.js

| Tickets       | https://jira.ez.no/browse/EZP-31412

EZP-31412: Inconsistent date format in the relation field type table

---

src/bundle/Resources/public/scss/_flatpickr.scss
src/bundle/Resources/public/scss/ezplatform.scss

| Tickets       | https://jira.ez.no/browse/EZP-31515

EZP-31515: Schedule later widget is hiding after clicking calendar input

---

src/bundle/Resources/views/content/tab/versions/table.html.twig

| Tickets       | [EZEE-2961](https://jira.ez.no/browse/EZEE-2961)
Depends on: [ezsystems/ezplatform-workflow#109](https://github.com/ezsystems/ezplatform-workflow/pull/109)

EZEE 2961 Added an additional condition to edit draft button to prevent error when a user is deleted

---

src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
src/bundle/Resources/public/scss/_main-row.scss

| Tickets       | https://jira.ez.no/browse/EZP-31403

EZP-31403: Widget header is not visible

---

src/bundle/Resources/public/js/scripts/admin.picker.js

| Tickets       | https://jira.ez.no/browse/EZEE-3067
Needed by https://github.com/ezsystems/date-based-publisher/pull/170

EZEE-3067: Confirm button is covered by date picker in schedule hide

---

src/bundle/Resources/public/scss/ui/modules/common/_popup.scss

| Tickets       | https://jira.ez.no/browse/EZEE-3066

EZEE-3066: changed height for modal close button

---

src/lib/Menu/Admin/ContentType/ContentTypeCreateRightSidebarBuilder.php
src/lib/Menu/Admin/ContentType/ContentTypeEditRightSidebarBuilder.php
src/lib/Menu/Admin/ContentType/ContentTypeGroupCreateRightSidebarBuilder.php
src/lib/Menu/Admin/ContentType/ContentTypeGroupEditRightSidebarBuilder.php
src/lib/Menu/Admin/Language/LanguageCreateRightSidebarBuilder.php
src/lib/Menu/Admin/Language/LanguageEditRightSidebarBuilder.php
src/lib/Menu/Admin/ObjectState/ObjectStateGroupCreateRightSidebarBuilder.php
src/lib/Menu/Admin/ObjectState/ObjectStateGroupEditRightSidebarBuilder.php
src/lib/Menu/Admin/Role/RoleCreateRightSidebarBuilder.php
src/lib/Menu/Admin/Role/RoleEditRightSidebarBuilder.php
src/lib/Menu/ContentCreateRightSidebarBuilder.php
src/lib/Menu/ContentEditRightSidebarBuilder.php
src/lib/Menu/ContentRightSidebarBuilder.php
src/lib/Menu/ContentTypeRightSidebarBuilder.php
src/lib/Menu/LeftSidebarBuilder.php
src/lib/Menu/SectionCreateRightSidebarBuilder.php
src/lib/Menu/SectionEditRightSidebarBuilder.php
src/lib/Menu/TrashRightSidebarBuilder.php
src/lib/Menu/URLEditRightSidebarBuilder.php
src/lib/Menu/UserPasswordChangeRightSidebarBuilder.php
src/lib/Menu/UserSetting/UserSettingUpdateRightSidebarBuilder.php

Jira ref: https://jira.ez.no/browse/EZP-31439
Removed tooltips form right sidebar buttons with label

EZP-31439: Removed title from right/left sidebar

---

src/bundle/Resources/public/js/scripts/button.translation.edit.js
src/bundle/Resources/public/scss/_translation-selector.scss
src/bundle/Resources/views/themes/admin/ui/edit_translation_button.html.twig
src/bundle/Resources/views/themes/admin/ui/search/list_item.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31532

EZP-31532: Update design of edit translation widget in search and dashboard

---

src/bundle/Resources/translations/content.en.xliff
src/bundle/Resources/translations/content_edit.en.xliff
src/bundle/Resources/translations/content_type.en.xliff
src/bundle/Resources/translations/messages.en.xliff
src/bundle/Resources/translations/multi_file_upload.en.xliff
src/bundle/Resources/translations/search.en.xliff
src/bundle/Resources/views/themes/admin/ui/search/form.html.twig
src/bundle/ui-dev/src/modules/common/tooltip-popup/tooltip.popup.component.js
src/bundle/ui-dev/src/modules/multi-file-upload/components/upload-popup/upload.popup.component.js

Jira ref: https://jira.ez.no/browse/EZP-31439

EZP-31439: Harmonize tooltips

---

src/bundle/Resources/public/scss/ui/modules/content-tree/_list.scss
src/bundle/Resources/public/scss/ui/modules/content-tree/_main.scss
src/bundle/ui-dev/src/modules/content-tree/components/content-tree/content.tree.js
src/bundle/ui-dev/src/modules/content-tree/components/list/list.component.js

| Tickets       | https://jira.ez.no/browse/EZP-31408

EZP-31408: 'This Location has no Sub-items' msg is displayed above location

---

src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-tableremove.js

| Tickets       | [EZP-30940](https://jira.ez.no/browse/EZP-30940)
PR for 3.0 will be created once this solution is approved.

EZP-30940: Cannot remove table from richtext field

---

src/bundle/Resources/public/scss/_icons.scss
src/bundle/Resources/views/themes/admin/user/role/list.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31537

EZP-31537: Update color for icon button in Roles table

---

src/lib/Menu/Admin/Role/RoleCopyRightSidebarBuilder.php

JIRA: https://jira.ez.no/browse/EZEE-3077

EZEE-3077: Update missing translations in ezplatform-admin-ui

---

src/bundle/Resources/translations/notifications.en.xliff
src/bundle/Resources/views/themes/admin/account/notifications/modal.html.twig

Jira ref: https://jira.ez.no/browse/EZP-31439

Added tooltip 'close' for notifications popup

---

src/bundle/Resources/public/js/scripts/admin.limitation.pick.js
src/bundle/Resources/public/js/scripts/admin.search.filters.js
src/bundle/Resources/public/js/scripts/udw/select.location.js
src/bundle/ui-dev/src/modules/common/services/content.service.js
src/bundle/ui-dev/src/modules/common/services/location.service.js
src/bundle/ui-dev/src/modules/universal-discovery/services/universal.discovery.service.js

| Tickets       | https://jira.ez.no/browse/EZP-31183

EZP-31183: Removed dropped Criteria from REST calls

---

src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js

| Tickets       | https://jira.ez.no/browse/EZP-31548

EZP-31548: Sidebar widget sometimes is overlapped by header

---

src/bundle/Resources/public/scss/core/_custom.tooltip.scss

| Tickets       | https://jira.ez.no/browse/EZEE-3093

EZEE-3093: Changed z-index for tooltips

---

src/bundle/Controller/LanguageController.php
src/bundle/Controller/NotificationController.php
src/lib/Behat/PageObject/LanguagePage.php
src/lib/Behat/PageObject/ObjectStatePage.php
src/lib/Tests/RepositoryForms/Form/Processor/PreviewFormProcessorTest.php

| Tickets       | https://jira.ez.no/browse/EZP-31578

EZP-31578: Fixed phpdoc_var_without_name code style issue

---

src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-embed.js
src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-embedinline.js
src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-embedupdate.js
src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-image.js
src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-imageupdate.js
src/bundle/Resources/public/js/scripts/fieldType/ezobjectrelationlist.js
src/bundle/Resources/translations/alloy_editor.en.xliff
src/bundle/Resources/translations/universal_discovery_widget.en.xliff
src/bundle/Resources/views/fieldtypes/edit/relation_base.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-29475

EZP-29475: Changes for UDW title

---

src/bundle/Tests/Templating/Twig/FieldEditRenderingExtensionTest.php
src/lib/Tests/Validator/Constraint/PasswordValidatorTest.php
src/lib/Tests/Validator/Constraint/UserPasswordValidatorTest.php
src/lib/Validator/Constraints/PasswordValidator.php
src/lib/Validator/Constraints/UserPasswordValidator.php

| Tickets       | https://jira.ez.no/browse/EZP-31572

EZP-31017: Fixed failing unit tests

---

.travis.yml

Fixed tests matrix in .travis.yml 

---

behat_suites.yml
features/standard/SearchContent.feature
src/lib/Behat/BusinessContext/SearchContext.php
src/lib/Behat/PageObject/Page.php
src/lib/Behat/PageObject/PlatformPageObjectFactory.php
src/lib/Behat/PageObject/SearchPage.php

https://jira.ez.no/browse/EZP-31609
I have added initial search test

[Behat] Added initial search test

---

src/bundle/Resources/public/scss/_content-edit.scss

| Tickets       | https://jira.ez.no/browse/EZP-31445

EZP-31445: Update design of ez-edit-header__details in Editing view

---

src/bundle/Resources/public/scss/_badges.scss

| Tickets       | https://jira.ez.no/browse/EZP-31446

EZP-31446: Update design for badge with icon

---

src/lib/Menu/ContentEditRightSidebarBuilder.php

| Tickets       | https://jira.ez.no/browse/EZP-31222
With: https://github.com/ezsystems/ezplatform-page-builder/pull/585

EZP-31222: Harmonize sidebar ez-context-menu in Editing views

---

src/bundle/Resources/config/universal_discovery_widget.yaml

| Tickets       | https://jira.ez.no/browse/EZP-31577

EZP-31577: Remove Selected locations panel from UDW when COTF is triggered

---

src/bundle/Resources/public/js/alloyeditor/src/widgets/ez-embed-base.js
src/bundle/Resources/translations/alloy_editor.en.xliff

| Tickets       | https://jira.ez.no/browse/EZP-31626
Screenshot:

EZP-31626: Fixed error in AlloyEditor when embed location

---

src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-linkedit.js

| Tickets       | [EZP-31641](https://jira.ez.no/browse/EZP-31641)
Original PR: https://github.com/ezsystems/ezplatform-richtext/pull/149
@dew326

EZP-31641: Unable to manage links in table cells

---

src/bundle/Resources/public/scss/_custom.scss
src/bundle/Resources/public/scss/_extra-actions.scss

| Tickets       | https://jira.ez.no/browse/EZP-31419
Needed by: https://github.com/ezsystems/ezplatform-page-builder/pull/588

EZP-31419: Widgets animation integrated in a single SASS variable

---

src/bundle/Resources/translations/content.en.xliff
src/bundle/Resources/views/themes/admin/content/content_preview.html.twig
src/bundle/Resources/views/themes/admin/content/create/create.html.twig
src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
src/bundle/Resources/views/themes/admin/user/create.html.twig
src/bundle/Resources/views/themes/admin/user/edit.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31656

EZP-31656: Added missing tooltip for exit buttons

---

src/lib/Behat/PageElement/Fields/EzFieldElement.php

| Tickets       | Part of EZEE-3142
Required for https://github.com/ezsystems/BehatBundle/pull/156
This is needed to create a new Content Type with Form fieldtype using Behat.

[Behat] Added support for Form fieldtype

---

src/lib/Behat/PageElement/Fields/DefaultFieldElement.php

Testing upstream merge of https://github.com/ezsystems/ezplatform-admin-ui/pull/1393#event-3406358514

[DON'T MERGE] Test 1.5 -> 2.0 merge

---

src/bundle/DependencyInjection/Configuration/Parser/Pagination.php

| Tickets       | https://jira.ez.no/browse/EZP-31668
As an additional cleanup to https://github.com/ezsystems/ezplatform-user/pull/72, I think those can be safely removed and not introduced further confusion.

EZP-31668: Introduced new key for user related pagination configuration

---

src/bundle/Resources/config/services/ui_config/common.yaml
src/bundle/Resources/public/js/scripts/admin.location.view.js
src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js
src/lib/Behat/BusinessContext/NavigationContext.php
src/lib/Behat/PageElement/PlatformElementFactory.php
src/lib/Behat/PageElement/SubItemsList.php
src/lib/Behat/PageElement/Tables/ItemsList.php
src/lib/Behat/PageElement/Tables/SubitemsGridList.php
src/lib/Behat/PageElement/Tables/Table.php
src/lib/Behat/PageObject/ContentItemPage.php
src/lib/UI/Config/Provider/Locations.php

| Tickets       | https://jira.ez.no/browse/EZP-31575
Set grid view of sub items for media site

EZP-31575: When in Media section show Sub-Items grid view by default

---

src/lib/Form/Processor/PreviewFormProcessor.php
src/lib/Form/Type/Extension/Content/ContentEditTypeExtension.php

| Tickets       | https://jira.ez.no/browse/EZP-31574

EZP-31574: Added posibility to save and preview incomplete draft

---

src/lib/Behat/PageElement/ContentUpdateForm.php

Adjusting Behat selectors for changes done in https://github.com/ezsystems/ezplatform-admin-ui/pull/1386
Failing build: https://travis-ci.org/github/ezsystems/ezplatform-admin-ui/jobs/698916236

[Behat] Updated selector for specific field in Content edit

---

src/bundle/Controller/TrashController.php
src/bundle/Resources/public/js/scripts/admin.search.filters.js
src/bundle/Resources/public/js/scripts/admin.trash.list.js
src/bundle/Resources/public/scss/_tables.scss
src/bundle/Resources/public/scss/_trash-list.scss
src/bundle/Resources/public/scss/_trash-search-form.scss
src/bundle/Resources/public/scss/ezplatform.scss
src/bundle/Resources/views/themes/admin/trash/list.html.twig
src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
src/bundle/Resources/views/themes/admin/ui/search/form.html.twig

jira ref: https://jira.ez.no/browse/EZP-31650

Ezp 31650 search in trash frontend

---

features/standard/Trash.feature
src/bundle/Controller/TrashController.php
src/bundle/Resources/config/bazinga_js_translation.yaml
src/bundle/Resources/config/services/forms.yaml
src/bundle/Resources/config/services/query_types.yaml
src/bundle/Resources/public/js/scripts/admin.search.filters.js
src/bundle/Resources/public/js/scripts/admin.trash.list.js
src/bundle/Resources/public/scss/_tables.scss
src/bundle/Resources/public/scss/_trash-search-form.scss
src/bundle/Resources/public/scss/ezplatform.scss
src/bundle/Resources/translations/date_period.en.xliff
src/bundle/Resources/translations/messages.en.xliff
src/bundle/Resources/translations/trash.en.xliff
src/bundle/Resources/translations/trash_ui.en.xliff
src/bundle/Resources/views/themes/admin/trash/list.html.twig
src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
src/lib/Form/Data/Search/TrashSearchData.php
src/lib/Form/Data/TrashItemData.php
src/lib/Form/Factory/FormFactory.php
src/lib/Form/Factory/TrashFormFactory.php
src/lib/Form/Type/ChoiceList/Loader/DatePeriodChoiceLoader.php
src/lib/Form/Type/Content/SortType.php
src/lib/Form/Type/Search/TrashSearchType.php
src/lib/Form/Type/Trash/ChoiceList/Loader/SearchContentTypeChoiceLoader.php
src/lib/QueryType/TrashSearchQueryType.php

| Tickets       | https://jira.ez.no/browse/EZP-31650
Added view for trash search
Related PR kernel: https://github.com/ezsystems/ezplatform-kernel/pull/80/files
Frontent CR continuation from: https://github.com/ezsystems/ezplatform-admin-ui/pull/1406

EZP-31650: Added search in trash

---

src/lib/Form/Type/Trash/ChoiceList/Loader/SearchContentTypeChoiceLoader.php

…
Fixed code style issues in `src/lib/Form/Type/Trash/ChoiceList/Loader/SearchContentTypeChoiceLoader.php` reported in https://travis-ci.org/ezsystems/ezplatform-admin-ui/builds/703220882?utm_source=slack&utm_medium=notification

Fixed code style issues in SearchContentTypeChoiceLoader

---

src/bundle/Resources/translations/messages.en.xliff

Jira ref: https://jira.ez.no/browse/EZP-31714

EZP-31714: Fix translation 'Any Content Type'

---

src/bundle/Resources/translations/messages.en.xliff
src/bundle/Resources/views/themes/admin/content/modal/location_trash.html.twig

jira ref: https://jira.ez.no/browse/EZP-31695

EZP-31695: Add mising tooltips for close modal (send to trash)

---

src/bundle/Resources/translations/messages.en.xliff
src/bundle/Resources/views/themes/admin/ui/modal/bulk_delete_confirmation.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31703

EZP-31703: Added missing tooltip 'Close' for modal 'Remove from trash'

---

src/bundle/Resources/public/scss/_warning-icon.scss
src/bundle/Resources/views/themes/admin/content/create/create.html.twig

Jira ref: https://jira.ez.no/browse/EZEE-3195

EZEE-3195: Fixed error message position

---

src/bundle/Resources/config/services.yaml
src/bundle/Resources/config/services/forms.yaml
src/bundle/Resources/config/services/views.yaml
src/bundle/Resources/config/views.yaml
src/lib/EventListener/SearchViewFilterParametersListener.php
src/lib/Form/Type/Search/SearchType.php
src/lib/View/Filter/AdminSearchViewFilter.php

| Tickets       | https://jira.ez.no/browse/EZP-31693
https://github.com/ezsystems/ezplatform-search/pull/4

EZP-31693: Used custom SearchType for admin SA

---

src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js

| Tickets       | https://jira.ez.no/browse/EZP-31730

EZP-31730: [Content-Tree] Uncaught TypeError: Cannot read property 'contains' of undefined

---

src/bundle/Resources/public/scss/_breadcrumb.scss
src/bundle/Resources/public/scss/_custom.scss
src/bundle/Resources/public/scss/_field-group.scss
src/bundle/Resources/public/scss/_header.scss
src/bundle/Resources/public/scss/_icons.scss
src/bundle/Resources/public/scss/_main-nav.scss
src/bundle/Resources/public/scss/_main-row.scss
src/bundle/Resources/public/scss/_mixins.scss
src/bundle/Resources/public/scss/_page-title.scss
src/bundle/Resources/public/scss/_tabs.scss
src/bundle/Resources/public/scss/ui/modules/muti-file-upload/_main.scss
src/bundle/Resources/public/scss/ui/modules/sub-items-list/_action.btn.scss
src/bundle/Resources/public/scss/ui/modules/sub-items-list/_main.scss
src/bundle/Resources/public/scss/ui/modules/sub-items-list/_table.view.item.scss
src/bundle/Resources/public/scss/ui/modules/sub-items-list/_table.view.scss
src/bundle/Resources/public/scss/ui/modules/sub-items-list/_view.switcher.button.scss
src/bundle/Resources/public/scss/ui/modules/sub-items-list/_view.switcher.scss
src/bundle/Resources/views/themes/admin/content/location_view.html.twig
src/bundle/Resources/views/themes/admin/ui/breadcrumbs.html.twig
src/bundle/Resources/views/themes/admin/ui/page_title.html.twig
src/bundle/Resources/views/themes/admin/ui/tab/location_view.html.twig
src/bundle/ui-dev/src/modules/multi-file-upload/multi.file.upload.module.js
src/bundle/ui-dev/src/modules/sub-items/components/action-btn/action.btn.js
src/bundle/ui-dev/src/modules/sub-items/components/view-switcher/view.switcher.button.component.js

| Tickets       | https://jira.ez.no/browse/EZP-31733

EZP-31733: U.I colors

---

src/lib/Form/Type/Search/SearchType.php

| Tickets       | https://jira.ez.no/browse/EZP-31710
https://github.com/ezsystems/ezplatform-admin-ui/commit/3e065634ad4f319b5de00e1034200d688dde1181

EZP-31710: Search in frontend can now be filtered by multiple users

---

src/bundle/Resources/config/services/forms.yaml
src/lib/Form/Data/Search/SearchData.php
src/lib/View/Filter/AdminSearchViewFilter.php

https://github.com/ezsystems/ezplatform-search/pull/6

New search Bundle namespace

---

src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js

| Tickets       | https://jira.ez.no/browse/EZP-31694

EZP-31694: Error when the user clicks on the link in the notification

---

src/lib/Form/SubmitHandler.php

| Tickets | EZP-30686 (2.0 #1021 backport to 1.5)
| Target version | eZ Platform 2.5 LTS+
Some uncommon exceptions (e.g. "Database error") should be logged when handling them. Otherwise it's difficult to find exact cause quickly - message usually is not enough, which is useful for the `dev` environment and important for the `prod` one.
This PR adds logging of exceptions to Form submission handler. Known API exceptions, like `ForbiddenException`, `NotFoundException`, `UnauthorizedException` are handled as before, just by adding a notification.
Update: looks like it's a backport of #1021.
This is about …

EZP-30686: Improved form submission error handling by logging errors

---

src/bundle/Resources/public/scss/_content-tree.scss

| Tickets       | https://jira.ez.no/browse/EZP-31418

EZP-31418: Consistent content tree animation

---

features/standard/Authentication.feature
features/standard/ContentTypeFields.feature

JIRA: https://jira.ez.no/browse/EZEE-3222
Test cases from Authentication.feature (line 4) & ContentTypeFields.feature (line 135 & 138) are unstable on eZCommerce, therefore they are temporarily disabled.

[BEHAT] added tags to avoid using TC which are faulty in eZCommerce

---

src/bundle/Resources/config/admin_ui_forms.yml
src/bundle/Resources/views/content/content_view_fields.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31805

EZP-31805: Moved default template configuration from twig file to yaml

---

src/bundle/Resources/public/scss/_card.scss
src/bundle/Resources/public/scss/_field-group.scss
src/bundle/Resources/public/scss/_general.scss
src/bundle/Resources/public/scss/_tables.scss
src/bundle/Resources/public/scss/fieldType/preview/_ezbinaryfile.scss
src/bundle/Resources/public/scss/fieldType/preview/_ezgmaplocation.scss
src/bundle/Resources/public/scss/fieldType/preview/_ezkeyword.scss
src/bundle/Resources/public/scss/mixins/_image-preview.scss
src/bundle/Resources/views/themes/admin/content/content_view_fields.html.twig
src/bundle/Resources/views/themes/admin/content_type/create.html.twig
src/bundle/Resources/views/themes/admin/content_type/edit.html.twig
src/bundle/Resources/views/themes/admin/ui/field_type/preview/content_fields.html.twig
src/bundle/Resources/views/themes/admin/ui/field_type/preview/ezimageasset.html.twig

jira ref: https://jira.ez.no/browse/EZP-31774

EZP-31744: Content preview/admin content type update

---

src/bundle/Resources/public/scss/_custom.scss

jira ref: https://jira.ez.no/browse/EZP-31774

EZP-31774: Updated custom scss variable

---

src/bundle/Resources/views/themes/admin/content_type/create.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31827

EZP-31827: It's not possible to create a new Content Type

---

src/bundle/Resources/public/js/scripts/admin.location.view.js
src/bundle/ui-dev/src/modules/sub-items/components/sub-items-list/sub.items.list.component.js
src/bundle/ui-dev/src/modules/sub-items/components/table-view/table.view.component.js
src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js

| Tickets       | https://jira.ez.no/browse/EZP-31823

EZP-31823: Cannot reuse subitems in other pages than content structure

---

src/bundle/Resources/views/themes/admin/user/role/list.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31833

EZP-31833: It's not possible to delete a Role when on Roles page

---

src/bundle/Resources/views/themes/admin/ui/modal/bulk_delete_confirmation.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31832

EZP-31832: Delete button in Trash restores Content Item

---

src/bundle/Resources/views/themes/admin/system_info/hardware.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31830

EZP-31830: "Hardware" tab is described as "Database" in System information

---

src/bundle/Resources/public/scss/_inputs.scss
src/bundle/Resources/views/themes/admin/language/create.html.twig

Fixed checkboxes for languages forms

EZP-31812: Admin section

---

src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31828
The displayed time didn't account for months and years.

EZP-31828: Fixed password expiration info in 'ezuser' fieldtype

---

features/standard/ContentTypeFields.feature

JIRA: https://jira.ez.no/browse/EZEE-3237
Deleted tag @commerceExcluded.
Added ItemsPerPage & Parameters values into the test case.
Searched value changed to 'Images' as the query works properly now.

[BEHAT] added support for parameters in ContentTypeFields.feature

---

src/lib/Behat/PageElement/ContentTypePicker.php

| Tickets       | https://jira.ez.no/browse/EZP-31816
| Bug fix?      | fix in tests
Failing build:
https://travis-ci.com/github/ezsystems/ezcommerce-shop/jobs/382898056
https://res.cloudinary.com/ezplatformtravis/image/upload/v1599678529/screenshots/5f5928412ddd5480454420-vendor_ezsystems_ezplatform-admin-ui_features_standard_contenttypefields_feature_42_psujmy.png
```
| ezrichtext           | Rich text                    |                                                                       | value     | Lorem ipsum dolor sit …
```

[Behat] Added filtering of Content Types in Content Type Picker

---

src/lib/Behat/PageElement/ContentTypePicker.php

| Tickets       | https://jira.ez.no/browse/EZP-31816
Follow up to: https://github.com/ezsystems/ezplatform-admin-ui/pull/1478
Failing job: https://travis-ci.com/github/ezsystems/ezplatform-form-builder/jobs/383574826
```
@javascript @common
Scenario: New form creation can be cancelled                          # vendor/ezsystems/ezplatform-form-builder/features/FormContentItemAdministration.feature:11
When I start creating a new content "Form"                          # EzSystems\EzPlatformAdminUi\Behat\BusinessContext\ContentViewC …
```

[Behat] Added checks to make sure Content Type filtering can be interacted with

---

src/bundle/Resources/config/services/form_processors.yml
src/lib/RepositoryForms/Form/Processor/Content/SystemUrlRedirectProcessor.php

https://jira.ez.no/browse/EZP-31086
| Tickets       | https://jira.ez.no/browse/EZP-31086
requires: 
https://github.com/ezsystems/repository-forms/pull/323

EZP-31086: Redirect based on router, not url alias

---

src/bundle/Resources/public/scss/_filters.scss

| Tickets       | https://jira.ez.no/browse/EZP-31889
https://github.com/ezsystems/ezcommerce-admin-ui/pull/37

EZP-31889: Control panel redesign

---

src/bundle/Resources/config/services/form_processors.yml
src/lib/RepositoryForms/Form/Processor/Content/UrlRedirectProcessor.php

Reverts ezsystems/ezplatform-admin-ui#1122

Revert "EZP-31086: Redirect based on router, not url alias"

---

src/bundle/Resources/public/scss/_custom.scss

| Tickets       | https://jira.ez.no/browse/EZEE-3268

EZEE-3268: Added new color to variables

---

src/lib/Behat/PageElement/ContentTypePicker.php
src/lib/Behat/PageObject/ContentItemPage.php

Testing upstream merge of #1482

[DON'T MERGE] Test merge 2.1 -> master

---

src/bundle/Resources/views/themes/admin/account/base.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31840

EZP-31840: Remove LTS from version number on the login screen

---

src/bundle/Resources/public/scss/_filters.scss
src/bundle/Resources/public/scss/_search-form.scss
src/bundle/Resources/public/scss/ezplatform.scss
src/bundle/Resources/views/themes/admin/ui/search/form.html.twig
src/bundle/Resources/views/themes/admin/ui/search/index.html.twig
src/lib/Behat/PageObject/SearchPage.php

| Tickets       | https://jira.ez.no/browse/EZP-31869

EZP-31869: Search redesign

---

src/bundle/Resources/public/scss/_custom.scss
src/bundle/Resources/public/scss/_pagination.scss
src/bundle/ui-dev/src/modules/common/pagination/pagination.js

| Tickets       | https://jira.ez.no/browse/EZP-31913

EZP-31913: Back button is not properly styled in sub-items pagination

---

src/bundle/Resources/public/scss/_buttons.scss
src/bundle/Resources/public/scss/_tables.scss
src/bundle/Resources/public/scss/_trash-search-form.scss
src/bundle/Resources/views/themes/admin/trash/list.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31843

EZP-31843: Trash management screen - Design inconsistencies

---

src/bundle/ui-dev/src/modules/universal-discovery/components/filters/filters.js

| Tickets       | https://jira.ez.no/browse/EZP-31916
https://github.com/ezsystems/ezcommerce-admin-ui/pull/40

EZP-31916: Filters redesign

---

src/bundle/Resources/public/scss/ui/modules/universal-discovery/_view.switcher.scss

| Tickets       | https://jira.ez.no/browse/EZP-31845

EZP-31845: UDW - Change color of icon when for a view is selected

---

src/bundle/Resources/views/themes/admin/account/base.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31858

EZP-31858: Broken links (Support & Contact Us) on the login screen

---

src/bundle/Resources/public/scss/_mixins.scss

| Tickets       | https://jira.ez.no/browse/EZP-31899

EZP-31899: CT - eztime/ezdate/ezdatetime - clear button ('x' in circle) is visible through dropdown

---

src/bundle/Resources/public/scss/_buttons.scss
src/bundle/Resources/public/scss/_custom.scss
src/bundle/Resources/public/scss/_search-form.scss

| Tickets       | https://jira.ez.no/browse/EZP-31921

EZP-31921: Adjust buttons height to match inputs height

---

src/bundle/Resources/public/scss/_extra-actions.scss

| Tickets       | https://jira.ez.no/browse/EZP-31919

EZP-31919: Unnecessary Create button at create content side menu

---

src/bundle/Resources/public/scss/_tag.scss

| Tickets       | https://jira.ez.no/browse/EZP-31892

EZP-31892: X button is misaligned

---

src/bundle/Resources/views/themes/admin/ui/field_type/preview/content_fields.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31883

EZP-31883: [File] Download button has wrong colour and is not properly formatted

---

src/bundle/Resources/public/scss/mixins/_general.scss
src/bundle/Resources/public/scss/ui/modules/sub-items-list/_table.view.columns.toggler.scss
src/bundle/Resources/public/scss/ui/modules/sub-items-list/_table.view.scss
src/bundle/ui-dev/src/modules/sub-items/components/table-view/table.view.columns.toggler.list.element.js

| Tickets       | https://jira.ez.no/browse/EZP-31867
Fixed styles for filter menu in sub items list

EZP-31867: styled filter in sub items

---

src/bundle/Resources/public/scss/fieldType/edit/_ezobjectrelationlist.scss

| Tickets       | https://jira.ez.no/browse/EZP-31910
Set small font size for CT - ezbojectrelation / ezobjectrelationlist tooltips

EZP-31910: Set small font for tooltips in CT - ezbojectrelation / ezobjectrelationlist

---

src/bundle/Resources/public/scss/_inputs.scss

| Tickets       | https://jira.ez.no/browse/EZP-31903
Set min-width and min-height for .ez-input--checkbox

EZP-31902: Set min-width and min-height for checkbox

---

src/bundle/Resources/public/scss/_main-row.scss

| Tickets       | https://jira.ez.no/browse/EZP-31922

EZP-31922: [Hide content] content hide conflict popup window is partially obscured by side menu

---

src/bundle/Resources/public/scss/ui/modules/universal-discovery/_toggle.selection.button.scss

| Tickets       | https://jira.ez.no/browse/EZP-31873

EZP-31873: Check icon in UDW is flattened for longer content items name

---

src/bundle/Resources/public/scss/_buttons.scss
src/bundle/Resources/public/scss/_general.scss

| Tickets       | https://jira.ez.no/browse/EZEE-3266

EZEE-3266: Send to review button is not properly formatted

---

src/bundle/Resources/public/scss/_mixins.scss

| Tickets       | https://jira.ez.no/browse/EZP-31885

EZP-31885: Enable switcher do not change colour to red when enabled

---

src/bundle/Resources/public/scss/_inputs.scss

| Tickets       | https://jira.ez.no/browse/EZP-31902

EZP-31902: Indeterminate state of the checkbox is not displayed in sub-items list

---

src/bundle/Resources/public/scss/ui/modules/universal-discovery/_top.menu.scss

| Tickets       | https://jira.ez.no/browse/EZP-31878

EZP-31878: Set correct margin for back button

---

src/bundle/Resources/views/themes/admin/content/tab/translations/tab.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31894

EZP-31894: Set correct container for tab content

---

src/bundle/Resources/views/themes/admin/content/tab/details.html.twig
src/bundle/Resources/views/themes/admin/content/tab/translations/tab.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31866
Added class "ml-2" to form_widget in "Sub-item sorting order"

EZP-31866: Please add spaces between ":" character and dropdown's

---

src/lib/View/Filter/AdminSearchViewFilter.php

| Tickets       | https://jira.ez.no/browse/EZP-31870

EZP-31935: Fixed TypeError error occuring while Section filter in Search is used

---

src/bundle/Resources/public/scss/_inputs.scss

| Tickets       | https://jira.ez.no/browse/EZP-31943

EZP-31943: Add opacity to show that a checkbox is disabled

---

src/bundle/Resources/public/scss/ui/modules/content-tree/_list.item.scss

| Tickets       | https://jira.ez.no/browse/EZP-31939

EZP-31939: Set color ibexa-color-primary for active carret in content tree

---

src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js

| Tickets       | [EZEE-3215](https://jira.ez.no/browse/EZEE-3215)

EZEE-3215: changed selector container for tooltip to closest

---

src/bundle/Resources/public/scss/_breadcrumb.scss

| Tickets       | https://jira.ez.no/browse/EZP-31942

EZP-31942: styled breadcrumbs links as regular system links

---

src/bundle/Resources/public/scss/_trash-search-form.scss
src/bundle/Resources/views/themes/admin/account/bookmarks/list.html.twig
src/bundle/Resources/views/themes/admin/trash/list.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31937

EZP-31937: adjust headers and tables to be placed at the same height on each page

---

src/bundle/Resources/public/scss/ui/modules/sub-items-list/_table.view.item.scss
src/bundle/Resources/public/scss/ui/modules/sub-items-list/_table.view.scss
src/bundle/ui-dev/src/modules/sub-items/components/table-view/table.view.item.component.js

| Tickets       | https://jira.ez.no/browse/EZP-31949
- [ x] Ready for Code Review

EZP-31949: Cannot see edit button in subitems

---

src/bundle/Resources/public/scss/_search-form.scss
src/bundle/Resources/translations/content_create.en.xliff
src/bundle/Resources/translations/search.en.xliff
src/bundle/Resources/views/themes/admin/ui/search/form.html.twig
src/bundle/Resources/views/themes/admin/ui/search/index.html.twig
src/bundle/Resources/views/themes/admin/ui/search_tag.html.twig
src/bundle/ui-dev/src/modules/universal-discovery/components/search/search.js

| Tickets       | https://jira.ez.no/browse/EZP-31929
https://github.com/ezsystems/ezplatform-search/pull/10

EZP-31929: Design issues

---

src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss

| Tickets       | https://jira.ez.no/browse/EZP-31847
- [ x] Ready for Code Review

EZP-31847: Content Edit screen - Change the position of the label to improve readability

---

src/bundle/Resources/views/themes/admin/content/tab/locations/panel_swap.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31947
| Doc needed?   | yno

EZP-31947: Added correct class for button 'Select Content Item' in content view -> locations

---

src/bundle/Resources/public/scss/ui/modules/universal-discovery/_grid.item.scss
src/bundle/Resources/public/scss/ui/modules/universal-discovery/_main.scss
src/bundle/ui-dev/src/modules/universal-discovery/components/grid-view/grid.view.item.js

| Tickets       | https://jira.ez.no/browse/EZP-31965

EZP-31965: Set smaller cards for grid view of UDW

---

src/bundle/Resources/public/scss/fieldType/edit/_ezuser.scss

| Tickets       | https://jira.ez.no/browse/EZP-31955

EZP-31955: Removed padding on 'user account' input row

---

src/bundle/Resources/public/scss/core/_custom.dropdown.scss
src/bundle/Resources/public/scss/fieldType/edit/_ezselection.scss

| Tickets       | https://jira.ez.no/browse/EC-255
- [ x] Ready for Code Review

EC-255: Add buttons and dropdown is not properly styled

---

src/bundle/Resources/views/themes/admin/content/page_title_edit.html.twig
src/bundle/Resources/views/themes/admin/ui/on_the_fly/create_on_the_fly.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31977

EZP-31977: Removed close button form COTF create template

---

src/bundle/Resources/views/themes/admin/content/tab/url/modal_add_custom_url.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31948

EZP-31948: Implemented new design to modal 'Create a new URL alias'

---

src/bundle/Resources/public/scss/ui/modules/universal-discovery/_content.create.widget.scss

| Tickets       | https://jira.ez.no/browse/EZP-31970

EZP-31970: Content on the fly - On clicking a content type the UI does not show the selection

---

src/bundle/Resources/public/js/scripts/admin.notifications.js
src/bundle/Resources/public/scss/_alerts.scss
src/bundle/Resources/public/scss/_badges.scss
src/bundle/Resources/public/scss/_custom.scss
src/bundle/Resources/public/scss/_notifications.scss
src/bundle/Resources/views/themes/admin/ui/dashboard/block/ez.html.twig
src/bundle/Resources/views/themes/admin/ui/layout.html.twig
src/bundle/Resources/views/themes/admin/ui/notification.html.twig
src/lib/Behat/PageElement/Notification.php

| Tickets       | https://jira.ez.no/browse/EZP-31980
Screen:

EZP-31980: New design for notifications/alerts

---

src/bundle/Resources/translations/content.en.xliff
src/bundle/Resources/translations/messages.en.xliff
src/bundle/Resources/views/themes/admin/content/page_title_edit.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31953

EZP-31953: Fixed missing and wrongly located translations

---

src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
src/bundle/Resources/views/themes/admin/content/form_fields.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31988

EZP-31988: Description of input fields need styling (icon)

---

src/bundle/Resources/translations/dashboard.en.xliff

| Tickets       | https://jira.ez.no/browse/EZP-31980

EZP-31980: New design for notifications/alerts - translations

---

src/bundle/Resources/views/themes/admin/content/page_title_edit.html.twig
src/bundle/Resources/views/themes/admin/user/edit.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31991

EZP-31991: Added missing information for header (user edit)

---

src/bundle/Resources/public/js/scripts/admin.location.add.translation.js
src/bundle/Resources/public/js/scripts/admin.location.view.js
src/bundle/Resources/public/scss/_add-translation.scss
src/lib/Form/Type/ContentType/Translation/TranslationAddType.php

| Tickets       | https://jira.ez.no/browse/EZP-31990

EZP-31990: Cannot add translation to Content Type

---

src/bundle/Resources/public/scss/_card.scss

JIRA ref: https://jira.ez.no/browse/EZEE-3288
- [x ] Ready for Code Review

EZEE-3288: added border to toggle headers

---

src/bundle/Resources/public/scss/_notifications.scss
src/bundle/Resources/views/themes/admin/ui/notification.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31993

EZP-31993: vertical centered notifications message

---

src/bundle/Resources/public/scss/_icons.scss
src/bundle/Resources/views/themes/admin/user/role/list.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31995

EZP-31993: Set icons color as ibexa-color-base-dark for admin->roles list

---

src/bundle/Resources/views/themes/admin/account/base.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-31985

EZP-31985: set correct page title on login screen

---

src/bundle/Resources/public/js/scripts/admin.location.adaptive.tabs.js
src/bundle/Resources/public/scss/_tabs.scss

| Tickets       | https://jira.ez.no/browse/EZP-31957
- [ x] Ready for Code Review

EZP-31957: More tab is visible while having no items

---

src/bundle/Resources/public/scss/_notifications.scss

| Tickets       | https://jira.ez.no/browse/EZP-31992
- [x ] Ready for Code Review

EZP-31992: Links are not visible on notifications

---

src/bundle/Resources/public/scss/_buttons.scss
src/bundle/Resources/public/scss/_custom.scss
src/bundle/Resources/views/themes/admin/account/forgot_password/index.html.twig
src/bundle/Resources/views/themes/admin/content/modal/add_translation.html.twig
src/bundle/Resources/views/themes/admin/content/modal/location_trash.html.twig
src/bundle/Resources/views/themes/admin/content/modal/user_delete.html.twig
src/bundle/Resources/views/themes/admin/content/modal/version_conflict.html.twig
src/bundle/Resources/views/themes/admin/content/tab/locations/panel_swap.html.twig
src/bundle/Resources/views/themes/admin/content/tab/url/modal_add_custom_url.html.twig
src/bundle/Resources/views/themes/admin/content_type/modal/delete_confirmation.html.twig
src/bundle/Resources/views/themes/admin/language/modal/delete_confirmation.html.twig
src/bundle/Resources/views/themes/admin/section/modal/delete_confirmation.html.twig
src/bundle/Resources/views/themes/admin/trash/modal/empty_trash_confirmation.html.twig
src/bundle/Resources/views/themes/admin/ui/field_type/edit/binary_base.html.twig
src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezgmaplocation.html.twig
src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimageasset.html.twig
src/bundle/Resources/views/themes/admin/ui/field_type/edit/relation_base.html.twig
src/bundle/Resources/views/themes/admin/ui/menu/sidebar_base.html.twig
src/bundle/Resources/views/themes/admin/ui/menu/sidebar_right.html.twig
src/bundle/Resources/views/themes/admin/ui/modal/bulk_delete_confirmation.html.twig
src/bundle/Resources/views/themes/admin/ui/search/form.html.twig
src/bundle/Resources/views/themes/admin/url_wildcard/modal_create.html.twig
src/bundle/ui-dev/src/modules/common/tooltip-popup/tooltip.popup.component.js
src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js
src/bundle/ui-dev/src/modules/universal-discovery/components/search/search.js
src/lib/Behat/PageElement/Dialog.php

| Tickets       | https://jira.ez.no/browse/EZP-31994

EZP-31994: Set color of secondary buttons as ibexa-color-base-deep

---

src/bundle/Resources/public/scss/_buttons.scss

| Tickets       | https://jira.ez.no/browse/EZP-31963

EZP-31963: Added bold for create button on dashboard (hover state)

---

src/bundle/Resources/public/scss/_card.scss
src/bundle/Resources/views/themes/admin/content_type/create.html.twig
src/bundle/Resources/views/themes/admin/content_type/edit.html.twig

JIRA ref: https://jira.ez.no/browse/EZP-31886

EZP-31886: Fieldtypes redesign

---

src/bundle/Resources/public/scss/_buttons.scss

JIRA ref: https://jira.ez.no/browse/EZP-32021

EZP-32021: Buttons in sidebar should be red on hover

---

src/bundle/Resources/public/scss/_filters.scss
src/bundle/Resources/views/themes/admin/ui/search/form.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-32012

EZP-32012: Search page has not properly aligned elements

---

src/bundle/Resources/public/scss/ui/modules/universal-discovery/_content.create.widget.scss

| Tickets       | https://jira.ez.no/browse/EZP-31969

EZP-31969: UDW - Content on the Fly - I cannot scroll all the way down to see the entire list

---

src/bundle/ui-dev/src/modules/content-tree/components/list-item/list.item.component.js

JIRA ref: https://jira.ez.no/browse/EZP-32005

EZP-32005: Add icon for each content item in the Content Tree

---

src/bundle/Resources/views/themes/admin/content/page_title_edit.html.twig

fix: Do not check referrer location if content does not exist

---

src/bundle/Resources/views/themes/admin/content/tab/policies/tab.html.twig
src/bundle/Resources/views/themes/admin/content/tab/policies/table.html.twig
src/bundle/Resources/views/themes/admin/content/tab/relations/tab.html.twig
src/bundle/Resources/views/themes/admin/content/tab/relations/table_relations.html.twig
src/bundle/Resources/views/themes/admin/content/tab/relations/table_relations_reverse.html.twig
src/bundle/Resources/views/themes/admin/content/tab/roles/tab.html.twig
src/bundle/Resources/views/themes/admin/content/tab/roles/table.html.twig
src/bundle/Resources/views/themes/admin/content/tab/url/custom_urls_table.html.twig
src/bundle/Resources/views/themes/admin/content/tab/url/system_urls_table.html.twig
src/bundle/Resources/views/themes/admin/content/tab/urls.html.twig
src/bundle/Resources/views/themes/admin/ui/dashboard/tab/all_content.html.twig
src/bundle/Resources/views/themes/admin/ui/dashboard/tab/all_media.html.twig
src/bundle/Resources/views/themes/admin/ui/dashboard/tab/my_content.html.twig
src/bundle/Resources/views/themes/admin/ui/dashboard/tab/my_draft_list.html.twig
src/bundle/Resources/views/themes/admin/ui/dashboard/tab/my_media.html.twig

JIRA ref: https://jira.ez.no/browse/EZP-31961

EZP-31961: Table header missing when the table is empty

---

src/bundle/Controller/ContentOnTheFlyController.php

| Tickets       | https://jira.ez.no/browse/EZP-32030

EZP-32030: Fixed CotF blank screen after publishing

---

src/bundle/Resources/views/themes/admin/user/role/list.html.twig

| Tickets       |  https://jira.ez.no/browse/EZP-32032

EZP-32032: Wrong color icons for Create/Delete buttons on Roles view

---

src/bundle/ui-dev/src/modules/universal-discovery/components/selected-locations/selected.locations.js
src/bundle/ui-dev/src/modules/universal-discovery/components/top-menu/top.menu.js

| Tickets       | https://jira.ez.no/browse/EZP-32036

EZP-32036: UDW icons got a wrong size for expanding and collapsing panel

---

src/bundle/Resources/public/js/scripts/fieldType/ezmedia.js

| Tickets       | https://jira.ez.no/browse/EZP-32019

EZP-32019: Switching Player settings in ezmedia field causes console error

---

src/bundle/Resources/public/scss/_icons.scss
src/bundle/Resources/public/scss/ui/modules/sub-items-list/_table.view.item.scss
src/bundle/Resources/views/themes/admin/account/bookmarks/list.html.twig
src/bundle/Resources/views/themes/admin/account/settings/list.html.twig
src/bundle/Resources/views/themes/admin/content/draft/draft_list.html.twig
src/bundle/Resources/views/themes/admin/content/draft/list.html.twig
src/bundle/Resources/views/themes/admin/content/tab/versions/table.html.twig
src/bundle/Resources/views/themes/admin/content_type/content_type_group/list.html.twig
src/bundle/Resources/views/themes/admin/content_type/macros.html.twig
src/bundle/Resources/views/themes/admin/language/index.html.twig
src/bundle/Resources/views/themes/admin/language/list.html.twig
src/bundle/Resources/views/themes/admin/link_manager/list.html.twig
src/bundle/Resources/views/themes/admin/link_manager/view.html.twig
src/bundle/Resources/views/themes/admin/object_state/list.html.twig
src/bundle/Resources/views/themes/admin/object_state/object_state_group/list.html.twig
src/bundle/Resources/views/themes/admin/object_state/object_state_group/view.html.twig
src/bundle/Resources/views/themes/admin/object_state/view.html.twig
src/bundle/Resources/views/themes/admin/section/list.html.twig
src/bundle/Resources/views/themes/admin/section/view.html.twig
src/bundle/Resources/views/themes/admin/trash/list.html.twig
src/bundle/Resources/views/themes/admin/ui/dashboard/tab/my_draft_list.html.twig
src/bundle/Resources/views/themes/admin/ui/dashboard/tab/my_drafts.html.twig
src/bundle/Resources/views/themes/admin/ui/edit_translation_button.html.twig
src/bundle/Resources/views/themes/admin/url_wildcard/list.html.twig
src/bundle/Resources/views/themes/admin/user/policy/list.html.twig
src/bundle/Resources/views/themes/admin/user/role/list.html.twig

JIRA ref: https://jira.ez.no/browse/EZP-32024

EZP-32024: Icon inside row tables should be grey

---

src/bundle/Resources/public/js/scripts/admin.content.edit.js
src/bundle/Resources/public/scss/_content-edit.scss
src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
src/bundle/Resources/translations/content.en.xliff
src/bundle/Resources/views/themes/admin/content/form_fields.html.twig
src/bundle/Resources/views/themes/admin/content/page_title_edit.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-32015

EZP-32015: Header in edit mode need visual correction

---

src/bundle/Resources/public/scss/_badges.scss
src/bundle/Resources/public/scss/_dashboard.scss

| Tickets       | https://jira.ez.no/browse/EZP-32007

EZP-32007 Styling of notification box

---

src/bundle/Resources/public/scss/_content-edit.scss
src/bundle/Resources/views/themes/admin/content/page_title_edit.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-32035

EZP-32035: [X] button overlaps with Creating/Editing in edit/draft (or create/user)

---

src/bundle/Resources/public/scss/_login.scss
src/bundle/Resources/translations/messages.en.xliff
src/bundle/Resources/views/themes/admin/account/base.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-32029

EZP-32029: Update wording on the Admin login screen

---

src/bundle/Resources/public/scss/_notifications-menu.scss
src/bundle/Resources/public/scss/_user-menu.scss

| Tickets       | https://jira.ez.no/browse/EZP-31975

EZP-31975: FR/DE backoffice language - summary bug for redesign

---

src/bundle/Resources/public/js/scripts/core/custom.dropdown.js
src/bundle/Resources/public/scss/core/_custom.dropdown.scss
src/bundle/Resources/public/scss/mixins/_tags.scss
src/bundle/Resources/views/themes/admin/ui/component/custom_dropdown.html.twig
src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezcountry.html.twig
src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezselection.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-32016

EZP-32016: Redesign multi select

---

src/bundle/Resources/public/scss/_buttons.scss
src/bundle/Resources/views/themes/admin/ui/menu/sidebar_base.html.twig

| Tickets       | https://jira.ez.no/browse/EZEE-3315

EZEE-3315: Discard publish later icon is too small

---

src/bundle/Resources/public/scss/_custom.scss

| Tickets       | https://jira.ez.no/browse/EZP-32049

EZP-32049: Update primary color

---

src/bundle/Resources/public/scss/_buttons.scss

| Tickets       | https://jira.ez.no/browse/EZP-32028

EZP-32028: Hover status in the left side menu should be lighten

---

src/bundle/Resources/public/scss/_alerts.scss
src/bundle/Resources/public/scss/_buttons.scss
src/bundle/Resources/views/themes/admin/ui/dashboard/dashboard.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-32050

EZP-32050: Design fixes for dashboard

---

src/bundle/Resources/views/themes/admin/ui/search/form.html.twig
src/bundle/Resources/views/themes/admin/ui/search/index.html.twig
src/lib/Behat/PageObject/SearchPage.php

| Tickets       | https://jira.ez.no/browse/EZP-32054

EZP-32054: Search view is inconsistent with other main views

---

src/bundle/Resources/views/themes/admin/content/page_title_edit.html.twig

| Tickets       | https://jira.ez.no/browse/EC-276

EC-276: Create new Product catalog content form contains unnecessary information icon in header

---

src/bundle/Resources/translations/messages.en.xliff

jira ref: https://jira.ez.no/browse/EZP-32055

EZP-32055: Removed unnecessary apostrophe on login page

---

src/lib/Behat/Environment/PlatformEnvironmentConstants.php

| Tickets       | jira.ez.no/browse/EZP-32040
Failing build: https://travis-ci.org/github/ezsystems/ezplatform/builds/737015690
Related PR introducing the change: https://github.com/ezsystems/ezplatform-kernel/pull/119/files

[Behat] Changed root content name to Ibexa

---

src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js

| Tickets       | https://jira.ez.no/browse/EZP-32052

EZP-32052: Widget in right sidebar sometimes is not visible after click

---

src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss

| Tickets       | https://jira.ez.no/browse/EZP-32065

EZP-32065: Icon i next to label - size change needed from 1.5 rem to 1

---

src/bundle/Resources/public/scss/fieldType/edit/_base-preview.scss
src/bundle/Resources/translations/content_type.en.xliff
src/bundle/Resources/translations/ezplatform_content_forms_content.en.xliff
src/bundle/Resources/translations/ezplatform_content_forms_policies.en.xliff
src/bundle/Resources/translations/forms.en.xliff
src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezbinaryfile.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-32061

EZP-32061: [File] Incorrect label for download button / buttons are too close to each other

---

src/bundle/Resources/public/scss/_icons.scss

| Tickets       | https://jira.ez.no/browse/EZP-32058

EZP-32058: Dialog box need visual correction (exactly comments)

---

src/bundle/Resources/views/themes/admin/content_type/field_types.html.twig

JIRA ref: https://jira.ez.no/browse/EZEE-3325

EZEE-3325: Cancel publication button has wrong color

---

src/bundle/Resources/public/scss/core/_custom.dropdown.scss
src/bundle/Resources/views/themes/admin/ui/component/custom_dropdown.html.twig
src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezcountry.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-32059

EZP-32059: Muli-select issues

---

src/bundle/Resources/public/scss/_buttons.scss
src/bundle/Resources/public/scss/_icons.scss

JIRA ref: https://jira.ez.no/browse/EZP-32066

EZP-32066: Active hover button in right sidebar has wrong icon fill

---

src/bundle/Resources/public/scss/_custom.scss

jira ref: https://jira.ez.no/browse/EZP-32071

EZP-32071: added more space in breadcrumbs

---

src/bundle/Resources/public/scss/_alerts.scss
src/bundle/Resources/views/themes/admin/content/location_view.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-32068

EZP-32068: Document alerts - need redesign

---

src/bundle/Resources/views/themes/admin/limitation/base_limitation_values.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-32070

EZP-32070: Fixed Content Edit and Publish policy with grouped choices

---

src/bundle/Resources/views/themes/admin/account/bookmarks/toggle_switch.html.twig
src/bundle/ui-dev/src/modules/universal-discovery/components/selected-locations/selected.locations.js
src/bundle/ui-dev/src/modules/universal-discovery/content.meta.preview.module.js

| Tickets       | https://jira.ez.no/browse/EZP-32074

EZP-32074: Missing hover state in UDW buttons

---

src/bundle/Resources/public/scss/_badges.scss

Fixed white font color in badges

---

src/bundle/Resources/public/scss/_badges.scss

Fixed badge hover state

---

src/bundle/Resources/public/scss/_error-page.scss
src/bundle/Resources/public/scss/_general.scss
src/bundle/Resources/views/themes/admin/ui/error_page/403.html.twig
src/bundle/Resources/views/themes/admin/ui/error_page/404.html.twig
src/bundle/Resources/views/themes/admin/ui/error_page/unknown.html.twig

| Tickets       | https://jira.ez.no/browse/EZP-32075

EZP-32075: Redesign error page

---

src/bundle/Resources/translations/universal_discovery_widget.en.xliff
src/bundle/ui-dev/src/modules/sub-items/components/table-view/table.view.columns.toggler.js
src/bundle/ui-dev/src/modules/universal-discovery/components/top-menu/top.menu.js

| Tickets       | https://jira.ez.no/browse/EZP-32100

EZP-32100: Missing hover state in subitems buttons

---

src/bundle/Resources/public/scss/ui/modules/universal-discovery/_finder.branch.scss
src/bundle/ui-dev/src/modules/universal-discovery/components/finder/finder.branch.js

jira ref: https://jira.ez.no/browse/EZP-31734

EZP-31968: Added spinner to UDW

---

src/bundle/Resources/public/scss/core/_custom.dropdown.scss

jira ref:  https://jira.ez.no/browse/EC-286

EC-286: set max width for ez-custom-dropdown options container

---

src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimage.html.twig
src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimageasset.html.twig

| Tickets       | https://issues.ibexa.co/browse/EZEE-3355

EZEE-3355: Create extension point in ezimage and ezimageasset fieldtype

---

features/standard/UserCreation.feature
src/lib/Behat/BusinessContext/ContentUpdateContext.php
src/lib/Behat/BusinessContext/ContentViewContext.php
src/lib/Behat/PageElement/ContentField.php
src/lib/Behat/PageElement/ContentUpdateForm.php
src/lib/Behat/PageElement/Fields/UserAccount.php
src/lib/Behat/PageObject/ContentItemPage.php
src/lib/Behat/PageObject/Page.php
src/lib/Behat/PageObject/PlatformPageObjectFactory.php
src/lib/Behat/PageObject/UserCreationPage.php

| Tickets       |  EZP-32136
- Added test scenario with user creation
- Added test scenario with editing an existing user

[Behat] EZP-32136 User creation

---

src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimage.html.twig

| Tickets       | EZEE-3350
Part of:
https://github.com/ezsystems/ezplatform-content-forms/pull/36
https://github.com/ezsystems/ezplatform-kernel/pull/137
Build : 
:green_circle: https://github.com/ezsystems/ezplatform-page-builder/pull/701/checks?check_run_id=1447401584

EZEE-3350: Added support for saving additional image data from adminUI

---

features/standard/UserCreation.feature
src/lib/Behat/BusinessContext/ContentUpdateContext.php
src/lib/Behat/BusinessContext/ContentViewContext.php
src/lib/Behat/PageElement/ContentField.php
src/lib/Behat/PageElement/ContentUpdateForm.php
src/lib/Behat/PageElement/Fields/UserAccount.php
src/lib/Behat/PageObject/ContentItemPage.php
src/lib/Behat/PageObject/PlatformPageObjectFactory.php
src/lib/Behat/PageObject/UserCreationPage.php

Test PR for upstream merge of https://github.com/ezsystems/ezplatform-admin-ui/pull/1652

[Behat] Test upstream merge

---

src/bundle/Resources/public/scss/fieldType/edit/_ezgmaplocation.scss

| Tickets       | [EZP-32197](https://issues.ibexa.co/browse/EZP-32197)

EZP-32197: added z-index to prevent overlapping with other elements

---

src/bundle/Resources/public/scss/_icons.scss

| Tickets       | https://issues.ibexa.co/browse/EZEE-3399

EZEE-3399: Remove icon hover state on disabled buttons

---

src/bundle/Resources/public/scss/_error-page.scss

| Tickets       | https://issues.ibexa.co/browse/EZP-32226

EZP-32226: Logo in error page is misaligned

---

src/bundle/Resources/public/js/scripts/fieldType/ezimage.js

| Tickets       | https://issues.ibexa.co/browse/EC-288

EC-288: Uncaught typeerror cannot read property focus of undefined

---

features/standard/SystemInfo.feature

| Tickets       | [EZP-32243](https://issues.ibexa.co/browse/EZP-32243)
Adapted Behat tests for changes introduced in **required PR**: https://github.com/ezsystems/ez-support-tools/pull/76.

EZP-32243: Exposed repository object counts in database tab

---

src/lib/Strategy/ContentTypeThumbnailStrategy.php

| Tickets       | https://jira.ez.no/browse/EZP-31795
https://github.com/ezsystems/ezplatform-kernel/pull/158

EZP-31795: Aligned getThumbnail method signature

---

src/bundle/Resources/public/js/scripts/core/custom.dropdown.js
src/bundle/Resources/public/scss/_add-translation.scss
src/bundle/Resources/public/scss/core/_custom.dropdown.scss

| Tickets       | https://issues.ibexa.co/browse/EZP-32166

EZP-32166: Base translation dropdown single selection issue

---

src/bundle/Resources/public/scss/ui/modules/universal-discovery/_grid.item.scss

| Tickets       | https://issues.ibexa.co/browse/EZP-32285

EZP-32285: Cropped image needs to be improved in UDW thumbnail view

---

src/bundle/Resources/public/scss/_inputs.scss
src/bundle/Resources/public/scss/_mixins.scss
src/bundle/Resources/public/scss/mixins/_inputs.scss

| Tickets       | https://issues.ibexa.co/browse/EZEE-3375
https://github.com/ezsystems/ezplatform-page-builder/pull/724
https://github.com/ezsystems/ezplatform-admin-ui/pull/1700

EZEE-3375: 'Multiple' PB block's attribute is not rendering properly

---

src/bundle/Resources/config/services/views.yaml
src/lib/View/Filter/AdminSearchViewFilter.php

>https://issues.ibexa.co/browse/IBX-2
Applying changes from https://github.com/ezsystems/ezplatform-search/pull/14 on adminUI side

IBX-2: Specified action path for search form for easier reuse

---

src/lib/Behat/BusinessContext/ContentViewContext.php

Test merge

---

src/bundle/Resources/config/services/form_ui_action_mappers.yaml

Fixed invalid EzSystems\EzPlatformAdminUi\UI\Action\FormUiActionMapperInterface alias definition

Fixed EzSystems\EzPlatformAdminUi\UI\Action\FormUiActionMapperInterface alias definition

---

src/lib/Form/SubmitHandler.php

| Tests pass?   | unrelated
Fixes wrong type declared in SubmitHandler closure.

Fixed wrong type declared in phpdoc in SubmitHandler

---

src/bundle/Resources/public/scss/_picker.scss

| Tickets       | https://issues.ibexa.co/browse/EZEE-3496

EZEE-3496: Remove buttons disappear from set data inputs

---

src/bundle/ui-dev/src/modules/universal-discovery/components/finder/finder.leaf.js

| Tickets       | https://issues.ibexa.co/browse/IBX-247
Cuts loadedLocations in different point.

IBX-247: UDW - cannot select item

---

src/bundle/Resources/public/scss/ui/modules/sub-items-list/_table.view.item.scss

| Tickets       | https://issues.ibexa.co/browse/IBX-241

IBX-241: Subitems - priority buttons hidden behind most-right column

---

src/bundle/Resources/public/scss/_custom.scss

| Tickets       | https://issues.ibexa.co/browse/IBX-267
| BC breaks?    | ?
| Doc needed?   | ?
Added new colors for 4.0 redesign.

IBX-267: As a Maintainer, I want to have defined color palette and typography

---

src/lib/Behat/BusinessContext/UserPreferencesContext.php
src/lib/Behat/PageObject/ChangePasswordPage.php

Fixes upstream merge of https://github.com/ezsystems/ezplatform-admin-ui/pull/1764

[Behat] Fixed imports in v3 merge-up

---

src/lib/EventListener/UserPasswordChangeRightSidebarListener.php

| Tickets       | [IBX-457](https://issues.ibexa.co/browse/IBX-457)
Fixes "Update" button in Change my password view.

IBX-457: Fix update button in Change my password

---

src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js

| Tickets       | https://issues.ibexa.co/browse/IBX-523

IBX-523: Create content menu causes console error

---

src/bundle/ui-dev/src/modules/universal-discovery/components/content-create-widget/content.create.widget.js

| Tickets       | [IBX-445](https://issues.ibexa.co/browse/IBX-445)

IBX-445: selected first enabled language for create content #291

---

src/bundle/Resources/public/scss/_breadcrumb.scss
src/bundle/Resources/public/scss/_general.scss
src/bundle/Resources/public/scss/ui/modules/sub-items-list/_table.view.item.scss

| Tickets       | https://issues.ibexa.co/browse/IBX-491
https://github.com/ezsystems/ezplatform-admin-ui/pull/1774
https://github.com/ezsystems/ezplatform-page-builder/pull/766

IBX-491: As an Editor, I want to see redesigned links

---

src/lib/Form/DataTransformer/UDWBasedValueModelTransformer.php
src/lib/Limitation/Templating/LimitationBlockRenderer.php
src/lib/Tests/Form/DataTransformer/UDWBasedValueViewTransformerTest.php

| Tickets       | [IBX-461](https://jira.ez.no/browse/IBX-461)
Follow up PR of https://github.com/ezsystems/repository-forms/pull/347.

IBX-461: Fixed roles with deleted limitations

---

src/bundle/Resources/views/themes/admin/content/tab/locations/tab.html.twig

| Tickets       | [IBX-664](https://issues.ibexa.co/browse/IBX-664)

IBX-664: changed desc for pagination.viewing trans

---

src/bundle/Resources/public/scss/_buttons.scss

| Tickets       | https://issues.ibexa.co/browse/IBX-737
Issue: https://github.com/ezsystems/ezplatform-admin-ui/pull/1785#issuecomment-875678323

IBX-737: Disabled buttons in Context Menu should be purple instead of grey

---

src/bundle/Resources/views/themes/admin/account/settings/list.html.twig

Fixed reference to tab_pane.html.twig

---

.github/workflows/ci.yaml
.travis.yml
composer.json

https://issues.ibexa.co/browse/IBX-673

IBX-673 Moving some jobs from Travis to GitHub actions in ezplatform-admin-ui

---

src/bundle/Resources/public/js/scripts/fieldType/ezrichtext.js
src/bundle/Resources/public/scss/fieldType/edit/_ezrichtext.scss
src/bundle/Resources/views/themes/admin/content/edit/javascripts.html.twig
src/bundle/Resources/views/themes/admin/content/edit/stylesheets.html.twig
src/bundle/Resources/views/themes/admin/ui/layout.html.twig
src/lib/Behat/Component/Fields/RichText.php

| Tickets       | https://issues.ibexa.co/browse/IBX-93

IBX-93: Replaced AlloyEditor with CKEditor5

---

src/lib/Behat/Page/AdminUpdateItemPage.php
src/lib/Behat/Page/ContentTypeUpdatePage.php
src/lib/Behat/Page/RoleUpdatePage.php

Adapted CSS selectors to the redesign. Follow up to https://github.com/ezsystems/ezplatform-admin-ui/pull/1796

[Behat] Corrected selector for main container in Admin update pages

---

src/lib/Behat/Component/ContentActionsMenu.php

| Tickets       | https://issues.ibexa.co/browse/IBX-836
Error:
```
And I click on the edit action bar button "Update"                             # Ibexa\AdminUi\Behat\BrowserContext\ContentActionsMenuContext::clickEditActionBar()
Exception: element click intercepted: Element is not clickable at point (1208, -7)
(Session info: chrome=90.0.4430.85)
(Driver info: chromedriver=90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429}),platform=Linux 4.4.0-101-generic x86_64) in …
```

IBX-836: [Behat] Changed menu buttons to click directly on label

---

src/bundle/Resources/public/js/scripts/fieldType/ezdate.js
src/bundle/Resources/public/js/scripts/fieldType/ezdatetime.js
src/bundle/Resources/public/js/scripts/fieldType/eztime.js
src/bundle/Resources/public/scss/_icons.scss
src/bundle/Resources/public/scss/_inputs.scss
src/bundle/Resources/public/scss/_mixins.scss
src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
src/bundle/Resources/public/scss/fieldType/edit/_ezdate.scss
src/bundle/Resources/public/scss/fieldType/edit/_ezdatetime.scss
src/bundle/Resources/public/scss/fieldType/edit/_eztime.scss
src/bundle/Resources/public/scss/mixins/_inputs.scss
src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezdate.html.twig
src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezdatetime.html.twig
src/bundle/Resources/views/themes/admin/ui/field_type/edit/eztime.html.twig
src/lib/Behat/Component/Fields/Date.php
src/lib/Behat/Component/Fields/DateAndTime.php
src/lib/Behat/Component/Fields/Time.php

| Tickets       | https://issues.ibexa.co/browse/IBX-626 https://issues.ibexa.co/browse/IBX-627 https://issues.ibexa.co/browse/IBX-642

IBX-626,627,642: Redesigned eztime, ezdate, ezdatetime

---

src/bundle/Resources/public/js/scripts/fieldType/ezfloat.js
src/bundle/Resources/public/js/scripts/fieldType/ezinteger.js
src/bundle/Resources/public/scss/fieldType/edit/_ezfloat.scss
src/bundle/Resources/public/scss/fieldType/edit/_ezinteger.scss
src/bundle/Resources/views/themes/admin/content/form_fields.html.twig

| Tickets       | https://issues.ibexa.co/browse/IBX-633 https://issues.ibexa.co/browse/IBX-629

IBX-629,633: Redesigned ezfloat, ezinteger

---

src/bundle/Resources/public/scss/fieldType/edit/_eznoneditable.scss
src/bundle/Resources/views/themes/admin/content/edit/base.html.twig
src/lib/Behat/Page/ContentUpdateItemPage.php

| Tickets       | https://issues.ibexa.co/browse/IBX-624

IBX-624: Redesigned ezquery

---

src/bundle/Resources/public/js/scripts/fieldType/ezauthor.js
src/bundle/Resources/public/scss/fieldType/edit/_ezauthor.scss
src/bundle/Resources/translations/messages.en.xliff
src/bundle/Resources/translations/trash.en.xliff
src/bundle/Resources/views/themes/admin/content/modal/location_trash.html.twig
src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezauthor.html.twig

| Tickets       | https://issues.ibexa.co/browse/IBX-620

IBX-620: Redesigned ezauthor

---

src/bundle/Resources/public/js/scripts/fieldType/ezuser.js
src/bundle/Resources/public/scss/fieldType/edit/_ezuser.scss
src/bundle/Resources/public/scss/fieldType/preview/_ezuser.scss
src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig

| Tickets       | https://issues.ibexa.co/browse/IBX-645

IBX-645: Redesigned ezuser

---

src/bundle/Resources/public/js/scripts/fieldType/ezstring.js
src/bundle/Resources/public/scss/fieldType/edit/_ezstring.scss

| Tickets       | https://issues.ibexa.co/browse/IBX-641

IBX-641: Text Line Field Type redesign

---

src/bundle/Resources/views/themes/admin/ui/form_fields/dropdown_widget.html.twig

| Tickets       | https://issues.ibexa.co/browse/IBX-884

IBX-884: It's not possible to set block reveal and hide date

---

src/bundle/Resources/public/js/scripts/fieldType/eztext.js
src/bundle/Resources/public/scss/fieldType/edit/_eztext.scss

| Tickets       | https://issues.ibexa.co/browse/IBX-640

IBX-640: Text Block Field Type redesign

---

src/bundle/Resources/public/js/scripts/fieldType/ezauthor.js
src/bundle/Resources/public/js/scripts/fieldType/ezobjectrelationlist.js
src/bundle/Resources/public/scss/_inputs.scss
src/bundle/Resources/public/scss/_tables.scss
src/bundle/Resources/public/scss/fieldType/edit/_ezobjectrelationlist.scss
src/bundle/Resources/public/scss/mixins/_inputs.scss
src/bundle/Resources/translations/ezplatform_content_forms_content.en.xliff
src/bundle/Resources/translations/messages.en.xliff
src/bundle/Resources/views/themes/admin/ui/field_type/edit/relation_base.html.twig
src/bundle/ui-dev/src/modules/universal-discovery/components/pure-toggle-selection-button/pure.toggle.selection.button.js
src/lib/Behat/Component/Fields/ContentRelationMultiple.php
src/lib/Behat/Component/Fields/ContentRelationSingle.php

| Tickets       | https://issues.ibexa.co/browse/IBX-622 https://issues.ibexa.co/browse/IBX-623

IBX-622,623: Redesigned ezobjectrelation, ezobjectrelationlist

---

src/bundle/Resources/public/js/scripts/fieldType/ezboolean.js

| Tickets       | https://issues.ibexa.co/browse/IBX-621

IBX-621: Redesigned ezboolean

---

src/bundle/Resources/public/js/scripts/fieldType/ezcountry.js
src/bundle/Resources/public/scss/_dropdown.scss
src/bundle/Resources/views/themes/admin/ui/component/table/table.html.twig
src/bundle/Resources/views/themes/admin/ui/component/table/table_header.html.twig

| Tickets       | https://issues.ibexa.co/browse/IBX-625

IBX-625: Redesigned ezcountry

---

src/bundle/Resources/public/js/scripts/fieldType/ezkeyword.js

| Tickets       | https://issues.ibexa.co/browse/IBX-634

IBX-634: Redesigned ezkeyword

---

src/bundle/Resources/public/js/scripts/fieldType/ezboolean.js
src/bundle/Resources/public/js/scripts/fieldType/ezcountry.js
src/bundle/Resources/public/js/scripts/fieldType/ezkeyword.js
src/bundle/Resources/public/js/scripts/fieldType/ezselection.js
src/bundle/Resources/public/scss/fieldType/edit/_ezboolean.scss
src/bundle/Resources/public/scss/fieldType/edit/_ezcountry.scss
src/bundle/Resources/public/scss/fieldType/edit/_ezkeyword.scss
src/bundle/Resources/public/scss/fieldType/edit/_ezselection.scss
src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezcountry.html.twig
src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezkeyword.html.twig
src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezselection.html.twig
src/lib/Behat/Component/Fields/Keywords.php

| Tickets       | https://issues.ibexa.co/browse/IBX-639

IBX-639: Redesigned ezselection

---

src/lib/Behat/Component/IbexaDropdown.php

JIRA:https://issues.ibexa.co/browse/IBX-835
This PR improves stability of Roles.feature tests (by slowing them down).
Usleep() methods are to be removed after redesign ends

[Behat] Improved Ibexa dropdown stability

---

src/bundle/Resources/public/js/scripts/fieldType/base/base-file-field.js
src/bundle/Resources/public/js/scripts/fieldType/base/base-preview-field.js
src/bundle/Resources/public/js/scripts/fieldType/ezbinaryfile.js
src/bundle/Resources/public/js/scripts/fieldType/ezimage.js
src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js
src/bundle/Resources/public/js/scripts/fieldType/ezmedia.js
src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
src/bundle/Resources/public/scss/fieldType/edit/_base-preview.scss
src/bundle/Resources/public/scss/fieldType/edit/_ezbinaryfile.scss
src/bundle/Resources/public/scss/fieldType/edit/_ezimage.scss
src/bundle/Resources/public/scss/fieldType/edit/_ezimageasset.scss
src/bundle/Resources/public/scss/fieldType/edit/_ezmedia.scss
src/bundle/Resources/public/scss/fieldType/preview/_ezimageasset.scss
src/bundle/Resources/translations/ezplatform_content_forms_content.en.xliff
src/bundle/Resources/views/themes/admin/ui/field_type/edit/binary_base.html.twig
src/bundle/Resources/views/themes/admin/ui/field_type/edit/binary_base_fields.html.twig
src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezbinaryfile.html.twig
src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimage.html.twig
src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimageasset.html.twig
src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezmedia.html.twig
src/lib/Behat/Component/Fields/ImageAsset.php

| Tickets       | https://issues.ibexa.co/browse/IBX-628, https://issues.ibexa.co/browse/IBX-631, https://issues.ibexa.co/browse/IBX-632, https://issues.ibexa.co/browse/IBX-637
Requires:
https://github.com/ezsystems/ezplatform-connector-dam/pull/36
https://github.com/ibexa/image-editor/pull/35

IBX-628,631,632,637: Redesigned ezbinary, ezmedia, ezimage, ezimageasset

---

src/bundle/Resources/public/js/scripts/fieldType/ezselection.js

| Tickets       | https://issues.ibexa.co/browse/IBX-916

IBX-916: Changed selector for ezselection validator

---

src/bundle/Resources/views/themes/admin/content_type/content_type_group/list.html.twig

| Tickets       | https://issues.ibexa.co/browse/IBX-923

IBX-923: Fixed issue with disabling deletion of Content Type Groups

---

src/bundle/Resources/public/js/scripts/core/dropdown.js

| Tickets       | https://issues.ibexa.co/browse/IBX-927

IBX-927: Ibexa dropdown overflows under screen on bottom if too many options

---

src/bundle/Resources/public/js/scripts/core/base.chart.js
src/bundle/Resources/public/scss/core/_chart.scss
src/bundle/Resources/views/themes/admin/ui/chart.html.twig

| Tickets       | https://issues.ibexa.co/browse/IBX-930

IBX-930: As a Developer, I want to use ibexa-chart class name

---

src/lib/Menu/ContentRightSidebarBuilder.php

| Tickets       | https://issues.ibexa.co/browse/IBX-949

IBX-949: "Copy" button does not invoke the Copy action

---

src/bundle/Resources/public/js/scripts/admin.location.add.translation.js
src/bundle/Resources/public/js/scripts/core/dropdown.js
src/bundle/Resources/public/js/scripts/fieldType/ezcountry.js
src/bundle/Resources/public/js/scripts/fieldType/ezdate.js
src/bundle/Resources/public/js/scripts/fieldType/ezdatetime.js
src/bundle/Resources/public/js/scripts/fieldType/ezselection.js
src/bundle/Resources/public/js/scripts/fieldType/eztime.js

JIRA ref: https://issues.ibexa.co/browse/IBX-928
https://github.com/ezsystems/ezplatform-admin-ui/pull/1873
https://github.com/ezsystems/ezcommerce-shop/pull/343
https://github.com/ezsystems/ezplatform-form-builder/pull/302

IBX-928: Change valueChanged event to change event in inputs

---

src/bundle/Resources/public/scss/_dropdown.scss
src/bundle/Resources/views/themes/admin/ui/component/dropdown.html.twig
src/bundle/Resources/views/themes/admin/ui/form_fields/dropdown_widget.html.twig

| Tickets       | https://issues.ibexa.co/browse/IBX-959

IBX-959: As a Developer I want Custom Dropdowns to respect "preferred_choices" in ChoiceType forms

---

src/bundle/Controller/ContentEditController.php
src/bundle/Controller/TranslationController.php
src/bundle/Resources/config/routing.yaml
src/lib/Event/ContentProxyTranslateEvent.php
src/lib/EventListener/ContentProxyCreateDraftListener.php
src/lib/Tests/EventListener/ContentProxyCreateDraftListenerTest.php

| Tickets       | [IBX-862](https://issues.ibexa.co/browse/IBX-862)
This PR is a direct follow-up of PR for branch `1.5`: https://github.com/ezsystems/ezplatform-admin-ui/pull/1845

IBX-862: Fixed translation action originating from non-main Location

---

src/bundle/Resources/public/scss/_general.scss

| Tickets       | https://issues.ibexa.co/browse/IBX-955
Removed style for :visited link and set transition as $admin-transition-duration for links

IBX-955: clicked buttons links

---

src/bundle/Resources/public/scss/_icons.scss

| Tickets       | https://issues.ibexa.co/browse/IBX-1044

IBX-1044: Add ibexa-icon 8px & 12px variants

---

src/bundle/Resources/public/js/scripts/fieldType/ezauthor.js

| Tickets       | https://issues.ibexa.co/browse/IBX-1041

IBX-1041: Fixed checkbox selector in ezauthor field type

---

src/bundle/Resources/public/scss/_header-user-menu.scss
src/bundle/Resources/views/themes/admin/ui/menu/user.html.twig

| Tickets       | https://issues.ibexa.co/browse/IBX-1028

IBX-1028: Fixed notification dot to be circle

---

src/bundle/Resources/public/scss/_login.scss
src/bundle/Resources/views/themes/admin/account/base.html.twig
src/bundle/Resources/views/themes/admin/account/login/index.html.twig

| Tickets       | https://issues.ibexa.co/browse/IBX-1036

IBX-1036: Fixed login button size

---

src/bundle/Resources/public/scss/_buttons.scss

| Tickets       | https://issues.ibexa.co/browse/IBX-1030

IBX-1030: Fixed secondary button hover state

---

src/bundle/Resources/public/scss/_inputs.scss
src/bundle/Resources/public/scss/_labels.scss
src/bundle/Resources/public/scss/_tables.scss

| Tickets       | https://issues.ibexa.co/browse/IBX-1048

IBX-1048: Fixed checkbox alignment in tables

---

src/bundle/Resources/public/js/scripts/sidebar/instant.filter.js

| Tickets       | https://issues.ibexa.co/browse/IBX-1024

IBX-1024: Hide group when all children are hidden in instant filter

---

src/bundle/Resources/views/themes/admin/ui/dashboard/tab/all_content.html.twig
src/bundle/Resources/views/themes/admin/ui/dashboard/tab/all_media.html.twig
src/bundle/Resources/views/themes/admin/ui/dashboard/tab/my_content.html.twig
src/bundle/Resources/views/themes/admin/ui/dashboard/tab/my_draft_list.html.twig
src/bundle/Resources/views/themes/admin/ui/dashboard/tab/my_media.html.twig

| Tickets       | https://issues.ibexa.co/browse/IBX-1059

IBX-1059: Fixed icon color in tables

---

src/bundle/Resources/views/themes/admin/content/widget/content_create.html.twig
src/bundle/Resources/views/themes/admin/content/widget/content_edit.html.twig

| Tickets       | https://issues.ibexa.co/browse/IBX-1026
| Requires    | https://github.com/ezsystems/date-based-publisher/pull/240 https://github.com/ezsystems/ezplatform-workflow/pull/225

IBX-1026: Changed icon size in extra actions header

---

src/bundle/Resources/public/js/scripts/admin.content.edit.js
src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js

| Tickets       | [IBX-823](https://issues.ibexa.co/browse/IBX-823)

IBX-823: Enable/Disable validation form before send workflow review

---

src/bundle/Resources/public/js/scripts/user_password.change.js
src/bundle/Resources/public/scss/_forms.scss
src/bundle/Resources/views/themes/admin/account/change_password/form_fields.html.twig

| Tickets       | https://issues.ibexa.co/browse/IBX-1092

IBX-1092: Fixed validation styles in change password

---

src/bundle/Resources/public/scss/_dropdown.scss
src/bundle/Resources/views/themes/admin/ui/component/input_text.html.twig

| Tickets       | https://issues.ibexa.co/browse/IBX-1025

IBX-1025: Fixed search icon size in custom dropdown

---

src/bundle/Resources/public/scss/_dropdown.scss

| Tickets       | https://issues.ibexa.co/browse/IBX-1029

IBX-1029: Fixed white arrow in dropdown

---

src/bundle/Resources/public/scss/_tables.scss
src/bundle/Resources/public/scss/_tabs.scss

| Tickets       | https://issues.ibexa.co/browse/IBX-1096

IBX-1096: Changed border from table to table header

---

src/bundle/Resources/public/js/scripts/admin.dropdown.js
src/bundle/Resources/views/themes/admin/ui/component/dropdown.html.twig
src/bundle/Resources/views/themes/admin/ui/component/dropdown_item.html.twig
src/bundle/Resources/views/themes/admin/ui/form_fields/dropdown_widget.html.twig

| Tickets       | https://issues.ibexa.co/browse/IBX-1097
https://github.com/ezsystems/ezcommerce-admin-ui/pull/108
https://github.com/ezsystems/ezcommerce-shop/pull/351

IBX-1097: Change properties for reusable Dropdown widget

---

src/bundle/Resources/encore/ez.js.config.js
src/bundle/Resources/public/js/scripts/admin.role_assignment.add.js
src/bundle/Resources/public/js/scripts/core/tag.view.select.js
src/bundle/Resources/public/scss/_tag-view-select.scss
src/bundle/Resources/public/scss/ezplatform.scss
src/bundle/Resources/views/themes/admin/ui/component/tag_view_select.html.twig
src/bundle/Resources/views/themes/admin/ui/component/tag_view_select_selected_item.html.twig
src/bundle/Resources/views/themes/admin/ui/component/tag_view_select_selected_item_tag.html.twig
src/bundle/Resources/views/themes/admin/user/role_assignment/create.html.twig
src/lib/Behat/Page/AdminUpdateItemPage.php
src/lib/Behat/Page/RoleUpdatePage.php

| Tickets       | https://issues.ibexa.co/browse/IBX-981

IBX-981: Select content widget

---

src/bundle/Resources/public/js/scripts/core/dropdown.js
src/bundle/Resources/public/scss/_dropdown.scss

| Tickets       | https://issues.ibexa.co/browse/IBX-1101

IBX-1101: Changed transition from scale to opacity

---

src/bundle/Resources/views/themes/admin/content_type/index.html.twig
src/bundle/Resources/views/themes/admin/ui/tab/content_type.html.twig
src/lib/Menu/ContentTypeRightSidebarBuilder.php

| Tickets       | https://issues.ibexa.co/browse/IBX-1128

IBX-1128: Fixed header in content type view

---

src/bundle/Resources/public/scss/_main-menu.scss
src/bundle/Resources/public/scss/core/_custom.tooltip.scss

| Tickets       | https://issues.ibexa.co/browse/IBX-1054

IBX-1054: Fixed navigation font size

---

src/bundle/Resources/views/themes/admin/content/tab/locations/tab.html.twig
src/bundle/Resources/views/themes/admin/content/tab/translations/tab.html.twig
src/bundle/Resources/views/themes/admin/content/tab/urls.html.twig
src/bundle/Resources/views/themes/admin/content/tab/versions/tab.html.twig
src/bundle/Resources/views/themes/admin/ui/tab/location_view.html.twig

| Tickets       | https://issues.ibexa.co/browse/IBX-1066

IBX-1066: Changed buttons padding in table actions

---

src/bundle/Resources/translations/content_edit.en.xliff
src/bundle/Resources/translations/content_type.en.xliff
src/bundle/Resources/translations/messages.en.xliff
src/bundle/Resources/translations/multi_file_upload.en.xliff
src/bundle/Resources/translations/role.en.xliff

JIRA ref: https://issues.ibexa.co/browse/IBX-1139

IBX-1139: Add translation to admin-ui

---

src/bundle/Resources/encore/ez.js.config.js
src/bundle/Resources/public/js/scripts/admin.content.tree.js
src/bundle/Resources/public/js/scripts/button.translation.edit.js
src/bundle/Resources/public/js/scripts/sidebar/main.menu.js
src/bundle/Resources/public/scss/_extra-actions.scss
src/bundle/Resources/public/scss/_general.scss
src/bundle/Resources/public/scss/_main-container.scss
src/bundle/Resources/public/scss/_main-header.scss
src/bundle/Resources/public/scss/_main-menu.scss
src/lib/Behat/Component/SubItemsList.php

| Tickets       | https://issues.ibexa.co/browse/IBX-1013

IBX-1013: Fixed top header and disabled animation for scrolling side menu

---

src/bundle/Resources/public/scss/_grid-view-item.scss
src/bundle/Resources/public/scss/_grid-view.scss
src/bundle/Resources/public/scss/ezplatform.scss
src/bundle/Resources/public/scss/ui/modules/_sub.items.list.scss
src/bundle/ui-dev/src/modules/sub-items/components/grid-view/grid.view.component.js
src/bundle/ui-dev/src/modules/sub-items/components/grid-view/grid.view.item.component.js
src/lib/Behat/Component/Table/SubitemsGrid.php

| Tickets       | https://issues.ibexa.co/browse/IBX-1145

IBX-1145: Reusable grid CSS classes

---

src/bundle/Resources/public/scss/ui/modules/universal-discovery/_content.create.widget.scss
src/bundle/Resources/public/scss/ui/modules/universal-discovery/_dropdown.scss
src/bundle/ui-dev/src/modules/universal-discovery/components/content-create-widget/content.create.widget.js

| Tickets       | https://issues.ibexa.co/browse/IBX-1373

IBX-1373: There's no CustomDropdown in UDW Create widget

---

src/bundle/Controller/ContentViewController.php
src/bundle/Resources/views/dashboard/tab/all_content.html.twig
src/bundle/Resources/views/dashboard/tab/all_media.html.twig
src/bundle/Resources/views/dashboard/tab/my_content.html.twig
src/bundle/Resources/views/dashboard/tab/my_media.html.twig
src/lib/Form/Type/ChoiceList/Loader/ContentEditTranslationChoiceLoader.php
src/lib/Form/Type/Content/Translation/TranslationAddType.php
src/lib/Tab/Dashboard/PagerContentToDataMapper.php

| Tickets       | [IBX-1356](https://issues.ibexa.co/browse/IBX-1356)
Based on: https://github.com/ezsystems/ezplatform-admin-ui/pull/1885
Related `ezplatform-page-builder` PR:  https://github.com/ezsystems/ezplatform-page-builder/pull/890

IBX-1356: Backported fix for TranslationChoiceLoader

---

src/bundle/Resources/public/js/scripts/edit.header.js
src/bundle/Resources/public/scss/_field-group.scss
src/bundle/Resources/views/themes/admin/content/content_view_fields.html.twig
src/lib/Behat/Component/ContentItemAdminPreview.php
src/lib/Behat/Component/Fields/Matrix.php

| Tickets       | [](https://issues.ibexa.co/browse/IBX-1211)

IBX-1211: Updated content strucutre fieldtypes preview

---

src/bundle/Resources/public/js/scripts/admin.preview.js
src/bundle/Resources/public/scss/_general.scss
src/bundle/Resources/public/scss/_preview-header.scss
src/bundle/Resources/public/scss/_preview.scss
src/bundle/Resources/public/scss/ezplatform.scss
src/bundle/Resources/views/themes/admin/content/content_preview.html.twig
src/lib/Behat/Page/ContentPreviewPage.php

| Tickets       | [](https://issues.ibexa.co/browse/IBX-1375)

IBX-1375: Redesigned content preview

---

src/bundle/Resources/public/scss/_login.scss
src/bundle/Resources/translations/messages.en.xliff
src/bundle/Resources/views/themes/admin/account/forgot_password/confirmation_page.html.twig
src/bundle/Resources/views/themes/admin/account/forgot_password/index.html.twig

| Tickets       | https://issues.ibexa.co/browse/IBX-1301
| Requires    | https://github.com/ezsystems/ezplatform-user/pull/104

IBX-1301: Redesigned reset password
