ezsystems/ezplatform-admin-ui

src/bundle/EzPlatformAdminUiBundle.php, src/bundle/Resources/config/views.yml, src/bundle/Resources/views/content/tab/content.html.twig, src/bundle/Resources/views/content_fields.html.twig
> JIRA: https://jira.ez.no/browse/EZP-27992
This PR contains patch for the EZP-27992: "Content view for Author field - Display the name and the email address separately"
Notes for reviewers:
* Original JIRA ticket don't take into consideration that editor can specify multiple authors
* Removed redundant inheritance from EzPublishCoreBundle, because it causes infinite recursion if `content fields.html.twig` extends `@EzPublishCore/content_fields.html.twig`
=> EZP-27992: Display the name and the email address separately in Content view for Author field

src/bundle/Resources/views/content/locationview.html.twig
Added bottom spacing to the location view, so the **Show more results** button doesn't stick to the bottom.
=> Added bottom spacing to the location view

src/bundle/Resources/translations/role.en.xliff, src/bundle/Resources/views/admin/policy/list.html.twig, src/bundle/Resources/views/admin/role_assignment/list.html.twig
> https://jira.ez.no/browse/EZP-24699
> **Requires merge first**: ~https://github.com/ezsystems/repository-forms/pull/159~ and https://github.com/ezsystems/repository-forms/pull/164
This PR makes the values of policy limitations readable to humans. See https://github.com/ezsystems/repository-forms/pull/159 for more details.
=> EZP-24699: Enrich policy limitations view with human readable names

composer.json
So far we had to use workaround to require kernel 7.0 (`7.0.x-dev as 6.99.x-dev`).
Recent updates of version constraints via:
- ezsystems/ez-support-tools#24
- ezsystems/ezplatform-http-cache#16
allows to require simply `^7.0@dev`.
Note that `@dev` is needed for this package due to `minimum-stability`.
This is hopefully the last step before it can be fixed for `ezplatform:2.0` meta-repository.
**TODO**:
=> [Composer] Fixed ezpublish-kernel ^7.0 dependency

src/bundle/Resources/config/services/menu.yml, src/bundle/Resources/views/admin/trash/list.html.twig, src/bundle/Resources/views/content/locationview.html.twig, src/bundle/Resources/views/dashboard/dashboard.html.twig, src/bundle/Resources/views/parts/menu/sidebar_left.html.twig, src/lib/Menu/LeftSidebarBuilder.php
> JIRA: https://jira.ez.no/browse/EZP-28127
> **Requires: #26**
**!! Reopening this one after it was merged too early !!**
This PR reimplements left sidebar (which is visible in Location View and Trash) using `knplabs/knp-menu-bundle` package. I also created extensibility point based on events. 
Developers can take advantage of `ConfigureMenuEvent::CONTENT_SIDEBAR_LEFT` event to make customization to the sidebar i.e. reorder, add or remove items. Code snippets on how to customize sidebar are available at #26 as managing sidebar items uses the same approach.
All items are styled by default, more advanced buttons can use custom attributes as shown below: 
```php
$this->createMenuItem('sidebar_left__browse', [
'extras' => ['icon' => 'browse'],
'attributes' => [
'class' => 'btn--udw-browse', …
```
=> EZP-28127: Create extendable left sidebar

src/bundle/Resources/config/services/menu.yml, src/bundle/Resources/views/admin/trash/list.html.twig, src/bundle/Resources/views/content/locationview.html.twig, src/bundle/Resources/views/parts/menu/sidebar_base.html.twig, src/bundle/Resources/views/parts/menu/sidebar_right.html.twig, src/lib/Menu/ContentRightSidebarBuilder.php, src/lib/Menu/Event/ConfigureMenuEvent.php, src/lib/Menu/TrashRightSidebarBuilder.php
> JIRA: https://jira.ez.no/browse/EZP-28131
> Requires: #26 
This PR implements extendable menu system for contextual sidebars which are a part of Location View and Trash (blue sidebar on the right side). 
Similarly to #28 developers are allowed to do their own customizations using `EventSubscriber` on:
* `ConfigureMenuEvent::CONTENT_SIDEBAR_RIGHT` for right sidebar in Location View
* `ConfigureMenuEvent::TRASH_SIDEBAR_RIGHT` for right sidebar in Trash
For example code snippets for most common use cases please refer to #26.
=> [WIP] EZP-28131: Create extendable right sidebar

src/bundle/Resources/views/admin/content_type/create.html.twig, src/bundle/Resources/views/admin/content_type/edit.html.twig
> JIRA: https://jira.ez.no/browse/EZP-28159
This PR adds missing CSRF token field in the content type create/edit form. 
1. Go to *Admin* > *Content Types* > *Content*
2. Click *Edit* button right to *Article* 
3. Click *Add field definition*
4. Changed wasn't saved because of missing CSRF token
=> EZP-28159: Missing CSRF token field in the content type create/edit form

src/bundle/Resources/views/admin/content_type/create.html.twig, src/bundle/Resources/views/admin/content_type/edit.html.twig, src/bundle/Resources/views/admin/content_type/view.html.twig
> JIRA: -
Removed hardcoded `language_code` from `src/bundle/Resources/admin/content_type/{create,edit,view}.html.twig`. 
Disclaimer: we don't support translating content types in UI yet, so in fact we always use `mainLanguageCode`
=> Removed hardcoded language_code from content type create/edit/view templates

src/lib/Form/Data/Language/LanguageCreateData.php
> JIRA: https://jira.ez.no/browse/EZP-28173
This PR provide fix for the following error: `Return value of EzSystems\EzPlatformAdminUi\Form\Data\Language\LanguageCreateData::isEnabled() must be of the type boolean, null returned` on create language form.  Besides of this, by default language should be enabled. 
> 1. Go to Admin > Languages
> 2. Click Create a new Language
=> EZP-28173: Return value of EzSystems\...\LanguageCreateData::isEnabled() must be of the type boolean, null returned

src/bundle/Resources/views/content/tab/relations/tab.html.twig, src/bundle/Resources/views/content/tab/relations/table.html.twig, src/lib/UI/Dataset/RelationsDataset.php
>JIRA: https://jira.ez.no/browse/EZP-28184
This PR fixes incorrect calls to `ValueFactory::createRelation` as well as some issues in twig i.e. incorrect constants access (single slashes instead of double), wrong bundle name in include template calls.
=> EZP-28184: Location View / Relation Tab is broken

src/bundle/Resources/config/services/tabs/dashboard.yml
This PR adds required `parent` definition to services handling rendering Dashboard Tabs.
Unfortunately this means we cannot use `_defaults` in this file and make all services private manually.
This stopped working since Symfony `3.4.0-BETA3` tag, but seems that worked for us by accident as `parent` is needed AFAIK
=> [Tabs] Fixed Dashboard Tabs services definition

src/bundle/Resources/public/scss/ezplatform-bootstrap.scss, src/bundle/Resources/views/layout.html.twig
Corrected assets paths. Now the assets come with `ezplatform-admin-ui-assets` instead of being installed while running `bower install` command in the meta repo.
=> Corrected assets paths

src/bundle/Controller/SearchController.php, src/bundle/Resources/views/admin/search/search_form.html.twig
> https://jira.ez.no/browse/EZP-28055
This PR fixed a bug with out of range page number. Now setCurrentPage method receives page that user request or last available page.
=> EZP-28055: As a v2 Editor I want to search for content items by entering a search keyword

src/bundle/Resources/translations/content.en.xliff, src/bundle/Resources/translations/content_type.en.xliff, src/bundle/Resources/translations/dashboard.en.xliff, src/bundle/Resources/translations/ezrepoforms_role.en.xliff, src/bundle/Resources/translations/fieldview.en.xliff, src/bundle/Resources/translations/forms.en.xliff, src/bundle/Resources/translations/language.en.xliff, src/bundle/Resources/translations/location.en.xliff, src/bundle/Resources/translations/locationview.en.xliff, src/bundle/Resources/translations/menu.en.xliff, src/bundle/Resources/translations/messages.en.xliff, src/bundle/Resources/translations/role.en.xliff, src/bundle/Resources/translations/search.en.xliff, src/bundle/Resources/translations/section.en.xliff, src/bundle/Resources/translations/systeminfo.en.xliff, src/bundle/Resources/translations/translation.en.xliff, src/bundle/Resources/translations/trash.en.xliff, src/bundle/Resources/translations/version.en.xliff
> JIRA: https://jira.ez.no/browse/EZP-28150
I've regenerated translation by running in project root directory:  
```bash
bin/console translation:extract en --output-format=xliff --dir=vendor/ezsystems/ezplatform-admin-ui/src --output-dir=vendor/ezsystems/ezplatform-admin-ui/src/bundle/Resources/translations/
```
Also I've needed to manually set source and target to `{0}No|{1}Yes`, because `JMSTranslationBundle` wasn't able to do this automatically (not sure why).
=> EZP-28150: In preview of Content type, field Container shows "yes_no"

.php_cs, composer.json, src/lib/Form/Data/ContentTypeGroupData.php, src/lib/Form/Data/Language/LanguageCreateData.php, src/lib/Form/Data/Policy/PolicyCreateData.php, src/lib/Form/Data/PolicyData.php, src/lib/Form/Data/Role/RoleCreateData.php, src/lib/Form/Data/Role/RoleUpdateData.php, src/lib/Form/Data/RoleData.php, src/lib/Form/Data/Search/SearchData.php, src/lib/Form/Data/Section/SectionCreateData.php
This PR updates `.php_cs` config to be compatible with `v2.7.1`.
To simplify fixing code it also adds dev dependency on `php-cs-fixer` and introduces composer command:
```
composer fix-cs
```
which runs fixer on all files.
**TODO**:
=> EZP-28161: Update php-cs-fixer configuration to align with v2.7.1

src/bundle/Resources/views/fieldtypes/ezboolean.html.twig
> JIRA: https://jira.ez.no/browse/EZP-28225
Fixes an issue with `ezboolean` in which it wasn't reflecting default value (or initial value in edit mode) in the UI.
=> EZP-28225: ezboolean's UI is ignoring default value

src/bundle/Resources/public/js/scripts/fieldType/ezdatetime.js, src/bundle/Resources/views/content/content_edit.html.twig, src/bundle/Resources/views/fieldtypes/ezdatetime.html.twig
> JIRA: https://jira.ez.no/browse/EZP-27901
> Requires: https://github.com/ezsystems/repository-forms/pull/171
**THINGS DONE:**
=> EZP-27901: As an Editor, I want to edit a DateAndTime field type with the new UI guidelines

src/bundle/Resources/translations/content_type.en.xliff, src/lib/Form/Type/ContentType/SortFieldChoiceType.php, src/lib/Tab/LocationView/DetailsTab.php
JIRA: https://jira.ez.no/browse/EZP-28274
--
Fix error: 
```
`Key "1" for array with keys "2, 3, 8, 9" does not exist` z `vendor/ezsystems/ezplatform-admin-ui/src/bundle/Resources/views/content/tab/details.html.twig (line 111)`
```
Reason: some sorting options are missing on Location View.
=> EZP-28274: Fix missing sub-items sorting options

src/bundle/Controller/SearchController.php, src/bundle/Controller/SectionController.php
Using `Core` namespace results in the following exception:
```
Cannot autowire service "EzSystems\EzPlatformAdminUiBundle\Controller\SearchController": argument
"$searchService" of method "__construct()" references class
"eZ\Publish\Core\Repository\SearchService" but no such service exists. Try changing the type-hint to
"eZ\Publish\API\Repository\SearchService" instead.
```
=> EZP-28285: Fix typehints for core services

src/bundle/Resources/public/js/scripts/fieldType/eztime.js, src/bundle/Resources/views/content_fields.html.twig
> JIRA: https://jira.ez.no/browse/EZP-28287
This PR fixes how time is computed into seconds for `eztime` field type.
=> EZP-28287: Inconsistent eztime value across timezones

src/lib/SiteAccess/AdminFilter.php
It appears that this filter is ran for every file which has `ezpublish` configuration defined.
So, if there are any files with `ezpublish` configuration, but without siteaccess groups config, this causes an exception.
=> EZP-28284: Do not run admin siteaccess filter in there are no groups defined

src/bundle/Resources/public/js/scripts/fieldType/ezdatetime.js
> JIRA: https://jira.ez.no/browse/EZP-28296
This PR fixes timezone issue for ezdatetime. The issue was caused by invalid assumption that selected date should is in UTC timezone which is incorrect - date is in user's local timezone.
=> EZP-28296: Inconsistent ezdatetime value across timezones

src/bundle/Resources/views/content_fields.html.twig
> JIRA: https://jira.ez.no/browse/EZP-28309
This PR reverses #87 as we decided to fix the issue in kernel instead: https://github.com/ezsystems/ezpublish-kernel/pull/2162
=> EZP-28309: Twig template for eztime is incorrectly parsing time value

src/bundle/Resources/views/content/locationview.html.twig, src/lib/Menu/ContentRightSidebarBuilder.php
> JIRA: https://jira.ez.no/browse/EZP-28317
This PR disabled Create button if content type `container` setting is set to `no/false`. Also I passed more data to the contextual sidebar builder to avoid accessing these objects from services.
=> EZP-28317: Can create content despite ContentType's Container setting

src/bundle/Resources/translations/content_edit.en.xliff, src/bundle/Resources/views/content/content_edit/content_edit.html.twig
> JIRA: https://jira.ez.no/browse/EZP-28315
This PR fixes heading in content edit in case of nonpublished content. Previously it displayed empty location ID.
=> EZP-28315: Cannot delete draft in case of nonpublished content

src/bundle/Resources/views/content/content_edit/content_edit_base.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28333
=> EZP-28333: User can't add a content item based on specific content type

src/bundle/Resources/views/admin/section/list.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28283
=> EZP-28283: Double Assign content labels in Sections

src/bundle/Resources/views/layout.html.twig
Use twig csrf_token to get the correct token.
| Tickets       | https://jira.ez.no/browse/EZP-28304
This uses the correct token regardless of http or https.
=> EZP-28304: Fix meta CSRF token to be https namespace aware

src/lib/UI/Service/PathService.php
Make `PathService::loadPathLocations` guarantee order.
| Tickets       | https://jira.ez.no/browse/EZP-28419
PathService::loadPathLocations is used to get the paths but the returned locations are not guaranteed to be in any order. This corrects that.
=> EZP-28419: Fix breadcrumb order after reindex

src/bundle/Resources/views/content/form_fields.html.twig, src/bundle/Resources/views/fieldtypes/binary_base.html.twig, src/bundle/Resources/views/fieldtypes/binary_base_fields.html.twig, src/bundle/Resources/views/fieldtypes/ezbinaryfile.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28311
This PR simplifies fieldtypes twig templates and removes duplicated code from binary based fieldtypes.
=> EZP-28311: There is no description, when translation is disabled for a field

src/bundle/Resources/public/js/scripts/fieldType/base/base-field.js, src/bundle/Resources/public/js/scripts/fieldType/ezbinaryfile.js, src/bundle/Resources/public/js/scripts/fieldType/ezimage.js, src/bundle/Resources/public/js/scripts/fieldType/ezmedia.js
| Tickets       | https://jira.ez.no/browse/EZP-28448
The fields: `ezmedia`, `ezbinaryfile` and `ezimage` should be retested with this fix.
=> EZP-28448: Cannot change the value of player settings in a content containing multiple ezmedia field types

src/bundle/Resources/translations/content_type.en.xliff, src/bundle/Resources/views/admin/content_type/list.html.twig, src/bundle/Resources/views/admin/content_type/view.html.twig, src/bundle/Resources/views/admin/content_type_group/list.html.twig, src/bundle/Resources/views/admin/content_type_group/view.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-27995
Following the UI Guidelines, following elements have been updated:
- Breadcrumbs
- Page Title
- Table header
- Content Type Icons
In order to completely work, some of the Content Types icons have to be renamed: 
blog-post.svg -> blog_post.svg.
=> EZP-27995: Naming conventions for Content Types

src/bundle/Resources/public/scss/_user-menu.scss
| Tickets       | https://jira.ez.no/browse/EZP-28483
=> EZP-28483: Modal is not visible in user menu on safari

src/bundle/Resources/public/scss/_buttons.scss, src/bundle/Resources/public/scss/_icons.scss, src/bundle/Resources/public/scss/_tables.scss, src/bundle/Resources/views/admin/content_type/list.html.twig, src/bundle/Resources/views/admin/content_type/view.html.twig, src/bundle/Resources/views/admin/content_type_group/list.html.twig, src/bundle/Resources/views/admin/language/list.html.twig, src/bundle/Resources/views/admin/policy/list.html.twig, src/bundle/Resources/views/admin/role/list.html.twig, src/bundle/Resources/views/admin/role_assignment/list.html.twig, src/bundle/Resources/views/admin/search/list.html.twig, src/bundle/Resources/views/admin/search/search.html.twig, src/bundle/Resources/views/admin/section/assigned_content.html.twig, src/bundle/Resources/views/admin/section/list.html.twig, src/bundle/Resources/views/admin/section/view.html.twig, src/bundle/Resources/views/admin/systeminfo/composer.html.twig, src/bundle/Resources/views/admin/systeminfo/symfony_kernel.html.twig, src/bundle/Resources/views/admin/trash/list.html.twig, src/bundle/Resources/views/parts/table_header.html.twig
| Tickets       | [EZP-28360](https://jira.ez.no/browse/EZP-28360)
- Standardized style of `.ez-table-header` throughout the application (based also on HTML standards), as well as provided style for interactive icon buttons allocated within it;
- Updated style of Dashboard tables based on design specifications;
- Update design view for Admin > Content types > Specific Content type view based on specifications.
Next steps:
- All buttons inside `.ez-table-header` should be styled as icon buttons;
- In tables, delete …
=> EZP-28360: Design consistency for tables across the whole application

src/bundle/Resources/public/scss/_tables.scss, src/bundle/Resources/views/admin/section/assigned_content.html.twig, src/bundle/Resources/views/admin/trash/list.html.twig, src/bundle/Resources/views/content/tab/relations/tab.html.twig, src/bundle/Resources/views/content/tab/urls.html.twig, src/bundle/Resources/views/dashboard/tab/all_content.html.twig, src/bundle/Resources/views/dashboard/tab/all_media.html.twig, src/bundle/Resources/views/dashboard/tab/my_content.html.twig, src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig, src/bundle/Resources/views/dashboard/tab/my_media.html.twig
| Tickets       | [EZP-28360](https://jira.ez.no/browse/EZP-28360)
- Standardized style of message shown when there's no content to be displayed.
=> EZP-28360: Tables consistency, standardized message when no content displayed

src/bundle/Resources/public/js/scripts/fieldType/ezimage.js, src/bundle/Resources/public/scss/fieldType/_base-field.scss, src/bundle/Resources/public/scss/fieldType/_ezgmaplocation.scss, src/bundle/Resources/public/scss/fieldType/_ezimage.scss
| Tickets       | https://jira.ez.no/browse/EZP-28389
Additionaly, I've added a visual error state to the alternative text input when it's empty and required.
=> EZP-28322: No space between validation message and field label

src/bundle/Resources/translations/forms.en.xliff, src/bundle/Resources/translations/section.en.xliff, src/bundle/Resources/views/admin/section/view.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28515
Section header don't contain section name
=> EZP-28515: Section header don't contain section name

src/bundle/Resources/views/content/tab/locations/tab.html.twig, src/bundle/Resources/views/content/tab/translations/tab.html.twig, src/bundle/Resources/views/content/tab/versions/tab.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28520
Design improvements for icons in content tabs (locations, versions, translations)
=> EZP-28520: Design improvements for icons in Content tabs

src/bundle/Resources/public/js/scripts/fieldType/ezauthor.js, src/bundle/Resources/public/js/scripts/fieldType/ezstring.js, src/bundle/Resources/public/js/scripts/fieldType/ezurl.js, src/bundle/Resources/public/js/scripts/fieldType/ezuser.js, src/bundle/Resources/public/scss/fieldType/_base-field.scss
| Tickets       | https://jira.ez.no/browse/EZP-28427
=> EZP-28427: Red label is missing when validation appears

src/bundle/Controller/ContentTypeGroupController.php, src/bundle/Resources/config/routing.yml, src/bundle/Resources/translations/forms.en.xliff, src/bundle/Resources/views/admin/content_type_group/list.html.twig, src/lib/Form/Data/ContentTypeGroup/ContentTypeGroupsDeleteData.php, src/lib/Form/Factory/FormFactory.php, src/lib/Form/Type/ContentTypeGroup/ContentTypeGroupsDeleteType.php
| Tickets       | https://jira.ez.no/browse/EZP-28521
Design improvements for Content Type Groups list
=> EZP-28521: Design improvements for Content Type Groups list

src/bundle/Controller/ContentTypeGroupController.php, src/bundle/Resources/config/services/menu.yml, src/bundle/Resources/translations/content_type.en.xliff, src/bundle/Resources/translations/menu.en.xliff, src/bundle/Resources/views/admin/content_type_group/base.html.twig, src/bundle/Resources/views/admin/content_type_group/create.html.twig, src/bundle/Resources/views/admin/content_type_group/edit.html.twig, src/lib/Form/Type/ContentTypeGroup/ContentTypeGroupCreateType.php, src/lib/Form/Type/ContentTypeGroup/ContentTypeGroupUpdateType.php, src/lib/Menu/Admin/ContentType/ContentTypeGroupCreateRightSidebarBuilder.php, src/lib/Menu/Admin/ContentType/ContentTypeGroupEditRightSidebarBuilder.php, src/lib/Menu/Event/ConfigureMenuEvent.php
| Tickets       | https://jira.ez.no/browse/EZP-28523
Design improvements for Content Type Groups create and edit
=> EZP-28523: Design improvements for Content Type Groups create and edit

src/bundle/Controller/ContentTypeGroupController.php, src/bundle/Resources/views/admin/content_type_group/list.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28529
Delete action can be run on non-empty group
=> EZP-28529: Fixed deletion of Content Type Group on non-empty group

src/bundle/Controller/RoleAssignmentController.php, src/bundle/Resources/public/js/scripts/admin.role_assignment.add.js, src/bundle/Resources/public/scss/_buttons.scss, src/bundle/Resources/public/scss/_icons.scss, src/bundle/Resources/translations/menu.en.xliff, src/bundle/Resources/translations/role.en.xliff, src/bundle/Resources/translations/validators.en.xliff, src/bundle/Resources/views/admin/role_assignment/create.html.twig, src/lib/Form/Data/Role/RoleAssignmentCreateData.php, src/lib/Form/DataTransformer/LocationsTransformer.php, src/lib/Form/Type/Content/Draft/ContentCreateType.php, src/lib/Form/Type/Role/RoleAssignmentCreateType.php, src/lib/Form/Type/UniversalDiscoveryWidget/UniversalDiscoveryWidgetType.php, src/lib/Menu/Admin/Role/RoleAssignmentCreateRightSidebarBuilder.php
| Tickets       | https://jira.ez.no/browse/EZP-28493
=>  EZP-28493: Interface improvements when assigning roles to user / groups

src/bundle/Controller/ContentController.php, src/bundle/Controller/ContentViewController.php, src/bundle/Resources/config/routing.yml, src/bundle/Resources/views/content/locationview.html.twig, src/bundle/Resources/views/content/widgets/content_edit.html.twig, src/lib/Form/Data/Content/Draft/ContentEditData.php, src/lib/Form/Factory/FormFactory.php, src/lib/Form/Type/Content/Draft/ContentEditType.php
| Tickets       | https://jira.ez.no/browse/EZP-28556
=> EZP-28556: Replace ContentDraftCreate with ContentEdit action handling optional draft creation

src/bundle/Controller/ContentController.php, src/bundle/Controller/ContentViewController.php, src/bundle/Resources/public/js/scripts/admin.location.view.js, src/bundle/Resources/views/content/locationview.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28547
**Description**
Fixed bug with handle submits form with a different name than the default. When the name of the form is set to some custom the submit creates a form with the wrong name. In my case I set name to `form_sub_items_content_edit` and the submit creates form with name `content_draft_create`
**Requires:** https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/28
=> EZP-28547: SubItems should not redirect to form on edit item

src/bundle/DependencyInjection/Configuration/Parser/LocationIds.php, src/bundle/Resources/config/services/menu.yml, src/lib/Menu/AbstractBuilder.php, src/lib/Menu/ContentRightSidebarBuilder.php, src/lib/Menu/MainMenuBuilder.php, src/lib/Menu/MenuItemFactory.php, src/lib/Menu/TrashRightSidebarBuilder.php, src/lib/Menu/UserMenuBuilder.php
| Tickets       | https://jira.ez.no/browse/EZP-28553
| Tests pass?   | maybe
This PR take care about user policies and display or not Content / Media link on Top Menu
=> EZP-28553: Adds Permission Awareness to all menus

src/bundle/Resources/translations/language.en.xliff, src/bundle/Resources/views/admin/language/view.html.twig
| Tickets       | https://jira.ez.no/browse/EZEE-1822
Fixed wrong header in language view
=> EZEE-1822: Fixed wrong header in language view

src/bundle/Resources/public/scss/_general.scss, src/bundle/Resources/views/admin/base.html.twig, src/bundle/Resources/views/admin/content_type_group/base.html.twig, src/bundle/Resources/views/admin/language/base.html.twig, src/bundle/Resources/views/admin/policy/base.html.twig, src/bundle/Resources/views/admin/role/base.html.twig, src/bundle/Resources/views/admin/role_assignment/base.html.twig, src/bundle/Resources/views/admin/section/base.html.twig, src/bundle/Resources/views/admin/trash/list.html.twig, src/bundle/Resources/views/content/content_edit/content_edit_base.html.twig, src/bundle/Resources/views/content/locationview.html.twig, src/bundle/Resources/views/layout.html.twig, src/bundle/Resources/views/parts/menu/sidebar_base.html.twig
https://jira.ez.no/browse/EZP-28273
In the administration interface the views can be very long. This causes the user to scroll down and then the sidebar buttons are lost. This is especially prominent when editing content with multiple field.
This PR adds a wrapper element and some styles to set the buttons in the sidebar to be sticky when scrolling. See video for a preview - sticky functionality in video has white border.
https://www.youtube.com/watch?v=GZoD7GJ99Y4
=> EZP-28273: Make v2 admin sidebar buttons sticky

src/bundle/Resources/public/scss/_alloyeditor-buttons.scss, src/bundle/Resources/public/scss/_alloyeditor-link-edit.scss
| Tickets       | https://jira.ez.no/browse/EZP-28570
=> EZP-28570: Incorrect background for buttons in link toolbar in AlloyEditor

src/bundle/Resources/public/scss/_field-group.scss
| Tickets       | [EZP-28458](https://jira.ez.no/browse/EZP-28458)
- Styled positioning of Translations switcher in Content view.
=> EZP-28458: Styled position of translations switcher in Content view

src/bundle/Resources/views/admin/trash/list.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28572
Misleading message on Empty trash action about number of deleted items
=> EZP-28572: Misleading message on Empty trash action

src/bundle/Resources/views/bulk_delete_confirmation_modal.html.twig, src/bundle/Resources/views/content/tab/locations/tab.html.twig, src/bundle/Resources/views/content/tab/translations/tab.html.twig, src/bundle/Resources/views/content/tab/versions/tab.html.twig, src/bundle/Resources/views/content/tab/versions/table.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28335
Added modal with deleting confirmation in Content tabs and fixed delete button active state in versions, locations and translations.
=> EZP-28335: Added modal with deleting confirmation in Content tabs and fixed delete button active state

src/bundle/Resources/public/js/scripts/admin.location.version.restore_archived.js, src/bundle/Resources/views/content/locationview.html.twig, src/bundle/Resources/views/content/tab/versions/tab.html.twig, src/bundle/Resources/views/content/tab/versions/table.html.twig, src/lib/Tab/LocationView/VersionsTab.php
| Tickets       | https://jira.ez.no/browse/EZP-28567
=> EZP-28567: As an editor I want to be able to restore archived Content version

src/bundle/Resources/config/services/components.yml, src/bundle/Resources/views/dashboard/block/all.html.twig, src/bundle/Resources/views/dashboard/block/me.html.twig, src/bundle/Resources/views/dashboard/dashboard.html.twig, src/bundle/Templating/Twig/ComponentExtension.php, src/lib/Component/Event/RenderGroupEvent.php, src/lib/Component/Event/RenderSingleEvent.php, src/lib/Component/Registry.php, src/lib/Component/Renderer/DefaultRenderer.php, src/lib/Component/Renderer/RendererInterface.php
Ping @DominikaK : 
Example EventSubscriber to demonstrate how to intercept and alter rendering of elements:
```php
<?php
declare(strict_types=1);
namespace EzSystems\EzPlatformAdminUi\EventListener;
use EzSystems\EzPlatformAdminUi\Component\Event\RenderGroupEvent;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
class DashboardEventSubscriber implements EventSubscriberInterface
{
public static function getSubscribedEvents()
{
return [
RenderGroupEvent::NAME => ['onRenderGroupEvent', 20],
];
}
public …
```
=> fix: Make Dashboard extensible

src/bundle/Resources/public/scss/_forms.scss, src/bundle/Resources/translations/content_type.en.xliff, src/bundle/Resources/translations/locationview.en.xliff, src/bundle/Resources/views/content/tab/details.html.twig, src/lib/Form/Type/Location/LocationUpdateType.php
| Tickets       | https://jira.ez.no/browse/EZP-28576
Design improvements for Sub-items sorting order panel
=> EZP-28576: Design improvements for Sub-items sorting order panel

src/bundle/Resources/public/js/scripts/fieldType/ezselection.js
| Tickets       | https://jira.ez.no/browse/EZP-28445
=> EZP-28445: Ezselection fills itself when required after publish

src/bundle/Resources/config/ezplatform_default_settings.yml
EZP-28553: Adds Permission Awareness to all menus
| Tickets       | Related to EZP-28553
=> Missed reference to location_ids.content (EZP-28553)

src/bundle/Controller/LocationController.php, src/lib/Tab/LocationView/DetailsTab.php
| Tickets       | https://jira.ez.no/browse/EZP-28586
Setting ordering of sub-items moves user to the location tab
=> EZP-28586: Setting ordering of sub-items moves user to the location tab

src/bundle/Controller/ContentTypeGroupController.php, src/bundle/Resources/translations/content_type.en.xliff, src/bundle/Resources/views/admin/content_type_group/list.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28589
Added information about number of Content Types on CTG list
=> EZP-28589: Added information about number of Content Types on CTG list

src/bundle/Resources/public/scss/_general.scss
| Tickets       | https://jira.ez.no/browse/EZP-28593
=> EZP-28593: Sticky container doesn't work in safari

src/bundle/Resources/public/js/scripts/fieldType/ezdate.js, src/bundle/Resources/public/js/scripts/fieldType/ezdatetime.js, src/bundle/Resources/public/js/scripts/fieldType/ezkeyword.js, src/bundle/Resources/public/js/scripts/fieldType/ezselection.js, src/bundle/Resources/public/js/scripts/fieldType/eztime.js, src/bundle/Resources/public/scss/_mixins.scss, src/bundle/Resources/public/scss/fieldType/_ezkeyword.scss, src/bundle/Resources/public/scss/fieldType/_ezselection.scss
| Tickets       | https://jira.ez.no/browse/EZP-28428
The rich text field type validation will be implemented in another PR.
=> EZP-28427: There is no red glow for a field when focused

src/bundle/Resources/translations/forms.en.xliff, src/bundle/Resources/views/admin/trash/list.html.twig, src/bundle/Resources/views/form_fields.html.twig, src/lib/Form/Type/Trash/TrashItemRestoreType.php
| Tickets       | https://jira.ez.no/browse/EZP-28600
Design improvements for Trash restore buttons
=> EZP-28600: Design improvements for Trash restore buttons

src/bundle/Resources/public/scss/_main-nav.scss, src/bundle/Resources/views/parts/navigation.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28604
=> EZP-28604: Menu is not collapsed when switching tab

src/bundle/Resources/public/scss/_buttons.scss, src/bundle/Resources/public/scss/_custom.scss, src/bundle/Resources/public/scss/_modals.scss, src/bundle/Resources/public/scss/ezplatform.scss, src/bundle/Resources/views/admin/bulk_delete_confirmation_modal.html.twig, src/bundle/Resources/views/admin/content_type/delete_confirmation_modal.html.twig, src/bundle/Resources/views/admin/language/delete_confirmation_modal.html.twig, src/bundle/Resources/views/admin/section/delete_confirmation_modal.html.twig, src/bundle/Resources/views/admin/trash/empty_trash_confirmation_modal.html.twig, src/bundle/Resources/views/bulk_delete_confirmation_modal.html.twig, src/bundle/Resources/views/content/modal_location_trash.html.twig
| Tickets       | [EZP-28463](https://jira.ez.no/browse/EZP-28463)
- Updated design of modals Send to TRash
=> EZP-28463: Updated design for Modal Send to trash

src/bundle/Resources/config/services.yml, src/lib/Notification/FlashBagNotificationHandler.php
| Tickets       | https://jira.ez.no/browse/EZP-28612
This refactors a bit `FlashBagNotificationHandler` in order not to start the session for anonymous user, by calling the `getFlashBag` only when neeeded, since it is responsible for starting the session.
=> Fix EZP-28612: Session is always started for anonymous user

src/bundle/Resources/public/js/scripts/fieldType/ezurl.js, src/bundle/Resources/views/layout.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28607
| Bug fix?      | yes/
=> EZP-28607: URL field type validation is not always working correctly

src/bundle/Controller/LinkManagerController.php, src/bundle/Resources/translations/linkmanager.en.xliff, src/bundle/Resources/views/link_manager/view.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28581
This PR contains bugfix mentioned in JIRA ticket and missing translation for Content Object status in Link Manager.
=> EZP-28581: Cannot edit Content Object from Link Manager

src/bundle/Resources/config/services.yml, src/bundle/Resources/config/services/form_types.yml, src/bundle/Resources/config/services/type_extensions.yml, src/lib/Form/Type/Content/Draft/ContentCreateType.php, src/lib/Form/Type/Language/LimitedLanguageChoiceType.php
| Tickets       | https://jira.ez.no/browse/EZP-28598
=> EZP-28598: Fixes no filtering langauge on create content UI

src/bundle/DependencyInjection/Configuration/Parser/LocationIds.php, src/bundle/Resources/config/ezplatform_default_settings.yml, src/lib/Menu/MainMenuBuilder.php
| Tickets       | https://jira.ez.no/browse/EZP-28624
=> EZP-28624: Content structure link in top menu should not rely on root_tree.location_id setting

src/bundle/Controller/ContentTypeController.php, src/bundle/Controller/ContentTypeGroupController.php, src/bundle/DependencyInjection/Configuration/Parser/Pagination.php, src/bundle/Resources/config/ezplatform_default_settings.yml, src/bundle/Resources/config/routing.yml, src/bundle/Resources/config/services/controllers.yml, src/bundle/Resources/translations/pagination.en.xliff, src/bundle/Resources/views/admin/content_type/list.html.twig, src/bundle/Resources/views/admin/content_type_group/list.html.twig, src/bundle/Resources/views/admin/content_type_group/view.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28616
Added pagination to the Content Type Groups and Content Type
=> EZP-28616: Add pagination to the Content Type Groups and Content Type

src/bundle/Resources/config/services.yml, src/lib/Menu/Voter/LocationVoter.php
Top menu disappear on CI, Media Item and Users detail views. May need tests in another places.
=> EZP-28626: Top menu disappear on CI, Media Item and Users detail views

src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js
| Tickets       | https://jira.ez.no/browse/EZP-28560
=> EZP-28560: Wrong validator on longitude

src/lib/Menu/MainMenuBuilder.php
| Tickets       | https://jira.ez.no/browse/EZP-28634
Top menu disappeared on Search and Trash. Current solution is to show top menu always with selected position "Content" -> "Content structure selected"
=> EZP-28634: Top menu disappear on Search and Trash

src/bundle/Resources/views/content/content_edit/content_edit_base.html.twig, src/bundle/Resources/views/layout.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28574
**Requires:**
- https://github.com/ezsystems/ezplatform-admin-ui-assets/pull/6
=> EZP-28574: Updated dependencies paths after dropping support for Bower

src/lib/Menu/Voter/LocationVoter.php
Voters should return `null` if they can't decide if menu item is active or not, rather than `false`, because returning `false` prevents other voters from functioning properly.
This messes up the voter implemented in Tags Bundle for example.
| Tickets       | https://jira.ez.no/browse/EZP-28626
=> Fix menu item voter conflicting with other voters

src/bundle/Controller/PolicyController.php, src/bundle/Controller/RoleAssignmentController.php, src/bundle/Controller/RoleController.php, src/bundle/DependencyInjection/Configuration/Parser/Pagination.php, src/bundle/Resources/config/ezplatform_default_settings.yml, src/bundle/Resources/config/routing.yml, src/bundle/Resources/config/services/controllers.yml, src/bundle/Resources/views/admin/policy/list.html.twig, src/bundle/Resources/views/admin/role/view.html.twig, src/bundle/Resources/views/admin/role_assignment/list.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28619
Add pagination to Role Assignments and Policies
=> EZP-28619: Add pagination to Role Assignments and Policies

src/bundle/Controller/SectionController.php, src/bundle/Resources/config/validation/section.yml
| Tickets       | https://jira.ez.no/browse/EZP-28514
It's possible to save section with identifier containing spaces
=> EZP-28514: It's possible to save section with identifier containing spaces

src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js
| Tickets       | https://jira.ez.no/browse/EZP-28646
=> EZP-28646: Validation alert for map location which is not required

src/bundle/Resources/translations/content_type.en.xliff, src/bundle/Resources/translations/locationview.en.xliff, src/bundle/Resources/translations/trash.en.xliff
| Tickets       | https://jira.ez.no/browse/EZP-28408
Add missing translations for sub items order
=> EZP-28548: Add missing translations for sub items order

src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js
| Tickets       | https://jira.ez.no/browse/EZP-28650
=> EZP-28650: [ezgmaplocation] Coordinate inputs don't remove the error statuses when searching by address

src/bundle/Resources/config/views.yml, src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28655
=> EZP-28655: RelationList fieldtype view in AdminUI has invalid render call

src/bundle/Resources/views/parts/menu/top_menu.html.twig, src/lib/Menu/MainMenuBuilder.php
| Tickets       | https://jira.ez.no/browse/EZP-28660
=> EZP-28660: Top menu is not adding sections when there is no children which breaks extensibility

src/bundle/Resources/views/content/tab/versions/tab.html.twig, src/bundle/Resources/views/content/tab/versions/table.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28661
Add pagination to the Draft under edit
=> EZP-28661: Add pagination to the Draft under edit

src/bundle/Resources/views/content/tab/relations/tab.html.twig, src/bundle/Resources/views/content/tab/relations/table_relations.html.twig, src/bundle/Resources/views/content/tab/relations/table_relations_reverse.html.twig, src/lib/Tab/LocationView/RelationsTab.php
| Tickets       | https://jira.ez.no/browse/EZP-28658
=> EZP-28658: Reverse relations link to the object itself, instead of relating objects

src/bundle/Resources/public/js/scripts/fieldType/ezuser.js, src/bundle/Resources/public/scss/_mixins.scss, src/bundle/Resources/public/scss/fieldType/edit/_ezuser.scss, src/bundle/Resources/translations/fieldtypes_preview.en.xliff, src/bundle/Resources/views/content/form_fields.html.twig, src/bundle/Resources/views/fieldtypes/edit/ezuser.html.twig, src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig
**Requires: https://github.com/ezsystems/repository-forms/pull/208**
| Tickets       | https://jira.ez.no/browse/EZP-28664
=> EZP-28664: Enabled checkbox should be a part of ezuser fieldtype in Content Edit

src/bundle/Resources/views/parts/menu/top_menu.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28669
=> EZP-28669: Top menu hides all items with no children despite being a valid link item

src/bundle/Controller/TranslationController.php, src/lib/Form/Data/Content/Translation/TranslationDeleteData.php, src/lib/Form/Factory/FormFactory.php, src/lib/Form/Type/Content/Translation/TranslationDeleteType.php, src/lib/Tab/LocationView/TranslationsTab.php
| Tests pass?   | hopefully
This PR:
1. Replaces usage of deprecated `ContentService::removeTranslation` with `ContentService::deleteTranslation` as the former one will be dropped in `7.x` (4d61694)
2. Aligns naming conventions to avoid further confusion.
3. Changes typo in variable related to adding Translation. (f43e938)
=> [Content Translations] Replaced removeTranslation with deleteTranslation

src/bundle/Resources/public/scss/fieldType/edit/_ezselection.scss
List of option hides behind next field after expand
=> EZP-28621: List of option hides behind next field after expand

src/bundle/Resources/config/services.yml, src/bundle/Resources/config/services/controllers.yml
| Tickets       | https://jira.ez.no/browse/EZP-28674
=> EZP-28674: performAccessCheck not called after EZP-28661 for ContentViewController

src/bundle/Resources/config/services.yml, src/lib/Form/Type/Language/LanguageChoiceType.php
| Tests pass?   | n/a
| Doc needed?   | unsure
E.g. If I configure admin to be [nor-NO, eng-GB], then I expect norwegian to be the default
choice so I don't need to click to change it when I create new content.
Review note:
- I'm unsure if this is right layer to do this, but until we move forward on SiteAccess aware
Repo PR, this is currently only place we can do it.
- As class is autowired with no service config, I opted for type hinting for full config resolver
- EDIT: And besides, we need to filter out disabled languages here anyway
=> As an Editor I want language choices to be ordered by SiteAccess settings

src/bundle/Resources/translations/locationview.en.xliff, src/bundle/Resources/views/content/tab/versions/table.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28730
Fix tooltip messages for buttons in Content Version tab.
=> EZP-28730: Wrong tooltip messages for buttons

src/bundle/Resources/views/admin/section/assigned_content.html.twig, src/bundle/Resources/views/parts/path.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28743
Fix for different behaviour of breadcrumbs when ezplatform is hidden. Same issue was in Admin->Sections->Specific Section->Content items panel.
=> EZP-28743: Different behaviour of breadcrumbs when ezplatform is hidden

src/bundle/Resources/translations/dashboard.en.xliff, src/bundle/Resources/views/dashboard/tab/all_content.html.twig, src/bundle/Resources/views/dashboard/tab/all_media.html.twig, src/lib/Tab/Dashboard/PagerContentToDataMapper.php
| Tickets       | https://jira.ez.no/browse/EZP-28686
Fixed error 500 while user is going to dashboard after deleting another user. After user deletion we will display text "Can not fetch contributor" in a "Contributor" cell.
=> EZP-28686: Error 500 while user is going to dashboard after deleting another user

src/bundle/Controller/ContentViewController.php, src/bundle/Controller/User/UserDeleteController.php, src/bundle/Resources/config/routing.yml, src/bundle/Resources/config/services/controllers.yml, src/bundle/Resources/translations/content.en.xliff, src/bundle/Resources/translations/forms.en.xliff, src/bundle/Resources/translations/menu.en.xliff, src/bundle/Resources/translations/user_delete.en.xliff, src/bundle/Resources/views/content/locationview.html.twig, src/bundle/Resources/views/content/modal_user_delete.html.twig, src/lib/Form/Data/User/UserDeleteData.php, src/lib/Form/Factory/FormFactory.php, src/lib/Form/Type/User/UserDeleteType.php, src/lib/Menu/ContentRightSidebarBuilder.php, src/lib/Specification/ContentIsUser.php, src/lib/Specification/ContentSpecification.php
| Tickets       | https://jira.ez.no/browse/EZP-28737
| Tests pass?   |no
This PR fixed problem with partially deleted user. Now, if Content is a User, it can be only deleted via userService.
=> EZP-28737: User account partially deleted

composer.json, src/bundle/DependencyInjection/Compiler/ComponentPass.php, src/bundle/DependencyInjection/Compiler/SystemInfoTabGroupPass.php, src/bundle/DependencyInjection/Compiler/TabPass.php, src/bundle/DependencyInjection/Compiler/UiConfigProviderPass.php, src/bundle/Tests/DependencyInjection/Compiler/ComponentPassTest.php, src/bundle/Tests/DependencyInjection/Compiler/SystemInfoTabGroupPassTest.php, src/bundle/Tests/DependencyInjection/Compiler/TabPassTest.php, src/bundle/Tests/DependencyInjection/Compiler/UiConfigProviderPassTest.php
| Tickets       | https://jira.ez.no/browse/EZP-28722
Add unit tests to Compiler Passes
=> EZP-28722: Add unit tests to Compiler Passes

src/bundle/Resources/public/scss/_notifications.scss
| Tickets       | https://jira.ez.no/browse/EZP-28766
Notification gets covered by radio-button in content editor.
=> EZP-28766: Notification gets covered by radio-button in content editor

src/lib/Tests/Pagination/Pagerfanta/TrashItemAdapterTest.php, src/lib/Tests/Tab/TabGroupTest.php, src/lib/Tests/Tab/TabRegistryTest.php
| Tickets       | https://jira.ez.no/browse/EZP-28709
Add unit tests to TrashItemAdapter, TabRegistry and TabGroup
=> EZP-28709: Add unit tests to TrashItemAdapter, TabRegistry and TabGroup

src/bundle/Resources/views/content/tab/relations/table_relations.html.twig, src/bundle/Resources/views/content/tab/relations/table_relations_reverse.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28678
Removed unnecessary inactive edit button in Relations tab.
=> EZP-28678: Unnecessary inactive edit button in Relations tab

src/bundle/Controller/TranslationController.php, src/bundle/Controller/TrashController.php, src/bundle/Resources/translations/translation.en.xliff, src/bundle/Resources/translations/trash.en.xliff
| Tickets       | https://jira.ez.no/browse/EZP-28683
Replace apostrophes ( ` ) with single quote ( ' ). Probably this could be (and maybe should be for future cases) solved on css level but  this way it is unified across bundle.
=> [EZP-28683] Replace apostrophes (`) with single quote(')

src/lib/Tests/RepositoryForms/Data/ContentTranslationDataTest.php, src/lib/Tests/RepositoryForms/Data/Mapper/ContentTranslationMapperTest.php, src/lib/Tests/RepositoryForms/Form/Processor/PreviewFormProcessorTest.php, src/lib/Tests/RepositoryForms/View/ViewParametersListenerTest.php
| Tickets       | https://jira.ez.no/browse/EZP-28742
Add unit tests to RepositoryForms
=> EZP-28742: Add unit tests to RepositoryForms

src/bundle/Resources/public/scss/_forms.scss, src/bundle/Resources/public/scss/_mixins.scss, src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
| Tickets       | https://jira.ez.no/browse/EZP-28676
At first wanted to edit in _base-fields.scss but then it turns out that asterisk is added also in _forms.scss. 
Dont know if it should be somehow excluded from .ez-data-source__label instead.
=> [EZP-28683] Removes asterisk sign from labels when content editing

src/bundle/Controller/ContentController.php, src/bundle/Resources/views/content/content_preview.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28768
Unable to exit Preview using navigation arrow. In addition, this PR is also fixed a problem with 'out of date' content presented as a preview. The last published version was indicated to a user.
=> EZP-28768: Unable to exit Preview using navigation arrow

src/bundle/Resources/views/content/locationview.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28782
Removed classes which moves whole breadcrumbs + title container.
=> [EZP-28782] Remove extra div classes

src/bundle/Controller/Content/VersionDraftConflictController.php, src/bundle/Resources/config/routing.yml, src/bundle/Resources/public/js/scripts/sidebar/btn/location.edit.js, src/bundle/Resources/public/scss/_buttons.scss, src/bundle/Resources/public/scss/_general.scss, src/bundle/Resources/translations/draft_conflict.en.xliff, src/bundle/Resources/views/content/locationview.html.twig, src/bundle/Resources/views/content/modal_draft_conflict.html.twig, src/bundle/Resources/views/content/tab/versions/table.html.twig, src/lib/Specification/Content/ContentDraftHasConflict.php, src/lib/UI/Dataset/VersionsDataset.php
| Tickets       | https://jira.ez.no/browse/EZP-27786
As a Editor, I want to see a draft conflict window when I edit a content item which has existing drafts.
=> EZP-27786: I want to see a draft conflict window when I edit a content item which has existing drafts

behat_suites.yml, composer.json, features/ContentType.feature, features/ContentTypeGroup.feature, src/lib/Behat/BusinessContext/AdministrationContext.php, src/lib/Behat/BusinessContext/AuthenticationContext.php, src/lib/Behat/BusinessContext/ContentTypeContext.php, src/lib/Behat/BusinessContext/UpdateContext.php, src/lib/Behat/PageElement/AdminList.php, src/lib/Behat/PageElement/Dialog.php, src/lib/Behat/PageElement/RightMenu.php, src/lib/Behat/PageElement/UpdateForm.php, src/lib/Behat/PageElement/UpperMenu.php, src/lib/Behat/PageObject/ContentStructurePage.php, src/lib/Behat/PageObject/ContentTypePage.php, src/lib/Behat/PageObject/PageObjectFactory.php
=> EZP-28172 behat specs for content types

src/bundle/Resources/views/layout.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28839
=> EZP-28839: AlloyEditor is not displayed on production

src/bundle/Resources/public/scss/fieldType/edit/_ezselection.scss
| Tickets       | https://jira.ez.no/browse/EZP-28845
| Tests pass?   | N/A
Fix a conflict between ezselection and ezboolean due to a zindex trouble. If a ezboolean field follows a ezselection field then the ezboolean field goes over the options drop down. See screenshots.
**Before**:
**After**:
=> EZP-28845: Fix conflict between ezselection and ezboolean

src/bundle/Resources/views/dashboard/dashboard.html.twig, src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28810
Version conflict window after clicking edit button of existing draft in Dashboard
=> EZP-28810: Version conflict window after clicking edit button of existing draft in Dashboard

src/bundle/Resources/public/scss/_extra-actions.scss, src/bundle/Resources/translations/locationview.en.xliff, src/bundle/Resources/views/content/widgets/content_create.html.twig
| Tickets       | [EZEE-1877](https://jira.ez.no/browse/EZEE-1877)
Design updates for Create Content widget according to UI Guidelines:
- Update the wording for the label of the Create Content widget:
From "Choose content type" to "Create your content".
- Color contrast:
Change font color, when not using white color, to $ez-black for better color contrast purposes.
- Font-size: 
Changed font-size for content inside widget.
- Add padding top and bottom to the _header of .ez-extra-actions
=> EZEE-1877: Design improvement - Create Content widget

src/lib/Behat/Helper/StudioUtility.php
| Tickets       | [EZEE-1610](https://jira.ez.no/browse/EZEE-1610)
| Bug fix?      | actually yes
This PR introduces a quick fix for Studio tests:
1) The click was never retried (because of missing namespace 😞 )
2) Changed a bit how the method works: now the number of retries isn't fixed at 2 but can be specified, I've chosen 5 as arbitrary value - in most cases it won't make a difference, but in some edge-spinner-is-everywhere-cases it should help.
=> EZEE-1610: Fix click with overlay method

src/lib/Behat/Helper/StudioUtility.php
| Tickets       | [EZEE-1610](https://jira.ez.no/browse/EZEE-1610)
| Bug fix?      | sort-of
Follow-up to https://github.com/ezsystems/ezplatform-admin-ui/pull/348 - the comparison was actually wrong, meaning the function was never retried. Thanks for @m-tyrala for catching it 👍
=> EZEE-1610: Change invalid comparison

src/bundle/Resources/public/js/scripts/admin.location.view.js, src/bundle/Resources/public/js/scripts/button.content.edit.js, src/bundle/Resources/public/js/scripts/sidebar/btn/location.edit.js, src/bundle/Resources/public/scss/_tables.scss, src/bundle/Resources/views/content/locationview.html.twig, src/bundle/Resources/views/content/tab/versions/table.html.twig, src/bundle/Resources/views/layout.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28831
Draft conflict window after clicking edit button of existing draft in Dashboard, Sub-items list, Search results list and Content item using this URL in Link Manager.
=> EZP-28831: Draft conflict window after clicking edit button of existing draft in Dashboard and Sub-items list

src/lib/Menu/ContentRightSidebarBuilder.php, src/lib/UI/Value/ValueFactory.php
| Tickets       | https://jira.ez.no/browse/EZP-28875
This PR contains the fix for removing content translation if a user doesn't have *content/all* permission.
As requested by @lserwatka https://github.com/ezsystems/ezplatform-admin-ui/pull/358/commits/d9ba6785e66f450ca3880b16636d56f947945f49 contains fix for a similar issue in case of removing a user account. 
1. Do all the steps mentioned in JIRA ticket.
2. Go to the admin panel, log in as a user
3. Go to users list, select one, go to the view
4. You can see that the delete button on the …
=> EZP-28875: User can't remove translation without content/all permission

src/lib/UI/Config/Provider/User.php
| Tickets       | https://jira.ez.no/browse/EZP-28892
Using Guard, you get a `PostAuthenticationGuardToken`, which breaks the application.
=> EZP-28892: User UI Config provider breaks when using Guard authentication

src/bundle/Resources/views/content/content_edit/content_edit_base.html.twig, src/bundle/Resources/views/content/content_edit/parts/javascripts.html.twig, src/bundle/Resources/views/content/content_edit/parts/stylesheets.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28852
Here comes twig madness but it's actually beneficial as we now can extend content edit/create templates from other bundles to embed them in different layout. It's will be required by Page Builder. I need someone to check on potential BC breaks as templates are usually risky to change.
Please retest briefly content edit/create.
=> EZP-28852: Rework AdminUI content edit views to allow extending without using pagelayout

src/bundle/Controller/Content/VersionDraftConflictController.php, src/bundle/Controller/ContentController.php, src/bundle/Controller/ContentEditController.php, src/bundle/Controller/ContentViewController.php, src/bundle/Resources/config/routing.yml, src/bundle/Resources/views/content/content_edit/content_edit.html.twig, src/bundle/Resources/views/content/content_preview.html.twig, src/bundle/Resources/views/content/modal_draft_conflict.html.twig, src/bundle/Resources/views/content/tab/versions/table.html.twig, src/lib/Form/Data/Content/Draft/ContentEditData.php, src/lib/Form/Type/Content/Draft/ContentEditType.php, src/lib/RepositoryForms/Form/Processor/PreviewFormProcessor.php, src/lib/Tab/LocationView/VersionsTab.php, src/lib/Tests/RepositoryForms/Form/Processor/PreviewFormProcessorTest.php
| Tickets       | https://jira.ez.no/browse/EZP-28850
| Requires:  | https://github.com/ezsystems/repository-forms/pull/214
Adapting AdminUI to https://github.com/ezsystems/repository-forms/pull/214. With this change it's now possible to use location context when editing the content. This means we are now able to provide proper redirection for Close button in draft edit mode. Previously it was always redirecting to the main location.
Please retest content edit, all edit buttons, version/draft conflict popups, subitems, dashboard, …
=> EZP-28850: Add optional location parameter to draft edit for more appropriate redirection

src/bundle/Resources/public/js/scripts/sidebar/btn/content.edit.js, src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js, src/bundle/Resources/views/content/locationview.html.twig, src/bundle/Resources/views/content/widgets/content_edit.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28884
This probably could be done more on backend part, but I think that would involve modifications in menu build since we would have to inject content services there to build correct uri. And there are already events for language select form submission.
=> EZP-28884: Removing click when editing content in one single language

src/bundle/DependencyInjection/Compiler/SecurityLoginPass.php, src/bundle/EzPlatformAdminUiBundle.php, src/lib/Security/Authentication/RedirectToDashboardAuthenticationSuccessHandler.php, src/lib/Specification/SiteAccess/IsAdmin.php
| Tickets       | https://jira.ez.no/browse/EZP-26238
This solves correct redirecting for admin_sitegroups after login, without messing up frontend login redirect. Resolves /admin redirect to /dashboard.
=> EZP-26238: eZPlatform login screen redirecting to the link the user entered initially

src/bundle/Controller/ContentController.php, src/bundle/Resources/config/services.yml, src/bundle/Resources/config/services/components.yml, src/bundle/Resources/config/services/components/content/edit.yml, src/bundle/Resources/config/services/controllers.yml, src/bundle/Resources/config/services/siteaccess.yml, src/bundle/Resources/public/js/scripts/admin.preview.js, src/bundle/Resources/public/scss/_alerts.scss, src/bundle/Resources/public/scss/_icons.scss, src/bundle/Resources/public/scss/_preview.scss, src/bundle/Resources/public/scss/ezplatform.scss, src/bundle/Resources/translations/content_edit_component_preview_unavailable.en.xliff, src/bundle/Resources/translations/content_preview.en.xliff, src/bundle/Resources/views/content/content_edit/component/preview_unavailable.html.twig, src/bundle/Resources/views/content/content_edit/content_edit.html.twig, src/bundle/Resources/views/content/content_preview.html.twig, src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig, src/lib/Component/Content/PreviewUnavailableTwigComponent.php, src/lib/Menu/ContentEditRightSidebarBuilder.php, src/lib/RepositoryForms/Form/Processor/PreviewFormProcessor.php, src/lib/Siteaccess/NonAdminSiteaccessResolver.php, src/lib/Siteaccess/SiteaccessResolver.php, src/lib/Siteaccess/SiteaccessResolverInterface.php
| Tickets       | https://jira.ez.no/browse/EZP-28314
| Requires    | #374 and https://github.com/ezsystems/repository-forms/pull/214 
Since this PR is relying on a lot of other PR my advice is to wait till we merge other things first.
=> EZP-28314: As a v2 Editor, I want to select a SiteAccess in the Preview mode

src/bundle/Resources/views/fieldtypes/edit/ezbinaryfile.html.twig, src/bundle/Resources/views/fieldtypes/edit/ezimage.html.twig, src/bundle/Resources/views/fieldtypes/edit/ezmedia.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28871
The second part of https://github.com/ezsystems/repository-forms/pull/218
=> EZP-28871: upload_max_filesize setting should be taken into account in the validation of uploaded files

src/bundle/Resources/config/default_parameters.yml, src/bundle/Resources/config/views.yml, src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28921
=> EZP-28921: Configure content create view in AdminUI

src/bundle/Resources/views/admin/content_type/create.html.twig, src/bundle/Resources/views/admin/content_type/edit.html.twig, src/bundle/Resources/views/admin/language/create.html.twig, src/bundle/Resources/views/admin/language/edit.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28930
Global Properties:
Fields:
ezboolean:
ezcountry:
ezdate:
ezdatetime:
ezselection:
=> EZP-28930: Labels are one line below checkbox/radiobutton

src/bundle/Templating/Twig/TabExtension.php, src/lib/Tab/Event/TabEvent.php, src/lib/Tab/Event/TabGroupEvent.php
| Tickets       | https://jira.ez.no/browse/EZP-28938
=> EZP-28938: Make TabGroupEvent and TabEvent aware of execution context

src/bundle/Controller/LanguageController.php
| Tests pass?   | TBD
This PR fixes wrong usage of non-existent policy when trying to view Admin -> Languages Tab.
The proper one is [`content / translations`](https://github.com/ezsystems/ezpublish-legacy/blob/master/settings/menu.ini#L363-L364).
=> Fixed wrong policy check for Admin -> Languages Tab

src/bundle/Resources/public/scss/_add-translation.scss
| Tickets       | [EZP-28922](https://jira.ez.no/browse/EZP-28922)
Design consistency for modals across the whole application:
- Updated styling for modals (Translations, Send to Trash and Send to Trash from Trash manager), background-colors.
- In Translations modal aligned colors for language selection for translations to the existing one in content-edit-language widget.
=> EZP-28922: Design consistency for modals across the whole application

src/bundle/Controller/ContentEditController.php
| Tickets       | [EZP-28929](https://jira.ez.no/browse/EZP-28929)
| Tests pass?   | TBD
This PR fixes inability to add new Translation to a Content item by providing missing Content edit template.
=> EZP-28929: User is unable to add translation to Content item

src/bundle/Resources/views/content/content_edit/content_create_draft.html.twig, src/bundle/Resources/views/content/content_edit/content_edit_base.html.twig, src/bundle/Resources/views/parts/navigation.html.twig, src/lib/Behat/PageElement/UpperMenu.php
| Tickets       | https://jira.ez.no/browse/EZP-28874
**THINGS FIXED:**
**HOW TO TEST IT?**
Just resize the browser window and watch if navbar and the sidebar are not breaking the layout. Test on all modern browsers.
=> EZP-28874: Main Menu is not responsive under 992 pixels

src/bundle/Resources/views/admin/trash/list.html.twig, src/lib/Form/Data/TrashItemData.php
| Tickets       | https://jira.ez.no/browse/EZP-28334
When a Parent item is sent to Trash - then all the corresponding child items will no longer have a parent location ID and each of these child content item's should display a status/message 'Item's ancestors are in Trash' under the path column.
And whenever a user tries to restore the child item then the option to restore is disabled and only the option to restore under a new parent is enabled.
=> EZP-28334: Fix for restoring from trash after removing structure of items.

src/bundle/Controller/SearchController.php, src/bundle/Resources/public/js/scripts/admin.search.filters.js, src/bundle/Resources/public/scss/_content-type-selector.scss, src/bundle/Resources/translations/messages.en.xliff, src/bundle/Resources/translations/search.en.xliff, src/bundle/Resources/views/admin/search/search_form.html.twig, src/bundle/Resources/views/form_fields.html.twig, src/lib/Form/Data/Search/SearchData.php
| Tickets       | https://jira.ez.no/browse/EZP-28947 https://jira.ez.no/browse/EZP-28946
=> EZP-28947: Filtered search inconsistencies

src/bundle/Resources/public/js/scripts/admin.location.tab.js, src/bundle/Resources/public/js/scripts/admin.location.view.js, src/bundle/Resources/public/js/scripts/admin.search.filters.js, src/bundle/Resources/public/js/scripts/admin.version.edit.conflict.js, src/bundle/Resources/public/js/scripts/button.content.edit.js, src/bundle/Resources/public/js/scripts/sidebar/btn/location.edit.js, src/bundle/Resources/views/content/locationview.html.twig, src/bundle/Resources/views/content/tab/versions/tab.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28957
=> EZP-28957: Cannot open draft conflict modal when two jQuery are loaded

src/bundle/Resources/public/scss/_icons.scss, src/bundle/Resources/public/scss/_modals.scss, src/bundle/Resources/views/admin/bulk_delete_confirmation_modal.html.twig, src/bundle/Resources/views/admin/content_type/delete_confirmation_modal.html.twig, src/bundle/Resources/views/admin/language/delete_confirmation_modal.html.twig, src/bundle/Resources/views/admin/section/delete_confirmation_modal.html.twig, src/bundle/Resources/views/admin/trash/empty_trash_confirmation_modal.html.twig, src/bundle/Resources/views/bulk_delete_confirmation_modal.html.twig, src/bundle/Resources/views/content/modal_draft_conflict.html.twig, src/bundle/Resources/views/content/modal_location_trash.html.twig, src/bundle/Resources/views/content/modal_user_delete.html.twig, src/bundle/Resources/views/content/modal_version_conflict.html.twig, src/bundle/Resources/views/content/tab/translations/modal_add_translation.html.twig
| Tickets       | [EZP-28965](https://jira.ez.no/browse/EZP-28965)
- Updated Close button style for Modals.
=> EZP-28965: Modals Close button harmonization in AdminUI

src/bundle/Resources/public/scss/fieldType/edit/_ezselection.scss, src/bundle/Resources/public/scss/fieldType/preview/_ezselection.scss
| Tickets       | https://jira.ez.no/browse/EZP-28932
=> EZP-28932: Broken empty option design after selecting it from ezselection fieldtype

src/bundle/Resources/views/fieldtypes/edit/ezimage.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28279
Fix display and frontend js validation.
related to:
https://github.com/ezsystems/ezpublish-kernel/pull/2280
https://github.com/ezsystems/repository-forms/pull/226
=> EZP-28279: User cannot set max file size in Image field type

src/bundle/Resources/public/js/scripts/admin.prevent.click.js, src/bundle/Resources/public/scss/_general.scss, src/bundle/Resources/views/layout.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28682 https://jira.ez.no/browse/EZP-28685
=> EZP-28682: Error 404 after fast double click

src/bundle/Resources/public/scss/_content-edit.scss, src/bundle/Resources/public/scss/fieldType/edit/_ezgmaplocation.scss, src/bundle/Resources/views/content/content_edit/component/preview_unavailable.html.twig, src/bundle/Resources/views/content/content_edit/content_create.html.twig, src/bundle/Resources/views/content/content_edit/content_edit.html.twig, src/bundle/Resources/views/content/content_edit/content_edit_base.html.twig, src/bundle/Resources/views/content/content_edit/user_create.html.twig, src/bundle/Resources/views/content/content_edit/user_edit.html.twig
| Tickets       | [EZP-28386](https://jira.ez.no/browse/EZP-28386)
- Updated Create and Design layouts based on UI Guidelines design;
- Close button placed on left side, in order to avoid usability issues due to the closeness of Close and Discard buttons when the first one is on the right side;
- Form fields contained within `ez-card` following consistency with Editing view in Admin section.
- Added offset margins to Creating/Editing language name, Content item title, Content Type name and Content Type descriptions;
- …
=> EZP-28386: Update Create & Edit design layout

src/bundle/Resources/public/scss/_icons.scss, src/bundle/Resources/views/admin/search/search_form.html.twig
| Tickets       | [EZP-28973](https://jira.ez.no/browse/EZP-28973)
- Three more modal close buttons needed to be included for harmonization based on QA feedback, Search filters custom range (`ez-modal--select-modified-range`) and content type editing view delete confirmation modal.
=> EZP-28973: Modal close button harmonization review

src/bundle/Controller/SearchController.php, src/lib/Form/Data/Search/SearchData.php, src/lib/Form/Type/Search/SearchType.php
| Tickets       | https://jira.ez.no/browse/EZP-28945
User should be able to search for content items by just selecting the filters and applying the changes.
=> EZP-28945: User will be able to search for content items by just selecting the filters.

src/bundle/Resources/public/scss/_card.scss, src/bundle/Resources/views/admin/content_type/delete_confirmation_modal.html.twig, src/bundle/Resources/views/bulk_delete_confirmation_modal.html.twig
| Tickets       | [EZP-28982](https://jira.ez.no/browse/EZP-28982)
- Update content from Send to trash URL for consistency purposes;
- Update content  and color from Send to trash field type when in Content type editing view.
=> EZP-28982: Modal Send to trash content update

src/bundle/Resources/config/services/ui_config/common.yml, src/bundle/Resources/views/content/tab/urls.html.twig, src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig, src/lib/UI/Config/Provider/Languages.php
| Tickets       | https://jira.ez.no/browse/EZP-28362
| Requires    | https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/59
Display language name instead of language code.
=> EZP-28362: Display Language name and not language code.

src/bundle/Resources/views/content/tab/details.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29008
| Tests pass?   |yes
Number and language in the same line on Details tab of CI
=> EZP-29008: Number and language in the same line on Details tab of CI

src/bundle/Resources/config/services/ui_config/common.yml, src/bundle/Resources/views/content/tab/urls.html.twig, src/bundle/Resources/views/content/tab/versions/table.html.twig, src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig, src/lib/UI/Config/Provider/ContentTypes.php, src/lib/UI/Config/Provider/Languages.php, src/lib/UI/Config/Provider/Module/UniversalDiscoveryWidget.php
| Tickets       | https://jira.ez.no/browse/EZP-29010
| Requires/QA    | https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/61
=> EZP-29010: Move Content on the Fly common configuration to root namespace od AdminUI config

src/bundle/Resources/views/admin/section/view.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28803
Edit button in sections is aligned to the right
=> EZP-28803: Edit button in sections is not aligned to the right

features/ContentType.feature, src/bundle/Resources/translations/content_type.en.xliff, src/bundle/Resources/views/admin/content_type/view.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28181
Labels changes in the Content Type View. 'Content name schema' to 'Content name pattern'
and 'Default availability' to 'Default content availability'
=> EZP-28181: Inconsistence with labels in content type specific view

src/bundle/Resources/views/content/content_edit/content_edit.html.twig, src/bundle/Resources/views/content/content_edit/user_edit.html.twig, src/lib/RepositoryForms/View/ViewParametersListener.php, src/lib/Tests/RepositoryForms/View/ViewParametersListenerTest.php
| Tickets       | https://jira.ez.no/browse/EZP-28915
Now Content Item creator name is displayed. It comes from Content Item ownerId field. Displayed date near creator information is changed to contentInfo publishedDate.
=> EZP-28915: Hardcoded Administrator in content edit details section

src/bundle/Resources/public/scss/_forms.scss, src/bundle/Resources/views/content/tab/details.html.twig
| Tickets       | [EZP-28999](https://jira.ez.no/browse/EZP-28999)
Update Object state set button style update to `btn-secondary` in order to align with the rest of UI
=> EZP-28999: Object state set button style update

src/lib/Menu/ContentRightSidebarBuilder.php
| Tickets       | https://jira.ez.no/browse/EZP-29019
=> EZP-29019: "Send to trash" action should be disabled when user doesn't have sufficient permission

src/bundle/Controller/ContentViewController.php, src/bundle/Resources/translations/messages.en.xliff, src/bundle/Resources/views/fieldtypes/preview/ezobjectrelationlist_row.html.twig
| Tickets       | [EZP-28439](https://jira.ez.no/browse/EZP-28439), (with Kernel it also solves [EZP-28781](https://jira.ez.no/browse/EZP-28781) and [EZP-28865](https://jira.ez.no/browse/EZP-28865))
=> EZP-28439: Related content is still displayed after it is moved to trash

.travis.yml, src/lib/Behat/BusinessContext/ContentViewContext.php, src/lib/Behat/Helper/UtilityContext.php, src/lib/Behat/PageElement/ElementFactory.php, src/lib/Behat/PageElement/LanguagePicker.php
| Tickets       | https://jira.ez.no/browse/EZEE-1610
This change is for 1.1 - since 2.1 release, the Language Picker is not visible if Content has only one language.
This is required by: https://github.com/ezsystems/flex-workflow/pull/97/files
=> EZEE-1610: Ignore Language Picker for Content with one Language

src/bundle/Resources/public/js/scripts/admin.trash.list.js
| Tickets       | https://jira.ez.no/browse/EZP-28980
=> EZP-28980: When restoring a trash item under a new parent, the user should not be able to select multiple location in the UDW

src/bundle/Controller/ContentViewController.php, src/bundle/Resources/views/content/locationview.html.twig, src/bundle/Resources/views/content/tab/pagination.html.twig, src/bundle/Resources/views/content/tab/url/custom_urls_table.html.twig, src/bundle/Resources/views/content/tab/url/system_urls_table.html.twig, src/bundle/Resources/views/content/tab/urls.html.twig, src/lib/Tab/LocationView/UrlsTab.php
| Tickets       | https://jira.ez.no/browse/EZP-28955
=> EZP-28955: Adding pagination to URL Aliases in the URL alias tab

src/lib/Menu/ContentRightSidebarBuilder.php
| Tickets       | [EZP-29087](https://jira.ez.no/browse/EZP-29087)
| Depends on | ezsystems/ezpublish-kernel#2314
This is AdminUI counterpart for ezsystems/ezpublish-kernel#2314. See either that PR or Jira issue description for  more details. 
QA: Kernel PR is targeted to `6.7` so to test this, changes needs to be cherry-picked.
=> Fixed EZP-29087: Changed policy which allows to trash a Location

src/bundle/Controller/ContentTypeController.php, src/bundle/Resources/translations/content_type.en.xliff
| Tickets       | https://jira.ez.no/browse/EZP-29022
This PR adds notification with information that Content Type Draft cannot be edited.
=> EZP-29022: If user has logged out in edit mode of CT nobody can edit this CT

src/bundle/Resources/translations/object_state.en.xliff, src/bundle/Resources/views/admin/language/view.html.twig, src/bundle/Resources/views/admin/section/list.html.twig, src/bundle/Resources/views/admin/section/view.html.twig, src/bundle/Resources/views/content/tab/details.html.twig, src/lib/Form/Type/ObjectState/ContentObjectStateUpdateType.php, src/lib/Tab/LocationView/DetailsTab.php
| Tickets       | https://jira.ez.no/browse/EZP-29131
Basically this removes some leftovers from unused `data-disabled` attribute and improves object state dropdown. (filtering by policies and not displaying when empty).
Previously, for some reason in order to disable button (due to lack of access to functionality, `data-disabled` attribute was added to corresponding element). Because of missing JS (probably) that was not working correctly. That was fixed with removing those attributes and, as guildlines says, hiding the button instead of …
=> EZP-29131: Improvements to disabling/hiding elements

src/bundle/Resources/views/content/form_fields.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28479
=> EZP-28479: In the content item edit view, the application does not display the help text when I hover over the input field

features/Roles.feature, src/bundle/Controller/PolicyController.php, src/bundle/ParamConverter/PolicyDraftParamConverter.php, src/bundle/Resources/config/routing.yml, src/bundle/Resources/translations/role.en.xliff, src/bundle/Resources/views/admin/policy/create_with_limitation.html.twig, src/lib/Behat/BusinessContext/RolesContext.php, src/lib/Behat/PageObject/RolePage.php, src/lib/Form/Data/Policy/PolicyCreateData.php, src/lib/Form/DataMapper/PolicyCreateMapper.php, src/lib/Form/Factory/FormFactory.php, src/lib/Form/Type/Policy/PolicyCreateWithLimitationType.php
| Tickets       | https://jira.ez.no/browse/EZP-29023
Currently, after creating/adding a new policy to a role it is instantly active with no limitations. They could be added by editing this policy. The idea is to specify limitations while creating a new policy by setting this as next step to follow when policy can have limitations.
=> EZP-29023: Setting limitations while creating policies

src/bundle/Resources/public/js/scripts/admin.search.filters.js, src/bundle/Resources/views/admin/search/search_form.html.twig, src/bundle/Resources/views/content/tab/details.html.twig, src/lib/Form/Type/Search/SearchType.php, src/lib/Tab/LocationView/DetailsTab.php
| Tickets       | https://jira.ez.no/browse/EZP-29161
=> EZP-29161: Hide Section table in Details if the user does not have "Section/View"

src/lib/Tab/LocationView/PoliciesTab.php, src/lib/Tab/LocationView/RolesTab.php
| Tickets       | https://jira.ez.no/browse/EZP-29160
This PR hide Roles and Policies tab if the user does not have "Role/Read" permission.
=> EZP-29160: Hide Roles and Policies tab if the user does not have "Role/Read" permission

src/bundle/Resources/views/content/content_edit/content_edit_base.html.twig
| Tickets       | https://jira.ez.no/browse/EZEE-2025
This is needed to fix https://jira.ez.no/browse/EZEE-2024. My PR adds new variable `form_templates` which can be defined outside when embedding `content_edit_base.html.twig` providing injection point of custom Twig templates for content edit/create form.
=> EZEE-2025: Add extension point in `content_edit_base.html.twig` allowing spoofing form templates

src/lib/Tab/LocationView/RelationsTab.php
| Tickets       | https://jira.ez.no/browse/EZP-29213
=> EZP-29213: Error 500 when user doesn't have Content/reverserelatedlist policy

src/bundle/Controller/ObjectStateController.php, src/bundle/Controller/ObjectStateGroupController.php, src/bundle/Resources/views/admin/object_state/list.html.twig, src/bundle/Resources/views/admin/object_state_group/list.html.twig, src/bundle/Resources/views/content/tab/details.html.twig, src/lib/Form/Type/ObjectState/ContentObjectStateUpdateType.php, src/lib/Menu/MainMenuBuilder.php, src/lib/Tab/LocationView/DetailsTab.php
| Tickets       | https://jira.ez.no/browse/EZP-29103
For now state/assign policy is only checked by `$this->permissionResolver->hasAccess('state', 'assign')` method. When user has some limitation, button will be displayed.
=> EZP-29103: Implement permissions for Object State in Admin Panel

src/bundle/DependencyInjection/Configuration/Parser/Notifications.php, src/bundle/EzPlatformAdminUiBundle.php, src/bundle/Resources/config/ezplatform_default_settings.yml, src/bundle/Resources/config/services/ui_config/common.yml, src/bundle/Resources/public/js/scripts/admin.notifications.js, src/bundle/Resources/translations/messages.en.xliff, src/bundle/Resources/views/layout.html.twig, src/bundle/Resources/views/parts/notification.html.twig, src/lib/UI/Config/Provider/Notifications.php
| Tickets       | https://jira.ez.no/browse/EZP-29209
| Doc needed?   | yes?
**Screenshot**
**Usage**
```js
const eventInfo = new CustomEvent('ez-notify', {
detail: {
label: 'info',
message: 'this is info message'
}
});
const eventSuccess = new CustomEvent('ez-notify', {
detail: {
label: 'success',
message: 'this is success message'
}
});
const eventWarning = new CustomEvent('ez-notify', {
detail: {
label: 'warning',
message: 'this is warning message'
}
});
const eventError = new CustomEvent('ez-notify', {
detail: {
label: 'danger',
message: 'this is error …
```
=>  EZP-29209: Front-end Notification System (from JS) API

src/bundle/Resources/public/css/alloyeditor/alloyeditor-ez.css
| Tickets       | https://jira.ez.no/browse/EZP-29204
Change from `height: 40px` to `height: auto` inside `.ae-ui IE10-PLUS::-ms-reveal, .ae-ui [class^=ae-toolbar]` fixes background not stretching for entire toolbar problem on Edge, that shows mostly when new link toolbar is open.
=> EZP-29204: RichText link popup on Microsoft Edge has broken styling

.php_cs, src/lib/Tests/Form/DataTransformer/LanguageTransformerTest.php, src/lib/Tests/Form/DataTransformer/LocationTransformerTest.php, src/lib/Tests/Form/DataTransformer/RoleAssignmentTransformerTest.php, src/lib/Tests/Form/DataTransformer/RoleTransformerTest.php, src/lib/Tests/Form/DataTransformer/SectionTransformerTest.php, src/lib/Tests/Form/DataTransformer/SectionsTransformerTest.php
This PR aligns code with missing CS rules on 1.1 (one more remaining for master).
I planned to push this directly, however there's one debatable change.
The php-cs-fixer, according to `self_accessor` rule, tries to fix:
[src/lib/Specification/SpecificationInterface.php](https://github.com/ezsystems/ezplatform-admin-ui/blob/v1.1.1/src/lib/Specification/SpecificationInterface.php) in the following way:
```php
/**
* @param SpecificationInterface $other
*
* @return SpecificationInterface
*/
public function and(self $other): self;
```
While this seems like a good direction, it looks like PhpStorm (2018.1.4) is completely unable to understand that (in terms of classes implementing that interface and also param type hinting). This is really annoying and leads to bad dev experience.
We've decided …
=> [CS][1.1] Aligned missed CS fixes and adjusted php-cs-fixer conf

src/lib/Form/Type/ObjectState/ContentObjectStateUpdateType.php, src/lib/Tab/Dashboard/MyDraftsTab.php
| Tickets       | https://jira.ez.no/browse/EZP-29218
Hide tab if user has absolutely no access to content/versionread. If user has no access content/versionread for one of versions, exception is caught and draft array is empty.
=> EZP-29247: Error 500 after trying to enter dashboard with "My drafts" without Content/VersionRead policy

.travis.yml, composer.json
Currently build for 1.1 branch is failing on Travis - this PR checks whether setting proper branch in composer.json is enough and adds Travis notification for this branch to Slack.
=> [Travis] Add notifications and set proper metarepo branch

src/bundle/Resources/config/services/ui_config/common.yml, src/lib/UI/Config/Provider/ContentTypeNames.php
| Tickets       | http://jira.ez.no/browse/EZEE-2040
We need to expose additional (flap) map of ContentType identifiers to names, without grouping etc.
=> EZEE-2040: Expose in config map of content type identifiers to names

src/bundle/Resources/public/js/scripts/admin.location.bookmark.js
| Tickets       | https://jira.ez.no/browse/EZP-29268
| Doc needed?   | ?
Status of a bookmark from Location page should be changed when this location is being bookmarked or unbookmarked elsewhere on the page. 
E.g. when I bookmark Location 2 in Content Meta Preview in UDW, while being on the page of Location 2, the bookmark from the page should change.
=> EZP-29268: Change bookmark status in Location page when bookmark changed elsewhere on the site

src/bundle/Resources/views/Security/base.html.twig, src/bundle/Resources/views/layout.html.twig
| Tickets       | [EZP-28890](http://jira.ez.no/browse/EZP-28890)
Adds support for in-context translation, as introduced in https://github.com/ezsystems/PlatformUIBundle/pull/773.
=> EZP-28890: Added crowdin in-context translation JS code

src/bundle/Resources/public/js/scripts/admin.location.bookmark.js, src/bundle/Resources/public/scss/_add-to-bookmarks.scss, src/bundle/Resources/views/parts/form/location_bookmark.html.twig
Fixes the bug concerning a bookmark star on a location page. The content was always bookmarked, even if it wasn't.
| Tickets       | https://jira.ez.no/browse/EZP-29266
=> EZP-29266: Content item seems to be always bookmarked

src/bundle/Resources/public/js/scripts/fieldType/base/base-file-field.js, src/bundle/Resources/public/js/scripts/fieldType/base/base-preview-field.js, src/bundle/Resources/views/content/form_fields.html.twig, src/bundle/Resources/views/fieldtypes/edit/binary_base.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29119
This PR is also fixing doubled error messages (backend).
=> EZP-29119: Display proper validation error message when non-image file uploaded in image FieldType

src/bundle/Resources/views/content/tab/locations/tab.html.twig, src/lib/Tab/LocationView/LocationsTab.php
| Tickets       | https://jira.ez.no/browse/EZP-29310
=> EZP-29310: Implement permissions for Add Location in Locations tab

src/bundle/Resources/config/services/ui_config/common.yml, src/lib/UI/Config/Provider/SortFieldMappings.php, src/lib/UI/Config/Provider/SortOrderMappings.php
| Tickets       | https://jira.ez.no/browse/EZP-29270
| Tests pass?   | ?
Unfortunately serialized values of `\eZ\Publish\API\Repository\Values\Content\Location::$sortField` and `\eZ\Publish\API\Repository\Values\Content\Location::$sortOrder` are hardcoded in REST API.
=> EZP-29270: Sub-items sorting order not respected by UDW

src/bundle/Resources/views/content/tab/locations/tab.html.twig, src/lib/UI/Value/Content/Location.php, src/lib/UI/Value/ValueFactory.php
| Tickets       | https://jira.ez.no/browse/EZP-29311
=> EZP-29311: Implement permissions for Change main Location in Locations tab

src/bundle/Resources/translations/role.en.xliff, src/bundle/Resources/views/admin/policy/add.html.twig, src/bundle/Resources/views/content/tab/url/custom_urls_table.html.twig, src/bundle/Resources/views/content/tab/urls.html.twig, src/lib/Tab/LocationView/UrlsTab.php
| Tickets       | [EZP-29316](https://jira.ez.no/browse/EZP-29316)
Urls should only allow add/remove urls if policy allows
=> EZP-29316: Only show add/remove buttons for urls if policy allows

src/bundle/Resources/translations/pagination.en.xliff
| Tickets       | none
Running the extractor did not modify the string, even though it was okay in the template.
=> [i18n] updated wrong source message in pagination domain

src/bundle/DependencyInjection/Configuration/Parser/AdminUiForms.php, src/bundle/DependencyInjection/EzPlatformAdminUiExtension.php, src/bundle/EzPlatformAdminUiBundle.php, src/bundle/Resources/config/admin_ui_forms.yml, src/bundle/Resources/config/services/ui_config/common.yml, src/bundle/Resources/views/content/content_edit/content_edit_base.html.twig, src/bundle/Tests/DependencyInjection/Configuration/Parser/AdminUiFormsTest.php
| Tickets       | https://jira.ez.no/browse/EZEE-2111
| Requies | ezsystems/ezplatform-page-builder#98
This PR exposes SiteAccess-aware setting to inject custom Twig Form Theme into Admin UI Content edit forms.
Usage:
```yaml
ezpublish:
system:
admin_group: # configuration per SiteAccess or SiteAccess group
admin_ui_forms:
content_edit_form_templates: 
- { template: 'my_template.html.twig', priority: 0 }
```
The higher the priority, the higher the template will be placed on the list.
=> EZEE-2111: Landing Page field is visible while creating new Page with COTF

src/bundle/Resources/public/scss/_custom.scss, src/bundle/Resources/public/scss/_pagination.scss, src/bundle/Resources/views/admin/bookmark/list.html.twig, src/bundle/Resources/views/admin/content_type/list.html.twig, src/bundle/Resources/views/admin/content_type_group/list.html.twig, src/bundle/Resources/views/admin/language/list.html.twig, src/bundle/Resources/views/admin/policy/list.html.twig, src/bundle/Resources/views/admin/role/list.html.twig, src/bundle/Resources/views/admin/role_assignment/list.html.twig, src/bundle/Resources/views/admin/search/list.html.twig, src/bundle/Resources/views/admin/search/search.html.twig, src/bundle/Resources/views/admin/section/assigned_content.html.twig, src/bundle/Resources/views/admin/section/list.html.twig, src/bundle/Resources/views/admin/trash/list.html.twig, src/bundle/Resources/views/content/tab/pagination.html.twig, src/bundle/Resources/views/content/tab/versions/tab.html.twig, src/bundle/Resources/views/link_manager/list.html.twig, src/bundle/Resources/views/link_manager/view.html.twig
| Tickets       | [EZP-28461](https://jira.ez.no/browse/EZP-28461)
- Design goals:
- Customer request -> When a Notification message shows up it blocks pagination buttons.
- Harmonize Pagination and Load more features.
- Design specifications:
- Pagination text that specifies viewed items and items in total should have the same font-size as in Load more feature;
- Pagination buttons should have the same font-size as regular buttons in the application (= 1rem)
- Add extra space below pagination feature, in order to avoid …
=> [EZP-28461] Pagination design consistency

src/bundle/Resources/public/js/scripts/admin.location.view.js
Instead of sending to _SubItems_ & _MultiFileUpload_ paramaters as string, they are sent as numbers. Parameters are: `parentLocationId` & `contentTypeId` respectively.
Connected with:
https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/74
=> Fixed 2 parameters types passed to SubItems & MultiFileUpload

src/bundle/Resources/public/scss/_add-to-bookmarks.scss, src/bundle/Resources/public/scss/_page-title.scss, src/bundle/Resources/views/content/locationview.html.twig, src/bundle/Resources/views/layout.html.twig, src/bundle/Resources/views/parts/page_title.html.twig
| Tickets       | [EZP-29327](https://jira.ez.no/browse/EZP-29327)
- Updated `ez-page-title` design due to long content item title was covered by Bookmark button;
- Added `grid` for re-arranging elements;
- Resized bookmark button (according to UI Guidelines);
- Added `text-indent` for wrapping long content item titles.
=> [EZP-29327] Updated ez-page-title for bookmark button

src/bundle/Resources/public/scss/_notifications.scss
| Tickets       | https://jira.ez.no/browse/EZP-29330
Fixed long text in notification covering close button.
=> EZP-29330: Long title covers (X) button in message bar

src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
| Tickets       | [EZP-29172](https://jira.ez.no/browse/EZP-29172)
- Updated error color in editing view based on usability (color contrast) standards.
- Justification: `$ez-color-warning-dark` is the color that passes all color contrast requirements for legibility of text in that specific view for people with certain visual conditions, as well as improving the reading experience for the rest of users. We are aiming to cover these standards given our users/customers base.
=> EZP-29172 - Updated error color in editing view based on usability standards

src/bundle/Resources/config/services.yml, src/bundle/Resources/config/services/form_ui_action_mappers.yml, src/lib/Form/Type/ContentType/SortFieldChoiceType.php, src/lib/Form/Type/ContentType/SortOrderChoiceType.php, src/lib/Form/Type/Policy/PolicyChoiceType.php
| Tickets       | https://jira.ez.no/browse/EZP-28774
| Bug fix?      | yes| New feature?  | yes/no
Fixed the following deprecation warnings generated by admin ui:
1. ```The configuration key "tags" is unsupported for the service "EzSystems\EzPlatformAdminUi\UI\Action\FormUiActionMapperInterface" which is defined as an alias in "/Users/awojs/Workspace/ezplatform-admin-ui/src/bundle/DependencyInjection/../Resources/config/services/form_ui_action_mappers.yml". Allowed configuration keys for service aliases are "alias" and "public". The YamlFileLoader will raise an exception in Symfony …
```
=> EZP-28774: Fixed misc. deprecation warnings

src/bundle/Resources/views/admin/bookmark/list.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29288
| Bug fix?      | -
Fixed position of edit button in Bookmark table
Now:
Previously:
=> EZP-29288: Edit button on Bookmarks list is not aligned

src/bundle/Controller/ContentViewController.php, src/bundle/Resources/config/services/controllers.yml
| Tickets       | https://jira.ez.no/browse/EZP-29114
Long time ago, there was this idea that there would be only one pagination parameter. Reality has shown something different ;)
As we two times already fall into trap of this defaultPaginationParam name be missguiding, we decided to rename it to be more specific.
=> EZP-29114: Fix pagination parameter naming for draft, system and custom url

src/bundle/Controller/ContentTypeController.php, src/bundle/Controller/ContentTypeGroupController.php, src/bundle/Resources/views/admin/content_type/list.html.twig, src/bundle/Resources/views/admin/content_type/view.html.twig, src/bundle/Resources/views/admin/content_type_group/list.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29101
=> EZP-29101: Implement permissions for Content Types

features/ContentCreation.feature, src/bundle/Controller/LocationController.php, src/bundle/Resources/translations/location.en.xliff
| Tickets       | https://jira.ez.no/browse/EZP-29159
=> EZP-29159: [Copy/Move] Wrong notifications after moving and copying

features/ContentCreation.feature, src/lib/Behat/PageElement/UniversalDiscoveryWidget.php
Build https://travis-ci.org/ezsystems/ezplatform-admin-ui/jobs/400311814 failed with:
```
WebDriver\Exception\UnknownError: unknown error: Element <button class="btn--trigger btn btn-secondary btn-block" data-click="#ezrepoforms_content_edit_publish" id="content_create__sidebar_right__publish-tab">...</button> is not clickable at point (1369, 58). Other element would receive the click: <h1 class="m-ud__title">...</h1
```
It's caused by UDW modal not disappearing fast enough after Confirm is clicked - Publish was still …
=> [Fix build] Wait until UDW is closed with further actions.

composer.json, src/bundle/Resources/config/services.yml, src/bundle/Resources/config/services/translation.yml, src/lib/Translation/Extractor/JavaScriptFileVisitor.php
| Tickets       | https://jira.ez.no/browse/EZP-28890
Configuration for `willdurand/js-translation-bundle` will be separate PR.
=> EZP-28890: Impl. extractor for *.js files

src/lib/Behat/Helper/UtilityContext.php, src/lib/Behat/PageElement/UniversalDiscoveryWidget.php
| Tickets       | https://jira.ez.no/browse/EZEE-2181
This fix is required for Page Builder, otherwise the tests will be failing soon 😢 
What happens:
in Collection Block scenario, the following items are picked (one after another): 'Home,Home/eZ Platform,Media/Images`.
Sometimes it fails when trying to select the last item: I believe it's because we have to switch the parent UDW path (from Home to Media), but for a brief moment before the switch is done the Home items are still displayed. So, in a timeline:
1. Home is selected (Home items …
=> EZEE-2181: Improve UDW branch switching

src/bundle/Templating/Twig/UiConfigExtension.php, src/lib/UI/Config/ConfigWrapper.php
| Tickets       | https://jira.ez.no/browse/EZP-29423
`bazinga:js-translation:dump` internally use Twig to generate JS translations files. Some implementations of the `Config\ProviderInterface` (used to compute value of the `admin_ui_config` Twig global variable ) depends indirect on database connection which cause this command to fail when database connection isn't properly setup. For instance when the `bazinga:js-translation:dump` is executed as part of `composer install` on the newly created projects. Ref. …
=> EZP-29423: Lazy loading value of the admin_ui_config Twig global variable

src/bundle/Templating/Twig/UiConfigExtension.php, src/lib/UI/Config/ConfigWrapper.php
| Tickets       | https://jira.ez.no/browse/EZP-29423
=> EZP-29423: Lazy loading value of the admin_ui_config Twig global variable (CS)

src/bundle/Resources/public/js/scripts/fieldType/base/base-file-field.js, src/bundle/Resources/public/js/scripts/fieldType/ezmedia.js, src/bundle/Resources/public/scss/_forms.scss, src/bundle/Resources/public/scss/fieldType/edit/_ezimage.scss, src/bundle/Resources/views/fieldtypes/edit/ezmedia.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29449
=> EZP-29449: Cannot read property 'innerHTML' of null on upload in ezimage, ezmedia & ezbinaryfile

src/bundle/Resources/translations/content_url.en.xliff, src/bundle/Resources/views/content/tab/url/modal_add_custom_url.html.twig, src/lib/Tab/LocationView/UrlsTab.php
…the parent location
| Tickets       | https://jira.ez.no/browse/EZP-29433
When the situation explained in the ticket, the user has read permissions limited to '/1/2/' and '/1/43/' 
When viewing the location 2 in the admin, it tries to render the tabs with the info about related urls. The tab related code is trying to load the parent Location at some point and hence the error. 
This is not only a problem with the root node. if you have a role with content / read and limitations `/1/2/100/200` `/1/2/100/300`, you will have the same error if …
=> Fix EZP-29433. Unauthorized exception user has no permission to read the parent location

src/bundle/Controller/ContentViewController.php
| Tickets       | https://jira.ez.no/browse/EZP-29342
Now if `$view->getLocation()` returns null (because of sending related location to trash) `location_is_bookmarked` parameter will be set to false.
=> EZP-29342: Deleting related object for ezobjectrelations field throws error 500

src/bundle/Resources/views/admin/bookmark/list.html.twig
| Tickets       | [EZP-29468](https://jira.ez.no/browse/EZP-29468)
-Improve styling of bookmarks manager's delete button. Current markup for that button should be replaced by `class="btn btn-danger"`
=> EZP-29468 Improved style of bookmarks manager's delete button

src/bundle/Resources/config/services/form_processors.yml, src/lib/RepositoryForms/Form/Processor/Content/UrlRedirectProcessor.php
| Tickets       | https://jira.ez.no/browse/EZP-29091
Added new FormProcessor into adminUi in order to properly handle redirects after publishing/canceling content inside admin panel. There is change in default behavior in repository-forms as right now it by defaults redirect onto system-url instead of /content/location/{id}.
Relevant PR:
https://github.com/ezsystems/repository-forms/pull/244
=> EZP-29091: Publishing Content from the frontend results in error

src/bundle/Resources/views/content/content_on_the_fly/content_create_on_the_fly.html.twig
| Tickets       | [EZP-29491](https://jira.ez.no/browse/EZP-29491)
- Harmonized color of content item status in Content On The Fly, Create view, as defined in Content section - Edit/Create views.
=> EZP-29491: Harmonized item status color in COTF

src/bundle/Resources/public/scss/fieldType/edit/_ezauthor.scss
| Tickets       | [EZP-29496](https://jira.ez.no/browse/EZP-29496)
- Reviewed alignment of buttons in `ez_author` field type.
=> EZP-29496: Improved styling of ez_author field type buttons in edit view

src/lib/Menu/ContentRightSidebarBuilder.php
| Tickets       | https://jira.ez.no/browse/EZP-29224
This PR is hiding 'Send to Trash' button for the content and 'Delete' button for the user when the user has no proper permissions.
=> EZP-29224: Implement permissions for "Content/Remove"

src/bundle/Resources/public/js/scripts/helpers/notification.helper.js
| Tickets       | https://jira.ez.no/browse/EZP-29498
Currently there are 4 types of notifications: 'info', 'success', 'warning' & 'danger', but in fact 'danger' should be an 'error' notification. Thus `showDangerNotification` should be removed; `showErrorNotification` already exists.
*For QA*: notifications should work as before.
=> EZP-29498: showDangerNotification duplicates the functionality of showErrorNotification

src/bundle/Resources/public/scss/_user-menu.scss
| Tickets       | [EZP-29232](https://jira.ez.no/browse/EZP-29232)
- `ez-user-menu` covered by `ez-context-menu` in Safari (Safari on iOS do not interpret `z-index: initial` correctly - [Recurrent issue in cross-browser testing](https://stackoverflow.com/a/42142794/4551872)
- Tested solution on Safari 11.1.2, Firefox Dev Ed 62.0b13, Firefox 61.0.2, Opera 54.0.2952.71 all for IOS
=> EZP-29232: ez-user-menu covered by ez-context-menu in Safari

src/bundle/Resources/public/scss/fieldType/edit/_base-preview.scss, src/bundle/Resources/public/scss/fieldType/edit/_ezauthor.scss, src/bundle/Resources/public/scss/fieldType/edit/_ezgmaplocation.scss, src/bundle/Resources/public/scss/fieldType/edit/_ezurl.scss, src/bundle/Resources/public/scss/fieldType/edit/_ezuser.scss
| Tickets       | [EZP-29562](https://jira.ez.no/browse/EZP-29562)
- Harmonized background color contrast of multiple input fields when grouped in Content section Create & Edit views. It's hard to distinguish for users, specially in monitors with low screen resolution, when there are several input fields grouped. Changed to color `$ez-ground-base-medium` (= #ededed).
=> EZP-29562: Harmonized background color contrast of multiple input fields when grouped in Edit view

src/bundle/Resources/views/admin/base.html.twig, src/bundle/Resources/views/admin/content_type_group/base.html.twig, src/bundle/Resources/views/admin/language/base.html.twig, src/bundle/Resources/views/admin/object_state/base.html.twig, src/bundle/Resources/views/admin/object_state_group/base.html.twig, src/bundle/Resources/views/admin/policy/base.html.twig, src/bundle/Resources/views/admin/role/base.html.twig, src/bundle/Resources/views/admin/role_assignment/base.html.twig, src/bundle/Resources/views/admin/section/base.html.twig, src/bundle/Resources/views/link_manager/edit.html.twig
| Tickets       | [EZP-29553](https://jira.ez.no/browse/EZP-29553)
- Harmonized breadcrumbs positioning across the UI. Some view showed breadcrumbs moved down, specially Edit views in Admin Panel section. Added changes so that all `ez-header` have now same format (unless they contain tabs)
=> EZP:29553 Harmonized breadcrumbs positioning across the UI

src/bundle/Resources/views/admin/content_type/field_types.html.twig
| Tickets       | [EZP-29290](https://jira.ez.no/browse/EZP-29290)
JIRA excerpt:
>Currently, in v2 there is no preconfigured author section (fields filled in with the name and e-mail of the currently logged user). It would be more convenient for the editors to have this fields set automatically while creating a new content. Also, prefilling section with the default data should be configurable at the Author FieldType level.
**Depends on:**
- ezsystems/ezpublish-kernel#2392
- ezsystems/ezpublish-kernel#2417
- …
=> EZP-29290: As an Editor, I want to have preconfigured "Author" section while creating the content

src/bundle/Resources/public/scss/_buttons.scss, src/bundle/Resources/views/admin/bulk_delete_confirmation_modal.html.twig, src/bundle/Resources/views/admin/trash/empty_trash_confirmation_modal.html.twig, src/bundle/Resources/views/bulk_delete_confirmation_modal.html.twig, src/bundle/Resources/views/content/modal_add_translation.html.twig, src/bundle/Resources/views/content/modal_location_trash.html.twig, src/bundle/Resources/views/content/modal_user_delete.html.twig, src/bundle/Resources/views/content/tab/url/modal_add_custom_url.html.twig
| Tickets       | [EZP-29572](https://jira.ez.no/browse/EZP-29572)
Harmonized modal footer buttons in Content section in order to get a consistent view of them across the UI. This work is aligned with buttons in Page Builder modals.
- Removed unnecessary padding (`btn--wide`);
- Added Bootstrap's `font-weight-bold` for the primary action button within the modal we want to highlight;
- Aligned footer buttons with `.modal-header` `.close` button.
=> EZP-29572: Harmonized modal footer buttons in Content section

src/bundle/Resources/views/content/tab/details.html.twig, src/bundle/Resources/views/content/tab/locations/panel_swap.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29576
I recommend drinking a coffee or two before committing one cell tables to any repository.
=> EZP-29576: Location Swap and Sort Order panels are using one cell <table> elements

src/bundle/Controller/AssetController.php, src/bundle/Resources/config/bazinga_js_translation.yml, src/bundle/Resources/config/routing.yml, src/bundle/Resources/config/services/controllers.yml, src/bundle/Resources/config/services/ui_config/common.yml, src/bundle/Resources/config/universal_discovery_widget.yml, src/bundle/Resources/config/views.yml, src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js, src/bundle/Resources/public/scss/_general.scss, src/bundle/Resources/public/scss/ezplatform.scss, src/bundle/Resources/public/scss/fieldType/edit/_base-preview.scss, src/bundle/Resources/public/scss/fieldType/edit/_ezimageasset.scss, src/bundle/Resources/public/scss/fieldType/preview/_ezimageasset.scss, src/bundle/Resources/translations/assets.en.xliff, src/bundle/Resources/translations/ezrepoforms_content.en.xliff, src/bundle/Resources/translations/fieldtypes_edit.en.xliff, src/bundle/Resources/translations/fieldtypes_preview.en.xliff, src/bundle/Resources/translations/universal_discovery_widget.en.xliff, src/bundle/Resources/views/content/form_fields.html.twig, src/bundle/Resources/views/fieldtypes/edit/binary_base.html.twig, src/bundle/Resources/views/fieldtypes/edit/ezimageasset.html.twig, src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig, src/bundle/Resources/views/fieldtypes/preview/ezimageasset.html.twig, src/lib/Form/Data/Asset/ImageAssetUploadData.php, src/lib/Form/Factory/FormFactory.php, src/lib/UI/Config/Provider/FieldType/ImageAsset/Mapping.php, src/lib/UniversalDiscovery/Event/Subscriber/ImageAssetDefaultLocationId.php
| Tickets       | https://jira.ez.no/browse/EZP-29104
| **Depends on** | https://github.com/ezsystems/repository-forms/pull/246, https://github.com/ezsystems/ezpublish-kernel/pull/2403
=> EZP-29104:  Implemented UI for ImageAsset Field Type

src/bundle/Resources/public/js/scripts/core/draggable.js, src/bundle/Resources/views/layout.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29606
There is nothing to test in this PR. This developer feature will be used in other PRs.
Prepare the HTML structure like this:
```html
<div class="items-container" data-placeholder="HTML template for placeholder"></div>
```
In your JS code follow the convention:
```javascript
const draggable = new global.eZ.core.Draggable({
itemsContainer: HTMLElement of .items-container,
selectorItem: String,
selectorPlaceholder: String,
});
```
- `itemsContainer` - a reference to DOM node containing a …
=> EZP-29606: As a developer I want to have a generic interface for drag and drop interactions

src/lib/Form/Factory/FormFactory.php
| Tickets       |  -
It seems that I accidentially removed `\EzSystems\EzPlatformAdmin Ui\Form\Factory\FormFactory::updateUserSetting` method during rebase of #580. This PR recovers it.
=> Recovered \EzSystems\EzPlatformAdminUi\Form\Factory\FormFactory::updateUserSetting method

src/bundle/Resources/public/js/scripts/admin.prevent.click.js, src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29614
This behavior is caused by firing an `onbeforeunload` event when the file is downloading.
=> EZP-29614: Application does not respond after downloading a file.

src/bundle/Resources/public/scss/_notifications-menu.scss, src/bundle/Resources/public/scss/_user-menu.scss
| Tickets       | [EZP-29174](https://jira.ez.no/browse/EZP-29174)
Most interesting aspects:
- Update `ez-user-menu__item` based on consistency for hover states and box-shadow too. 
(Reviewed also `ez-user-menu__name` font-weight).
=> EZP-29174: Updated ez-user-menu styling

src/bundle/Resources/views/layout.html.twig
| Tickets       | https://jira.ez.no/browse/EZEE-2323
MS Edge does not support spread in object literals natively yet.
Browser compatibility: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Browser_compatibility
=> EZEE-2323: Fixes js error in MS Edge

src/bundle/Resources/views/user/settings/update.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29636
=> EZP-29636: Additional Update button visible on User Setting update screen

src/bundle/Resources/public/scss/_main-nav.scss
| Tickets       | [EZP-29651](https://jira.ez.no/browse/EZP-29651)
- Remove property border-bottom from `.ez-main-sub-nav` in order to align design to Page Builder bars (`.ez-page-info-bar` and `c-timeline`)
- Connected to PRs:  [EZEE-2315](https://github.com/ezsystems/ezplatform-page-builder/pull/170) and [EZEE-2317](https://github.com/ezsystems/ezplatform-page-builder/pull/171)
=> EZP-29651: Reviewed ez-main-sub-nav styling

src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js, src/bundle/Resources/views/fieldtypes/edit/ezimageasset.html.twig, src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig, src/bundle/Resources/views/fieldtypes/preview/ezimageasset.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29508
| Depends on  | https://github.com/ezsystems/ezpublish-kernel/pull/2451, https://github.com/ezsystems/repository-forms/pull/254
Impl. possibility to define Alternative Text for Image Asset.
=> EZP-29508: As an editor I want to manage ALT field with an image asset field type

src/bundle/Resources/public/scss/_content-edit.scss, src/bundle/Resources/public/scss/fieldType/edit/_ezobjectrelationlist.scss, src/bundle/Resources/views/content/content_edit/content_create.html.twig, src/bundle/Resources/views/content/content_edit/content_edit.html.twig, src/bundle/Resources/views/content/content_edit/user_create.html.twig, src/bundle/Resources/views/content/content_edit/user_edit.html.twig
| Tickets       | [EZP-29599](https://jira.ez.no/browse/EZP-29599)
- Harmonized spacing among field types in Edit view, so that this view has a balanced UI structure making it easier to scan information for users;
- Added extra off-set margin-bottom.
=> EZP-29599: Improved spacing among field types in Edit view

src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig
| Tickets       | [EZP-29652](https://jira.ez.no/browse/EZP-29652)
For now, in the admin, if you display the main view of a content in another language than the default one, it will display the correct link (with the filename in the correct language) but if you click on the download button, you will always get the content of the file in the language of the admin.
I hope that this fix could be convenient, I tried it on two of my projects and it fixed the wrong behaviour with no side effect so far and basic tests running fine. I …
=> EZP-29652 - Multilingual support for ezbinaryfile download in admin UI

src/bundle/Resources/views/content/widgets/content_create.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29615
Disables browser autocomplete in form resposible for creating new content (side menu).
=> EZP-29615: User is unable to redo the same step after using web browser back button

src/bundle/Resources/public/css/alloyeditor/alloyeditor-ez.css
| Tickets       | [EZP-29602](https://jira.ez.no/browse/EZP-29602)
Before:
After:
=> EZP-29602: Large images do not fit in the editor window

src/bundle/Resources/public/scss/_buttons.scss, src/bundle/Resources/public/scss/_content-type-selector.scss, src/bundle/Resources/public/scss/_filters.scss, src/bundle/Resources/public/scss/_icons.scss, src/bundle/Resources/public/scss/_modals.scss, src/bundle/Resources/views/admin/search/search.html.twig, src/bundle/Resources/views/admin/search/search_form.html.twig
| Tickets       | [EZP-29603](https://jira.ez.no/browse/EZP-29603)
- Adjusted offset margins to the rest of the UI views within the app;
- Added font-weight 700 to Search button and increase font-size of icons within buttons (styled according to approach used for buttons with icons in Edit view);
- Added a caret pointing up in the border-top when filters are displayed;
- Added font-weight for filter labels (700);
- Reviewed spacing and font-size for Content-type dropdown;
- Updated Custom range modal based on defined Ui standards for modals already implemented in the UI (center alignment & bolded font-weight for …
=> EZP-29603: Improved styling of Search and Search filters

src/bundle/Resources/public/scss/_card.scss, src/bundle/Resources/public/scss/_modals.scss, src/bundle/Resources/views/admin/content_type/delete_confirmation_modal.html.twig, src/bundle/Resources/views/admin/content_type/edit.html.twig
| Tickets       | [EZP-29662](https://jira.ez.no/browse/EZP-29662)
Most important aspects: 
When in Admin section > specific Content Type > Editing view and sending a field type to the Trash, .ez-card__header component interacts at the same layer level as the modal;
- Reviewed `z-index` conflict;
- Added `$ez-black` as color for `.ez-modal-body__explanation`;
- Added bold font-weight to Delete button.
=> EZP-29662: Reviewed Send to Trash modal in Content Type Editing view

src/bundle/Resources/views/fieldtypes/edit/ezdate.html.twig, src/bundle/Resources/views/fieldtypes/edit/ezdatetime.html.twig, src/bundle/Resources/views/fieldtypes/edit/eztime.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29649
Add `hidden` attribute to fields that should not be visible.
=> EZP-29649: [Content Type Fields] Date and time hidden fields not hidden enough

src/bundle/Resources/translations/content_url.en.xliff, src/bundle/Resources/translations/ezrepoforms_content_type.en.xliff, src/bundle/Resources/translations/ezrepoforms_role.en.xliff, src/bundle/Resources/translations/search.en.xliff
This PR adds missing AdminUI translations related to several parts of the user interface.
=> [i18n] Added missing UI translations

src/bundle/Resources/public/scss/_labels.scss, src/bundle/Resources/public/scss/ezplatform.scss, src/bundle/Resources/views/admin/content_type/create.html.twig, src/bundle/Resources/views/admin/content_type/edit.html.twig, src/bundle/Resources/views/admin/content_type/field_types.html.twig, src/bundle/Resources/views/admin/content_type_group/create.html.twig, src/bundle/Resources/views/admin/content_type_group/edit.html.twig, src/bundle/Resources/views/admin/language/create.html.twig, src/bundle/Resources/views/admin/language/edit.html.twig, src/bundle/Resources/views/admin/object_state/add.html.twig, src/bundle/Resources/views/admin/object_state/edit.html.twig, src/bundle/Resources/views/admin/object_state_group/add.html.twig, src/bundle/Resources/views/admin/object_state_group/edit.html.twig, src/bundle/Resources/views/admin/role/add.html.twig, src/bundle/Resources/views/admin/role/edit.html.twig, src/bundle/Resources/views/admin/section/create.html.twig, src/bundle/Resources/views/admin/section/update.html.twig, src/bundle/Resources/views/link_manager/edit.html.twig, src/bundle/Resources/views/user-profile/change_user_password.html.twig, src/bundle/Resources/views/user-profile/form_fields.html.twig, src/bundle/Resources/views/user/settings/update.html.twig
| Tickets       | [EZP-29635](https://jira.ez.no/browse/EZP-29635)
**Most important aspects:**
- Harmonized form labels in Editing views by styling existing class labels when permitted or by adding a new specific class `ez-label`, as well as adding a specific class for the view, `ez-admin-edit`;
- **Need help for exceptional cases:**
-> Content type specific Edit view for field type `ezdatetime`: Year, Month, Day, Minute, Second;
-> Roles specific Edit view `limitation` group.
**Would need help _>**
-> Content type specific Edit view for …
=> EZP-29635: Styled labels in Admin Panel Edit views

src/bundle/Resources/config/services/ui_config/mappers.yml, src/lib/UI/Config/Mapper/FieldType/RichText/CustomTag.php, src/lib/UI/Config/Mapper/FieldType/RichText/CustomTag/CommonAttributeMapper.php
| Tickets       | [EZP-29674](https://jira.ez.no/browse/EZP-29674)
| **Target version** | **2.2**
JMS Translation extractor has to ignore dynamic labels that are translated by Custom Tags UI configuration mapper. Otherwise it will display the error described in the [JIRA issue](https://jira.ez.no/browse/EZP-29674).
The change also involves refactoring - moving responsibility of translating labels
to a separate method, so it's more readable. For 2.3 we could refactor this even further moving that responsibility to a custom translation …
=> EZP-29674: Translation extractor displays error when processing Tag/Style mappers

src/bundle/Resources/public/js/scripts/admin.picker.js
| Tickets       | https://jira.ez.no/browse/EZP-29687
In ezPicker field after clicking "clear" button (X) date in flatpickr instance is not cleared.
For QA: when it comes to fields `date`, `datetime`, `time` from CI edit, these are other fields. You can find eZPicker in e.g. Scheduler tab in Page Builder.
=> EZP-29687: eZ(date)Picker field clear button (X) does not clear date in flatpickr instance

src/bundle/Resources/views/link_manager/list.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29683
=> EZP-29683: Status in link manager is misaligned

src/bundle/Resources/views/dashboard/dashboard.html.twig, src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig
| Tickets       | https://jira.ez.no/browse/EZEE-2487
As there was problem with displaying modal included on different tab (prolly some display none issue) and including it second time made it duplicated I have moved this modal from single tab into dashboard.
=> EZEE-2487: Version conflict pop-up missing for My scheduled on Dashboard

src/bundle/Resources/public/scss/fieldType/preview/_ezimageasset.scss, src/bundle/Resources/views/fieldtypes/preview/ezimageasset.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29653
=> EZP-29653: Image asset is not properly styled on Safari

src/bundle/Resources/public/scss/core/_custom.dropdown.scss, src/bundle/Resources/public/scss/fieldType/edit/_ezselection.scss
| Tickets       | https://jira.ez.no/browse/EZP-29650
Fixes 1. problem - pointer cursor.
2. problem was fixed in: https://github.com/ezsystems/ezplatform-admin-ui/pull/648 by the by of other task.
Previous PR to this task was closed: https://github.com/ezsystems/ezplatform-admin-ui/pull/644.
More info in JIRA.
=> EZP-29650: Fix Selection field (Content Type fields) arrow color

src/bundle/Resources/public/js/scripts/admin.location.add.custom_url.js, src/bundle/Resources/views/content/tab/urls.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29610
When the user can not add Custom URL modal is not rendered (it depends on `content/urltranslator` policy.
=> EZP-29610: 'Create new URL alias' modal is rendered when user select URL tab

src/lib/Menu/ContentEditRightSidebarBuilder.php
| Tickets       |  https://jira.ez.no/browse/EZP-29510
Depends on https://github.com/ezsystems/ezpublish-kernel/pull/2414
=> EZP-29510: Editing a draft should be able to cancel if user has version remove permission

src/bundle/Resources/public/scss/_filters.scss, src/bundle/Resources/views/admin/search/search_form.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29080
Firefox: 
Safari:
Chrome:
=> EZP-29080: Select data range - date selectors are too close

src/bundle/Resources/public/scss/_forms.scss
| Tickets       | https://jira.ez.no/browse/EZP-29639
Note for QA: This code was introduced to fix this issue: https://jira.ez.no/browse/EZP-28641
From my briefly testing is not occur, but please check it.
=> EZP-29639: Labels for checkboxes and radioboxes are misaligned with inputs

src/bundle/Resources/public/scss/_filters.scss
| Tickets       | https://jira.ez.no/browse/EZP-29676
Chrome:
Edge:
Firefox
=> EZP-29676: Arrow pointing into Filters is too thin in Edge

src/bundle/Resources/public/js/scripts/core/custom.dropdown.js
| Tickets       | https://jira.ez.no/browse/EZP-29707
=> EZP-29707: Cannot read property remove of null error from Selection

src/lib/Behat/PageElement/DateAndTimePopup.php, src/lib/Behat/PageElement/PlatformElementFactory.php
Inlined flatpickr doesn't have the `open` class, but has `inline`. Required by https://github.com/ezsystems/date-based-publisher/pull/79
~~Contains TMP commit, please do not merge~~
=> [Behat] Adjust tests for inlined date picker

src/bundle/Resources/config/bazinga_js_translation.yml, src/bundle/Resources/public/js/scripts/admin.notifications.modal.js, src/bundle/Resources/translations/notifications.en.xliff
When a user has logged out a notification with information is show one time. When the user is logged back in and log out again information is shown again.
=> EZP-29700: Syntax error after logging out

src/lib/EventListener/RequestLocaleListener.php
| Tickets       | [EZP-29709](https://jira.ez.no/browse/EZP-29709)
The `RequestLocaleListener` is called too early. In case of request to `/_fos_user_context_hash` it tries to resolve SiteAccess from the request, but since this route is not SiteAccess aware it ends-up with an Exception thrown from: https://github.com/ezsystems/ezplatform-admin-ui/blob/master/src/lib/Specification/SiteAccess/IsAdmin.php#L39
The `FOS\HttpCacheBundle\EventListener\UserContextSubscriber::onKernelRequest()` should be called before, therefore I've decreased the …
=> EZP-29709: RequestLocaleListener tries to match SiteAccess on /_fos_user_context_hash

src/bundle/Resources/views/fieldtypes/edit/relation_base.html.twig, src/lib/UniversalDiscovery/Event/Subscriber/ObjectRelationAllowedContentTypes.php
| Tickets       | [EZP-29660](https://jira.ez.no/browse/EZP-29660)
Currentlym ezobjectrelationlist doesn't take CT's set as allowed via UI into account - only settings from `/src/bundle/Resources/config/universal_discovery_widget.yml` are visible.
=> EZP-29660: Ezobjectrelationlist ignores allowed content types when creating content via UDW

src/bundle/Resources/config/services/form_processors.yml, src/lib/RepositoryForms/Form/Processor/Content/UrlRedirectProcessor.php
| Tickets       | https://jira.ez.no/browse/EZP-29617
| Tests pass?   | yes (locally, depends on repository-forms)
This solves redirect problem, when published content do not match any siteaccess. 
Flow of redirect is changed - repository-forms redirects now to `_ezpublishLocation` route, and adminUI handles the redirect in terms of frontend / adminUI side.
https://github.com/ezsystems/repository-forms/pull/256
=> EZP-29617: No route found after adding new translation

src/bundle/Resources/public/js/scripts/sidebar/btn/location.edit.js
| Tickets       | https://jira.ez.no/browse/EZEE-2462
Enables passing onClose callback for location edit modal window.
Related with: https://github.com/ezsystems/ezplatform-page-builder/pull/234
=> EZEE-2462: Edit button still active after closing draft conflict modal window - enable passing onClose callback for location edit modal

src/lib/Behat/BusinessContext/ContentViewContext.php
| Tickets       | [EZP-29712](https://jira.ez.no/browse/EZP-29712)
Run nightly Behat tests on demo metarepos
There is one ambiguous step in admin-ui contexts. Did not appear earlier because flex-workflow tests does not need `AdministrationContext` hence this context was not a part of the FWF profile.
```
And I start editing the content
Ambiguous match of "I start editing the content":
to `I start editing the content` from EzSystems\EzPlatformAdminUi\Behat\BusinessContext\ContentViewContext::startEditingContent()
to `I start editing :itemType …
```
=> EZP-29712 Run nightly Behat tests on demo metarepos

src/lib/Tests/UI/Config/Mapper/FieldType/RichText/CustomTagTest.php, src/lib/UI/Config/Mapper/FieldType/RichText/CustomTag.php
| Tickets       | [EZP-29731](https://jira.ez.no/browse/EZP-29731)
=> EZP-29731: Fixed missing icon in RichText Custom Tags UI config

.travis.yml, composer.json
| Tickets       | https://jira.ez.no/browse/EZP-29711
Enabling Symfony debug allows us to take better screenshots, showing the exception that happened. It won't have a performance impact.
=> EZP-29711: Enable symfony debug

src/lib/Behat/PageElement/Notification.php
Differentiation between notification alert and content item preview alert. ([Example](https://res.cloudinary.com/ezplatformtravis/image/upload/v1539952736/screenshots/vendor_ezsystems_ezplatform-form-builder_features_formcontentitemadministration_feature_47_s7dic4.png))
=> EZEE-1674 Create a spike of Form Builder scenarios for v2

src/bundle/Controller/SectionController.php, src/bundle/Resources/views/admin/section/assigned_content.html.twig, src/bundle/Resources/views/admin/section/list.html.twig, src/lib/UniversalDiscovery/Event/Subscriber/SectionAssign.php, src/lib/Util/PermissionUtil.php
| Tickets       | https://jira.ez.no/browse/EZP-29734
=> EZP-29734: As an Administrator I want to add Content Type limitation for Section/Assign policy

src/bundle/Controller/ContentOnTheFlyController.php, src/bundle/Resources/views/content/content_edit/content_create.html.twig, src/bundle/Resources/views/content/content_on_the_fly/content_create_on_the_fly.html.twig
| Tickets       | Required by https://jira.ez.no/browse/EZEE-2234
We need language as a context parameter for components in Content Create.
=> EZEE-2234: Extend context of Create component to pass language

src/lib/Behat/PageElement/DateAndTimePopup.php
Currently the tests are failing because of how difference between two dates (in months) is calculated.
Current logic (this can be tested in interactive shell):
```
$dateToSet = new DateTime('2019-12-30 00:00:00.000000');
$currentDate = new DateTime('2019-11-23 10:41:31.000000');
$dateToDiff = DateTime::createFromFormat('Y-m', $dateToSet->format('Y-m')); // 2019-12-31 10:43:37.000000
$currentDateToDiff = DateTime::createFromFormat('Y-m', $currentDate->format('Y-m')); //2019-12-01 10:43:40.000000
$interval = …
```
=> Fix Behat DateTime tests

src/bundle/Controller/ContentViewController.php, src/bundle/Controller/LocationController.php, src/bundle/Resources/config/routing.yml, src/bundle/Resources/public/js/scripts/admin.trash.container.js, src/bundle/Resources/public/js/scripts/button.state.checkbox.toggle.js, src/bundle/Resources/public/scss/_modals.scss, src/bundle/Resources/translations/forms.en.xliff, src/bundle/Resources/translations/messages.en.xliff, src/bundle/Resources/translations/validators.en.xliff, src/bundle/Resources/views/content/locationview.html.twig, src/bundle/Resources/views/content/modal_location_trash_container.html.twig, src/lib/Form/Data/Location/LocationTrashContainerData.php, src/lib/Form/Factory/FormFactory.php, src/lib/Form/Type/Location/LocationTrashContainerType.php, src/lib/Menu/ContentRightSidebarBuilder.php, src/lib/Specification/Location/HasChildren.php, src/lib/Validator/Constraints/LocationHasChildren.php, src/lib/Validator/Constraints/LocationHasChildrenValidator.php
| Tickets       | https://jira.ez.no/browse/EZP-29089
This checks if location is non-empty container and if it is displays additional info modal. If content have asset fieldtype additional modals are displayed after first one.
=> EZP-29089: Usability bug when deleting containers

src/bundle/Resources/views/admin/content_draft/list.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29769
=> EZP-29769: Added discovery bar to the Drafts interface

src/bundle/Resources/views/parts/menu/sidebar_base.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29813
Adding menu item in an event listener:
```php
$root->addChild(
'custom_menu_item',
[
'extras' => [
'template' => 'MyBundle::menu_item_template.html.twig',
'template_parameters' => [
'custom_parameter' => 'value',
],
],
]
);
```
Later in `MyBundle::menu_item_template.html.twig` variable `custom_parameter` is available:
```yaml
{# MyBundle::menu_item_template.html.twig #}
{{ dump(custom_parameter) }}
```
=> EZP-29813: Pass custom parameters to menu item templates in right sidebar

features/ContentCreation.feature
| Tickets       | Related to [EZP-28009](https://jira.ez.no/browse/EZP-28009)
| Related PRs | <ul><li>ezsystems/ezplatform-richtext#11</li><li>ezsystems/ezplatform#337</li></ul>
This PR tags ContentCreation Behat tests Feature with `@richtext` tag as these tests are mostly based on RichText Field type.
This distinction is needed to speed-up running Behat tests for https://github.com/ezsystems/ezplatform-richtext package (see ezsystems/ezplatform-richtext#11). Without that, entire test suite requires [~ 48 minutes to …
=> [Behat] EZP-28009: Tagged ContentCreation Feature with richtext tag

features/Roles.feature, src/bundle/Resources/config/services/translation.yml, src/bundle/Resources/translations/ezrepoforms_role.en.xliff, src/bundle/Resources/translations/forms.en.xliff, src/bundle/Resources/views/admin/policy/list.html.twig, src/bundle/Resources/views/content/tab/policies/table.html.twig, src/lib/Form/Type/Policy/PolicyChoiceType.php, src/lib/Translation/Extractor/PolicyTranslationExtractor.php
| Tickets       | https://jira.ez.no/browse/EZP-29748
See [https://github.com/ezsystems/repository-forms/pull/259](https://github.com/ezsystems/repository-forms/pull/259) [https://github.com/ezsystems/ezplatform/pull/336](https://github.com/ezsystems/ezplatform/pull/336)
=> EZP-29748: Replacing the outdated verbiage of eZ Publish from eZ Platform when adding a Policy

src/bundle/Resources/config/services/ui_config/common.yml
| Tickets       | https://jira.ez.no/browse/EZP-29819
This fixes an issue where the dynamic parameters in arguments are injected to the config provider services in the `default` scope instead of `admin` scope, resulting in admin content edit interface without any styles.
I have not been able to deduce why this is happening, though, since it seems that clean eZ Platform install works fine. It maybe a combination of some other config, but anyway, setting these services to lazy helps.
=> [EZP-29819] Set config providers which use dynamic settings to lazy

features/ContentTypeFields.feature, src/lib/Behat/Helper/UtilityContext.php, src/lib/Behat/PageElement/DateAndTimePopup.php, src/lib/Behat/PageElement/ElementFactory.php, src/lib/Behat/PageElement/PlatformElementFactory.php, src/lib/Behat/PageObject/FolderPreview.php, src/lib/Behat/PageObject/PageObjectFactory.php, src/lib/Behat/PageObject/PlatformPageObjectFactory.php, src/lib/Behat/PageObject/PreviewPage.php, src/lib/Behat/lib/drag-mock.js
| Tickets       | https://jira.ez.no/browse/EZEE-2306
This PR is required by https://github.com/ezsystems/ezplatform-page-builder/pull/254/files
What has been done:
- extract JS-based drag and drop so that it can be used outside of PageBuilderEditor (it was needed in Collection and Content Scheduler blocks).
- make debugging easier by adding more details to `ElementNotFoundException`
- add parent container to DateTimePicker - it's required for Pages with more than 1 DatePicker (Content Scheduler airtime)
- add Content Type Preview skeleton - …
=> EZEE-2306: Add new Page Builder tests

src/lib/Menu/Admin/ReorderMenuListener.php
| Tickets       | https://jira.ez.no/browse/EZP-29832
=> EZP-29832: Unable to use AdminUI without admin rights

src/bundle/Controller/SearchController.php, src/bundle/Resources/config/services/ui_config/common.yml, src/bundle/Resources/public/js/scripts/admin.search.filters.js, src/bundle/Resources/public/js/scripts/udw/select.location.js, src/bundle/Resources/public/scss/_content-type-selector.scss, src/bundle/Resources/public/scss/_filters.scss, src/bundle/Resources/translations/search.en.xliff, src/bundle/Resources/translations/universal_discovery_widget.en.xliff, src/bundle/Resources/views/admin/search/search.html.twig, src/bundle/Resources/views/admin/search/search_form.html.twig, src/bundle/Resources/views/form_fields.html.twig, src/bundle/Templating/Twig/PathStringExtension.php, src/lib/Form/Data/Search/SearchData.php, src/lib/Form/Type/Search/SearchType.php
| Tickets       | https://jira.ez.no/browse/EZP-29766
This PR only adds filtering by subtree and simple displaying selected path.
This PR also includes restyling of Search filters.
View should adapt to window width; 
e.g number of columns in "Content type" filters now changes accordingly to window width:
Arrow always point to the center of the filters button:
=> EZP-29766: As an editor, I want to filter the search using subtree parameter

composer.json, src/bundle/Controller/ContentViewController.php, src/bundle/Controller/LocationController.php, src/bundle/Controller/SectionController.php, src/bundle/Controller/TrashController.php, src/lib/EventListener/ContentTranslateViewFilterParametersListener.php, src/lib/Menu/ContentCreateRightSidebarBuilder.php, src/lib/Specification/Location/IsContainer.php, src/lib/Tab/Dashboard/PagerContentToDataMapper.php, src/lib/Tab/LocationView/RelationsTab.php, src/lib/Tests/Validator/Constraint/LocationIsContainerValidatorTest.php, src/lib/UI/Config/Provider/User.php, src/lib/UI/Dataset/ContentDraftsDataset.php, src/lib/UI/Dataset/PoliciesDataset.php, src/lib/UI/Dataset/RelationsDataset.php, src/lib/UI/Dataset/RolesDataset.php, src/lib/UI/Module/Subitems/ContentViewParameterSupplier.php, src/lib/UI/Value/ValueFactory.php, src/lib/UniversalDiscovery/Event/Subscriber/SectionAssign.php, src/lib/Validator/Constraints/LocationIsContainerValidator.php, src/lib/View/Builder/ContentTranslateViewBuilder.php, src/lib/View/Filter/ContentTranslateViewFilter.php
| Tickets       | [EZP-29613](https://jira.ez.no/browse/EZP-29613)
Uses https://github.com/ezsystems/ezpublish-kernel/pull/2444, and `$location->getContent()`
(v2.2) in order avoid several repository loads not needed anymore.
Besides avoiding executing unneeded PHP code, here are some numbers for cache lookups on clean install, expect difference to be bigger when you have more data _(demo or project)_:
dashboard:
- 418 / 1240 (33.71%) _(master)_
- 468 / 1315 (35.59%) _(with kernel PR, only)_*
- 364 / 1043 (34.9%) _(with this PR + kernel PR)_
content structure:
- …
=> EZP-29613: As a developer I want access ContentType on Content to avoid re-loading it

src/bundle/Resources/views/content/content_edit/content_edit_base.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29825
| BC breaks?    | guess not
For a customer I need to override some specific content edit form fragment depending of the content type of the edited content. (The customer will go in 2.4 when released)
This could be achieved easily with the ViewProvider on the content_edit_view passing a form_templates param containing the specific form fragments I want to display ( see example in jira ticket )
For this I need my custom form templates to be after the standard form templates in the array used by the …
=> EZP-29825 Change form templates merge order to let me override form fragments

src/bundle/Resources/config/services/tabs.yml, src/bundle/Resources/views/content/tab/versions/tab.html.twig, src/bundle/Resources/views/content/tab/versions/table.html.twig, src/lib/Tab/AbstractEventDispatchingTab.php, src/lib/Tab/Event/TabEvents.php, src/lib/Tab/Event/TabViewRenderEvent.php, src/lib/Tab/EventDispatchingAbstractTab.php, src/lib/Tab/LocationView/ContentTab.php, src/lib/Tab/LocationView/DetailsTab.php, src/lib/Tab/LocationView/LocationsTab.php, src/lib/Tab/LocationView/PoliciesTab.php, src/lib/Tab/LocationView/RelationsTab.php, src/lib/Tab/LocationView/RolesTab.php, src/lib/Tab/LocationView/TranslationsTab.php, src/lib/Tab/LocationView/UrlsTab.php, src/lib/Tab/LocationView/VersionsTab.php
| Tickets       | https://jira.ez.no/browse/EZP-29848
1. Introduced new abstract class `EventDispatchingAbstractTab` which dispatches `TabEvents::ON_RENDER` event before rendering tab. This gives a flexibility of changing template and accessing parameters to modify them.
2. I've added some useful twig blocks to Versions tab allowing to add custom columns and tables from other bundles. It's being used by upcoming Workflow bundle.
=> EZP-29848: Make existing AdminUI tabs extendable by allowing template path and parameters change

src/bundle/Controller/ContentViewController.php, src/bundle/Resources/public/js/scripts/admin.location.view.js, src/bundle/Resources/views/content/locationview.html.twig, src/lib/UI/Module/Subitems/ContentViewParameterSupplier.php
| Tickets       | [https://jira.ez.no/browse/EZP-29744](https://jira.ez.no/browse/EZP-29744)
Requires: [https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/116](https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/116)
=> EZP-29744: Implement permissions for Content/Create in Sub-items table

src/bundle/Resources/public/js/scripts/admin.trash.list.js, src/bundle/Resources/public/js/scripts/button.state.radio.toggle.js, src/bundle/Resources/public/js/scripts/button.state.toggle.js
| Tickets       | https://jira.ez.no/browse/EZP-29862
After using "back button" in a browser, browser sets inputs values to values entered by a user before. 
Thus, we cannot assume that all checkboxes/radios are unchecked at the beginning, therefore we need to check at the start their values and set disabled state accordingly.
**For QA**: fix will affect all tables with checkboxes and Trash buttons + it will affect trash modal for content item with Immage Asset field.
=> EZP-29862: Trash button is disabled after using browser back button

src/lib/Behat/PageObject/DashboardPage.php
Adjusting the tests for the Review Queue - when it's present then it's the first card.
AdminUI tests should pass in https://github.com/ezsystems/ezplatform-page-builder/pull/273
=> Fix Dashboard "Me" section selector

src/lib/Behat/PageElement/Pagination.php
| Tickets       | http://jira.ez.no/browse/EZP-29714
Current ezplatform-ee-demo master branch build is failing, it hangs on `Changes can be discarded while creating Content Type` test, on `And there's no "Test Content Type" on "Content" "Content Type Group" list`. This is caused by incorrectly detecting that the Next button is disabled, sending the tests into an infinite loop 😓 This change fixes the issue.
Build for this PR: https://github.com/ezsystems/ezplatform-page-builder/pull/271 should be green (it has this PR added as a dependency: https://github.com/mnocon/ezplatform-ee-demo/commit/d03c88b23c5f8dfb3e19c0d4980c82 …
=> EZP-29714: Fix failing to detect disabled next button

src/bundle/Resources/public/js/scripts/admin.trash.list.js, src/bundle/Resources/public/js/scripts/button.state.radio.toggle.js, src/bundle/Resources/public/js/scripts/button.state.toggle.js
| Tickets       | https://jira.ez.no/browse/EZP-29889
In this fix: https://github.com/ezsystems/ezplatform-admin-ui/pull/739 I added functions executions, which set _disabled_ status of buttons just after page has been loaded. Previous code assumed that buttons are always present, but in case of Trash, when there are no items, there are no buttons:
it seems that the problem does not exist in other places because buttons are always present, e.g. in Bookmarks or always at least one item is present or table is not displayed when there are no …
=> EZP-29889: Cannot set property 'disabled' of null error in console in Trash

src/bundle/Tests/ParamConverter/LanguageParamConverterTest.php, src/lib/Tests/Form/DataTransformer/LocationsTransformerTest.php
* Fixed `\EzSystems\EzPlatformAdminUi\Tests\Form\DataTransformer\LocationsTransformerTest::testReverseTransformWithIds` 
* Added missing cases in `\EzSystems\EzPlatformAdminUiBundle\Tests\ParamConverter\LanguageParamConverterTest`
=> Fixed broken Unit tests

src/lib/Specification/ContentType/ContentTypeIsUser.php
| Tickets       | https://jira.ez.no/browse/EZP-29871
IMHO we can assume that if a content type contains `ezuser` field then it is "User" content type (and skip adding it to YAML configuration).
=> EZP-29871: Error 500 after creating Content Item based on Content Type with ezuser

src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
| Tickets       | https://jira.ez.no/browse/EZP-29897
=> EZP-29897: Workflow state panel becomes unusable in the Content Edit, when its container is displayed below the fold

src/lib/Specification/ContentType/ContentTypeIsUser.php, src/lib/Tests/Specification/ContentType/ContentTypeIsUserTest.php
Added unit tests for `\EzSystems\EzPlatformAdminUi\Specification\ContentTypeIsUser` and fixed incorrect arguments of `InvalidArgumentException` (first argument should be string)
=> Unit tests for Specification\ContentTypeIsUser

src/lib/Behat/PageElement/Fields/Date.php, src/lib/EventListener/RequestLocaleListener.php
| Tickets       | https://jira.ez.no/browse/EZP-29902
=> EZP-29902: Admin UI - Locale is not correctly set

src/bundle/Resources/views/parts/menu/sidebar_base.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29921
1. Introduces new `icon_path` parameter in menu item extras to be used instead of existing `icon` parameter if menu items need custom svg icons.
2. `icon_class` was added for adding custom classes to `<svg></svg>` element.
=> EZP-29921: Add possibility to use icons with custom path in Sidebar menu

src/bundle/Resources/views/content/locationview.html.twig, src/bundle/Resources/views/content/tab/translations/tab.html.twig, src/bundle/Resources/views/layout.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29904
| Requires     | https://github.com/ezsystems/ezplatform-page-builder/pull/281
=> EZP-29904: Unable to select Base translation for a Content Item

src/bundle/Resources/config/services/menu.yml, src/lib/Menu/ContentRightSidebarBuilder.php
| Tickets       | https://jira.ez.no/browse/EZP-28413
Copying user as content skips `account_user` data (`externalData`). In result we end with invalid entity in database. As copying user should be handled by specific method in UserService instead of Content/Location Service - copying (and copySubtree) of users and users groups is now disabled in adminUI.
=> EZP-28413: Empty username field after copying a user

src/bundle/Resources/config/services/modules/subitems.yml, src/bundle/Resources/config/services/user_settings.yml, src/bundle/Resources/translations/user_settings.en.xliff, src/lib/UI/Config/Provider/Module/SubItemsList.php, src/lib/UI/Module/Subitems/ContentViewParameterSupplier.php, src/lib/UserSetting/Setting/SubitemsLimit.php
| Tickets       | https://jira.ez.no/browse/EZP-29935
This PR adds new User Setting in Admin panel to set number of elements displayed on subitems list. A design will be changed in another PR.
=> EZP-29935: Add Sub items limit value to User Preferences

src/bundle/Resources/public/js/scripts/admin.location.add.translation.js
| Tickets       | https://jira.ez.no/browse/EZP-29890
How problem worked under the hood:
1. user starts adding a new content translation (by clicking (+) button)
2. modal, where the user can select language and base translation, shows up
3. user selects language _A_ and base translation _B_
4. then user closes modal and changes pages
5. user goes back to the previous page using back button; 
because he used back button, browser re-fills previously filled forms including the form with translation language and base translation
5. user starts …
=> EZP-29890: Wrong translation form is opened after using browser back button

src/lib/View/Builder/ContentTranslateViewBuilder.php, src/lib/View/Filter/ContentTranslateViewFilter.php
| Tickets       | https://jira.ez.no/browse/EZP-29925
=> EZP-29925: Content Type Translate in Edit mode is not based on browser's settings

src/bundle/Controller/ContentViewController.php
| Tickets       | https://jira.ez.no/browse/EZP-29952
| Requires | ezsystems/ezpublish-kernel#2507
| Tests pass?   | no, required kernel change
This PR injects `UserLanguagePreferenceProvider` implemented in ezsystems/ezpublish-kernel#2507 into ContentViewController in order to translate field definition labels to user-preferred language in Content (Location) view mode.
=> EZP-29952: Injected user-preferred language into CT of Content View mode

src/bundle/Resources/public/js/scripts/admin.location.add.translation.js
| Tickets       | https://jira.ez.no/browse/EZEE-2652
=> EZEE-2652: Cannot add Landing page translation via action bar button

src/lib/Form/Type/ChoiceList/Loader/BaseChoiceLoader.php
Added missing getChoiceList method declaration in BaseChoiceLoader.
=> Missing getChoiceList method declaration in BaseChoiceLoader

src/bundle/Resources/views/layout.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29779
When the back button is used in Safari, the `onload` event isn't called and the whole UI freezes. This PR contains workaround which is just about removing `ez-prevent-click` class from the `<body>` element.
=> EZP-29779: [Safari] Nothing responds after using web browser back button

src/lib/Menu/ContentCreateRightSidebarBuilder.php
| Tickets       | [EZP-29833](https://jira.ez.no/browse/EZP-29833)
Fixes permission check for content creation when rights are limited some section.
=> EZP-29833 : Limiting "Content\Create" to Section disables "Publish" button

src/bundle/Resources/public/js/scripts/fieldType/ezdate.js, src/bundle/Resources/public/js/scripts/fieldType/ezdatetime.js
| Tickets       | https://jira.ez.no/browse/EZP-29783
Fix clearing of date/datetime in ezdate & ezdatetime. Clear should clear both input element and date selected in calendar view.
Most of the changes were caused by formatting files with Prettier + changes in IIFE parameters.
The Problem was fixed by changing:
```js
flatPickrInput.value = '';	                 
sourceInput.value = '';
```
to
```js
flatPickrInput._flatpickr.clear();
```
in both files.
=> ezdatetime displays selected date and timeon calendar after clearing the field

src/bundle/Resources/views/admin/content_type/edit.html.twig, src/bundle/Resources/views/admin/content_type/field_types.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29914
=> EZP-29914: When translating the Content Type disable 'Select item' button for Content Relation (Single and Multi)

src/bundle/DependencyInjection/Compiler/ComponentPass.php, src/bundle/DependencyInjection/Compiler/TabPass.php
| Tickets       | https://jira.ez.no/browse/EZP-29970 Also fixes #501
| Improvment     | yes
| BC breaks?    |  no
| Tests pass?   | ? (maybe)
| Branch   | 1.4
Avoids having to mess around with event listener, and fight `ezplatform-workflow`, allows to use priority for sorting.
On the nitpick side, ideally the PriorityTaggedServiceTrait should have had method giving plain id /tags structure back like `findTaggedServiceIds` does, to avoid the `getDefinition()` and `getTag()` call. But unless we try to contribute that...
=> EZP-29970: As a Developer I'd like to order components & tabs in Admin UI

src/bundle/Resources/config/services/ui_config/common.yml, src/lib/Specification/ContentIsUser.php, src/lib/UI/Config/Provider/ContentTypeNames.php, src/lib/UI/Config/Provider/ContentTypes.php, src/lib/UI/Config/Provider/Languages.php
| Tickets       | https://jira.ez.no/browse/EZP-29821
| Improvment     | yes
| Tests pass?   | ??
- Take advantage of `isUser[Group]()` API's added in 2.4
- Avoid loading language map twice
- Deprecate content type config to just use one
- Possible todo or followup: Find a way to share the data between the two, could be done on JS side too, once that is done ContentTypeNames can be removed
=> EZP-29821: Reduce API/SPI lookups in Admin UI

src/bundle/Controller/TrashController.php, src/lib/Tab/Dashboard/PagerContentToDataMapper.php, src/lib/UI/Value/ValueFactory.php
| Tickets       | https://jira.ez.no/browse/EZP-29967
This PR fixes several issues of missing Content Type translation in various tables / data grids found in the AdminUI.
=> EZP-29967: Content Type name is not translated in AdminUI tables

src/lib/Menu/MainMenuBuilder.php
| Tickets       | [https://jira.ez.no/browse/EZP-29200](https://jira.ez.no/browse/EZP-29200)
=> EZP-29200: Admin menu disappear when user is redirected from policy to limitations

src/bundle/Resources/public/scss/_card.scss, src/bundle/Resources/public/scss/_icons.scss, src/bundle/Resources/views/admin/content_type/create.html.twig, src/bundle/Resources/views/admin/content_type/edit.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29811
=> EZP-29811: Content field definitions is misaligned while creating Content Type

src/bundle/Resources/public/scss/_main-row.scss
| Tickets       | https://jira.ez.no/browse/EZP-30053
Fixes Dashboard header width.
=> EZP-30053: Dashboard header is not adjusted

src/bundle/Resources/public/scss/_forms.scss, src/bundle/Resources/translations/locationview.en.xliff, src/bundle/Resources/views/content/tab/details.html.twig, src/lib/Form/Type/ObjectState/ContentObjectStateUpdateType.php
| Tickets       | [EZP-30024](https://jira.ez.no/browse/EZP-30024) [EZP-30055](https://jira.ez.no/browse/EZP-30055)
Simplifies object states table
=> EZP-30024: Simplifies object states table

src/bundle/Resources/public/js/scripts/admin.location.content.tree.js, src/bundle/Resources/public/scss/_buttons.scss, src/bundle/Resources/public/scss/_icons.scss, src/bundle/Resources/public/scss/_view-content.scss, src/lib/Menu/LeftSidebarBuilder.php
| Tickets       | https://jira.ez.no/browse/EZP-30090
=> EZP-30090: As an editor I would like content tree panel staying opened until clicking on a Content Tree button again

src/bundle/Resources/public/scss/_labels.scss
| Tickets       | https://jira.ez.no/browse/EZP-30103
=> EZP-30103: Missing asterisks from obligatory fields in Admin menu

src/bundle/Resources/views/admin/content_type/create.html.twig, src/bundle/Resources/views/admin/content_type_group/create.html.twig, src/bundle/Resources/views/admin/language/create.html.twig, src/bundle/Resources/views/admin/object_state/add.html.twig, src/bundle/Resources/views/admin/object_state_group/add.html.twig, src/bundle/Resources/views/admin/policy/add.html.twig, src/bundle/Resources/views/admin/role/add.html.twig, src/bundle/Resources/views/admin/section/create.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-30109
=> EZP-30109: Add autofocus attribute to creation forms in the Admin section

src/bundle/Resources/public/js/scripts/admin.location.view.js, src/bundle/Resources/public/scss/_extra-actions.scss, src/bundle/Resources/public/scss/_instant-filter.scss, src/bundle/Resources/public/scss/_tables.scss, src/bundle/Resources/views/admin/bookmark/list.html.twig, src/bundle/Resources/views/admin/content_draft/list.html.twig, src/bundle/Resources/views/admin/content_type/edit.html.twig, src/bundle/Resources/views/admin/content_type/list.html.twig, src/bundle/Resources/views/admin/search/search.html.twig, src/bundle/Resources/views/admin/search/search_table_row.html.twig, src/bundle/Resources/views/admin/trash/list.html.twig, src/bundle/Resources/views/content/content_edit/content_create.html.twig, src/bundle/Resources/views/content/content_edit/content_edit.html.twig, src/bundle/Resources/views/content/content_edit/user_create.html.twig, src/bundle/Resources/views/content/content_edit/user_edit.html.twig, src/bundle/Resources/views/dashboard/tab/all_content.html.twig, src/bundle/Resources/views/dashboard/tab/all_media.html.twig, src/bundle/Resources/views/dashboard/tab/my_content.html.twig, src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig, src/bundle/Resources/views/dashboard/tab/my_media.html.twig, src/bundle/Resources/views/form_fields.html.twig, src/bundle/Resources/views/parts/page_title.html.twig, src/bundle/Resources/views/parts/tab/content_type.html.twig, src/lib/Tab/Dashboard/PagerContentToDataMapper.php, src/lib/UI/Config/Provider/ContentTypes.php, src/lib/UI/Dataset/ContentDraftsDataset.php
| Tickets       | https://jira.ez.no/browse/EZP-29999
UDW part in: https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/132
date-based-publisher: https://github.com/ezsystems/date-based-publisher/pull/89
Workflow: https://github.com/ezsystems/ezplatform-workflow/pull/46
=> EZP-29999: As an editor, I want to see custom icons for content types

src/bundle/DependencyInjection/Configuration/Parser/UserPreferences.php, src/bundle/EzPlatformAdminUiBundle.php, src/bundle/Resources/config/ezplatform_default_settings.yml, src/bundle/Resources/config/services/forms.yml, src/bundle/Resources/config/services/user_settings.yml, src/bundle/Resources/translations/user_settings.en.xliff, src/lib/EventListener/RequestLocaleListener.php, src/lib/Form/Type/ChoiceList/Loader/AvailableLocaleChoiceLoader.php, src/lib/Tests/EventListener/RequestLocaleListenerTest.php, src/lib/Tests/Form/Type/ChoiceList/Loader/AvailableLocaleChoiceLoaderTest.php, src/lib/UserSetting/Setting/Language.php
| Tickets       | https://jira.ez.no/browse/EZP-29961
[2.5] This PR adds new User Setting which is used to set the language of the Administration Panel. The default value for setting is gathered from browsers language settings. The list of available languages has available translations on top.
Depends on [https://github.com/ezsystems/ezpublish-kernel/pull/2516](https://github.com/ezsystems/ezpublish-kernel/pull/2516)
=> [2.5] EZP-29961: Add preferred language value to User Preferences

src/lib/UserSetting/Setting/Language.php
| Tickets       | [https://jira.ez.no/browse/EZP-30119](https://jira.ez.no/browse/EZP-30119)
=> EZP-30119: Fix database error on cache clear command when database is not configured

src/bundle/Resources/views/link_manager/edit.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-30124
=> EZP-30124: Right sidebar menu is broken when editing link in Link manager

src/bundle/Controller/Content/VersionDraftConflictController.php, src/bundle/Resources/public/js/scripts/button.content.edit.js, src/bundle/Resources/translations/content.en.xliff
| Tickets       | [https://jira.ez.no/browse/EZP-29410](https://jira.ez.no/browse/EZP-29410)
To perform a conflict check action content/versionread permission is needed. If the user has no policy, he will be informed in the notification.
=> EZP-29410: As an Editor I want to be informed that I can't edit CI because of missing policies.

src/bundle/Resources/public/scss/fieldType/edit/_ezselection.scss, src/bundle/Resources/public/scss/fieldType/preview/_ezselection.scss
| Tickets       | [EZP-30102](https://jira.ez.no/browse/EZP-30102)
=> EZP-30102: updated ezselection field type

.travis.yml
| Tickets       | http://jira.ez.no/browse/ezp-30097
Our current experience with the Varnish/Redis job shows that it does not have to be run every time a PR is issued (but I still believe that having this job is valuable). Removing it from here, is it's also run in ezplatform: https://github.com/ezsystems/ezplatform/blob/master/.travis.yml#L28 (meaning it gets run every night as part of the cron builds).
=> [Travis] Move Varnish/Redis jobs to nightly jobs

src/bundle/Controller/SearchController.php
| Tickets       | [EZP-30096](https://jira.ez.no/browse/EZP-30096)
As mentioned in the JIRA ticket, Solr scoring is not taken in the search results list order.
=> EZP-30096: Solr scoring is not taken into account in the backend search results list order

README.md
This PR provides a better README for the eZ Platform Admin UI Bundle.
At the time of creating it, the `1.2` is still partially maintained, hence targeting it (as it contains link to the bug tracker).
**TODO**:
=> [Doc] Created more detailed README.md

src/bundle/Controller/ContentTypeController.php, src/bundle/Resources/views/admin/content_type/field_types.html.twig, src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29990
Kernel:
https://github.com/ezsystems/ezpublish-kernel/pull/2532
Repository-forms:
https://github.com/ezsystems/repository-forms/pull/277
=> EZP-29990: As an Administrator I want to translate ezselection Field Definition options

src/bundle/Resources/translations/object_state.en.xliff, src/bundle/Resources/views/content/tab/details.html.twig, src/lib/Form/Type/ObjectState/ContentObjectStateUpdateType.php
| Tickets       | [EZP-30162](https://jira.ez.no/browse/EZP-30162)
Adds submit button to the form removed in EZP-30100
=> EZP-30162: Revert BC broken in EZP-30100

src/bundle/Resources/views/content/tab/details.html.twig
=> Removed extra space from the end of the 'tab.details.change_section' translation key

src/bundle/Resources/views/admin/content_type/field_types.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-30172
| **Depends on**| https://github.com/ezsystems/repository-forms/pull/279 
=> EZP-30172: Cannot edit Content Type with ezobjectrelation/ezobjectrelationlist with deleted starting location

src/bundle/Controller/Content/ContentTreeController.php, src/bundle/DependencyInjection/Configuration/Parser/Module/ContentTree.php, src/bundle/EzPlatformAdminUiBundle.php, src/bundle/Resources/config/ezplatform_default_settings.yml, src/bundle/Resources/config/routing_rest.yml, src/bundle/Resources/config/services.yml, src/bundle/Resources/config/services/controllers.yml, src/bundle/Resources/config/services/modules/content_tree.yml, src/bundle/Resources/config/services/rest.yml, src/lib/REST/Input/Parser/ContentTree/LoadSubtreeRequest.php, src/lib/REST/Input/Parser/ContentTree/LoadSubtreeRequestNode.php, src/lib/REST/Output/ValueObjectVisitor/ContentTree/Node.php, src/lib/REST/Output/ValueObjectVisitor/ContentTree/Root.php, src/lib/REST/Value/ContentTree/LoadSubtreeRequest.php, src/lib/REST/Value/ContentTree/LoadSubtreeRequestNode.php, src/lib/REST/Value/ContentTree/Node.php, src/lib/REST/Value/ContentTree/Root.php, src/lib/UI/Module/ContentTree/NodeFactory.php
| Tickets       | https://jira.ez.no/browse/EZP-30065
This PR adds backend part for Content Tree feature. Content Tree uses two REST (based on REST Server from `ezpublish-kernel`) endpoints:
- `ezplatform.location.tree.load_children` for consecutive loading of given location subitems
-  `ezplatform.location.tree.load_subtree` for loading larger subtrees in single request
My implementation uses `SearchService`  to possibly speed up serving responses and offload database.
Content Tree is configurable:
```yaml
ezpublish:
system:
admin_group: # …
```
=> EZP-30065: As an editor I would like content tree to use real data

src/bundle/Controller/LocationController.php
| Tickets       | [EZP-29539](https://jira.ez.no/browse/EZP-29539)
returns to the same page on error
=> EZP-29539 : Deleting object will remove all subtree items even when user does not have permission to delete them

src/lib/UI/Module/ContentTree/NodeFactory.php
| Tickets       | https://jira.ez.no/browse/EZP-30182
=> EZP-30182: ContentTree/loadSubitems action is not respecting offset value

src/bundle/Resources/views/fieldtypes/edit/ezobjectrelation.html.twig, src/bundle/Resources/views/fieldtypes/edit/ezobjectrelationlist.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-30181
| **Depends on**| https://github.com/ezsystems/repository-forms/pull/280
=> EZP-20181: Editor is not able to select any item in the ezobjectrelation/ezobjectrelationlist FTs if starting location is not accessible

src/bundle/Resources/public/scss/_view-content.scss
| Tickets       | https://jira.ez.no/browse/EZP-30192
=> EZP-30192: Content Tree panel is partially visible when toggled

composer.json
Currently builds are failing: https://travis-ci.org/ezsystems/ezplatform-admin-ui/builds/500215494
This is caused by incorrectly set branch alias for tmp_ci_branch - it should be equal to master alias.
=> Set correct branch alias

src/bundle/Resources/config/ezplatform_default_settings.yml
| Tickets       | https://jira.ez.no/browse/EZP-29104
Add missing config for adminUI views
=> EZP-29104: Fix user-bundle views

src/bundle/DependencyInjection/Configuration/Parser/Module/ContentTree.php, src/bundle/Resources/config/ezplatform_default_settings.yml, src/bundle/Resources/config/services/modules/content_tree.yml, src/bundle/Resources/views/content/locationview.html.twig, src/lib/UI/Config/Provider/Module/ContentTree.php, src/lib/UI/Module/ContentTree/NodeFactory.php
| Tickets       | https://jira.ez.no/browse/EZP-30185
=> EZP-30185: Expose ContentTree configuration to AdminUI

src/bundle/Resources/public/js/scripts/admin.location.content.tree.js, src/bundle/Resources/views/content/locationview.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-30187
=> Use pathString instead of locationId in ContentTree

src/bundle/DependencyInjection/Configuration/Parser/Module/ContentTree.php, src/bundle/Resources/config/ezplatform_default_settings.yml
| Tickets       | https://jira.ez.no/browse/EZP-30197
=> EZP-30197: Missing default value for content_tree_module.tree_root_location_id setting

src/bundle/Resources/encore/ez.js.config.js, src/bundle/Resources/public/js/scripts/admin.location.tooglecontentpreview.js, src/bundle/Resources/public/scss/_field-group.scss, src/bundle/Resources/translations/messages.en.xliff, src/bundle/Resources/views/content/content_view_fields.html.twig, src/bundle/Resources/views/content/tab/content.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-30184
This PR introduces a feature which allows editors to collapse/expand content preview. Default state is configurable via User Setting. 
Front-end implementation based on  https://getbootstrap.com/docs/4.1/components/collapse/ with some CSS tweaks.
=> EZP-30184: As an Editor I want to collapse/expand content preview

src/bundle/Resources/public/js/scripts/admin.location.content.tree.js
| Tickets       | https://jira.ez.no/browse/EZP-30205
=> EZP-30205: As an editor I would like content tree to hold separate state for different users

src/bundle/Resources/encore/ez.js.config.js, src/bundle/Resources/public/js/alloyeditor/src/base/ez-blocktextalign.js, src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-customtag-edit.js, src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-customtag-update.js, src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-customtag.js, src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-embedinline.js, src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-inlinecustomtag-edit.js, src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-inlinecustomtag-update.js, src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-inlinecustomtag.js, src/bundle/Resources/public/js/alloyeditor/src/plugins/ez-custom-tag.js, src/bundle/Resources/public/js/alloyeditor/src/plugins/ez-remove-block.js, src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-inline-custom-tag.js, src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-text.js, src/bundle/Resources/public/js/alloyeditor/src/toolbars/ez-add.js, src/bundle/Resources/public/js/alloyeditor/src/widgets/ez-custom-tag-base.js, src/bundle/Resources/public/js/scripts/fieldType/alloyeditor/custom.tags.js, src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js, src/bundle/Resources/public/scss/_custom-tag.scss, src/bundle/Resources/public/scss/fieldType/edit/_ezgmaplocation.scss, src/lib/UI/Config/Mapper/FieldType/RichText/CustomTag.php, webpack.config.js
| Tickets       | https://jira.ez.no/browse/EZP-29802
| Requires | https://github.com/ezsystems/ezplatform-richtext/pull/29
=> EZP-29802: Inline custom tags support

src/lib/Tests/UI/Config/Mapper/FieldType/RichText/CustomTagTest.php
Due to configuration change in #869 dataProvider should have been updated to return `is_inline` configuration parameter.
=> EZP-30220: CustomTagTest::testMapConfig fails in phpunit

src/bundle/Templating/Twig/UserPreferencesGlobalExtension.php
| Tickets       | https://jira.ez.no/browse/EZP-30224
| Requires       | https://github.com/ezsystems/ezplatform-user/pull/10
This PR improves `ez_user_settings` global to provide dynamic access to User Setting values. Previously it was required to manually put all needed user settings in the `UserPreferencesGlobalExtension`  but it was prone to errors as can be seen in https://github.com/ezsystems/ezplatform-admin-ui/commit/45058c29eb60489457ed32867f4bcd8ee03807c9
=> EZP-30224: Make `ez_user_settings` twig global load user settings dynamically

composer.json, src/bundle/Resources/public/js/scripts/admin.format.date.js, src/bundle/Resources/public/js/scripts/helpers/timezone.helper.js, src/bundle/Resources/views/admin/content_draft/list.html.twig, src/bundle/Resources/views/admin/content_type/list.html.twig, src/bundle/Resources/views/admin/search/search_table_row.html.twig, src/bundle/Resources/views/admin/systeminfo/composer.html.twig, src/bundle/Resources/views/content/content_edit/content_edit.html.twig, src/bundle/Resources/views/content/content_edit/user_edit.html.twig, src/bundle/Resources/views/content/tab/details.html.twig, src/bundle/Resources/views/content/tab/versions/table.html.twig, src/bundle/Resources/views/dashboard/tab/all_content.html.twig, src/bundle/Resources/views/dashboard/tab/all_media.html.twig, src/bundle/Resources/views/dashboard/tab/my_content.html.twig, src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig, src/bundle/Resources/views/dashboard/tab/my_media.html.twig, src/bundle/Resources/views/fieldtypes/edit/relation_base.html.twig, src/bundle/Resources/views/fieldtypes/preview/ezobjectrelationlist_row.html.twig, src/bundle/Resources/views/form_fields.html.twig, src/bundle/Resources/views/link_manager/list.html.twig, src/bundle/Resources/views/link_manager/view.html.twig, src/bundle/Resources/views/notifications/notification_row.html.twig, src/bundle/Resources/views/user/settings/update.html.twig, src/lib/Pagination/Pagerfanta/UserSettingsAdapter.php, src/lib/UI/Config/Provider/DateFormat.php
| Tickets       | [EZP-30099](https://jira.ez.no/browse/EZP-30099)
User settings / datetime format.
=> EZP-30099: Define preferred user date format

src/bundle/Resources/public/js/scripts/admin.location.content.tree.js
| Tickets       | https://jira.ez.no/browse/EZP-30223
=> EZP-30223: Collapse all button is not always displayed in Content Tree

src/bundle/Resources/public/scss/_general.scss, src/bundle/Resources/public/scss/_view-content.scss
| Tickets       | https://jira.ez.no/browse/EZP-30231
=> EZP-30231: When resizing Content Tree text is accidentally selected

src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
| Tickets       | https://jira.ez.no/browse/EZP-30239
=> EZP-30239: Characters counter is activated only after clicking on RTE in edit mode

src/lib/Tab/LocationView/LocationsTab.php
| Tickets       | https://jira.ez.no/browse/EZP-30235
This fix implies that if a user will choose Location to which has no access for, red notification will be shown with information about missing permission.
=> EZP-30235: Editor can't add location if content/create limitations on ContentType of Parent are set

src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
| Tickets       | https://jira.ez.no/browse/EZP-30242
Output from the Editor isn't cleaned from zero-width characters which are treated like regular ones and corrupt the counter.
=> EZP-30242: Characters counter does not work properly with embed inline

src/lib/UI/Module/ContentTree/NodeFactory.php
| Tickets       | https://jira.ez.no/browse/EZP-30258
Fixing my huge programmer mistake...
=> EZP-30258: [Content tree] After reloading tree is partially collapsed

src/bundle/Controller/User/UserSettingsController.php, src/bundle/Resources/config/views.yml, src/bundle/Resources/encore/ez.js.config.js, src/bundle/Resources/public/js/scripts/admin.settings.datetimeformat.update.js, src/bundle/Resources/translations/user_settings.en.xliff, src/bundle/Resources/views/user/settings/update_datetime_format.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-30251
| **Depends on**|https://github.com/ezsystems/ezplatform-user/pull/21
Added missing preview for date/time format.
=> EZP-30251: Display the rendering of time & date when editing the Short/Long Date & Time format

src/bundle/Resources/public/js/scripts/admin.contenttype.selection.js, src/bundle/Resources/views/admin/content_type/field_types.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-30164
Instead of counting options, which creates problem with overlapping ids when prior to add option is removed, we use `id` extracted from `name` from last input.
=> EZP-30164: After removing option from ezselection it it not possible to add more options

src/bundle/Resources/public/js/scripts/fieldType/ezdate.js
| Tickets       | [EZP-29279](https://jira.ez.no/browse/EZP-29279)
Currently the value for Date Field Type displayed in the backoffice (in edit mode) is affected by the browser's timezone, meaning that if the browser has timezone below (west of) UTC, then the previous day is displayed.
Value stored in the database is always midnight in UTC.
Javascript automatically uses the browser's timezone when handling Date objects, so in this PR I fix the issue by manually adding the offset before passing the Date object to flatpickr library.
Similar to …
=> EZP-29279: Fix value displayed by the Date Field Type being affected by browser time zone

composer.json, src/bundle/Controller/ContentController.php, src/lib/Form/Data/Content/Translation/MainTranslationUpdateData.php, src/lib/Form/DataMapper/MainTranslationUpdateMapper.php, src/lib/Form/DataTransformer/ContentTransformer.php, src/lib/Form/Type/Content/ContentType.php, src/lib/Form/Type/Content/Translation/MainTranslationUpdateType.php, src/lib/Tab/LocationView/TranslationsTab.php
| Tickets       | https://jira.ez.no/browse/EZP-30107
| BC breaks?    | no (as this was not released yet)
Following changes in https://github.com/ezsystems/ezpublish-kernel/pull/2563 were needed.
=> EZP-30107: Name of Content Item is not updated after changing the main language

src/bundle/Resources/public/js/alloyeditor/src/widgets/ez-embed-base.js
| Tickets       | https://jira.ez.no/browse/EZP-30179
=> EZP-30179: Anchor to image not displayed when returning to editor

src/bundle/Resources/public/js/scripts/fieldType/ezauthor.js, src/bundle/Resources/views/fieldtypes/edit/ezauthor.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-30307
=> EZP-30307: After removing option from ezauthor it is not possible to add more

src/lib/RepositoryForms/Data/ContentTranslationData.php, src/lib/RepositoryForms/Data/Mapper/ContentTranslationMapper.php
| Tickets       | [EZP-30297](https://jira.ez.no/browse/EZP-30297)
[https://github.com/ezsystems/repository-forms/pull/282](https://github.com/ezsystems/repository-forms/pull/282)
=> EZP-30297: Error when I try to add a translation for a user object

features/ContentCreation.feature, src/lib/Behat/BusinessContext/NavigationContext.php, src/lib/Behat/BusinessContext/TrashContext.php, src/lib/Behat/Helper/Hooks.php, src/lib/Behat/PageElement/LeftMenu.php
After https://jira.ez.no/browse/EZEE-2718 the behaviour after Trashing a content item has changed:
Before:
Trashing a Content Item that has a Landing Page as a parent redirects to the Parent in Content View
After:
Trashing a Content Item that has a Landing Page as a parent redirects to the Parent:
- ezplatform: in Content View
- ezplatform-ee: in Page Builder
This is a bit tricky, as we don't have a mechanism right now to deal with logic like this.
Possible solutions:
1) the proposed one - adding an IF based on environment
I'm not a fan of this, but it works - we need to think of a better approach for future uses.
2) Defining the same step definition in two Contexts and specifying the correct one in behat_suites.yml
I've decided against at as it does not work for use cases like "I want to …
=> EZEE-2718: Adjust tests for redirects

src/bundle/Resources/public/css/alloyeditor/alloyeditor-ez.css
| Tickets       | https://jira.ez.no/browse/EZEE-2716
=> EZEE-2716: Richtext block: tooltip for links can render in way that part of it won't be visible

src/bundle/Resources/config/services/siteaccess.yml, src/lib/Siteaccess/AbstractSiteaccessPreviewVoter.php, src/lib/Siteaccess/AdminSiteaccessPreviewVoter.php, src/lib/Siteaccess/SiteaccessPreviewVoterContext.php, src/lib/Siteaccess/SiteaccessPreviewVoterInterface.php, src/lib/Siteaccess/SiteaccessResolver.php
| Tickets       | https://jira.ez.no/browse/EZEE-2533
[https://github.com/ezsystems/ezplatform-form-builder/pull/143](https://github.com/ezsystems/ezplatform-form-builder/pull/143)
=> EZEE-2533: Error HTTP 400 trying to preview Form during creation

src/bundle/Resources/public/js/scripts/fieldType/ezdatetime.js, src/bundle/Resources/public/js/scripts/helpers/timezone.helper.js, src/lib/Behat/PageElement/DateAndTimePopup.php
| Tickets       | https://jira.ez.no/browse/EZEE-2481, https://jira.ez.no/browse/EZEE-2480
=> EZEE-2481: Time picker bases on system time ignoring time zone in user settings

src/bundle/Resources/public/js/alloyeditor/src/plugins/ez-custom-tag.js, src/bundle/Resources/public/js/alloyeditor/src/widgets/ez-custom-tag-base.js
| Tickets       | https://jira.ez.no/browse/EZP-30285
=> EZP-30285: Focus is set to inline custom tag toolbar in edit mode

features/ContentCreation.feature
This should fix the failure from: https://travis-ci.com/ezsystems/ezplatform-page-builder/jobs/186035384
```
When I click on the edit action bar button "Edit"                                 # EzSystems\EzPlatformAdminUi\Behat\BusinessContext\RightMenuContext::clickEditActionBar()
And I click on the edit action bar button "Preview"                               # EzSystems\EzPlatformAdminUi\Behat\BusinessContext\RightMenuContext::clickEditActionBar()
WebDriver\Exception\StaleElementReference: stale element reference: element is not attached to the page document
```
I guess we're trying to click the "Preview" a bit too fast, added waiting that the Content Edit page is properly loaded.
=> Wait after clicking Edit

src/bundle/Resources/translations/locationview.en.xliff, src/bundle/Resources/views/content/locationview.html.twig
| Tickets       | [EZP-30233](https://jira.ez.no/browse/EZP-30233)
Adds one generic message for all scenarios when content is not publicly visible
=> EZP-30233: Messages for content item visibility are not displayed for all scenarios

features/ObjectStates.feature, src/bundle/Controller/ObjectStateController.php, src/bundle/Controller/ObjectStateGroupController.php, src/bundle/Resources/translations/object_state.en.xliff
| Tickets       | https://jira.ez.no/browse/EZP-29056
=> EZP-29056: [Object States] Update notification for Object State Group and Object State contains Identifiers instead of Names

src/bundle/Resources/public/js/scripts/udw/copy_subtree.js, src/lib/Menu/ContentRightSidebarBuilder.php
| Tickets       | https://jira.ez.no/browse/EZP-30323
=> EZP-30323: Copy Subtree does not use data-udw-config

src/bundle/Resources/public/js/scripts/admin.content.tree.js
| Tickets       | https://jira.ez.no/browse/EZP-30342
=> EZP-30342: Content tree should hold separate state for different users (opened/closed)

src/bundle/Resources/public/js/scripts/fieldType/ezdate.js, src/bundle/Resources/public/js/scripts/fieldType/ezdatetime.js, src/bundle/Resources/public/js/scripts/fieldType/eztime.js, src/bundle/Resources/public/js/scripts/helpers/timezone.helper.js, src/bundle/Resources/translations/fieldtypes_preview.en.xliff, src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig, src/lib/UI/Config/Provider/DateFormat.php
| Tickets       | [EZP-30263](https://jira.ez.no/browse/EZP-30263)
Adds into ez_full_datetime, ez_full_date, ez_full_time in ezdate_fields.
Warning, this PR can be merged only if https://github.com/ezsystems/ezplatform-user/pull/26 is merged
=> EZP-30263 : User date format don't apply to date fields in content item update and preview

src/bundle/Resources/encore/ez.js.config.js
Follow up after merging up https://github.com/ezsystems/ezplatform-admin-ui/pull/937
=> EZP-29754: Embed block is overwritten by Table in RichText Editor

src/bundle/Resources/public/js/scripts/admin.content.tree.js
| Tickets       | https://jira.ez.no/browse/EZP-30269
I was inspired by: https://css-tricks.com/styling-based-on-scroll-position/
Previously we were afraid of poor performance because of frequent updates of DOM element and use of `getBoundingClientRect`. Current solution should be performant.
=> EZP-30269: [Content Tree] Collapse all button jumps a little bit when scrolling

src/bundle/Resources/public/js/scripts/admin.location.view.js, src/bundle/Resources/views/content/locationview.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29808
| Requires     | https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/177
=> EZP-29808: Newly created content via Multi Upload has wrong language set

src/bundle/Resources/public/scss/_notifications-modal.scss
| Tickets       | https://jira.ez.no/browse/EZEE-2749
=> EZEE-2749: Long message not displayed correctly on Notifications pop-up
