ezsystems/ezplatform-admin-ui

- src/bundle/Resources/views/content/locationview.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-30425
> EZP-30425: Content view is shrunk - Remove redundant div added during merge-up

- src/bundle/Resources/views/notifications/notifications_modal_body.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-30454
> EZP-30454: Broken table in notifications modal when notification list is empty

- features/ContentManagement.feature
- src/lib/Behat/PageElement/Pagination.php
| Tickets       | https://jira.ez.no/browse/EZP-30098
This PR is bringing back fix for redirection after removing an item in Content structure, that was lost by merging Fastest. Additionally, it extends behat timeout for SIL spinner to disappear.
> EZP-30098 bringing back Mareks redirection fix, and extend timeout for waiting for SIL

- features/ContentDraft.feature
- features/ContentManagement.feature
- src/lib/Behat/PageElement/UniversalDiscoveryWidget.php
| Tickets       | https://jira.ez.no/browse/EZP-30098
- bringing back 'stale edit action bar button' fix
- increasing select button click timeout
> EZP-30098 bringing back 'stale edit action bar button' fix

- src/lib/Menu/Admin/ReorderMenuListener.php
- src/lib/Menu/ContentCreateRightSidebarBuilder.php
- src/lib/Menu/ContentEditRightSidebarBuilder.php
| Tickets       | https://jira.ez.no/browse/EZEE-2692
Ordering of menu items in Admin UI relies now on orderNumber which is necessary for repositories which add new items to the dropdown.
> EZEE-2692: Buttons are in different order while user doesn't have Content/Publish policy

- src/bundle/Controller/Content/VersionDraftConflictController.php
- src/bundle/Controller/ContentController.php
- src/bundle/Controller/Version/VersionConflictController.php
- src/bundle/Resources/config/routing.yml
- src/bundle/Resources/public/js/scripts/admin.location.view.js
- src/bundle/Resources/public/js/scripts/button.content.edit.js
- src/bundle/Resources/public/js/scripts/sidebar/btn/location.edit.js
- src/bundle/Resources/views/content/tab/versions/table.html.twig
- src/lib/Specification/Content/ContentDraftHasConflict.php
- src/lib/Specification/Version/VersionHasConflict.php
- src/lib/Tests/Specification/VersionHasConflictTest.php
- src/lib/UI/Config/Provider/FieldType/RichText/AlloyEditor.php
- src/lib/UI/Dataset/VersionsDataset.php
| Tickets       | https://jira.ez.no/browse/EZP-29694
| BC breaks?    | **yes**
This, together with https://github.com/ezsystems/ezpublish-kernel/pull/2598 should align how adminUI behaves comparing to ezPublish. 
This ticket should also be solved by this:
https://jira.ez.no/browse/EZP-29691
BC:
Additional route parameter was needed.
not sure if `Specifications` are under BC though
> EZP-29694: Draft conflict does not work as expected for a content item with multiple translations

- src/bundle/Controller/ContentController.php
- src/bundle/Controller/ContentViewController.php
- src/bundle/Resources/config/bazinga_js_translation.yml
- src/bundle/Resources/config/routing.yml
- src/bundle/Resources/config/services/permissions.yml
- src/bundle/Resources/public/js/scripts/admin.location.view.js
- src/bundle/Resources/public/js/scripts/admin.version.edit.conflict.js
- src/bundle/Resources/public/js/scripts/button.content.edit.js
- src/bundle/Resources/translations/content.en.xliff
- src/bundle/Resources/views/admin/content_draft/list.html.twig
- src/bundle/Resources/views/content/tab/versions/table.html.twig
- src/bundle/Resources/views/dashboard/macros.html.twig
- src/bundle/Resources/views/dashboard/tab/all_content.html.twig
- src/bundle/Resources/views/dashboard/tab/all_media.html.twig
- src/bundle/Resources/views/dashboard/tab/my_content.html.twig
- src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig
- src/bundle/Resources/views/dashboard/tab/my_media.html.twig
- src/lib/Form/Factory/FormFactory.php
- src/lib/Form/Type/ChoiceList/Loader/ContentEditTranslationChoiceLoader.php
- src/lib/Form/Type/Content/Draft/ContentEditType.php
- src/lib/Form/Type/Content/Translation/TranslationAddType.php
- src/lib/Menu/ContentEditRightSidebarBuilder.php
- src/lib/Menu/ContentRightSidebarBuilder.php
- src/lib/Permission/LookupLimitationsTransformer.php
- src/lib/Tab/LocationView/TranslationsTab.php
| Tickets       | https://jira.ez.no/browse/EZP-30344
| Requires | ezsystems/ezpublish-kernel#2585
This PR improves handling of `Language` Limitation based on logic implemented in ezsystems/ezpublish-kernel#2585
> EZP-30344: Improved handling Language Limitation

- src/lib/Behat/Helper/BrowserLogFilter.php
- src/lib/Behat/Helper/Hooks.php
- src/lib/Tests/Behat/BrowserLogFilterTest.php
| Tickets       | https://jira.ez.no/browse/EZP-30489
As seen in https://travis-ci.com/ezsystems/ezplatform-page-builder/jobs/195075830 , the console logs are not that useful now - we're displaying only 10 first errors, making the result look like this:
```
│  JS console errors:
│  http://varnish/bundles/netgentags/admin/jstree/js/jstree.min.js 5 document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for …
```
> EZP-30489: Improve console logs in tests

- src/bundle/Resources/config/services/user_settings.yml
- src/bundle/Resources/config/views.yml
| Tickets       |  [EZP-30514](https://jira.ez.no/browse/EZP-30514) 
For a more detailed description see https://github.com/ezsystems/ezplatform-user/pull/32
> EZP-30514: Moved default configuration to dedicated ViewProvider for the user_settings_update_view

- src/bundle/Resources/public/js/scripts/fieldType/base/base-preview-field.js
- src/bundle/Resources/public/js/scripts/fieldType/ezbinaryfile.js
- src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js
- src/bundle/Resources/public/js/scripts/fieldType/ezimage.js
- src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js
- src/bundle/Resources/public/js/scripts/fieldType/ezmedia.js
| Tickets       | https://jira.ez.no/browse/EZP-30397
**Admin UI** (this PR)
| old name      | new name
| invalidFileSize       | ez-invalid-file-size
| addressNotFound       | ez-address-not-found
| cancelErrors       | ez-cancel-errors
**Page builder** (https://github.com/ezsystems/ezplatform-page-builder/pull/334)
| old name      | new name
| openUdw       | ez-open-udw
| openAirtimePopup       | ez-open-airtime-popup
| postUpdateBlocksPreview       | ez-post-update-blocks-preview
| …
> EZP-30397: Unify JavaScript event names

- src/bundle/Controller/ContentViewController.php
| Tickets       | https://jira.ez.no/browse/EZP-30509
After setting Content/Read limitation by Location, it was not able to access `/admin` page.
Changed parent location loading to be used by `sudo` to be able to load root location children.
> EZP-30509: Location visibility check breaks limitation of Content/Read

- src/bundle/Resources/config/services/siteaccess.yml
- src/bundle/Resources/config/services/ui_config/common.yml
- src/lib/Siteaccess/NonAdminSiteaccessResolver.php
- src/lib/Siteaccess/SiteaccessResolver.php
- src/lib/UI/Config/Provider/Languages.php
Parameter `ezpublish.siteaccess.list` is not siteaccess aware and it should be directly injected into `\EzSystems\EzPlatformAdminUi\UI\Config\Provider\Languages`.
_Bug discovered during working on https://jira.ez.no/browse/EZEE-2775_
> Injected Site Access List directly into EzSystems\EzPlatformAdminUi\UI\Config\Provider\Languages

- src/lib/Behat/Helper/UtilityContext.php
| Tickets       | [EZEE-2782](https://jira.ez.no/browse/EZEE-2782)
fixing `waitUntilElementIsVisible` function
It seems, that there are situations when behat has a problem with nodeElement references when `callback` uses previously (outside) defined base element.
There is still one place, where the base element will be pre-defined (`UniversalDiscoveryWidget.php:62`), but changing that will be harder (as forwarded baseElement is found not only by its locator but also by text content). I'll fix that, but I need a little more time, and I want …
> EZEE-2782 [Behat] Problems with form preview and with notification close

- composer.json
- src/bundle/Resources/config/services/forms.yml
- src/lib/Form/Type/ChoiceList/Loader/ContentCreateContentTypeChoiceLoader.php
- src/lib/Form/Type/ChoiceList/Loader/ContentCreateLanguageChoiceLoader.php
- src/lib/Form/Type/ChoiceList/Loader/PermissionAwareContentTypeChoiceLoader.php
- src/lib/Form/Type/ChoiceList/Loader/PermissionAwareLanguageChoiceLoader.php
- src/lib/Form/Type/Content/Draft/ContentCreateType.php
- src/lib/Menu/ContentRightSidebarBuilder.php
- src/lib/Permission/LookupLimitationsTransformer.php
- src/lib/Permission/PermissionChecker.php
- src/lib/Permission/PermissionCheckerInterface.php
- src/lib/Tests/Permission/LookupLimitationsTransformerTest.php
| Tickets       | https://jira.ez.no/browse/EZP-30470
| Requires | ezsystems/ezpublish-kernel#2628
This PR provides better filtering od Content Types and Languages in the content create widget. It depends on new method `\eZ\Publish\SPI\Limitation\Target\Version::createFromAnyContentTypeOf`. It also introduces new method in `\EzSystems\EzPlatformAdminUi\Permission\PermissionCheckerInterface::getContentCreateLimitations` to get Limitations specificaly for Content creation.
> EZP-30470: Filtered Content Types and Languages in ContentCreate widget based on user permissions

- src/lib/RepositoryForms/Form/Processor/Content/ContentOnTheFlyProcessor.php
| Tickets       | https://jira.ez.no/browse/EZP-29694 / https://jira.ez.no/browse/EZEE-2661
This **change** how **default** behavior for publish works on our UI side. Instead of publishing all translations contained in draft (which right now cannot be edited outside of PAPI/REST) we are publishing draft only in `initialLanguageCode` of draft.
https://github.com/ezsystems/repository-forms/pull/296
https://github.com/ezsystems/ezpublish-kernel/pull/2615
> EZP-29694: Changed publishing to publish last modified translation

- src/bundle/Resources/public/js/scripts/fieldType/eztime.js
| Tickets       | [EZP-30494](https://jira.ez.no/browse/EZP-30494)
Default Time field value from Flatpicker is not saved.
> EZP-30494: Default Time field value is not saved

- features/ContentType.feature
- features/ContentTypeFields.feature
- src/lib/Behat/PageElement/UniversalDiscoveryWidget.php
| Tickets       | [EZP-30617](https://jira.ez.no/browse/EZP-30617)
There are three fixes here:
- first, for the occasional problems with waiting for notification - moving notification checking steps as close as it can be to action that causes this notification
- second, for the multi-select UDW, where we occasionally but regularly get errors with select button not showing up after performing mouse-over; as there is no clear solution for that problem at the moment, I decided to enclose this action in the three-iteration loop, and throw if the …
> EZP-30617 [Behat] Problem with select item in multiselect UDW

- src/bundle/DependencyInjection/Configuration/Parser/Pagination.php
- src/bundle/Resources/config/ezplatform_default_settings.yml
| Tickets       | https://jira.ez.no/browse/EZP-30553
This PR introduce separate pagination limit setting for admin_group and other siteaccesses.
`ezsettings.admin_group.pagination.user_settings_limit: 10`
and 
`ezsettings.default.pagination.user_settings_limit: 10`
Related PR: https://github.com/ezsystems/ezplatform-user/pull/38
> EZP-30553: User settings pagination limit should be different for admin_group and other siteaccesses

- src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-customtag-update.js
- src/lib/Tests/UI/Config/Mapper/FieldType/RichText/CustomTagTest.php
- src/lib/UI/Config/Mapper/FieldType/RichText/CustomTag.php
- src/lib/UI/Config/Mapper/FieldType/RichText/CustomTag/ChoiceAttributeMapper.php
| Tickets       | https://jira.ez.no/browse/EZP-30588
Let's say there is `my-tag` custom tag with `size` choice attribute. This custom tag is migrated from legacy, and it is used in a lot of different places. Possible options for "size" attribute are sm, md, lg. There is no way to translate those options and show the formatted label for them.
```
custom_tags:
test:
template: '@ezdesign/field_type/ezrichtext/custom_tag/my-tag.html.twig'
icon: '/bundles/ezplatformadminui/img/ez-icons.svg#my-tag'
is_inline: false
attributes:
size:
type: …
```
> EZP-30588: Make possible to translate custom tag choice attributes

- src/bundle/Resources/views/themes/admin/ui/search/index.html.twig
- src/bundle/Resources/views/themes/admin/ui/search/list.html.twig
| Tickets       |[EZP-30395](https://jira.ez.no/browse/EZP-30395)
I found the issue/typo that was not catched by our regression tests.  The regression was made by me durring "Move and rename template " task.
> Fixes paths in search templates

- src/bundle/Resources/views/themes/admin/ui/error_page/403.html.twig
- src/bundle/Resources/views/themes/admin/ui/error_page/404.html.twig
- src/bundle/Resources/views/themes/admin/ui/error_page/unknown.html.twig
| Tickets       | [EZP-30666](https://jira.ez.no/browse/EZP-30666)
> EZP-30666: fixed paths to images of error page

- src/bundle/Resources/views/themes/admin/content_type/tab/view.html.twig
| Tickets       | [EZP-30648](https://jira.ez.no/browse/EZP-30648)
fix
> EZP-30648: Values of checkboxes are not displayed properly in Content  Type view

- src/bundle/Resources/translations/systeminfo.en.xliff
- src/bundle/Resources/views/themes/admin/system_info/symfony_kernel.html.twig
| Tickets       | [EZP-30670](https://jira.ez.no/browse/EZP-30670)
According to the symfony documentation, since 4.2 the kernel name and root dir is deprecated so we should stop displaying it in our admin UI
https://symfony.com/blog/new-in-symfony-4-2-important-deprecations#deprecated-the-kernel-name-and-the-root-dir
> EZP-30670: Replaced deprecated Symfony Kernel parameters

- src/bundle/DependencyInjection/Compiler/TabPass.php
- src/bundle/Resources/config/services.yml
- src/bundle/Resources/config/services/controllers.yml
- src/bundle/Resources/config/services/menu.yml
- src/bundle/Resources/config/services/tabs.yml
- src/bundle/Resources/config/services/ui_config/common.yml
- src/bundle/Resources/config/services/universal_discovery_widget.yml
- src/lib/UniversalDiscovery/ConfigResolver.php
| Tickets       | [EZP-30699](https://jira.ez.no/browse/EZP-30699)
| Requires | <ul><li>ezsystems/ezpublish-kernel#2676</li><li>https://github.com/ezsystems/ezpublish-kernel/pull/2662</li><ul>
| Tests pass?   | yes, behat TBD
This PR resolves issues that cause warnings described in the ticket and in ezsystems/ezpublish-kernel#2676.
Ideally it should be debugged further and all services that rely on dynamic settings should be refactored to use Config resolver, however due to time constraints right now most of the changes is about making related services lazy. …
> EZP-30699: Made dynamic settings loaded too early to be lazy-loaded

- src/bundle/Resources/config/services/service_aliases.yml
| Tickets       | [EZEE-2793](https://jira.ez.no/browse/EZEE-2793)
| Required by | ezsystems/date-based-publisher#115
PermissionResolver is currently build by a chain of factories (`Repository::getPermissionResolver` -> `RepositoryFactory::buildRepository`) which fetch SiteAccessAware (dynamic) settings and thus trigger too early resolving of them.
Right now the bug manifests itself only when injecting PermissionResolver into commands, which occurs for some EE packages.
The better fix would be to de-couple PermissionResolver to avoid …
> EZEE-2793: Lazy-loaded PermissionResolver for auto-wiring

- src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js
| Tickets       | https://jira.ez.no/browse/EZP-30659
> EZP-30659: Cannot select image from repository in ImageAsset field

- src/lib/Behat/PageElement/UniversalDiscoveryWidget.php
| Tickets       | [EZP-30595](https://jira.ez.no/browse/EZP-30595)
We can't refresh (redefine) NodeElement so in case of the problem with StaleElementReferenceException on that element we can't use them as a base element (we still can do it in the other situations, where the element doesn't change dynamically). Because of that, to have the possibility to redefine element, we should use the full CSS locator to it, not the partial locator and the base element.
Though it's the most probable error cause, we still should test this solution for a …
> EZP-30595 [Behat] Element with selector: .c-select-content-button was not found

- src/lib/Behat/PageElement/Fields/Keywords.php
- src/lib/Behat/PageElement/Fields/RichText.php
| Tickets       | [EZP-30640](https://jira.ez.no/browse/EZP-30640)
I think that filling field with JS can help us to avoid this Selenium related issue. Though we should test this solution for a few days after merging, before closing the ticket.
> EZP-30640 [Behat] Invalid values are entered in text fields

- src/bundle/Resources/config/services/ui_config/common.yml
- src/lib/UI/Config/Provider/UserContentTypes.php
| Tickets       | https://jira.ez.no/browse/EZP-30128
Expose array of content type identifiers under `userContentTypes` key.
> EZP-30128: Expose user content types in adminUiConfig

- src/bundle/DependencyInjection/Configuration/Parser/Module/UniversalDiscoveryWidget.php
- src/bundle/Resources/config/ezplatform_default_settings.yaml
- src/bundle/Resources/config/universal_discovery_widget.yaml
- src/lib/Menu/ContentRightSidebarBuilder.php
- src/lib/Menu/LeftSidebarBuilder.php
- src/lib/UI/Config/Provider/Module/UniversalDiscoveryWidget.php
| Tickets       | https://jira.ez.no/browse/EZP-30701
Removed deprecated `universal_discovery_widget_module.default_location_id` setting in favor of `universal_discovery_widget_module.configuration.default.starting_location_id`
> EZP-30701: Removed deprecated 'universal_discovery_widget_module.default_location_id' setting

- src/lib/Permission/PermissionChecker.php
| Tickets       | https://jira.ez.no/browse/EZP-30728
> EZP-30728: flattenArrayOfLimitationsForCurrentUser works incorect

- src/lib/Permission/PermissionChecker.php
- src/lib/Tests/Permission/PermissionCheckerTest.php
| Tickets       | https://jira.ez.no/browse/EZP-30697
This issue was discovered during work on content/create permission. Limitation from Role assigning should be also taken into account when the policy has no her own limitations. Also, tests are added.
Related PR:
- https://github.com/ezsystems/ezpublish-kernel/pull/2701
> EZP-30697: Fixed adding RoleLimitation when policy has no limitation itself

- src/lib/Tests/UniversalDiscovery/Event/Subscriber/ContentCreateTest.php
- src/lib/UniversalDiscovery/Event/Subscriber/ContentCreate.php
| Tickets       | https://jira.ez.no/browse/EZEE-2819
ContentCreate subscriber should check restrictions when COTF is present in UDW. Also, for types other `content_create` or other configurations than `create` or `single`. The problem occurs in many places, e.g. in other PB blocks where user can select (or create it in COTF) content or when user want to move content within the sub-items list.
> EZEE-2819: Changed permission subscriber to be run when create tab is present in UDW

- src/bundle/Controller/SearchController.php
- src/bundle/Resources/views/admin/search/search_form.html.twig
- src/lib/EventListener/AdminExceptionListener.php
- src/lib/Form/Type/Search/SearchType.php
| Tickets       | https://jira.ez.no/browse/EZP-30766
`SubmitHandler` was misused in `SearchController::searchAction` as it's not designed to be used with responses rendering twig templates - it should only return `RedirectResponse` objects. 
This affected how page was rendered - when exception occurred in the template rendered inside callable it would make `SubmitHandler` return `null` which in case of `SearchController::searchAction` was rendering "default" template (page no results). The issue mentioned in the ticket (no CSS) was …
> EZP-30766: CSS might be not loaded when exception occurs in Twig

- composer.json
Reverted https://github.com/ezsystems/ezplatform-admin-ui/pull/1022/commits/21888e5f6f26ed2a8af7b3a97c6aa35231d20e6f: `_ezplatform_branch_for_behat_tests` in composer.json should point to `master`.
> Fixed _ezplatform_branch_for_behat_tests in composer.json

- src/lib/Behat/Helper/Hooks.php
- src/lib/Behat/Helper/LogFileReader.php
| Tickets       | yes, but JIRA is dead 😛 
Recently we've had issues with Content Types and Subitems list not loading on Travis. I'm 90% sure that this is caused by concurrency issues, which right now are almost impossible to debug, because we don't know which scenarios are running in the same time. This PR adds log entries when scenarios/steps stop and end, example log:
```
│  [2019-08-05 08:56:10] app.ERROR: Starting scenario | SingleLine Form   | Single line input  
│  [2019-08-05 08:56:10] app.ERROR: Starting step I am logged as "admin" …
```
> Added Behat debug info

- src/bundle/Resources/views/content/content_edit/content_edit_base.html.twig
- src/bundle/Resources/views/content/content_view_fields.html.twig
- src/bundle/Resources/views/content/tab/policies/limitation_values.html.twig
- src/bundle/Resources/views/content/tab/roles/limitation_values.html.twig
- src/bundle/Resources/views/fieldtypes/edit/ezselection.html.twig
- src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig
- src/bundle/Resources/views/parts/menu/top_menu.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-30814
Continuation of https://github.com/ezsystems/ezpublish-kernel/pull/2708:
* Replaced `spaceless` tag usages in favour of `spaceless` filter
* Removed `for ... if ` statements
> EZP-30814: Removed Twig deprecations

- src/bundle/Resources/config/services.yml
- src/lib/EventListener/AdminExceptionListener.php
| Tickets       | https://jira.ez.no/browse/EZP-30820
> EZP-30820: AdminExceptionListener could not be autowired due to missing EncoreBundle definitions

- src/bundle/Resources/config/services/service_aliases.yaml
| Tickets       | [EZP-29386](https://jira.ez.no/browse/EZP-29386)
This shouldn't be part of Admin UI. There is a PR to Kernel that makes aliases there.
> EZP-29386: Removed Admin service aliases in favor of Kernel

- src/bundle/Templating/Twig/TabExtension.php
- src/lib/Component/Renderer/DefaultRenderer.php
- src/lib/Menu/AbstractBuilder.php
- src/lib/Tab/AbstractEventDispatchingTab.php
- src/lib/UI/Action/EventDispatcher.php
- src/lib/UniversalDiscovery/ConfigResolver.php
| Tickets       | https://jira.ez.no/browse/EZP-30812
Fixed the following deprecation message:
```
Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as first argument is deprecated since Symfony 4.3, pass it second and provide the event object first instead.
```
by swapping argument order in  `Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()` method calls.
> EZP-30812: Fixed deprecated use of Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch method

- src/bundle/Resources/config/routing.yaml
- src/bundle/Resources/config/routing_rest.yaml
| Tickets       | https://jira.ez.no/browse/EZP-30819
Referencing controllers with `<Bundle>:<Controller>:<Action>` syntax (aka bundle notation) is deprecated since Symfony 4.1  and generate the following log entries:
```
[2019-08-05 19:39:35] php.INFO: User Deprecated: Referencing controllers with FrameworkBundle:Redirect:redirect is deprecated since Symfony 4.1, use "Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction" instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Referencing …
```
> EZP-30819: Removed deprecated controller references from routes definitions

- src/lib/Component/Event/RenderGroupEvent.php
- src/lib/Component/Event/RenderSingleEvent.php
- src/lib/Menu/AbstractBuilder.php
- src/lib/Menu/Event/ConfigureMenuEvent.php
- src/lib/Tab/Event/TabEvent.php
- src/lib/Tab/Event/TabGroupEvent.php
- src/lib/Tab/Event/TabViewRenderEvent.php
- src/lib/UI/Action/UiActionEvent.php
- src/lib/UniversalDiscovery/Event/ConfigResolveEvent.php
| Tickets       | https://jira.ez.no/browse/EZP-30828
Replaced `\Symfony\Component\EventDispatcher\Event` usage in favour of `Symfony\Contracts\EventDispatcher\Event`.
> EZP-30828: Replaced \Symfony\Component\EventDispatcher\Event usage in favor of Symfony\Contracts\EventDispatcher\Event

- src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-table-cell.js
- src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-table-row.js
- src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-table.js
- src/bundle/Resources/public/js/alloyeditor/src/toolbars/ez-add.js
| Tickets       | [EZP-30802](https://jira.ez.no/browse/EZP-30802)
1. Start to create any content with Richt Text field.
2. In Online Editor add any custom tag
3. Set "Right" align for added custom tag
4. Remove an empty paragraph above the custom tag (using trash icon)
5. Click on the area in Online Editor left to the custom tag
You will get following JavaScript error in the console:
```
TypeError: Cannot read property 'lastElement' of null
```
> EZP-30802: Fixed OE JS error in case of missing element path

- src/bundle/Resources/config/services/forms.yaml
- src/lib/Form/Extension/RichTextTypeExtension.php
- src/lib/Form/Type/Extension/Content/ContentEditTypeExtension.php
| Tickets       | https://jira.ez.no/browse/EZP-30844
Since Symfony 4.2 form type extensions should implement static method  `Symfony\Component\Form\FormTypeExtensionInterface::getExtendedTypes()" 
More information: https://symfony.com/blog/new-in-symfony-4-2-improved-form-type-extensions
> EZP-30844: Implemented getExtendedTypes method in Form Type Extensions

- src/lib/Form/Type/Search/SearchType.php
- src/lib/Menu/MainMenuBuilder.php
- src/lib/Tab/LocationView/DetailsTab.php
| Tickets       | https://jira.ez.no/browse/EZP-30848
When a user has a Section Limitation we can not rely on hasAccess method to check if we can load Section. We must use a canUser method. 
If we need to load a list of Sections it would be better and more readable to compare the result of hasAccess method with `false`. Because section list is filtered, so we should display it when `hasAccess` method return `true` or an array of Limitation.
> EZP-30848: Fixed usage of hasAccess method with section/view permission in Admin UI

- src/bundle/Controller/SectionController.php
- src/bundle/Resources/views/admin/section/list.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-30853
When a user has any Limitation related viewing section then he sees all sections available to him and there is no need to display button "Add Section". The button should be visible only when the user has section/edit Policy and can view a newly created section.
> EZP-30853: The button "Add Section" has been hidden for a user which has Limitation to view Sections

- src/bundle/Resources/public/js/alloyeditor/src/widgets/ez-embed-base.js
- src/bundle/Resources/translations/alloy_editor.en.xliff
| Tickets       | [EZP-30864](https://jira.ez.no/browse/EZP-30864)
1. Create content A
2. Create content B, which has RichtText fields
3. Embed content A in RichtText field of the content B
4. Remove content A
5. Try to edit content B
Expected result: you would be able to edit the content
Actual result: "Cannot read property 'value' of undefined" error is shown. And if you have a lot of content in the RichText field, it is hard to understand where this error comes from.
> EZP-30864: Handle removed content which is embed

- src/bundle/Resources/views/themes/admin/account/notifications/modal.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-30819
Follow up for https://github.com/ezsystems/ezplatform-admin-ui/pull/1051. Removed deprecated controller reference syntax from `account/notifications/modal.html.twig`
> EZP-30819: Removed deprecated controller reference syntax from account/notifications/modal.html.twig

- src/bundle/Controller/SearchController.php
- src/bundle/Resources/config/services/controllers.yaml
- src/bundle/Resources/config/services/query_types.yaml
- src/lib/QueryType/SearchQueryType.php
- src/lib/Tests/QueryType/SearchQueryTypeTest.php
| Tickets       | https://jira.ez.no/browse/EZP-30888
Moved query build logic from  the `\EzSystems\EzPlatformAdminUiBundle\Controller\SearchController::searchAction` to dedicated `QueryType` class in order to make ezplatform-admin-ui code more SOLID.
> EZP-30888: Moved search query build logic from SearchController to dedicated QueryType

- src/bundle/Controller/ContentTypeController.php
- src/lib/Form/Type/ChoiceList/Loader/ContentTypeChoiceLoader.php
- src/lib/UI/Config/Provider/ContentTypes.php
| Tickets       | [EZP-30899](https://jira.ez.no/browse/EZP-30899)
Excerpt from JIRA:
>Content Types are by default sorted by their identifiers. From Editor's perspective, it would be more convenient to sort them by name.
> EZP-30899: Change default CT sorting field from identifier to name in AdminUI

- src/bundle/Controller/NotificationController.php
- src/bundle/Resources/config/routing.yaml
- src/lib/Form/Factory/FormFactory.php
| Tickets       | https://jira.ez.no/browse/EZP-30947
Removed the following deprecated methods:
*  `\EzSystems\EzPlatformAdminUiBundle\Controller\NotificationController::renderNotificationsAction` and related `ezplatform.notifications.render` route
* `\EzSystems\EzPlatformAdminUi\Form\Factory\FormFactory::{createObjectState,deleteObjectState,deleteObjectStates,updateObjectState,updateContentObjectState}`
> EZP-30947: Removed deprecated methods

- .travis.yml
- behat_suites.yml
- features/personas/SubtreeEditor.feature
- src/lib/Behat/BusinessContext/ContentViewContext.php
- src/lib/Behat/BusinessContext/NavigationContext.php
- src/lib/Behat/BusinessContext/RightMenuContext.php
- src/lib/Behat/BusinessContext/UDWContext.php
- src/lib/Behat/PageElement/RightMenu.php
- src/lib/Behat/PageElement/UpperMenu.php
- src/lib/Behat/PageObject/ContentItemPage.php
JIRA: https://jira.ez.no/browse/EZP-30884
Adding scenarios that test whether SubtreeEditor can (and cannot) perform his usual actions in AdminUI.
> EZP-30884: Implement scenarios for Subtree editor

- src/bundle/Controller/ContentDraftController.php
- src/bundle/Resources/public/scss/_tables.scss
- src/bundle/Resources/translations/alloy_editor.en.xliff
- src/bundle/Resources/translations/dashboard.en.xliff
- src/bundle/Resources/translations/drafts.en.xliff
- src/bundle/Resources/views/admin/content_draft/draft_list.html.twig
- src/bundle/Resources/views/dashboard/tab/my_draft_list.html.twig
- src/bundle/Resources/views/dashboard/tab/my_drafts.html.twig
- src/lib/Pagination/Pagerfanta/ContentDraftAdapter.php
- src/lib/Tab/Dashboard/MyDraftsTab.php
- src/lib/UI/Dataset/ContentDraftListDataset.php
- src/lib/UI/Dataset/ContentDraftsDataset.php
- src/lib/UI/Dataset/DatasetFactory.php
- src/lib/UI/Value/Content/ContentDraft.php
- src/lib/UI/Value/Content/ContentDraftInterface.php
- src/lib/UI/Value/Content/UnauthorizedContentDraft.php
- src/lib/UI/Value/ValueFactory.php
| Tickets       | https://jira.ez.no/browse/EZP-30427
| Tests pass?   |no
This PR changed thy way which pagination for content drafts list load objects. The current implementation uses offset and limit to improve performance when many drafts are fetched (more than 5000). That change affects Dashboard and  list of user's drafts (`admin/contentdraft/list`)
If a user has no access to `content/versionread` then he will see information like `User does not have access to 'versionread' 'content' with content ID: 5178`
Related PR: …
> EZP-30427: Changed drafts pagination to use limit and offset

- src/bundle/Controller/ContentDraftController.php
- src/bundle/Resources/public/scss/_tables.scss
- src/bundle/Resources/translations/alloy_editor.en.xliff
- src/bundle/Resources/translations/dashboard.en.xliff
- src/bundle/Resources/translations/drafts.en.xliff
- src/bundle/Resources/views/themes/admin/content/draft/draft_list.html.twig
- src/bundle/Resources/views/themes/admin/content/draft/list.html.twig
- src/bundle/Resources/views/themes/admin/ui/dashboard/tab/my_draft_list.html.twig
- src/bundle/Resources/views/themes/admin/ui/dashboard/tab/my_drafts.html.twig
- src/lib/Pagination/Pagerfanta/ContentDraftAdapter.php
- src/lib/Tab/Dashboard/MyDraftsTab.php
- src/lib/UI/Dataset/ContentDraftListDataset.php
- src/lib/UI/Dataset/ContentDraftsDataset.php
- src/lib/UI/Dataset/DatasetFactory.php
- src/lib/UI/Value/Content/ContentDraft.php
- src/lib/UI/Value/Content/ContentDraftInterface.php
- src/lib/UI/Value/Content/UnauthorizedContentDraft.php
- src/lib/UI/Value/ValueFactory.php
| Tickets       | https://jira.ez.no/browse/EZP-30427
| Tests pass?   |no
This PR changed thy way which pagination for content drafts list load objects. The current implementation uses offset and limit to improve performance when many drafts are fetched (more than 5000). That change affects Dashboard and  list of user's drafts (`admin/contentdraft/list`)
If a user has no access to `content/versionread` then he will see information like `User does not have access to 'versionread' 'content' with content ID: 5178`
Related PR: …
> Merged PR with changed drafts pagination to use limit and offset

- src/bundle/Resources/public/scss/_user-menu.scss
| Tickets       | https://jira.ez.no/browse/EZP-30967
Now there is visible on-pixel-tall line of color 0xFDFDFD here:
but it is really hard to spot and I think it is OK.
> EZP-30967: Cannot open View notifications modal on Safari

- src/bundle/Controller/ContentViewController.php
- src/bundle/DependencyInjection/Configuration/Parser/Pagination.php
- src/bundle/Resources/config/ezplatform_default_settings.yml
- src/bundle/Resources/translations/locationview.en.xliff
- src/bundle/Resources/views/content/locationview.html.twig
- src/bundle/Resources/views/content/tab/relations/tab.html.twig
- src/bundle/Resources/views/content/tab/relations/table_relations_reverse.html.twig
- src/lib/Pagination/Pagerfanta/ReverseRelationAdapter.php
- src/lib/Tab/LocationView/RelationsTab.php
- src/lib/UI/Dataset/DatasetFactory.php
- src/lib/UI/Dataset/RelationListDataset.php
- src/lib/UI/Dataset/ReverseRelationListDataset.php
- src/lib/UI/Value/Content/Relation.php
- src/lib/UI/Value/Content/RelationInterface.php
- src/lib/UI/Value/Content/UnauthorizedRelation.php
- src/lib/UI/Value/ValueFactory.php
| Tickets       | https://jira.ez.no/browse/EZP-30900
To increase performance when content has many (~61k) reverse relations this PR adds pagination to Reverse relations list in the Location view. When the user has no permission to view the Relation he will see information like `User does not have access to 'read' 'content' with content ID: 100`
Related PRs:
- https://github.com/ezsystems/ezpublish-kernel/pull/2774
- https://github.com/ezsystems/ezpublish-kernel/pull/2777
> EZP-30900: Added pagination to content's reverse relations

- src/lib/EventListener/AdminExceptionListener.php
- src/lib/EventListener/RequestListener.php
- src/lib/EventListener/RequestLocaleListener.php
- src/lib/Tests/EventListener/RequestListenerTest.php
- src/lib/Tests/EventListener/RequestLocaleListenerTest.php
| Tickets       | https://jira.ez.no/browse/EZP-30985
Since Symfony 4.3:
* `\Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent` has been deprecated in favour of `\Symfony\Component\HttpKernel\Event\ExceptionEvent`
* `\Symfony\Component\HttpKernel\Event\GetResponseEvent` has been deprecated in favour of `\Symfony\Component\HttpKernel\Event\RequestEvent`
> EZP-30985: Removed usage of deprecated event classes

- src/bundle/Resources/public/scss/_alloyeditor-link-edit.scss
| Tickets       | [EZP-30959](https://jira.ez.no/browse/EZP-30959)
Long URL overlaps "clear URL button" which makes it hard to edit.
> EZP-30959: Long URL overlaps "clear URL input" button in Online Editor

- src/bundle/Resources/config/services.yaml
- src/lib/RepositoryForms/Form/Processor/Content/ContentOnTheFlyProcessor.php
- src/lib/Tab/Dashboard/MyDraftsTab.php
- src/lib/Translation/Extractor/JavaScriptFileVisitor.php
- src/lib/Translation/Extractor/NotificationTranslationExtractor.php
| Tickets       | [EZP-30985](https://jira.ez.no/browse/EZP-30985)
Part of the patch changes methods which implement `JMS\TranslationBundle\Translation\Extractor\FileVisitorInterface::visitTwigFile` which still uses old Twig class names. However, this is perfectly valid. The following code runs fine:
```php
<?php
require 'vendor/autoload.php';
interface Foo
{
public function foo(\Twig_Node $node);
}
class Bar implements Foo
{
public function foo(\Twig\Node\Node $node)
{
return 'foo';
}
}
$b = new Bar();
echo $b->foo(new \Twig\Node\Node()); …
```
> Use Twig namespaces

- src/lib/Form/DataTransformer/RoleAssignmentTransformer.php
- src/lib/Form/DataTransformer/RoleTransformer.php
- src/lib/Tests/Form/DataTransformer/RoleAssignmentTransformerTest.php
- src/lib/Tests/Form/DataTransformer/RoleTransformerTest.php
| Tickets       | https://jira.ez.no/browse/EZP-31029
After adding type hints to RoleService we must pass `integer` as a Role ID to RoleService:: loadRole and RoleService:: loadRoleAssignment methods
Needs https://github.com/ezsystems/ezpublish-kernel/pull/2822
> EZP-31029: Adjust Role transformers to introduced type hints in RoleService

- composer.json
- src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-customtag-update.js
- src/bundle/Resources/public/js/alloyeditor/src/widgets/ez-custom-tag-base.js
| Tickets       | [EZP-31052](https://jira.ez.no/browse/EZP-31052)
| Requires | ezsystems/ezplatform-richtext#73
| Tests pass?   | [yes](https://travis-ci.org/ezsystems/ezplatform-admin-ui/builds/601814379)
| Doc needed?   | yes, for RichText PR
This PR provides a minimal support for the Custom Tag link attribute type added via ezsystems/ezplatform-richtext#73. The support is in the form of a simple string input field, to avoid Online Editor crashing for the new attribute type.
**Note: _AdminUI crashing for RichText (`ezrichtext`) Field migrated from `ezxmltext` is considered here as …
> EZP-31052: Provided minimal support for CustomTag link attr. type

- src/bundle/Resources/translations/content_type.en.xliff
- src/bundle/Resources/translations/draft_conflict.en.xliff
- src/bundle/Resources/views/themes/admin/content/modal/draft_conflict.html.twig
- src/bundle/Resources/views/themes/admin/content_type/tab/view.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-30985
| BC breaks?    | yes? (New translation strings required)
`transchoice` has been deprecated since Symfony 4.2.
Here, I've opted for using separate translation strings, rather than reimplementing `trans` with ICU MessageFormat which requires renaming translation files to have a new prefix for ICU messages to be recognized.
> EZP-30985: Replaced usage of deprecated transchoice Twig function

- src/bundle/Resources/public/js/scripts/admin.search.filters.js
| Tickets       | https://jira.ez.no/browse/EZP-31057
> EZP-31057: UI creator search filter doesnit support multi user content type identifiers

- src/lib/Form/DataTransformer/SectionTransformer.php
- src/lib/Tests/Form/DataTransformer/SectionTransformerTest.php
| **JIRA issue**     | [EZP-31030](https://jira.ez.no/browse/EZP-31030)
| **Target version** | `master`
| **Doc needed**     | no
Fixed error when assigning content to section and removing section discovered while testing https://github.com/ezsystems/ezpublish-kernel/pull/2880
> Argument 1 passed to eZ\Publish\SPI\Repository\Decorator\SectionServiceDecorator::loadSection() must be of the type int, string given, called in /home/vagrant/master/vendor/ezsystems/ezplatform-admin-ui/src/lib/Form/DataTransformer/SectionTran …
> EZP-31030: Introduced strict types for SectionService

- src/lib/EventListener/AdminExceptionListener.php
| Tickets       | https://jira.ez.no/browse/EZEE-2941
> EZEE-2941: Added missing required argument when SiteAccess is constructed

- src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
| Tickets       | https://jira.ez.no/browse/EZP-31096
This PR allows injecting custom toolbars into the Alloy Editor. Usage:
1. Create the new toolbar config.
2. Add the toolbar config to `ezplatform-admin-ui-alloyeditor-js` entry using encore.
3. Add toolbar JavaScript class to `ezAlloyEditor.CustomSelections.<TOOLBAR_NAME>` eZ config. You can do it at the botton of toolbar config file:
```
eZ.addConfig('ezAlloyEditor.CustomSelections.ContentVariableEdit', ContentVariableEditConfig);
```
4. `ContentVariableEditConfig` toolbar is injected …
> EZP-31096: Custom toolbars in Alloy Editor

- src/bundle/Resources/views/form_fields.html.twig
| Tickets       |  [EZP-31138](https://jira.ez.no/browse/EZP-31138)
Elements Path is missing in Page Builder RichText Block. And because of this, it is impossible to use custom attributes/etc.
> EZP-31138: Fixed missing Elements Path for richtext_widget

- src/lib/Behat/PageElement/Fields/RichText.php
| Tickets       | part of https://jira.ez.no/browse/EZEE-2944
This PR tries to fix the issue from Travis:
```
| TextBlock             | Text              |
Exception: element click intercepted: Element <button class="ae-button ez-btn-ae ez-btn-ae--embed " tabindex="-1" title="Embed">...</button> is not clickable at point (250, 284). Other element would receive the click: <div class="ez-data-source__richtext cke_editable cke_editable_inline cke_contents_ltr ae-editable cke_focus" id="block_configuration_attributes_content_value__editable" …
```
> [Behat] Added waiting until RichText toolbar is visible

- src/bundle/Resources/views/admin/content_type/edit.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-31201
In the following code snippet the `child is not iterable` expression is always `false` (`child` is instance of `Symfony\Component\Form\FormView` which implement  `\IteratorAggregate`)
https://github.com/ezsystems/ezplatform-admin-ui/blob/b380a2b4601992976270e5ef3c5c8d6cc205f364/src/bundle/Resources/views/themes/admin/content_type/edit.html.twig#L116-L126
Moreover `group_class` variable is not defined.
> EZP-31201: Fixed Field Definition Edit Form rendering when custom edit template is not defined

- src/bundle/Templating/Twig/UniversalDiscoveryExtension.php
- src/lib/UniversalDiscovery/Event/Subscriber/ObjectRelationAllowedContentTypes.php
| Tickets       | https://jira.ez.no/browse/EZP-31089
Frontend PR: https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/234
Replaces: https://github.com/ezsystems/ezplatform-admin-ui/pull/1123
> EZP-31089: Wrong allowed content types list on object relation(s) fields

- src/lib/UniversalDiscovery/Event/Subscriber/ObjectRelationAllowedContentTypes.php
| Tickets       | https://jira.ez.no/browse/EZP-31194
Related with: [ezsystems/ezplatform-admin-ui-modules#231](https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/231)
~~- [ ] Coding standards (`$ composer fix-cs`)~~
> EZP-31194: Searching in UDW does not take allowed CT's into account when ezobjectrelation FieldType is used

- src/bundle/Resources/encore/ez.js.config.js
- src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-table-header.js
- src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
| Tickets       | [EZP-31207](https://jira.ez.no/browse/EZP-31207)
1. Start editing any content with RichText field
2. Using Online Editor add a table and set its headers
3. Point the cursor into header cells and no toolbar is shown
This PR adds a toolbar for the table header.
> EZP-31207: Table header toolbar is added

- src/bundle/Controller/ContentController.php
- src/bundle/Controller/ContentViewController.php
- src/bundle/Resources/public/js/scripts/admin.location.view.js
- src/bundle/Resources/public/js/scripts/button.content.edit.js
- src/bundle/Resources/views/admin/bookmark/list.html.twig
- src/bundle/Resources/views/admin/search/search_table_row.html.twig
- src/bundle/Resources/views/dashboard/macros.html.twig
- src/bundle/Resources/views/link_manager/view.html.twig
| Tickets       | [EZP-30758](https://jira.ez.no/browse/EZP-30758)
| Required by | EE: eZ Platform Page Builder (see references)
When creating a new draft via AdminUI, the latest version to create draft from was hard-coded in the form. As a side effect, when another version was published in the meantime by some external process, usually by another user or the same user in a different browser window (tab), the information got outdated and thus the user who opened content/location view page first, edited previous version. Please see the steps …
> EZP-30758: Ensured the latest version is used when editing content

- src/bundle/Resources/public/js/scripts/core/draggable.js
| Tickets       |https://jira.ez.no/browse/EZEE-2738
Hid previous location while dragging element;
Changed Draggable methods to public;
> EZEE-2738: Hid previous location while dragging in D&D

- src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-28900
Despite browser language, `ezfloat` was always displayed using dot as a decimal separator. This PR adds `localizednumber` filter to the output which formats the value according to locale.
> EZP-28900: Added `localizednumber` filter to ezfloat value preview

- src/lib/Behat/PageElement/Fields/RichText.php
| Tickets       | https://jira.ez.no/browse/EZEE-2944
| Bug fix?      | in tests
Tests error:
```
Exception: element click intercepted: Element <button class="ae-button ez-btn-ae ez-btn-ae--unordered-list " tabindex="-1" title="List">...</button> is not clickable at point (150, 346). Other element would receive the click: <div class="ez-richtext-tools">...</div>
(Session info: chrome=74.0.3729.169)
(Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.4.0-101-generic x86_64) in …
```
> [Behat] Added waiting until RichText toolbar transition ends

- composer.json
| Bug fix?      | dependencies bugfix?
| Tests pass?   | n/a
This fails on my machine with:
```
Your requirements could not be resolved to an installable set of packages.
Problem 1
- ezsystems/ez-support-tools v2.0.0-beta2 requires ezsystems/ezplatform-admin-ui ^2.0 -> satisfiable by ezsystems/ezplatform-admin-ui[2.0.x-dev, v2.0.0-beta1, v2.0.0-beta2, v2.0.0-beta3] but these conflict with your requirements or minimum-stability.
- ezsystems/ez-support-tools v2.0.0-beta1 requires ezsystems/ezplatform-admin-ui ^2.0@beta -> satisfiable by …
```
> Install latest dependencies

- src/lib/UI/Value/ValueFactory.php
EZP-31257: Load field definition only if the relation is a field related in `\EzSystems\EzPlatformAdminUi\UI\Value\ValueFactory::{createRelation,createRelationItem}`
> EZP-31257: Load field definition only if relation is field related in ValueFactory::{createRelation,createRelationItem}

- src/bundle/Resources/views/form_fields.html.twig
| Tickets       | https://jira.ez.no/browse/EZEE-2946
> EZEE-2946: Added missing html nodes for characters counter in the RichText twig template

- src/bundle/Resources/public/js/scripts/fieldType/ezobjectrelationlist.js
| Tickets       | https://jira.ez.no/browse/EZP-31263
Added event listener to the trash button in order to disable it after rows deletion.
> EZP-31263: trash button set to inactive after deleting relation items

- features/standard/ContentManagement.feature
| Tickets       | https://jira.ez.no/browse/EZP-31283
This is a tricky one, so a longer explanaition is needed 😉 
Tests are failing with:
```
@javascript @common
Scenario: Content can be moved to trash from root location                         # vendor/ezsystems/ezplatform-admin-ui/features/standard/ContentManagement.feature:99
Given I navigate to content "Test Article Manage" of type "Article" in root path # EzSystems\EzPlatformAdminUi\Behat\BusinessContext\NavigationContext::iNavigateToContentInRoot()
There's no subitem Test Article …
```
> [Behat] Changed navigation to UDW from Subitems in "Content can be moved to trash from root location" test

- src/bundle/Resources/public/js/scripts/sidebar/instant.filter.js
| Tickets       | https://jira.ez.no/browse/EZP-31291
If you try to filter the Content Type creation list, "File" does not work, nor does a bunch of words that are found in the HTML of the quick filter list (form, check, type, content, and more). This is because the filter is applied against the entire HTML of each item.
> EZP-31291: Fix Content Type creation filter on certain words such as "File"

- src/bundle/Resources/views/themes/admin/content/location_view.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-31128
Removed blank space under notification box
> EZP-31128: removed blank space under notification box

- src/bundle/Resources/views/content/content_view_fields.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-31241
Show 'No' in content view when checkbox is empty.
> EZP-31241: Changed behaviour for showing not checked value in checkbox

- src/bundle/Controller/LocationController.php
- src/bundle/Resources/public/scss/fieldType/edit/_ezobjectrelationlist.scss
- src/bundle/Resources/translations/ezrepoforms_content.en.xliff
- src/bundle/Resources/translations/forms.en.xliff
- src/bundle/Resources/translations/messages.en.xliff
- src/bundle/Resources/views/fieldtypes/edit/ezobjectrelation.html.twig
- src/bundle/Resources/views/fieldtypes/edit/ezobjectrelationlist.html.twig
- src/bundle/Resources/views/fieldtypes/edit/relation_base.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29249
Added and changed texts in relations fields.
> EZP-29249: Changed texts in relation fields

- src/bundle/Resources/encore/ez.js.config.js
- src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-styleslistitem.js
- webpack.config.js
| Tickets       | [EZEE-2914](https://jira.ez.no/browse/EZEE-2914)
AlloyEditor.ButtonStylesListItem on click does not update textarea element, because function _onClick is protected and we cannot override, so we need an override render function, for add a new function into onClick in order to update textarea
> EZEE-2914: Custom inline style does not update textarea after click on

- src/bundle/Resources/public/js/scripts/fieldType/ezdate.js
- src/bundle/Resources/views/fieldtypes/edit/ezdate.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-31277
flatpickr widget will now instantiate with server's timezone offset if provided, not just be the browser's one in order to handle different timezones.
> EZP-31277: added server timezone offset support for ezdate widget

- src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-attributes-update.js
| Tickets       | [EZP-31295](https://jira.ez.no/browse/EZP-31295)
In some cases custom CSS class is optional, and it should be possible to not select any. Right now UI is not allowing to do that. As a workaround, we added an empty custom CSS class and made it default, but it was causing some errors.
1. Setup custom CSS classed and default empty CSS class:
```                     
system:
default:
fieldtypes:
ezrichtext:
classes:
paragraph:
choices: ['', custom-paragraph-1, custom-paragraph-2, custom-paragraph-3]
default_value: ''
required: …
```
> EZP-31295: Unable to use default empty custom CSS class in the OE

- src/bundle/Resources/public/js/alloyeditor/src/plugins/ez-custom-tag.js
- src/bundle/Resources/public/js/alloyeditor/src/plugins/ez-embed.js
| Tickets       | [EZP-31321](https://jira.ez.no/browse/EZP-31321), related to [EZP-29882](https://jira.ez.no/browse/EZP-29882)
| Requires | ezsystems/ezplatform-richtext#88
Parent PR: https://github.com/ezsystems/ezplatform-richtext/pull/88.
> EZP-31321: Dropped injecting zero-width space into ezembed(inline) elements

- src/lib/Form/Type/ChoiceList/Loader/BaseChoiceLoader.php
| Tickets       | https://jira.ez.no/browse/EZP-31297
Resolve ticket issue (Symfony bugfix adaptation)
SF bugfix:
https://github.com/symfony/symfony/pull/29500
https://github.com/symfony/symfony/pull/29501
> EZP-31297: Narrowed user preferences values to the available list

- src/bundle/DependencyInjection/Configuration/Parser/Module/ContentTree.php
- src/bundle/Resources/config/ezplatform_default_settings.yml
| Tickets       | https://jira.ez.no/browse/EZP-31339
Due to the nature of _ConfigResolver_ the site access specific config is resolved before the group's one which is valid behavior, however, in certain cases when _SemanticConfig_ is being built it forces the default values to be taken in consideration for specific site access and there is no fallback to group config, even though there should be one.
> EZP-31339: Dropped default config enforcement for ContentTree parser

- src/lib/Behat/PageElement/UniversalDiscoveryWidget.php
| Tickets       | Follow-up to https://jira.ez.no/browse/EZP-31116
~~When reviewing please ignore Travis changes.~~
Example failures this PR tries to fix:
https://travis-ci.org/ezsystems/ezplatform-admin-ui/jobs/644285679?utm_medium=notification&utm_source=slack
https://travis-ci.com/ezsystems/ezplatform-page-builder/jobs/282689221?utm_medium=notification&utm_source=slack
https://travis-ci.com/ezsystems/ezplatform-page-builder/jobs/282125374?utm_medium=notification&utm_source=slack
Looks like we have a problem in UDW when we try to select …
> [Behat] Changed selecting multiple items to be more bullet-proof

- src/bundle/Resources/public/js/scripts/core/custom.dropdown.js
- src/bundle/Resources/public/scss/core/_custom.dropdown.scss
- src/bundle/Resources/public/scss/fieldType/edit/_ezselection.scss
| Tickets       | https://jira.ez.no/browse/EZP-31347
Select list now will be positioned above select field if there is less than 300px to the bottom of screen.
> EZP-31347: Added functionality to show dropdown above select field

- src/lib/Behat/PageElement/UniversalDiscoveryWidget.php
| Tickets       | Follow-up to https://github.com/ezsystems/ezplatform-admin-ui/pull/1220
| Bug fix?      | yes, in tests
The solution proposed in https://github.com/ezsystems/ezplatform-admin-ui/pull/1220 has one weak point - when a level has been previously selected in UDW we try to compare the current displayed items with the ones that were displayed previously. This scenario doesn't work when the new selected level has no children - the `getItemsFromLevel` does not find anything and throws exception.
We can consider the next level loaded when:
- the children …
> [Behat] Fixed UDW issue when the newly selected item has no children

- src/bundle/Resources/public/js/scripts/admin.content.tree.js
- src/bundle/Resources/public/scss/_content-tree.scss
| Tickets       | https://jira.ez.no/browse/EZP-31349
Disabled content tree animations after reload page
> EZP-31349: Triggered content tree animation only by clicking by mouse

- src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-styleslistitem.js
- src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-custom-style.js
| Tickets       | https://jira.ez.no/browse/EZP-31137
| Tests pass?   |yes
ez-custom-style.js for alloy editor was overriding base config styles by filtering out default styles unnecessarily if custom styles were in use.
> EZP-31137: Fixed styles dropdown when custom ones are in use for RTE

- src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
- src/bundle/Resources/public/scss/_extra-actions.scss
| Tickets       | https://jira.ez.no/browse/EZEE-2975
Rreverted setting top position
https://github.com/ezsystems/ezplatform-page-builder/pull/502
> EZEE-2975: In Page Builder dropdown widgets are too low after being expanded

- src/lib/UI/Module/ContentTree/NodeFactory.php
| Tickets       | https://jira.ez.no/browse/EZP-31367
This was discovered during testing of https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/264. For Location ID 1 there is no `VersionInfo` thus it is impossible to get translated name. As a fallback it uses `$contentInfo->name` property.
> EZP-31367: Do not use translated node name for Location ID 1 in Content Tree

- src/bundle/Resources/public/js/scripts/admin.content.edit.js
- src/bundle/Resources/public/scss/_content-edit.scss
- src/bundle/Resources/public/scss/_icons.scss
- src/bundle/Resources/public/scss/_main-row.scss
- src/bundle/Resources/public/scss/_preview.scss
- src/bundle/Resources/translations/content_create.en.xliff
- src/bundle/Resources/translations/content_edit.en.xliff
- src/bundle/Resources/translations/forms.en.xliff
- src/bundle/Resources/views/themes/admin/content/content_preview.html.twig
- src/bundle/Resources/views/themes/admin/content/create/create.html.twig
- src/bundle/Resources/views/themes/admin/content/edit/base.html.twig
- src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-31223
Harmonized headers and exit buttons for:
- Editing/Creating view in Content View
- Preview view when in Editing/Creating view in Content View
- Form Builder view
> EZP-31223: harmonize headers and exit buttons

- src/lib/Behat/PageObject/ContentUpdateItemPage.php
JIRA: https://jira.ez.no/browse/EZP-31223
Follow up to https://github.com/ezsystems/ezplatform-admin-ui/pull/1181 , where the edit design has been changed.
Trash tests are failing because of the issue described in https://jira.ez.no/browse/EZP-31381, unrelated to this PR.
> [Behat] Adjusted selector for new header design in Edit mode

- src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
- src/bundle/Resources/public/scss/_extra-actions.scss
Reverts ezsystems/ezplatform-admin-ui#1229
> Revert "EZEE-2975: In Page Builder dropdown widgets are too low after being expanded"

- src/lib/Behat/PageElement/ContentTypePicker.php
- src/lib/Behat/PageObject/ContentItemPage.php
| Tickets       | https://jira.ez.no/browse/EZP-31366
Making sure that the Content Type picker is rendered before we interact with it.
Also added the verifyVisibility call in PageBuilder: https://github.com/ezsystems/ezplatform-page-builder/pull/501
> EZP-31366: [Behat] Added checking visibility of ContentTypePicker

- src/bundle/Resources/public/scss/_content-edit.scss
- src/bundle/Resources/views/themes/admin/ui/on_the_fly/create_on_the_fly.html.twig
| Tickets       |https://jira.ez.no/browse/EZP-31384
> EZP-31384: Broken Content on the fly create template style

- src/bundle/Controller/Content/VersionDraftConflictController.php
- src/bundle/Resources/config/routing.yml
- src/bundle/Resources/public/js/scripts/admin.location.view.js
- src/bundle/Resources/public/js/scripts/sidebar/btn/location.edit.js
- src/bundle/Resources/views/content/tab/versions/table.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-31310
| Needs | <ul><li>https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/269 </li><li>https://github.com/ezsystems/repository-forms/pull/333</li></ul>
When the user wants to edit the content that has multiple locations and occurs checking if unpublished draft exists then we need to know in which location the user tries to do this. This is needed to prepare proper links to edit versions. We should do this when it is possible (when a user is on the location view). When the user …
> EZP-31310: Fixed VersionDraftConflict for content having multiple locations

- src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/base-table.js
- src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-table-cell.js
- src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/ez-table-header.js
| Tickets       | [EZP-31380](https://jira.ez.no/browse/EZP-31380)
AlloyEdior allows running the commands to manipulate the table content only when active element is `td` or `th`. So there is no need to have "insert rows"/"insert columns" buttons in "table" and "table row" toolbars.
**Steps to reproduce:**
1. Insert a table using the Online Editor
2. Using elements path click on "table" or "tr"
3. Try to insert new rows/cells
**Current results:**
No new rows/cells are inserted
**Expected result:**
New rows/cells will be inserted
This happens …
> EZP-31380: Disable manage rows/cells buttons for table and row toolbars

- features/standard/ContentTypeFields.feature
- src/lib/Behat/BusinessContext/ContentUpdateContext.php
- src/lib/Behat/BusinessContext/ContentViewContext.php
- src/lib/Behat/PageElement/ContentField.php
- src/lib/Behat/PageElement/ContentUpdateForm.php
- src/lib/Behat/PageElement/Fields/ContentQuery.php
- src/lib/Behat/PageElement/Fields/NonEditableField.php
- src/lib/Behat/PageElement/PlatformElementFactory.php
| Tickets       | https://jira.ez.no/browse/EZP-31311
| New feature?  | new tests
Adding tests for ezcontentquery. This fieldtype is not editable in Content Edit mode:
which means I had to rewrite a bit of current test logic to take that into account.
Because of that I've also decided that we shoudn't add it to existing examples (which try to set a value in fieldtype and then verify its correctness) but as new separate feature. Scenarios boil down to:
1) A Content Item with contenqeury fieldtype can be created (and Content Query field displays correct data) …
> EZP-31311: Add queryfieldtype tests

- src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
| Tickets       | [EZP-31371](https://jira.ez.no/browse/EZP-31371)
`HTTP` protocol prefix should be added on pasting links from external sources, if not specified already. This behavior is aligned with how prefixing works in RTE at the moment.
> EZP-31371: Copying a web page link w/o protocol in a Word paragraph leads to a 404 error

- src/lib/Behat/PageElement/Fields/ImageAsset.php
| Tickets       | https://jira.ez.no/browse/EZP-31392
| Bug fix?      | no (but makes tests more robust)
Making sure that the Image Asset is created correctly before proceeding with further test actions. I suppose the tests used to click "Publish" to soon (before the Image Asset has been uploaded and processed) which resulted in publishing a Content Item without changes. Making sure the notification is visible should be enough.
> [Behat] Added verification of notification when adding Image Asset

- src/bundle/Resources/views/themes/admin/content/create/create.html.twig
- src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
- src/bundle/Resources/views/themes/admin/ui/on_the_fly/create_on_the_fly.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-31404
Added container class to error messages
> EZP-31404: Validation error message is not aligned with new create form style

- src/bundle/Resources/config/universal_discovery_widget.yml
| Tickets       | [EZP-30482](https://jira.ez.no/browse/EZP-30482)
When embedding images in RTE, there should be restriction only to the "image" Content-Type. It works fine when embedding content newly created via COTF, but UDW is still affected. This issue is not reproducible in new version of UDW in 3.0.
> EZP-30482: No limitation to image content type when embedding image in RTE

- src/bundle/Resources/views/themes/admin/content/tab/versions/table.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-31394
> EZP-31394: Fixed wrong button and behavior for edit action in version table

- src/bundle/Resources/encore/ez.js.config.js
- src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-dropdown.js
- src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-styleslist.js
| Tickets       | https://jira.ez.no/browse/EZP-31356
The focus event which is hardcoded into the AlloyEditor and attached to the styles dropdown list is not working correctly on Firefox and Safari. The reasoning for the solution was to implement `ButtonDropdown` component without this `focus` event, which does more harm than good and inject it into newly created `EzButtonStylesList` component which overwrites the default AlloyEditor's `ButtonStylesList` in order to prevent other components of being mutated.
> EZP-31356: Fixed styles dropdown selection on Firefox and Safari

- src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js
| Tickets       | https://jira.ez.no/browse/EZP-31430
> EZP-31430: Can't select existing object for ImageAsset field

- src/bundle/Resources/public/js/scripts/admin.search.filters.js
- src/bundle/Resources/public/scss/_filters.scss
- src/bundle/Resources/translations/content_create.en.xliff
- src/bundle/Resources/translations/search.en.xliff
- src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
- src/bundle/Resources/views/themes/admin/ui/search/form.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29948
> EZP-29948: Improved dates select on the search content site

- src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js
- src/bundle/Resources/views/themes/admin/content/modal/draft_conflict.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-31438
| Reletad to | https://github.com/ezsystems/ezplatform-page-builder/pull/529
1.) Added in parse method (eZ.tooltips.helpers) optional parameter as domNode where bootstrap execute querySelector('[title]')
2.) Added data-tooltip-container-selector parameter
> EZP-31438: Added tooltips to site builder

- src/lib/Form/DataTransformer/ContentInfoTransformer.php
- src/lib/Form/DataTransformer/VersionInfoTransformer.php
- src/lib/Strategy/NotificationTwigStrategy.php
- src/lib/Tests/Form/DataTransformer/ContentInfoTransformerTest.php
- src/lib/Tests/Form/DataTransformer/VersionInfoTransformerTest.php
- src/lib/View/Filter/ContentTranslateViewFilter.php
| **JIRA issue**     | [EZP-31118](https://jira.ez.no/browse/EZP-31118)
| **Target version** |  `master`
Fixed issues reported in https://github.com/ezsystems/ezpublish-kernel/pull/2866#pullrequestreview-324628931
https://github.com/ezsystems/ezplatform-admin-ui/pull/1148/commits/72be1abbdcd8010430a68162c350d1c70af175e4: 
```
Argument 1 passed to eZ\Publish\SPI\Repository\Decorator\ContentServiceDecorator::loadContentInfo() must be of the type int, string given, called in /home/vagrant/master/vendor/ezsystems/ezplatform-admin-ui/src/lib/Form/DataTransformer/ContentInfoTransformer.php on …
```
> EZP-31118: Introduced strict types for ContentService

- src/bundle/Resources/config/services/role_form_mappers.yaml
- src/lib/Limitation/Mapper/SiteAccessLimitationMapper.php
- src/lib/Tests/Limitation/Mapper/SiteAccessLimitationMapperTest.php
| Tickets       | https://jira.ez.no/browse/EZP-31477
| Needs   | https://github.com/ezsystems/ezpublish-kernel/pull/2983
List of SiteAccesses on limitation list should be fetched from the service, not from configuration
> EZP-31477: Fixed loading Site Accesses on limitation list

- src/bundle/Resources/translations/forms.en.xliff
| Tickets       | https://jira.ez.no/browse/EZEE-3029
New labels for policies introduced in:
https://github.com/ezsystems/ezplatform-version-comparison/pull/30
> EZEE-3029: Added basic policy for version comparison

- src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
| Tickets       | [EZEE-3030](https://jira.ez.no/browse/EZEE-3030)
The recently introduced solution https://github.com/ezsystems/ezplatform-admin-ui/pull/1245 is missing proper checks for `ezcontent` and z`ezlocation` keywords that results in `http` protocol wrongly added, hence broken validation. Added proper conditions and flatten existing ones to increase readability. I will create a PR in `ezplatform-richtext` for 3.0 once this solution is approved.
> EZEE-3030: Links containing 'ezlocation` or 'ezcontent' keywords break RTE validation on paste

- src/bundle/Templating/Twig/PathStringExtension.php
- src/lib/Form/DataTransformer/UDWBasedValueModelTransformer.php
This PR fixes 2 issues when trying to edit/update Policy with already set Location ID:
In `admin/role/{roleId}/policy/{policyId}/update`;
```
Argument 1 passed to eZ\Publish\Core\Repository\SiteAccessAware\LocationService::loadLocation() must be of the type int, string given, called in src/lib/Form/DataTransformer/UDWBasedValueModelTransformer.php on line 49
```
```
Argument 1 passed to eZ\Publish\Core\Repository\SiteAccessAware\LocationService::loadLocation() must be of the type int, string given, called in src/bundle/Templating/Twig/PathStringExtension.php on line 53
```
> Fixed Location ID type-casting issues in Policy Limitation update

- src/bundle/Resources/views/themes/admin/ui/menu/top_menu_2nd_level.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-31500
Changed def icon to small
> EZP-31500: Menu entry icon is too big

- src/bundle/Resources/translations/draft_conflict.en.xliff
| Tickets       | https://jira.ez.no/browse/EZP-31509
> EZP-31509: Fixed missing translation for draft.conflict.close

- src/bundle/Resources/translations/messages.en.xliff
- src/bundle/Resources/translations/search.en.xliff
- src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
~This is output from `translation:extract`. Please, take a look if it's Ok (like, `search.date.range` moved from `search` domain to `messages`?)~
`search.date.range` moved back to `search` domain by @ViniTou
> fix: Missing translations

- src/bundle/Controller/User/UserDeleteController.php
| Tickets       | https://jira.ez.no/browse/EZP-31465
Added valid `contentId` param to `_ez_content_view` route after `User` deletion.
> EZP-31465: Fixed invalid redirect after User deletion

- src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js
| Tickets       | https://jira.ez.no/browse/EZP-31417
| Related to | https://github.com/ezsystems/date-based-publisher/pull/157
|| https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/278
|| https://github.com/ezsystems/ezplatform-calendar/pull/49
> EZP-31417: Prevent execute querySelectorAll on null in tooltips helper

- src/bundle/Resources/public/scss/_filters.scss
| Tickets       | https://jira.ez.no/browse/EZP-31458
| Tests pass?   |yes
`ez-filters__range-wrapper` had to have removed pointer-events in order to prevent unintentional render on click.
> EZP-31458: Fixed calendar date picker render event

- src/bundle/Resources/public/scss/_main-row.scss
- src/bundle/Resources/public/scss/_mixins.scss
| Tickets       | [EZP-31484](https://jira.ez.no/browse/EZP-31484)
> EZP-31484: Changed z-index 1 to 0 for checkbox

- src/lib/Behat/PageElement/Fields/Keywords.php
| Tickets       | https://jira.ez.no/browse/EZP-31471
| Doc needed?   |
https://jira.ez.no/browse/EZP-31471 changed how the keyword fieldtype behaves, adjusting for changes done there:
- the expected items are not compared as a string, but instead are parsed into separate keywords and are compared as collections (without taking the order into account).
> [Behat] Changed to comparing keywords ignoring their order

- src/bundle/ui-dev/src/modules/universal-discovery/components/finder/finder.branch.js
| Tickets       | https://jira.ez.no/browse/EZP-31526
> EZP-31526: UDW crushes when trying to collapse first row in bookmark tab

- src/lib/Menu/Listener/ReorderByOrderNumberListener.php
- src/lib/Tests/Menu/ReorderByOrderNumberListenerTest.php
| Tickets       | https://jira.ez.no/browse/EZP-31521 https://jira.ez.no/browse/EZEE-2953
https://jira.ez.no/browse/EZEE-2953
> EZP-31521: Fixed sorting logic listener for ordered menu items

- src/bundle/Resources/views/admin/language/view.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-29354
> EZP-29354: Language information in table header is not centered

- src/bundle/Resources/public/js/alloyeditor/src/buttons/ez-btn-imageupdate.js
| Tickets       | [EZP-31120](https://jira.ez.no/browse/EZP-31120)
Updating an image doesn't invoke `customUpdate` event that results in changes being not reflected in the edition form.
> EZP-31120: Image is not replaced in RTE/OE when publishing directly

- src/bundle/Resources/translations/messages.en.xliff
| Tickets       | https://jira.ez.no/browse/EZP-31051
Aligned message with https://github.com/ezsystems/ezplatform-admin-ui/pull/1115
> EZP-31051: Password expired screen incorrectly informs that email has been sent

- src/bundle/Resources/views/Security/mail/forgot_user_password.html.twig
| Tickets       | [EZP-31195](https://jira.ez.no/browse/EZP-31195)
Removed default mail from twig
Another PR's to this ticket
https://github.com/ezsystems/ezplatform-form-builder/pull/210
https://github.com/ezsystems/ezplatform-user/pull/59
> EZP-31195: Set From in twig to empty string

- src/bundle/Resources/public/scss/_content-edit.scss
- src/bundle/Resources/public/scss/_main-row.scss
| Tickets       | https://jira.ez.no/browse/EZP-31398
> EZP-31398: Field type element overlaps with ez-edit-header__content-type-name

- src/bundle/Resources/public/js/scripts/admin.limitation.pick.js
| Tickets       | https://jira.ez.no/browse/EZP-31545
As it was reported as "pgsql only", it turned out it is just because
```
SELECT COUNT(*) FROM ezcontentobject_tree t INNER JOIN ezcontentobject c ON t.contentobject_id = c.id INNER JOIN ezcontentobject_version v ON c.id = v.contentobject_id WHERE ((1 = 1) AND (t.node_id IN (?))) AND (c.status = ?) AND (v.status = ?) AND (t.depth <> ?) AND ((c.language_mask & ?) > ?)' with params ["NaN", 1, 1, 0, 3, 0]
```
is _valid_ query for mysql.
> EZP-31545: Filtered empty idString

- src/lib/Behat/Helper/Hooks.php
- src/lib/Behat/Helper/TestLogProvider.php
| Tickets       | https://jira.ez.no/browse/EZP-31453
This PR refactors how the logs are displayed (by moving the responsibility of providing the logs into a new class) so that most of the logic can be reused in Allure bundles (and add the logs as attachments).
Required by: https://github.com/ezsystems/allure-behat/pull/8
This PR also introduces some formatting changes to how the output is displayed, to make it more readable.
See: https://travis-ci.org/ezsystems/ezplatform-admin-ui/jobs/660613158?utm_medium=notification&utm_source=github_statu …
> [Behat] Refactored displaying of application/browser logs

- src/bundle/Resources/public/scss/_extra-actions.scss
| Tickets       | [EZP-31555](https://jira.ez.no/browse/EZP-31555)
After changing the menu theme in eZ Platform v3.0 if has too many CT's then the menu is not correctly displayed
> EZP-31555: Changed max-height and added overflow to better fit content

- src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
| Tickets       | [EZP-31539](https://jira.ez.no/browse/EZP-31539)
There are still unhandled cases when pasting links in RTE (`mailto`, `skype`, `callto` etc). Instead of adding more of restricted keywords (which could also be error-prone if the keyword is a present outside schema), I changed regexp to verify whether any schema was present before changing the actual URL. It should also work properly when someone uses some custom link schema, like `myschema://`.
> EZP-31539: Link Validation error in Richtext Editor

- src/bundle/Resources/translations/forms.en.xliff
| Tickets       | https://jira.ez.no/browse/EZEE-3090
| Related to |  https://github.com/ezsystems/ezplatform-site-factory/pull/53
> Added translations for advanced user permissions in Site Factory

- src/lib/UniversalDiscovery/Event/Subscriber/ObjectRelationAllowedContentTypes.php
| Tickets       | [EZP-31459](https://jira.ez.no/browse/EZP-31459)
If `allowed_content_types` key is not specified in the configuration (`null` value) the whole subscriber stops at this point even though the next condition provides proper handling for that case.
> EZP-31459: [UDW] Allowed Content Types are not respected in object relation field

- src/lib/Form/DataTransformer/TranslatablePropertyTransformer.php
- src/lib/Tests/Form/DataTransformer/TranslatablePropertyTransformerTest.php
| Tickets       | https://jira.ez.no/browse/EZP-31449
Reverse transformation in `TranslatablePropertyTransformer` was adapted to properly handle `ContentType` and `ContentType's`  fieldtype translatable fields when the empty value was provided in form.
Original kernel PR and discussion: https://github.com/ezsystems/ezpublish-kernel/pull/2988 -> closed right now.
Corresponding PR for 2.5: https://github.com/ezsystems/repository-forms/pull/338
> EZP-31449: Adapted TranslatablePropertyTransformer to properly handle nulls

- src/bundle/Resources/config/services/ui_config/mappers.yml
- src/lib/Tests/UI/Config/Mapper/FieldType/RichText/CustomTagTest.php
- src/lib/UI/Config/Mapper/FieldType/RichText/CustomTag.php
| Tickets       | https://jira.ez.no/browse/EZP-31547
This is continuation for https://github.com/ezsystems/ezplatform-admin-ui/pull/1058
This PR adds `$translator` argument to `EzSystems\EzPlatformAdminUi\UI\Config\Mapper\FieldType\RichText\CustomTag` to prevent autowiring issues.
> EZP-31547: Autowiring fails for CustomTag service when using 3rd party translator bundle

- src/lib/Behat/Helper/TestLogProvider.php
| Tickets       | https://jira.ez.no/browse/EZP-31453
| New feature?  | yes (for tests)
- CS fixer failure is unrelated and will be fixed in another issue: https://jira.ez.no/browse/EZP-31578
- this PR contains a TMP commit that will be removed
According to Selenium doc (https://github.com/SeleniumHQ/selenium/wiki/Logging#retrieval-of-logs):
```
In the scenario where a log is retrieved several times the same log entries should not be retrieved more than once. 
For this reason, and to same memory, after each retrieval of a log the log buffer of that log is reset. …
```
> [Behat] Added possibility to read browser logs multiple times

- src/bundle/Resources/translations/validators.en.xliff
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [EZP-31581](https://jira.ez.no/browse/EZP-31581)
| **Type**                                   | bug
| **BC breaks**                          | no
| **Tests pass**                          | yes
| **Doc needed**                       | no
Merge up from https://github.com/ezsystems/repository-forms/pull/340
> EZP-31581: Added missing translation

- src/bundle/ui-dev/src/modules/sub-items/components/table-view/table.view.item.component.js
| Tickets       | [EZP-31600](https://jira.ez.no/browse/EZP-31600)
1. Login as admin and create a "Parent" content
2. Create a new user, and login with its credentials
3. As a new user create "Parent" / "Child" content item
4. Logout as new user and log in as admin
5. Remove new user created on step #2
6. Open "Parent" content item full view in admin UI
7. No sub-items are shown, and the following error is displayed in browser console
```
TypeError: Cannot read property 'name' of null
at …
```
> EZP-31600: TableView throws an error when Creator/Contributor is removed for any of the content items

- .travis.yml
- composer.json
- src/bundle/Controller/LanguageController.php
- src/bundle/Controller/NotificationController.php
- src/bundle/Controller/SearchController.php
- src/lib/Behat/PageObject/LanguagePage.php
- src/lib/Behat/PageObject/ObjectStatePage.php
- src/lib/Permission/PermissionChecker.php
- src/lib/Tests/EventListener/RequestLocaleListenerTest.php
- src/lib/Tests/RepositoryForms/Form/Processor/PreviewFormProcessorTest.php
| **JIRA issue**     | [EZP-31542](https://jira.ez.no/browse/EZP-31542)
| **Target version** | `1.5`
| **BC breaks**      | no
| **Doc needed**     | no
> EZP-31542: Added PHP 7.4 support (eZ Platform 2.5)

- src/bundle/DependencyInjection/EzPlatformAdminUiExtension.php
| Tickets       | https://jira.ez.no/browse/EZP-31604
Behat Context classes were loaded also in `test` environemnt, but BehatBundle is loaded only in `behat` env, which caused the reported issue.
> [Behat] EZP-31604: Removed loading Context classes in test env

- src/bundle/Resources/views/themes/admin/ui/component/preview_unavailable.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-31399
> EZP-31399: ez-alert-info in Editing view is not aligned with content card

- src/bundle/Tests/DependencyInjection/Compiler/ComponentPassTest.php
- src/bundle/Tests/DependencyInjection/Compiler/SystemInfoTabGroupPassTest.php
- src/bundle/Tests/DependencyInjection/Compiler/TabPassTest.php
- src/bundle/Tests/DependencyInjection/Compiler/UiConfigProviderPassTest.php
- src/lib/Tests/Behat/BrowserLogFilterTest.php
- src/lib/Tests/Behat/ExtendedTableNodeTest.php
- src/lib/Tests/RepositoryForms/Form/Processor/PreviewFormProcessorTest.php
- src/lib/Tests/UI/Config/Mapper/FieldType/RichText/CustomTagTest.php
- src/lib/Tests/Validator/Constraint/UserPasswordTest.php
- src/lib/Tests/Validator/Constraint/UserPasswordValidatorTest.php
| **JIRA issue**     | [EZP-31560](https://jira.ez.no/browse/EZP-31560)
| **Target version** | `1.5`+
| **BC breaks**      | no
| **Doc needed**     | no
This PR aligns namespaces not following the defined psr-4 convention.
Only the test cases are affected.
See [EZP-31560](https://jira.ez.no/browse/EZP-31560) for more details.
**TODO**:
> EZP-31560: [Tests] Fixed namespaces not following PSR-4

- src/bundle/Resources/views/fieldtypes/preview/content_fields.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-27324
related:
https://github.com/ezsystems/ezpublish-kernel/pull/3033
> EZP-27324: Proper media/binary uri is now shown & generated for old content versions

- src/bundle/Resources/config/services/role_form_mappers.yaml
- src/bundle/Resources/config/services/siteaccess.yaml
- src/lib/Limitation/Mapper/SiteAccessLimitationMapper.php
- src/lib/Siteaccess/SiteAccessKeyGenerator.php
- src/lib/Siteaccess/SiteAccessKeyGeneratorInterface.php
- src/lib/Tests/Limitation/Mapper/SiteAccessLimitationMapperTest.php
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [EZEE-3071](https://jira.ez.no/browse/EZEE-3071)
| **Type**                                   | bug/improvement
| **BC breaks**                          | no
| **Tests pass**                          | yes
| **Doc needed**                       | no
Another PR for this ticket: https://github.com/ezsystems/ezplatform-site-factory/pull/58
> EZEE-3071: Moved generate key for SiteAccess to new Class

- src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js
| Tickets       | https://jira.ez.no/browse/EZEE-3020
Added auto hide of tooltips if tooltip node has been deleted
> EZEE-3020: Close tooltips when item is deleted

- src/bundle/Resources/views/admin/search/search_table_row.html.twig
- src/bundle/Resources/views/content/relation.html.twig
- src/bundle/Resources/views/content/tab/relations/table_relations.html.twig
- src/bundle/Resources/views/content/tab/relations/table_relations_reverse.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-31583
Some twig views have been tweaked to support `Contents` without `Locations`.
> EZP-31583: Fixed views for Content without Location

- src/lib/UI/Value/ValueFactory.php
| Tickets       | https://jira.ez.no/browse/EZP-30925
| Improvement?      | yes
Language remove checkboxes in `Content's` translations tab will now be checked against `content remove` policy.
Kernel PR: https://github.com/ezsystems/ezpublish-kernel/pull/3036
> EZP-30925: Added 'LanguageLimitation' functionality to 'Translations' tab

- src/lib/Behat/PageElement/Fields/DefaultFieldElement.php
| Tickets       | https://jira.ez.no/browse/EZP-31648
Tests for Languages, Sections, Content Types etc. are failing when trying to set the value for input fields. Example: https://res.cloudinary.com/ezplatformtravis/image/upload/v1589987442/screenshots/5ec548724f4d5131244793-vendor_ezsystems_ezplatform-admin-ui_features_standard_languages_feature_22_ndmmry.png (the fields are supposed to be filled, but they are empty).
All these tests are sharing the same (modified in this PR) piece of code, which first tries to clear the input field by …
> [Behat] Removed clearing the field before filling input

- src/bundle/Resources/config/services.yml
- src/lib/EventListener/ContentDownloadRouteReferenceListener.php
- src/lib/Tests/EventListener/ContentDownloadRouteReferenceListenerTest.php
| Tickets       | https://jira.ez.no/browse/EZP-31639
TL;DR: URLs to binary content of ezmedia/ezfile fields used in ezplatform-admin-ui should generated in scope of the current siteaccess, otherwise additional auth. might be required if resource is not public available e.g. specific versions (sessions are not shared between siteaccesses by default).  
1. Pass `siteaccess` parameter explicitly to `ez_content_download` route to force url generation in specific siteaccess. _it's not as easy as it sounds see `ez_content_download_field_id` …
> Fixed EZP-31639: media and file fields not loaded correctly in edit mode

- src/lib/Form/Type/ChoiceList/Loader/BaseChoiceLoader.php
- src/lib/Form/Type/ChoiceList/Loader/ContentCreateContentTypeChoiceLoader.php
- src/lib/Form/Type/ChoiceList/Loader/ContentCreateLanguageChoiceLoader.php
- src/lib/Form/Type/ChoiceList/Loader/ContentTypeChoiceLoader.php
| Tickets       | https://jira.ez.no/browse/EZP-31340
As a continue of https://github.com/ezsystems/ezplatform-admin-ui/pull/1211 fixed other places where outdated choice loaders are used (introduced Symfony bugfix)
> EZP-31340: Corrected outdated choiceloaders (introduced Symfony bugfix)

- src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
| Tickets       | [EZP-31405](https://jira.ez.no/browse/EZP-31405)
Make sure <ezlink> not removed by CKEditor HTML parser when `<ezlink>` located above `<ezconfig>` element inside embed image element (which is the case if content migrated from legacy).
not reproducible with eZPlatform v3
> EZP-31405 - fix embed image link removal

- features/standard/ContentTypeFields.feature
- src/lib/Behat/BusinessContext/ContentUpdateContext.php
- src/lib/Behat/PageElement/ContentField.php
- src/lib/Behat/PageElement/Fields/ImageAsset.php
| Tickets       | https://jira.ez.no/browse/EZP-31551
Adds a new Scenario that tests that an existing Image from the repository can be selected when creating a Content Type with Image Asset.
Also adds a new way of selecting content in ContentField.php
> [BEHAT]added test case regarding selecting ImageAsset from repository (EZP-31551)

- src/lib/Behat/PageElement/Fields/DefaultFieldElement.php
| Tickets       | JIRA: https://jira.ez.no/browse/EZP-31648
| Bug fix?      | in tests?
Looks like the tests keep failing even after https://github.com/ezsystems/ezplatform-admin-ui/pull/1389 has been merged:
https://travis-ci.org/github/ezsystems/ezplatform/jobs/694164455
https://travis-ci.org/github/ezsystems/ezplatform-admin-ui/jobs/692537680
https://travis-ci.org/github/ezsystems/ezplatform/jobs/692781698
So this PR tries to make the approach even more robust by:
1) delaying initialisation of the searched field until it's really needed
2) making sure the …
> [Behat] Changed how the field value is set for DefaultFieldElement

- behat_suites.yml
Small followup for: https://jira.ez.no/browse/EZP-31551
Failing build: https://travis-ci.org/github/ezsystems/BehatBundle/jobs/694940560
```
-- Use --snippets-for CLI option to generate snippets for following adminuimodules suite steps:
Given I create "Image" Content items in "/Media/Images/" in "eng-GB"
```
The new Image Asset Scenario is also part of the admin-ui-modules suite, but it does not include ContentContext which is required for the Scenario to run. This PR changes that.
> [Behat] Added ContentContext to adminuimodules suite

- src/lib/Behat/PageElement/LanguagePicker.php
| Tickets       | Done as part of https://jira.ez.no/browse/EZEE-3156
| Bug fix?      | n/a
| Tests pass?   | they should
Tests are failing in https://github.com/ezsystems/ezplatform-page-builder/pull/595 because after the changes Selenium thinks that the Language Picker is visible/displayed (in real usage it's not).
Making the LanguagePicker selector more specific solves this issue.
> [Behat] Adjusted language picker selector

- features/standard/ContentManagement.feature
- features/standard/Trash.feature
| Bug fix?      | fix failing tests
We have various failing jobs:
- https://travis-ci.org/github/ezsystems/ezplatform/jobs/697879345
- https://travis-ci.com/github/ezsystems/ezplatform-page-builder/jobs/348666587
- https://travis-ci.com/github/ezsystems/ezplatform-page-builder/jobs/348666598
in all of them the following Scenario is failing:
`Scenario: Content can be moved to trash from non-root location`
This is caused because this Scenario is run concurrently with this one: https://github.com/ezsystems/ezplatform-admin-ui/blob/1.5/features/s …
> [Behat] Moved and consolidated Trash tests into one feature

- src/bundle/Resources/encore/ez.js.config.js
- src/bundle/Resources/public/js/scripts/admin.content.edit.js
- src/bundle/Resources/public/js/scripts/admin.location.tooglecontentpreview.js
- src/bundle/Resources/public/scss/_field-group.scss
- src/bundle/Resources/public/scss/_tabs.scss
- src/bundle/Resources/public/scss/_warning-icon.scss
- src/bundle/Resources/public/scss/ezplatform.scss
- src/bundle/Resources/views/themes/admin/content/content_view_fields.html.twig
- src/bundle/Resources/views/themes/admin/content/create/create.html.twig
- src/bundle/Resources/views/themes/admin/content/edit/base.html.twig
- src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
- src/bundle/Resources/views/themes/admin/content/location_view.html.twig
- src/bundle/Resources/views/themes/admin/content/tab/content.html.twig
- src/bundle/Resources/views/themes/admin/content/warning_icon.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/warning_icon.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-31344
I made few improvments (not all in this ticket because I need help of backend team).
Changes:
- Added border for preview of content
- Added toggler for field group 
- Removed toggler from preview of content
- Removed sub items section title row
Related PR's:
https://github.com/ezsystems/ezplatform-kernel/pull/73
https://github.com/ezsystems/ezplatform-content-forms/pull/26
> EZP-31344: Added border and toggler for preview content

- src/bundle/Controller/ContentController.php
- src/bundle/Resources/config/services/controllers.yaml
- src/bundle/Resources/config/services/siteaccess.yaml
- src/bundle/Resources/views/themes/admin/content/content_preview.html.twig
- src/lib/Siteaccess/NonAdminSiteaccessResolver.php
- src/lib/Siteaccess/SiteAccessNameGenerator.php
- src/lib/Siteaccess/SiteAccessNameGeneratorInterface.php
- src/lib/Siteaccess/SiteaccessResolver.php
- src/lib/Siteaccess/SiteaccessResolverInterface.php
| Tickets       | https://jira.ez.no/browse/EZEE-3167
| Related PR     | https://github.com/ezsystems/ezplatform-site-factory/pull/70
List of the Site Accesses should come from `siteAccessService`. Site Factory should have the possibility to modify the Site Access name.
> EZEE-3167: Added generation of Site Access name for Sites

- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_search.scss
- src/bundle/ui-dev/src/modules/universal-discovery/components/search/search.js
- src/bundle/ui-dev/src/modules/universal-discovery/hooks/useSearchByQueryFetch.js
- src/bundle/ui-dev/src/modules/universal-discovery/services/universal.discovery.service.js
| Tickets       | https://jira.ez.no/browse/EZP-31680
| Improvement?      | yes
PR is a direct continuation of https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/286
Related `ezplatform-kernel` PR: https://github.com/ezsystems/ezplatform-rest/pull/51
> EZP-31680: Added UDW Search language filter

- .travis.yml
- behat_suites.yml
- features/standard/Trash.feature
| Tickets       | https://jira.ez.no/browse/EZP-31650
| Bug fix?      | yes (quick-fix for travis)
Temporarily disabling Trash test cases for 3.1.
Created ticket for updating those TCs: https://jira.ez.no/browse/EZP-31717
Also a revert for https://github.com/ezsystems/ezplatform-admin-ui/pull/1408/commits/283b5bb95ee1dc76eb9c864025066bf9b4b19948
> EZP-31650: Temporarily disable Trash test cases

- src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
- src/bundle/Resources/views/themes/admin/content/form_fields.html.twig
| Tickets       | https://jira.ez.no/browse/EZEE-3176
> EZEE-3176: Make disabled fields are non-interactable

- src/bundle/Resources/public/js/scripts/admin.content.edit.js
- src/bundle/Resources/translations/content_edit.en.xliff
- src/bundle/Resources/translations/validators.en.xliff
- src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
jira ref: https://jira.ez.no/browse/EZP-31692
> EZP-31692: Hide tooltip after show/hide details of content

- src/bundle/Resources/public/js/scripts/admin.content.tree.js
| Tickets       | https://jira.ez.no/browse/EZP-31696
Removed focus from button after content tree menu expand
> EZP-31696: removed focus after content tree expanded

- features/standard/Trash.feature
- src/lib/Behat/PageObject/TrashPage.php
| Tickets       | https://jira.ez.no/browse/EZP-31717
Adjusting the tests for the changed Column name - it used to be "Type", now it's called "Content Type".
Previous:
Current:
> [Behat] Adjusted Trash tests

- src/bundle/Resources/translations/dashboard.en.xliff
- src/bundle/Resources/views/themes/admin/ui/dashboard/block/ez.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-31719
| Tests pass?   | TBD
The alert box for end-of-life shows verbatim (escaped) HTML. This adds `raw` operators and indents in the same way as similar texts in the same template.
> EZP-31719: Verbatim HTML in end of life information on Dashboard

- src/bundle/Controller/ContentOnTheFlyController.php
- src/lib/View/Filter/ContentTranslateViewFilter.php
| Tickets       | https://jira.ez.no/browse/EZEE-3176
> EZEE-3176: Added context information to Form builders

- src/bundle/Resources/encore/ez.js.config.js
- src/bundle/Resources/public/js/scripts/fieldType/base/multi-input-field.js
- src/bundle/Resources/public/js/scripts/fieldType/ezauthor.js
| Tickets       | https://jira.ez.no/browse/EZP-31743
So far proof of concept
> EZP-31743: Multi-input single field validation doesn't show proper error

- src/lib/UniversalDiscovery/Event/Subscriber/ContentCreate.php
| Tickets       | [https://jira.ez.no/browse/EZP-31742](https://jira.ez.no/browse/EZP-31742)
**Steps to reproduce:**
1. Install clean eZ Platform 3.1.0/3.0.5.
2. Modify editor user role (https://ezplatform310.localhost/admin/role/3):
- Remove "Content / All functions" limitation
- Add "Content / Read, Content Type: Folder" limitation
- Add "Content / Create, Content Type: Folder" limitation
3. Create a test editor user.
4. Login into admin using test editor user credentials.
5. Open "Content Structure" page …
> EZP-31742: UDW error for users with restricted content types

- src/bundle/Resources/public/js/scripts/fieldType/ezdate.js
- src/bundle/Resources/views/fieldtypes/edit/ezdate.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-31557
There are basically two scenarios: creating new `Content` with `ezdate` fieldtype or updating one:
1. During the creation of a new `Content` the only thing we should care about is initializing valid date when `ezdate` has default date set as current date. What we need to get is just a current time based on the user browser's settings (not the server date as the user can be in a different timezone than the server).
2. During the update when the date has been set previously we need to …
> EZP-31557: Fixed ezdate editing within different timezones

- src/lib/UI/Value/ValueFactory.php
| Tickets       | https://jira.ez.no/browse/EZP-31584
`ValueFactory` will not utilize newly create `LocationResolver` (https://github.com/ezsystems/ezpublish-kernel/pull/3050) in order to load first available `Location` for `ContentInfo` instead of main `Location` which user does not have permission to access (he can access other `Locations` though).
**Regression suite:** https://github.com/ezsystems/ezplatform-page-builder/pull/631
> EZP-31584: Changed main Location to first available Location in Relations

- src/bundle/Resources/views/admin/search/search_table_row.html.twig
- src/bundle/Resources/views/content/tab/relations/table_relations.html.twig
- src/bundle/Resources/views/content/tab/relations/table_relations_reverse.html.twig
- src/lib/Search/AbstractPagerContentToDataMapper.php
- src/lib/Search/PagerSearchContentToDataMapper.php
- src/lib/Tab/Dashboard/PagerContentToDataMapper.php
- src/lib/UI/Value/Content/Relation.php
- src/lib/UI/Value/ValueFactory.php
| Tickets       |https://jira.ez.no/browse/EZP-31777
| Improvement?      | yes
Relation tabs in Content view and Search module have been improved by adding proper URLs to related/found Content based on first available `Location` instead of main `Location`.
> EZP-31777: Resolved Locations in Content relations and search module

- features/standard/ContentCreation.feature
- features/standard/ContentTypeFields.feature
- features/standard/SearchContent.feature
- features/standard/Trash.feature
- src/lib/Behat/PageObject/RolePage.php
Required for https://travis-ci.org/github/ezsystems/ezplatform/builds/715325679
Failing jobs on PostgreSQL: 
- https://travis-ci.org/github/ezsystems/ezplatform/jobs/715262666
- https://travis-ci.org/github/ezsystems/ezplatform/jobs/715325691
There are two types of errors in that build:
- Case sensitivity:
```
Given I create "Folder" Content items in "/Media/Files/" in "eng-GB"             # EzSystems\BehatBundle\Context\Object\ContentContext::createContentItems()
| name               | short_name         |
| TestFolderToRemove | TestFolderToRemove |
eZ\Publish\Core\Persistence\Legacy\Exception\TypeNotFound: Could not find 'eZ\Publish\SPI\Persistence\Content\Type' with identifier 'ID: Folder, Status: 0' in vendor/ezsystems/ezpublish-kernel/eZ/Publish/Core/Persistence/Legacy/Content/Type/Ha …
```
> [Behat] Fixed tests running on PostgreSQL

- src/bundle/Resources/views/themes/admin/ui/search/list_item.html.twig
| Tickets       | [EZP-31777](https://jira.ez.no/browse/EZP-31777)
This PR is a direct follow up of v2.5 PR but for v3.1: https://github.com/ezsystems/ezplatform-admin-ui/pull/1443
Required PR: https://github.com/ezsystems/ezplatform-search/pull/9
Regression suite: https://github.com/ezsystems/ezplatform-page-builder/pull/637
> EZP-31777: Added resolved 'locationId' to '_ez_content_view' path in Search module

- features/standard/CleanTrash.feature
- features/standard/Trash.feature
- src/lib/Behat/BusinessContext/TrashContext.php
| Tickets       | https://jira.ez.no/browse/EZP-31796
| Bug fix?      | in tests?
Failing build: https://travis-ci.com/github/ezsystems/ezplatform-page-builder/jobs/369564566
There are tests failing in nightly builds because they are checking that items are present in the Trash - this fails when the Trash is cleaned inbetween the Steps. (see JIRA ticket for more information)
I've decided to extract the Scenario emptying the Trash into a separate, single Feature - this causes it to run as the last one, which makes interference less likely.
> [Behat] Extracted Scenario emptying Trash

- src/lib/Behat/BusinessContext/TrashContext.php
This PR fixes incorrect upstream merge of https://github.com/ezsystems/ezplatform-admin-ui/pull/1447:
`utilityContext` has been replaced by `browserContext`
> [Behat] Fixed incorrect TrashContext merge

- src/lib/Behat/PageElement/Fields/Keywords.php
| Tickets       | https://jira.ez.no/browse/EZEE-3235
Passing 5 PostreSQL jobs: https://travis-ci.org/github/ezsystems/ezplatform-admin-ui/builds/718918387
Another 5 PostgreSQL jobs passing: https://travis-ci.org/github/ezsystems/ezplatform-admin-ui/builds/718941332
Failure this PR is trying to solve: https://travis-ci.org/github/ezsystems/ezplatform/jobs/717786184
```
Wrong page title.
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'first keyword, second, edit'
+'second, first keyword, edit'
```
When editing a …
> [Behat] Adapted Behat tests for PostgreSQL

- src/bundle/Resources/views/themes/admin/ui/dashboard/tab/all_content.html.twig
- src/bundle/Resources/views/themes/admin/ui/dashboard/tab/all_media.html.twig
- src/bundle/Resources/views/themes/admin/ui/dashboard/tab/my_content.html.twig
- src/bundle/Resources/views/themes/admin/ui/dashboard/tab/my_media.html.twig
- src/lib/Tab/Dashboard/PagerContentToDataMapper.php
| Tickets       | https://jira.ez.no/browse/EZP-31776
Dashboard Content should have resolved `LocationId` attribute passed to `_ez_content_view` path.
This PR is a direct follow up of https://github.com/ezsystems/ezplatform-admin-ui/pull/1443 but for v3.1
> EZP-31776: Resolved Contents' Locations in Dashboard

- src/bundle/Resources/public/js/scripts/fieldType/base/base-preview-field.js
- src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js
| Tickets       | https://jira.ez.no/browse/EZEE-3239
Unless there is different way to do this, I need those here:
https://github.com/ezsystems/ezplatform-connector-dam/pull/4
> EZEE-3239: Added additional event to show asset preview

- src/lib/Behat/Helper/TestLogProvider.php
| Tickets       | https://jira.ez.no/browse/EZP-31836
More details in JIRA issue, but we simply need to check whether the session is started before browser logs can be accessed.
> [Behat] Added check that session is started before browser logs are accessed

- src/lib/Behat/PageElement/SubItemsList.php
- src/lib/Behat/PageElement/Tables/SubItemsTable.php
- src/lib/Behat/PageObject/ContentItemPage.php
| Tickets       |  https://jira.ez.no/browse/EZP-31839
Please see Jira issue for a list of failing builds.
Sometimes our tests are unable to find a Content Item when navigating through subitems - I suspect this is a similar issue to https://github.com/ezsystems/ezplatform-admin-ui/pull/1184 , where the list of Subitems is modified by Scenarios running in parallel.
This solution sorts the Subitems by Modification date (descending), hoping that the item the tests are looking for is created recently and will be displayed on the first …
> [Behat] Added sorting subitems by Modified date before navigating

- src/lib/Behat/PageElement/SubItemsList.php
- src/lib/Behat/PageElement/Tables/SubItemsTable.php
- src/lib/Behat/PageElement/Tables/SubitemsGridList.php
- src/lib/Behat/PageObject/ContentItemPage.php
| Tickets       | https://jira.ez.no/browse/EZP-31839
Follow up to: https://github.com/ezsystems/ezplatform-admin-ui/pull/1479
Failing job: https://travis-ci.org/github/ezsystems/ezplatform-admin-ui/jobs/726265092
```
Given I navigate to content "Files" of type "Folder" in "Media"                # EzSystems\EzPlatformAdminUi\Behat\BusinessContext\NavigationContext::iNavigateToContent()
Behat\Testwork\Call\Exception\FatalThrowableError: Fatal error: Call to undefined method …
```
> [Behat] Adapted tests to subitems grid view which cannot be sorted

- src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
| Tickets       | https://jira.ez.no/browse/EZP-31852
Now UDW should have already selected locations when user is returning to collection block settings.
> EZP-31852: Fixed selectedLocations prop in UDW

- src/lib/Behat/PageElement/ContentTypePicker.php
- src/lib/Behat/PageObject/ContentItemPage.php
| Tickets       | https://jira.ez.no/browse/EZP-31856
See JIRA ticket for failing builds.
This is our most common issue in tests - the Content Type created by the API is not visible in Content Type picker. This is a highly random issue, because all of our Content Types in tests are created the same way. Most of the time everything is correct, but sometimes some Content Types are not loaded by the Content Type picker.
This PR does not solve the issue, but may help us get more data about it so we can make further improvements.
Since this looks …
> [Behat] Added reloading of the page when Content Type is not present in picker

- src/bundle/Resources/views/themes/admin/trash/list.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-31844
> EZP-31844: Trash Management screen - Display creator name and not ID in the table

- src/bundle/Resources/public/scss/_login.scss
- src/bundle/Resources/translations/messages.en.xliff
- src/bundle/Resources/views/themes/admin/account/forgot_password/index.html.twig
- src/bundle/Resources/views/themes/admin/account/login/index.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-31880
> EZP-31880: Login screen - change the order of items found by access key

- src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezdate.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-31906
> EZP-31906: Date fields automatically set to current date in Edit mode

- src/bundle/Resources/public/scss/fieldType/edit/_ezrichtext.scss
| Tickets       | https://jira.ez.no/browse/EZP-31890
> EZP-31890: CT - ezrichtext field takes too much space

- src/bundle/Resources/public/scss/_tables.scss
- src/bundle/Resources/views/themes/admin/content_type/content_type_group/list.html.twig
- src/bundle/Resources/views/themes/admin/content_type/list.html.twig
- src/bundle/Resources/views/themes/admin/language/index.html.twig
- src/bundle/Resources/views/themes/admin/language/list.html.twig
- src/bundle/Resources/views/themes/admin/object_state/list.html.twig
- src/bundle/Resources/views/themes/admin/object_state/object_state_group/list.html.twig
- src/bundle/Resources/views/themes/admin/section/assigned_content.html.twig
- src/bundle/Resources/views/themes/admin/section/list.html.twig
- src/bundle/Resources/views/themes/admin/section/view.html.twig
- src/bundle/Resources/views/themes/admin/url_wildcard/list.html.twig
- src/bundle/Resources/views/themes/admin/user/policy/list.html.twig
- src/bundle/Resources/views/themes/admin/user/role/list.html.twig
- src/bundle/Resources/views/themes/admin/user/role_assignment/list.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-31923
- [x ] Coding standards (`$ composer fix-cs`)
> EZP-31923: [Trash] Restore's and Delete buttons are displayed too close to each other

- src/bundle/Resources/public/scss/fieldType/edit/_base-preview.scss
| Tickets       | https://jira.ez.no/browse/EZP-31915
> EZP-31915: CT - ezimageasset - tooltips font too large

- src/bundle/Resources/public/scss/_tables.scss
- src/bundle/Resources/views/themes/admin/link_manager/view.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-31907
> EZP-31907: Link details view in URL Management is not properly styled

- src/bundle/Resources/public/scss/_buttons.scss
- src/bundle/Resources/public/scss/_tag.scss
| Tickets       | https://jira.ez.no/browse/EZEE-3271
> EZEE-3271: Fixed styles for 'Send to review' action menu

- src/bundle/Resources/views/themes/admin/account/bookmarks/list.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-31888
> EZP-31888: Bookmarks page header and item placement are not adjusted to other page views

- src/bundle/Resources/public/js/scripts/fieldType/ezauthor.js
| Tickets       | https://jira.ez.no/browse/EZP-31896
> EZP-31896: CT - ezauthor - tooltips have different fonts between lines

- src/bundle/Resources/views/themes/admin/link_manager/view.html.twig
- src/bundle/Resources/views/themes/admin/url_management/url_management.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-31946
> EZP-31946: Added missing 'Admin' to breadcrumbs and set correct margin for URL Management

- src/lib/UniversalDiscovery/Event/Subscriber/RichTextEmbedAllowedContentTypes.php
| Tickets       | [https://jira.ez.no/browse/EZP-31783](https://jira.ez.no/browse/EZP-31783)
> EZP-31783: Fixed embedding Content with read permissions

- src/lib/Pagination/Mapper/AbstractPagerContentToDataMapper.php
- src/lib/Tab/Dashboard/PagerContentToDataMapper.php
| Tickets       | [EZP-31767](https://jira.ez.no/browse/EZP-31767)
Currently, on content view page, we have displayed name of user who last edited the content.
But creator name displayed as a contributor on the dashboard (In common content block)
I would expect to see name of user who last edited the content.
> EZP-31767: Use version contributor name on dashboard

- src/bundle/Resources/public/js/scripts/admin.content.edit.js
- src/bundle/Resources/public/scss/_content-edit.scss
- src/bundle/Resources/public/scss/_header.scss
- src/bundle/Resources/translations/content_create.en.xliff
- src/bundle/Resources/translations/content_edit.en.xliff
- src/bundle/Resources/translations/messages.en.xliff
- src/bundle/Resources/translations/user_edit.en.xliff
- src/bundle/Resources/views/themes/admin/content/create/create.html.twig
- src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
- src/bundle/Resources/views/themes/admin/content/page_title_edit.html.twig
- src/bundle/Resources/views/themes/admin/ui/on_the_fly/create_on_the_fly.html.twig
- src/bundle/Resources/views/themes/admin/ui/on_the_fly/edit_on_the_fly.html.twig
- src/bundle/Resources/views/themes/admin/user/create.html.twig
- src/bundle/Resources/views/themes/admin/user/edit.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-31887 
|| https://jira.ez.no/browse/EZP-31846
> EZP-31887: Added missing header informations in create/edit content/user

- src/lib/Tests/UniversalDiscovery/Event/Subscriber/RichTextEmbedAllowedContentTypesTest.php
- src/lib/UniversalDiscovery/Event/ConfigResolveEvent.php
- src/lib/UniversalDiscovery/Event/Subscriber/RichTextEmbedAllowedContentTypes.php
| Tickets       | https://jira.ez.no/browse/EZP-31783
Follow up for https://github.com/ezsystems/ezplatform-admin-ui/pull/1441. Fixed few issues in previous implementation:
* Accessing unexciting `restrictedContentTypesIdentifier` property (see https://github.com/ezsystems/ezplatform-admin-ui/commit/81de433dd0f310461fd73c61e522d1e2b15d6f9f#diff-9dd2d0d839357c185ad9fc0a1d78a44aR99)
* "TypeError: Argument 1 passed to iterator_to_array() must implement interface Traversable, array given"  throw in …
> EZP-31783: Fixed RichTextEmbedAllowedContentTypes subscriber implementation

- src/lib/Permission/PermissionChecker.php
| Tickets       | https://jira.ez.no/browse/EZP-31814
Users with "Content/Edit, Limitation: Owner" security role are unable to use the UDW.
More details: https://jira.ez.no/browse/EZP-31814
> EZP-31814: Self owner limitation in a security role breaks the UDW

- composer.json
- src/bundle/Resources/translations/messages.en.xliff
- src/bundle/Resources/views/themes/admin/account/forgot_password/index.html.twig
| Tickets       | [EZP-31462](https://jira.ez.no/browse/EZP-31462)
| Required by  | ezsystems/ezplatform-user#75 ezsystems/ezplatform#593
In order to have better UX, when a user needs to reset password  because of unsupported password hash type, there was  added a message on route `admin/user/forgot-password/migration` analogous to `user/forgot-password/migration`
> EZP-31462: Added particular message when reset password reason in migration

- src/lib/Permission/PermissionChecker.php
| Tickets       | https://jira.ez.no/browse/EZP-31782
PermissionChecker caches policy limitations incorrectly. Please note https://github.com/ezsystems/ezplatform-admin-ui/pull/1441 depends on this PR.
More info:
- https://jira.ez.no/browse/EZP-31782
- https://github.com/ezsystems/ezplatform-admin-ui/security/advisories/GHSA-w355-8mff-w525
> EZP-31782: PermissionChecker caches policy limitations incorrectly

- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_breadcrumbs.scss
| Tickets       | https://jira.ez.no/browse/EZP-31966
> EZP-31966: Added underline and ibexa-color-primary for hover breadcrumb in UDW

- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_content.meta.preview.scss
| Tickets       | https://jira.ez.no/browse/EZP-31964
> EZP-31964: Set smaller (50%) padding between title and edit meta information button in UDW

- src/lib/Tab/Event/Subscriber/ConditionalTabSubscriber.php
| Tickets       | https://jira.ez.no/browse/EZP-31983
> EZP-31983: Catched exception thrown by empty tab group

- src/bundle/Resources/views/themes/admin/ui/on_the_fly/edit_on_the_fly.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-31984
> EZP-31984: Create/Edit on the fly footer is still visible after canceling by X button

- src/bundle/Resources/config/services/rest.yaml
- src/lib/REST/Security/AdminRESTRequestMatcher.php
- src/lib/REST/Security/NonAdminRESTRequestMatcher.php
- src/lib/Tests/REST/Security/NonAdminRESTRequestMatcherTest.php
| Tickets       | [EZP-31875](https://jira.ez.no/browse/EZP-31875)
This PR introduces a `RequestMatcher` that is needed for https://github.com/ezsystems/ezplatform-rest/pull/54.
I'm happy to change the class name if someone has any better ideas.
> EZP-31875: Added request matcher to recognize REST requests executed in AdminUI context

- src/bundle/Resources/public/scss/core/_custom.tooltip.scss
JIRA ref: https://jira.ez.no/browse/EZEE-3296
> EZEE-3296: Added ground-dark tooltip

- src/bundle/Controller/ContentTypeController.php
- src/bundle/Resources/config/routing.yaml
- src/bundle/Resources/encore/ez.js.config.js
- src/bundle/Resources/public/js/scripts/admin.contenttype.copy.js
- src/bundle/Resources/translations/content_type.en.xliff
- src/bundle/Resources/views/themes/admin/content_type/list.html.twig
- src/bundle/Resources/views/themes/admin/content_type/macros.html.twig
- src/lib/Form/Data/ContentType/ContentTypeCopyData.php
- src/lib/Form/Factory/ContentTypeFormFactory.php
- src/lib/Form/Type/ContentType/ContentTypeCopyType.php
| Tickets       | [EZP-31801](https://jira.ez.no/browse/EZP-31801)
This PR implements ContentType copy feature in the admin.
> As an Editor, I want to be able to copy the content type in admin interface

- src/bundle/Resources/public/scss/_buttons.scss
| Tickets       | https://jira.ez.no/browse/EZP-31924
> EZP-31924: Bookmarks barely fit in the left side menu

- features/standard/ContentDraft.feature
- src/bundle/Resources/views/themes/admin/content/page_title_edit.html.twig
| Tickets       | [EZP-32003](https://jira.ez.no/browse/EZP-32003)
**Steps to reproduce:**
1. Start editing the root location in admin UI
2.  Click on the "cancel" button in the top left
**Expected result:**
User is redirected to the full view page
**Actual result:**
The following error is shown:
```
Return value of eZ\Publish\Core\Repository\Values\Content\Content::getContentType() must be an instance of eZ\Publish\API\Repository\Values\ContentType\ContentType, null returned
```
> EZP-32003: Fix cancel editing redirect for root location

- src/bundle/Controller/ContentController.php
- src/bundle/Controller/ContentOnTheFlyController.php
- src/bundle/Controller/UserOnTheFlyController.php
- src/bundle/Resources/config/routing.yaml
- src/bundle/Resources/config/services/controllers.yaml
- src/lib/Event/ContentProxyCreateEvent.php
- src/lib/Event/Options.php
- src/lib/EventListener/ContentProxyCreateDraftListener.php
| Tickets       | https://jira.ez.no/browse/EZP-31784
Enable Autosave feature for Content on the Fly.
> EZP-31784: Enable autosave feature for Content on the Fly

- src/bundle/Resources/translations/content_type.en.xliff
- src/lib/Form/Type/ContentType/ContentTypeUpdateType.php
| Tickets       | https://jira.ez.no/browse/EZP-31904
> EZP-31094: Fixed unnecessary ":" in Content Type translations

- src/bundle/Resources/views/themes/admin/content_type/edit.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-32033
> EZP-32033: Wrong caret icon size on Content Type Edit view

- src/bundle/Resources/views/themes/admin/content/draft/draft_list.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-32034
> EZP-32034: Draft list view has a wrong padding for container and table

- src/bundle/Resources/public/scss/_tables.scss
| Tickets       | https://jira.ez.no/browse/EZP-32041
> EZP-32041: No left margin when empty table with icons

- src/bundle/Resources/public/scss/_content-edit.scss
- src/bundle/Resources/public/scss/fieldType/edit/_ezrichtext.scss
- src/bundle/Resources/public/scss/mixins/_inputs.scss
| Tickets       | https://jira.ez.no/browse/EZP-32047
> EZP-32047: Errors in forms should use danger color not primary

- src/bundle/Resources/public/scss/_trash-search-form.scss
| Tickets       | https://jira.ez.no/browse/EZP-32051
> EZP-32051: Remove icon is not centered in trash filter

- src/bundle/ui-dev/src/modules/universal-discovery/components/content-edit-button/content.edit.button.js
- src/bundle/ui-dev/src/modules/universal-discovery/content.meta.preview.module.js
| Tickets       | https://jira.ez.no/browse/EZP-32053
> EZP-32053: Missing hover state in content meta preview button in UDW

- composer.json
- src/lib/Menu/MainMenuBuilder.php
| Tickets       | [EZP-32038](https://jira.ez.no/browse/EZP-32038)
Excerpt from JIRA:
>System information tab should be moved from MainMenuBuilder.php to the dedicated listener within ez-support-tools to be aligned with other bundles practices.
> EZP-32038: Move System information tab to ez-support-tools

- src/bundle/Resources/public/scss/_buttons.scss
| Tickets       | https://jira.ez.no/browse/EZEE-3316
> EZEE-3316: Disabled button should have opacity 0.3 not 1

- src/bundle/Resources/views/themes/admin/link_manager/list.html.twig
| Tickets       | https://jira.ez.no/browse/EZP-32056
> EZP-32056: Wrong margin for Search button in the URL management list

- src/bundle/ui-dev/src/modules/sub-items/services/sub.items.service.js
| Tickets       | https://jira.ez.no/browse/EZP-31039
As the title states.
Related `ezplatform-rest` PR: https://github.com/ezsystems/ezplatform-rest
Parent `ezplatform-admin-ui-modules` PR: https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/287
> EZP-31039: Remove unnecessary sorting params when updating Location priority

- composer.json
- src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
| Tickets       | https://jira.ez.no/browse/EZEE-3324
> EZEE-3324: Form Builder: missing design for checkbox field in the Form preview

- composer.json
| Bug fix?      | sort of
This reverts commit 2a57e16bc20f3e6847673419c9e8370b37bbea86.
Reverting changes from https://github.com/ezsystems/ezplatform-admin-ui/pull/1629 that should not land in 2.2 branch (they are meant for master only).
> Revert "[Composer] Set metarepo branch for tests and requirements for master branch"

- features/standard/SystemInfo.feature
- src/lib/Behat/PageObject/SystemInfoPage.php
| Tickets       | https://jira.ez.no/browse/EZP-32097
In https://github.com/ezsystems/ez-support-tools/pull/69 the default tab opened when accessing "System Information" changed - it used to be the "Composer" tab, now it's "My Ibexa".
Adapted the tests for that and added a simple test that makes sure the tab is displayed. Also adding a `systemInformation` tab so we can run these tests only (used by https://github.com/ezsystems/ez-support-tools/pull/72)
> [Behat] Adapted tests for the new System Information tab

- src/lib/Specification/Location/IsWithinCopySubtreeLimit.php
We only need size of the subtree, not actual search results, to check if given subtree is within copy subtree limit in `EzSystems\EzPlatformAdminUi\Specification\Location\IsWithinCopySubtreeLimit::isSatisfiedBy`
> Limited subtree results to 0 in IsWithinCopySubtreeLimit::isSatisfiedBy

- src/bundle/Resources/public/js/scripts/core/custom.dropdown.js
- src/bundle/Resources/views/themes/admin/ui/component/custom_dropdown.html.twig
| Tickets       | https://issues.ibexa.co/browse/EZP-32170
> EZP-32170: Fixed policy limitation custom dropdown

- src/bundle/Resources/translations/time_diff.en.xliff
- src/bundle/Templating/Twig/FormatIntervalExtension.php
| Tickets       | https://issues.ibexa.co/browse/EZP-32135
PHP:
```php
$someDateInterval = new DateInterval('P1Y3DT10M');
```
Twig: `{{ some_date_interval|format_interval }}`
Result: `1 year 3 days 10 minutes`
Translatable.
> EZP-32135: Twig helper to to display interval in a human readable format

- composer.json
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **Type**                                   | feature
| **Target eZ Platform version** | `v3.3`
| **BC breaks**                          | yes
| **Doc needed**                       | yes
Bumped `willdurand/js-translation-bundle` package to ^4.0 to support Symfony 5.2.
Otherwise it would crash:
```
- Configuring symfony/webpack-encore-bundle (>=1.6): From github.com/symfony/recipes:master
Executing script cache:clear [KO]
[KO]
Script cache:clear returned with error code 1
!!
!!  In TranslationResourceFilesPass.php line 58:
!!
!!    Warning: array_merge(): Expected parameter 2 to be an array, object given
!!
!!
!!
Script @auto-scripts was called via post-update-cmd
```
3.3 …
> [Composer] Bumped BazingaJsTranslationBundle to ^4.0

- src/lib/Behat/PageObject/UserCreationPage.php
Upstream changes for https://github.com/ezsystems/ezplatform-admin-ui/pull/1652 :
The title page (also selector used to find it) is different after the redesign (3.2).
Failing build: https://travis-ci.com/github/ezsystems/ezplatform-admin-ui/builds/206551935
> [Behat] Adjusted title in UserCreationPage

- src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimageasset.html.twig
| Tickets       | https://issues.ibexa.co/browse/EZEE-3383
https://github.com/ezsystems/ezplatform-connector-dam/pull/26
> EZEE-3383: Additional data is now obtainable from html dataset

- src/lib/Behat/PageElement/ContentField.php
| Tickets       | [EZP-32212](https://issues.ibexa.co/browse/EZP-32212)
Related PR: https://github.com/ezsystems/ezplatform-matrix-fieldtype/pull/45
Passed tests: https://travis-ci.com/github/ezsystems/ezplatform-page-builder/builds/207258337
> EZP-32212: Changed class to correct recognition ezmatrix fieldType

- src/bundle/Resources/views/content/tab/locations/tab.html.twig
EZP-32210 - Allow to click on objects multiple locations labels (paths)
| Tickets       |  https://issues.ibexa.co/browse/EZP-32210
> EZP-32210  objects multiple locations labels

- src/bundle/Resources/views/themes/admin/ui/layout.html.twig
| Tickets       | https://issues.ibexa.co/browse/EZP-32216
> EZP-32216: As a Maintainer, I want to use chartjs and js-md5

- src/bundle/Resources/views/themes/admin/content/content_view_fields.html.twig
| Tickets       | [EZP-31659](https://issues.ibexa.co/browse/EZP-31659)
Adds the location as an extra parameter to `ez_render_field`. Used by the query field (ezsystems/ezplatform-query-fieldtype#38) to render the results for the current location, but may also apply to other fields who depend on it.
> Added location parameter to ez_render_field

- src/lib/Tests/UniversalDiscovery/Event/Subscriber/RichTextEmbedAllowedContentTypesTest.php
- src/lib/UniversalDiscovery/Event/Subscriber/RichTextEmbedAllowedContentTypes.php
| Tickets       | https://issues.ibexa.co/browse/EZP-32173
When 'allowed_content_types' was specified in the .yml config it wasn't taken into consideration. This has been fixed in this PR.
> EZP-32173: Fixed UDW 'allowed_content_types' configuration

- src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js
- src/bundle/Resources/translations/fieldtypes_edit.en.xliff
| Tickets       | https://issues.ibexa.co/browse/EZP-32193
> EZP-32193: Map location validation error message typo

- src/bundle/Resources/public/scss/fieldType/edit/_ezselection.scss
| Tickets       | https://issues.ibexa.co/browse/EZP-32225
> EZP-32225: Dropdown is not properly styled for content type with field ezselection

- src/bundle/Resources/views/themes/admin/ui/component/preview_unavailable.html.twig
| Tickets       | https://issues.ibexa.co/browse/EC-277
> EC-277: Components notification message is not aligned to the left

- src/bundle/Resources/public/js/scripts/fieldType/ezimage.js
> EC-288: Uncaught TypeError: Cannot read property focus of undefined

- src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimage.html.twig
- src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimageasset.html.twig
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | EZEE-3397
| **Type**                                   | feature
| **Target eZ Platform version** | `v3.3`
| **BC breaks**                          | no
| **Doc needed**                       | no
> EZEE-3397: Added fieldDefId & contentId to image editor button

- src/bundle/Resources/public/scss/_pagination.scss
- src/bundle/Resources/public/scss/ui/modules/sub-items-list/_main.scss
| Tickets       | https://issues.ibexa.co/browse/EZP-32223
> EZP-32223: Certain Back Office languages can break pager labels

- src/bundle/ui-dev/src/modules/content-tree/components/content-tree/content.tree.js
- src/bundle/ui-dev/src/modules/content-tree/content.tree.module.js
| Tickets       | https://issues.ibexa.co/browse/EZP-32248
> EZP-32248: Retain content tree state

- src/bundle/Resources/views/themes/admin/account/base.html.twig
| Tickets       | https://issues.ibexa.co/browse/EZP-32252
> EZP-32252: Wrong documentation link in login screen

- src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js
- src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimageasset.html.twig
> EZEE-3419: Fixed providing empty object instead of empty array when no data set

- src/bundle/Resources/public/scss/_links.scss
- src/bundle/Resources/views/themes/admin/account/base.html.twig
| Tickets       | https://issues.ibexa.co/browse/EZP-32253
> EZP-32253: Wrong links hover on login screen

- src/bundle/Resources/public/js/scripts/admin.content.edit.js
| Tickets       | https://issues.ibexa.co/browse/EZP-32117
> EZP-32117: [UI][UX] Content Field validation error is not auto-scrolled to when it occurs on a non-focused tab

- src/bundle/Resources/views/themes/admin/account/login/index.html.twig
| Question | Answer |
| --- | --- |
| Tickets | \- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Tests pass? | yes |
| Doc needed? | yes |
| License | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE) |
In order to simplify login form template (`src/bundle/Resources/views/themes/admin/account/login/index.html.twig`) customization:
*   Restructured template using blocks
*   Added `login-form-before` and `login-form-after` components groups
Assuming that as a Developer I would like to would like to add "Login via XYZ" button to login form. 
1.  Create  `/templates/login_via_oauth2.html.twig`
```twig
<div class="row mt-4">
<div class="col">
<p class="text-center">or</p>
<div class="btn-group d-flex">
<a href="#" class="btn btn-primary mr-1"> …
```
> Simplify login form view customization

- src/bundle/Resources/public/js/scripts/core/custom.dropdown.js
- src/bundle/Resources/public/scss/core/_custom.dropdown.scss
| Tickets       | https://issues.ibexa.co/browse/EZP-32180
> EZP-32180: Some of the selection list elements are not visible

- src/bundle/Resources/views/themes/admin/link_manager/edit.html.twig
| Tickets       | https://issues.ibexa.co/browse/EZP-32287
Added missing html container `.ez-sticky-container`
> EZP-32287: Wrong size of a Save tile on the URL management edit page

- src/bundle/Resources/public/js/scripts/fieldType/base/base-file-field.js
- src/bundle/Resources/public/js/scripts/fieldType/ezbinaryfile.js
- src/bundle/Resources/public/js/scripts/fieldType/ezimage.js
- src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js
- src/bundle/Resources/public/js/scripts/fieldType/ezmedia.js
| Tickets       | https://issues.ibexa.co/browse/EZEE-3455
> EZEE-3455: [Image upload] no validation message for files bigger than 2mb

- src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimage.html.twig
| Tickets       | https://issues.ibexa.co/browse/EZEE-3459
> EZEE-3459: Cannot use image editor in product content type

- src/lib/Menu/ContentRightSidebarBuilder.php
- src/lib/UI/Value/ValueFactory.php
| Tickets       | https://issues.ibexa.co/browse/EZP-32321
| Related PR   | https://github.com/ezsystems/ezpublish-kernel/pull/3084
A bug occurs how long a policy `content/remove` has a language limitation. If 'initialLanguageCode' of content is the same as one of the allowed languages then the user can delete content. Because initial language code is set when content is edited in given language behavior is nondeterministic. To eliminate this bug additional "target" should be passed as an argument when the permission check I performed. …
> EZP-32321: Added deleteTranslations target to fix 'content/remove' permission check

- src/lib/Siteaccess/AbstractSiteaccessPreviewVoter.php
- src/lib/Tests/Siteaccess/AdminSiteaccessPreviewVoterTest.php
| Tickets       | https://issues.ibexa.co/browse/EZEE-3465
As the title states.
Required `ezpublish-kernel` PR: https://github.com/ezsystems/ezpublish-kernel/pull/3085
Regression suite: https://github.com/ezsystems/ezplatform-page-builder/pull/726
PR is redone in order to fix rebase of https://github.com/ezsystems/ezplatform-admin-ui/pull/1704
> EZEE-3465: Made SiteaccessPreviewVoter repository aware

- src/bundle/Controller/ContentViewController.php
- src/lib/Form/Type/ChoiceList/Loader/ContentEditTranslationChoiceLoader.php
- src/lib/Form/Type/Content/Translation/TranslationAddType.php
- src/lib/Tab/LocationView/TranslationsTab.php
| Tickets       | https://jira.ez.no/browse/EZP-32308
Based on:
https://github.com/ezsystems/ezpublish-kernel/pull/3083
At least one valid `Location` object is needed to properly solve LocationLimitation (content/edit).
> EZP-32308: Passed mandatory Location into LocationLimitation

- src/bundle/Controller/LocationController.php
- src/bundle/Resources/public/scss/_modals.scss
- src/bundle/Resources/translations/locationview.en.xliff
- src/bundle/Resources/views/content/tab/locations/tab.html.twig
| Tickets       | [EZP-32294](https://issues.ibexa.co/browse/EZP-32294)
JIRA excerpt:
>When removing a location of an object, all child nodes will be removed, too. This happens silently and without going to the trash.
The frontend (CSS) part relates to modals' content: when the text is too long, it overflows the modal. This remark applies only to 2.5 so this change will be dropped on merge-up.
> EZP-32294: Location removal removes all children silently and unreversable

- src/lib/Tab/LocationView/UrlsTab.php
| Tickets       | https://issues.ibexa.co/browse/EZP-32338
Currently user is able to manage translations in all available languages but the list of url aliases is filter out (incompletely^) to `ezpublish.system.<scope>.languages`, which is misleading for users (see linked JIRA issue). This PR changes this behaviour to always show all available url aliases. 
^url alias for language out side of the `ezpublish.system.<scope>.languages` will be displayed on the list when it's exactly the same as one of the configured languages:
> EZP-32338: List url aliases for all available translations

- src/bundle/Resources/public/js/scripts/core/custom.dropdown.js
| Tickets       | [EZP-32311](https://issues.ibexa.co/browse/EZP-32311)
JIRA excerpt:
>When a Create a new translation window is shown and more than 6 Languages are defined, some of them won't be visible in the "Select a language for the new translation" field.
The idea is to check whether any of the dropdown parents is a modal (not to break dropdowns outside popups) and reduce the dropdown's height to not exceed the modal's height. Thanks to that, a scroll will appear allowing the user to select bottom options that are currently being …
> EZP-32311: Dropdown bottom options become inaccessible inside modals

- src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js
- src/lib/UniversalDiscovery/Event/Subscriber/ImageAssetAllowedContentTypes.php
| Tickets       | https://issues.ibexa.co/browse/EZEE-3486
This had nothing to do with unsplash, or dam connector.
From what I understand allowed CTs were passed here `ezplatform-admin-ui/src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js L178`
```
ReactDOM.render(
React.createElement(eZ.modules.UniversalDiscovery, {
onConfirm,
onCancel,
title,
allowedContentTypes: [imageAssetMapping['contentTypeIdentifier']],
...config,
}),
udwContainer
);
```
But since that key now exist with default value, this part is overridden by it.
> EZEE-3486: Added AllowedContentTypes to default config as it was overridden by default empty value

- src/lib/Event/ContentProxyCreateEvent.php
- src/lib/Event/ContentProxyTranslateEvent.php
- src/lib/Tests/EventListener/ContentProxyCreateDraftListenerTest.php
| Tickets       | https://issues.ibexa.co/browse/EZEE-3484
> EZEE-3484: Added missing PHPUnit tests

- src/lib/Behat/BusinessContext/ContentViewContext.php
Failing builds:
https://travis-ci.com/github/ezsystems/ezplatform/jobs/489625249 (v2)
https://travis-ci.com/github/ezsystems/ezplatform-page-builder/jobs/490255179 (v3.3)
Error:
```
@javascript @common
Scenario: Element in trash can be restored                                               # vendor/ezsystems/ezplatform-admin-ui/features/standard/Trash.feature:41
Given I click on the left menu bar button "Trash"                                      # EzSystems\EzPlatformAdminUi\Behat\BusinessContext\LeftMenuContext::iClick …
```
> [Behat] Added sorting subitems by Modified date

- src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/base-fixed.js
- src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/base-table.js
- src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/base.js
| Tickets       | [EZP-31632](https://issues.ibexa.co/browse/EZP-31632)
This PR is port from this PR: https://github.com/ezsystems/ezplatform-richtext/pull/148
> EZP-31632: Floating table toolbar

- src/bundle/Resources/public/js/scripts/admin.content.tree.js
> EZP-32396: Content tree doesn't expand to current location

- src/bundle/Controller/ContentViewController.php
- src/bundle/Resources/views/content/locationview.html.twig
- src/bundle/Resources/views/content/tab/locations/tab.html.twig
| Tickets       | https://issues.ibexa.co/browse/EZP-32395
`supplyIsLocationInvisible` method is not really necessary, we can easily check if the `Location` is hidden in the twig itself + it shows invalid data as it only accounts for a single `Location`.  A small performance increase is an upside as well.
> EZP-32395: Sort out Locations tab info on visibility

- composer.json
UDW, Sub-items list and config provider use json_* functions so ext-json should be declared as dependency.
> Added ext-json to dependencies

- src/bundle/Resources/views/content/locationview.html.twig
| Tickets       | https://issues.ibexa.co/browse/EZP-32395
Fixes BC as `not` keyword was missing. Direct continuation of https://github.com/ezsystems/ezplatform-admin-ui/pull/1725.
> EZP-32395: Fixed location visibility due to kept BC

- src/bundle/Resources/views/fieldtypes/edit/ezdate.html.twig
| Tickets       | https://issues.ibexa.co/browse/EZP-32397
| Bugfix?      | yes
This PR requires: https://github.com/ezsystems/repository-forms/pull/344
This PR removes logic from the template https://github.com/ezsystems/ezplatform-admin-ui/blob/v1.5.17/src/bundle/Resources/views/fieldtypes/edit/ezdate.html.twig#L10  as it is no longer needed (see https://github.com/ezsystems/repository-forms/pull/344)
> [EZP-32397] Removed logic from ezdate.html.twig

- src/bundle/Resources/views/themes/admin/content/edit/base.html.twig
| Tickets       | [IBX-183](https://issues.ibexa.co/browse/IBX-183)
Tab ids coming from custom category names containing spaces make tabs inaccessible. The idea is to sanitize them by replacing spaces with hyphens to match current `item-` notation.
> IBX-183: Fixed accessing Tabs with spaces and special characters

- src/bundle/Controller/ContentViewController.php
- src/lib/Specification/Content/ContentHaveUniqueRelation.php
| Tickets       | https://issues.ibexa.co/browse/IBX-251
See JIRA issue for more details.
> IBX-251: Replaced eZ\Publish\API\Repository\ContentService::loadReverseRelations usages

- src/bundle/Resources/public/js/scripts/fieldType/base/base-rich-text.js
| Tickets       | [EZP-32400](https://issues.ibexa.co/browse/EZP-32400)
SVG icon representing anchor is placed outside table by the AlloyEditor, hence is not saved alongside with the content. Therefore the icon is not presented in the edit mode.
> EZP-32400: Fixed displaying anchors for tables

- src/bundle/Resources/config/services/modules/content_tree.yaml
- src/lib/UI/Module/ContentTree/NodeFactory.php
The `load-subtree` endpoint can become very slow in big projects when there are multiple Content Tree nodes expanded.
With every new tree expanded, the load time grows significantly. 
Reasons behind the slowness:
1. Counting child number for every single visible node using `SearchService::findLocations` with `$searchQuery->performCount = true;`
2. Initialization of Content Proxy objects - when for example 1000 nodes are displayed in the tree, every single node is loaded separately from SPI.
This PR optimizes `NodeFactory` to improve the overall response times for `load-subtree` endpoint by limiting `countSubitems` action to only those Nodes, that ContentType is a container (reducing unnecessary `countSubitems` calls), by relying on `$location->getContentInfo();` instead of …
> Boosted performance of NodeFactory

- src/bundle/Resources/public/js/scripts/admin.location.view.js
- src/bundle/Resources/public/js/scripts/admin.trash.js
- src/bundle/Resources/translations/content.en.xliff
- src/bundle/Resources/views/content/locationview.html.twig
- src/bundle/Resources/views/content/modal_location_trash.html.twig
| Tickets       | https://issues.ibexa.co/browse/EZP-31602
| Related to | https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/289
> EZP-31602: Moving to trash confirmation modal is not updated after sub-items bulk move

- src/bundle/Resources/public/js/scripts/fieldType/ezdate.js
- src/bundle/Resources/views/themes/admin/ui/field_type/preview/content_fields.html.twig
| Tickets       | [IBX-300](https://issues.ibexa.co/browse/IBX-300)
Related PR: https://github.com/ezsystems/ezplatform-kernel/pull/181
> IBX-300: removed add offset timezone to date, after changed date field to using timezone with timestamp

- src/bundle/Resources/public/scss/_custom.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-22
| Related to | https://github.com/ezsystems/ezplatform-page-builder/pull/740
> IBX-22: Added danger font color

- src/lib/Pagination/Pagerfanta/URLSearchAdapter.php
| Tickets       | [IBX-340](https://issues.ibexa.co/browse/IBX-340)
See / depends on https://github.com/ezsystems/ezplatform-kernel/pull/180.
**Without it, calling the URL Management page will result in an error (!)**
Should we change the `composer.json` requirements?
> Prevent multiple database count queries when paginating URL lists.
> IBX-340: Prevented multiple count operations when attempting to paginate URL tab

- src/bundle/Resources/public/js/scripts/admin.role_assignment.add.js
- src/bundle/Resources/views/themes/admin/user/role_assignment/create.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-380
> IBX-380: Cannot deselect the subtree in Admin -> Roles

- src/bundle/ui-dev/src/modules/sub-items/components/grid-view/grid.view.item.component.js
- src/bundle/ui-dev/src/modules/sub-items/services/sub.items.service.js
| Tickets       | https://issues.ibexa.co/browse/IBX-354
https://github.com/ezsystems/ezplatform-graphql/pull/101
> IBX-354: Used fullsized thumbnails if svg is provided

- src/lib/Menu/UserMenuBuilder.php
| Tickets       | [EZP-32333](https://jira.ez.no/browse/EZP-32333)
This fragment is not needed here as this menu item is generated in `ezplatform-user` package nevertheless:  https://github.com/ezsystems/ezplatform-user/blob/1.0/src/lib/EventListener/UserMenuListener.php#L49
Related `ezplatform-user` PR: https://github.com/ezsystems/ezplatform-user/pull/92
> EZP-32333: Hidden duplicated 'change password' menu item

- src/lib/UI/Module/ContentTree/NodeFactory.php
| Tickets       | https://issues.ibexa.co/browse/IBX-418
The Tree View in UDW creates a node for the top location, which does not have content (`contentId === 0`).
This fix skips the content name retrieval for this node to avoid errors.
> IBX-418: Skipped content name retrieve for the top node

- src/bundle/Resources/config/default_parameters.yml
- src/bundle/Resources/translations/systeminfo.en.xliff
- src/bundle/Resources/views/admin/systeminfo/invalid.html.twig
| Tickets       | [IBX-385](https://issues.ibexa.co/browse/IBX-385)
| New feature?  | kinda (improvement)
>Currently, whenever composer.json or composer.lock files get accidentally corrupted, the system will return exceptions coming from ez-support-tools (where those files are parsed) which results in the system being unusable. The idea is to show some warnings in:
>- the dashboard,
> - the System Information tab,
> - ez-support-tools:dump-info
>if the composer files are either not accessible or don't contain valid data.
Given, we moved AdminUI part to …
> IBX-385: Fixed error handling when composer files are corrupted

- src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
- src/bundle/Resources/public/scss/_extra-actions.scss
- src/bundle/Resources/public/scss/_general.scss
> IBX-186: The top button of side menus gets hidden at the bottom of the page

- behat_suites.yml
- features/personas/ChangePassword.feature
- src/lib/Behat/BusinessContext/NavigationContext.php
- src/lib/Behat/BusinessContext/UserPreferencesContext.php
- src/lib/Behat/PageObject/ChangePasswordPage.php
- src/lib/Behat/PageObject/PlatformPageObjectFactory.php
| Tickets       | [IBX-405](https://issues.ibexa.co/browse/IBX-405)
| New feature?  | no (new test case)
Admin UI part of the test checking whether the user/password policy works correctly.
Related PRs: 
https://github.com/ezsystems/BehatBundle/pull/183
https://github.com/ezsystems/ezplatform-page-builder/pull/762
Passing AdminUI and PageBuilder tests using different personas job: https://travis-ci.com/github/ezsystems/ezplatform-page-builder/builds/227125137
> [Behat] IBX-405: Behat coverage for changing user password

- src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
| Tickets       | IBX-186
Without it initial height isn't set, only after resizing/scrolling
> IBX-186: The top button of side menus gets hidden at the bottom of the page (mergeup fix)

- composer.json
Fixes issues visible in https://travis-ci.com/github/ezsystems/ezplatform-admin-ui/jobs/510343428 :
tests are failing because Composer downloads incorrect dependencies:
```
- Locking ezsystems/ezplatform-kernel (v1.2.7)
```
where kernel ~1.2.8 is required (it's the first version containing changes from https://github.com/ezsystems/ezplatform-kernel/pull/180).
It's most likely caused by https://github.com/ezsystems/ezplatform-kernel/pull/192 - Composer doesn't know what to do (install Symfony higher than 5.1 and Kernel 1.2.7 or Symfony 5.1.x and Kernel 1.2.8-dev - the first option is chosen).
Bumping the kernel requirement makes Composer choose correctly.
> [Composer] Bumped ezplatform-kernel require to ~1.2.8@dev

- src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/base.js
| Tickets       | [EZP-32387](https://issues.ibexa.co/browse/EZP-32387)
JIRA excerpt:
>When editing a Page Builder, the Rich text inside a Text block is unconfortable to use in certain cases. Sometimes, impossible to use. When you click on align right on the toolbar inside the Text Block, the toolbar aligns itself to the right as well. But the toolbar collapses and a part of it is hidden. Also a scrollbar appears on the bottom of the window, but impossible to scroll.
>Steps to reproduce:
>1. Install a clean version of Ibexa V.3.3
>2. Edit a …
> EZP-32387: Fixed text block toolbar alignment

- src/bundle/Resources/config/universal_discovery_widget.yaml
- src/bundle/Resources/views/themes/admin/content/tab/locations/tab.html.twig
- src/lib/UniversalDiscovery/Event/Subscriber/AddLocation.php
| Tickets       | [IBX-426](https://jira.ez.no/browse/IBX-426)
`Add location` action should not take into account any `content/create` restrictions, it should allow every content to be used as a destination if the user can `content/read` it.
> IBX-426: Created additional UDW config for adding Location to Content

- src/lib/UniversalDiscovery/UniversalDiscoveryProvider.php
| Tickets       | [IBX-455](https://issues.ibexa.co/browse/IBX-455)
> IBX-455: Added selected content from bookmarks to the top of list content items

- src/bundle/Controller/AssetController.php
- src/bundle/Resources/public/js/scripts/fieldType/ezimage.js
- src/bundle/Resources/public/scss/fieldType/edit/_ezimage.scss
- src/bundle/Resources/views/admin/content_type/field_types.html.twig
- src/bundle/Resources/views/fieldtypes/edit/ezimage.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-154
| Doc needed?   | ?
https://github.com/ezsystems/ezplatform-admin-ui/pull/1777 for v2.5
> IBX-154: Allowed to define if the alternative text for image field is required (2.5)

- src/bundle/Resources/public/scss/_custom.scss
(cherry picked from commit c6245ee23cfe8206f9916fe12209d3ef417a433b)
https://issues.ibexa.co/browse/IBX-648
Related to:
https://github.com/ezsystems/ezplatform-page-builder/pull/769
https://github.com/ezsystems/ezplatform-page-fieldtype/pull/185
I have also added colors that were used in the design, but were missing from 2.5 file. Maybe they are already there but under different name but I am not sure if changing the templates to match it is no bigger fuss then adding them here.
> IBX-648: Added styles for backported landing page FT settings

- src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
| Tickets       | https://issues.ibexa.co/browse/IBX-662
> IBX-662: Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null at setContainerHeight

- src/bundle/Templating/Twig/FormatIntervalExtension.php
| Tickets       | [IBX-695](https://issues.ibexa.co/browse/IBX-695)
JMS Translation extractor has to ignore dynamic labels that are translated by Format Interval Extension twig. Otherwise, it will display the error described in the JIRA issue.
> IBX-695: Added ignore to trans id 'interval.format.%s'

- features/personas/AddLocation.feature
- src/lib/Behat/BusinessContext/ContentViewContext.php
- src/lib/Behat/PageElement/ContentTypePicker.php
- src/lib/Behat/PageObject/ContentItemPage.php
| Tickets       | [IBX-579](https://issues.ibexa.co/browse/IBX-579)
| New feature?  | no (new test case)
Admin UI part of the test checking whether user with Content Type limitation on content/create policy can add another location.
Related PRs:
https://github.com/ezsystems/BehatBundle/pull/185
Passing build (first job): https://travis-ci.com/github/ezsystems/ezplatform-page-builder/builds/231129567
> IBX-579: Behat coverage for user with CT limitation adding location

- src/bundle/Resources/encore/ez.js.config.js
- src/bundle/Resources/public/js/scripts/admin.location.adaptive.tabs.js
- src/bundle/Resources/public/js/scripts/core/adaptive.items.js
- src/bundle/Resources/public/js/scripts/core/popup.menu.js
- src/bundle/Resources/public/scss/_popup-menu.scss
- src/bundle/Resources/public/scss/_tabs.scss
- src/bundle/Resources/views/themes/admin/ui/component/popup_menu/popup_menu.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/tab/tabs_header.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/tab/tabs_tab.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-691
| Doc needed?   | ???
Popup menu component.
> IBX-691: As a Developer, I want to have reusable popup menu component

- src/bundle/Resources/public/scss/_buttons.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-587
Buttons on hover, should get darker, not lighter. Changes affect basically only search page.
> IBX-587: There are some inconsistencies in buttons: ez-btn--primary and ez-btn--base-dark

- src/lib/EventListener/CredentialsExpiredListener.php
| Tickets       | https://issues.ibexa.co/browse/IBX-725
`\EzSystems\EzPlatformAdminUi\EventListener\CredentialsExpiredListener::onPreContentView` throws TypeError when view is rendered in CLI env.
> IBX-725: CredentialsExpiredListener makes it impossible to render a content from using CLI

- src/lib/Behat/Page/ContentViewPage.php
- src/lib/Behat/Page/DashboardPage.php
- src/lib/Behat/Page/ObjectStateGroupPage.php
- src/lib/Behat/Page/SectionPage.php
| Tickets       | https://issues.ibexa.co/browse/IBX-264
Adapting the tests for the design changes in master.
For some reason the CSS selectors with `nth-of-type` can't be found, I've switched to others so that tests can pass.
> [Behat] Adapted tests to the redesign

- src/bundle/Resources/public/scss/_inputs.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-763
> IBX-763: Cursor should be in not-allowed state on hover when checkbox is disabled

- src/lib/Behat/Page/ContentViewPage.php
JIRA: https://issues.ibexa.co/browse/IBX-264
Failure:
https://travis-ci.com/github/ezsystems/ezplatform-page-fieldtype/jobs/524392449
```
And I switch to "Submissions" tab in Content structure # Ibexa\AdminUi\Behat\BrowserContext\ContentViewContext::switchTab()
Ibexa\Behat\Browser\Exception\ElementNotFoundException: Could not find element named: 'Submissions'. Found names: Locations instead. css locator 'tab': '#ibexa-tab-label-location-view-locations' in vendor/ezsystems/behatbundle/src/lib/Browser/Element/ElementCollection.php:53
```
The current CSS selector found only one tab, "Locations":
I've switched it to another one which finds all the tabs:
> [Behat] Fixed tab switching in Content View

- features/standard/ContentDraft.feature
https://issues.ibexa.co/browse/IBX-264
Added a `@richtext` tag that will be run in ezsystems/ezplatform-richtext (https://github.com/ezsystems/ezplatform-richtext/pull/197)
As I've changed the Content Item used to Folder during refactoring I've switched it back to Article, which contains a richtext fields that is required and needs to be set.
> [Behat] Changed ContentDraft tests to use article Content Type

- src/bundle/Resources/public/js/alloyeditor/src/toolbars/config/base.js
| Tickets       | [IBX-759](https://issues.ibexa.co/browse/IBX-759)
Followup for https://github.com/ezsystems/ezplatform-richtext/pull/196 targetting eZ Platform 2.5.
> IBX-759: Fixed wrong class taken to calculate toolbar's width

- .travis.yml
JIRA: https://issues.ibexa.co/browse/IBX-264
https://app.travis-ci.com/github/ezsystems/ezplatform-admin-ui/jobs/524369717
```
3 test classes into the queue.
- Will be consumed by 2 parallel Processes.
1/3	✘	2 s 323 ms	/var/www/vendor/ezsystems/behatbundle/features/personas/subtree_editor.feature
2/3	✔	3 s 381 ms	/var/www/vendor/ezsystems/behatbundle/features/personas/add_location.feature
3/3	✔	1 s 341 ms	/var/www/vendor/ezsystems/behatbundle/features/personas/change_password.feature
[2] /var/www/vendor/ezsystems/behatbundle/features/personas/subtree_editor.featureFeature: Editor that has access only to a Subtree of Content Structure
@admin @setup @subtreeEditor
Scenario: Create a Role and assign policies with limitations to it                                          # …
```
> [Behat] Use standard mode for setup phase

- src/lib/Behat/Page/AdminUpdateItemPage.php
https://issues.ibexa.co/browse/IBX-264
https://app.travis-ci.com/github/ezsystems/ezplatform-admin-ui/builds/232829581
Screen:
https://res.cloudinary.com/ezplatformtravis/image/upload/v1626346210/screenshots/60f012e285380609399926-vendor_ezsystems_ezplatform-admin-ui_features_standard_objectstates_feature_23_k4gmwo.png
The value is not always correctly entered into input fields in AdminUI part.
The solution was already present in the previous code:
https://github.com/ezsystems/ezplatform-admin-ui/blob/1.5/src/lib/Behat/PageElement/Fields/DefaultFieldElement.php#L36-L40
I must've removed it during refactoring, trusting that `setValue` is really doing it's job 😄
> IBX-264: [Behat] Fixed entering values in AdminUI forms

- src/lib/Behat/Component/Fields/Date.php
- src/lib/Behat/Component/Fields/DateAndTime.php
- src/lib/Behat/Component/Fields/Time.php
JIRA: https://issues.ibexa.co/browse/IBX-264
https://travis-ci.com/github/ezsystems/ezplatform-workflow/builds/232892471
```
| ezdate               | Date                         |                                                                       | value     | 11/23/2019                                                                |            |                       |         |             | Saturday 23 November 2019 |
Ibexa\Behat\Browser\Exception\TimeoutException: css selector 'dateSet': '.date-set' not found in 1 seconds. in vendor/ezsystems/behatbundle/src/lib/Browser/Element/BaseElement.php:65
Stack trace:
#0 vendor/ezsystems/behatbundle/src/lib/Browser/Element/BaseElement.php(86): Ibexa\Behat\Browser\Element\BaseElement->waitUntil()
#1 …
```
> IBX-264: [Behat] Make sure date picker is loaded before interacting with it.

- behat_suites.yml
- features/standard/Roles.feature
| Tickets       | [IBX-580](https://issues.ibexa.co/browse/IBX-580)
| New feature?  | no (new test case)
Test checking whether it is possible to access a role that has a policy with a location limitation pointing to a location that has been deleted.
> IBX-580: Added deleted location limitation role access scenario

- src/lib/Behat/BrowserContext/NotificationContext.php
- src/lib/Behat/Component/ContentItemAdminPreview.php
- src/lib/Behat/Component/Fields/Authors.php
- src/lib/Behat/Component/Fields/Checkbox.php
- src/lib/Behat/Component/Fields/ContentQuery.php
- src/lib/Behat/Component/Fields/ContentRelationMultiple.php
- src/lib/Behat/Component/Fields/ContentRelationSingle.php
- src/lib/Behat/Component/Fields/Date.php
- src/lib/Behat/Component/Fields/DateAndTime.php
- src/lib/Behat/Component/Fields/FieldTypeComponent.php
- src/lib/Behat/Component/Fields/File.php
- src/lib/Behat/Component/Fields/Image.php
- src/lib/Behat/Component/Fields/ImageAsset.php
- src/lib/Behat/Component/Fields/Keywords.php
- src/lib/Behat/Component/Fields/MapLocation.php
- src/lib/Behat/Component/Fields/Matrix.php
- src/lib/Behat/Component/Fields/Media.php
- src/lib/Behat/Component/Fields/NonEditableField.php
- src/lib/Behat/Component/Fields/RichText.php
- src/lib/Behat/Component/Fields/Selection.php
- src/lib/Behat/Component/Fields/Time.php
- src/lib/Behat/Component/Fields/URL.php
- src/lib/Behat/Component/Fields/User.php
- src/lib/Behat/Page/ContentViewPage.php
| Tickets       | https://issues.ibexa.co/browse/IBX-264
1) Using `assertContains` for string works in PHPUnit 8, but it's deprecated:
https://github.com/sebastianbergmann/phpunit/blob/8.5/src/Framework/Assert.php#L209-L214
changed usages to `assertStringContainsString` where it's applicable.
1) In some classes bad casing was used: `CssLocatorBuilder` instead of `CSSLocatorBuilder`. The class is called `CSSLocatorBuilder`: https://github.com/ezsystems/BehatBundle/blob/master/src/lib/Browser/Locator/CSSLocatorBuilder.php It works, …
> [Behat] Fixed PHPUnit 9 deprecations and class usage casing

- src/lib/Behat/Page/DashboardPage.php
https://issues.ibexa.co/browse/IBX-264
Required by: https://github.com/ezsystems/ezplatform-workflow/pull/197
Adjusting Dashboard tab locator:
on v3 it can be used to select Dashboard tabs:
But on v4 it has to be changed:
> [Behat] Adjusted tab CSS selector on the Dashboard

- src/bundle/Resources/public/scss/_general.scss
Example failure: https://travis-ci.com/github/ezsystems/ezplatform-form-builder/jobs/524856789
```
Examples:
| label             | value        | expectedSubmissionCount |
| Single line input | test value 1 | 1                       |
Exception: element click intercepted: Element <a href="#" data-toggle="modal" data-target="#submission-details-modal" data-submission-values="
<tr class='ez-table__row'>
<td class='ez-table__cell'>
Single line input
</td>
<td class='ez-table__cell'>
test value 1
</td>
</tr>
" class="btn ibexa-btn ibexa-btn--ghost ibexa-btn--no-text ibexa-btn--content-submission-view mx-3" title="" data-original-title="View submission">...</a> is not clickable at point (1340, 425). Other element would receive the click: <button class="ibexa-btn--udw-copy-subtree btn ibexa-btn …
```
> Temporary fix content position by added right margin, needed for tests

- src/lib/Behat/Component/DateAndTimePopup.php
| Tickets       |  https://issues.ibexa.co/browse/IBX-264
| Bug fix?      | yes?
https://app.travis-ci.com/ezsystems/ezplatform-page-builder/builds/233099716?utm_source=slack&utm_medium=notification
```
| ezdate               | Date                         |                                                                       | value     | 11/23/2019                                                                |            |                       |         |             | Saturday 23 November 2019 | …
```
> [Behat] Changed flatpickr locator to a more specific one

- src/lib/Behat/Component/DateAndTimePopup.php
- src/lib/Behat/Component/Fields/Date.php
- src/lib/Behat/Component/Fields/DateAndTime.php
- src/lib/Behat/Component/Fields/Time.php
| Tickets       | https://issues.ibexa.co/browse/IBX-264
| Tests pass?   | yes 🎉 
Reverting the change from https://github.com/ezsystems/ezplatform-admin-ui/pull/1820, as the `active` class is not present when the datepicker is inlined, for example when using Publish Later:
This time the solution is different:
1) We set the parent locator so that the tests interact with the correct date picker input
2) We use JS to get the CSS classes that are related to our input field and based on that we detect if it's a time only calendar (we can't use the current solution …
> [Behat] Fixed inline date picker interactions

- src/lib/Behat/Page/ContentTypeUpdatePage.php
Follow up to https://github.com/ezsystems/ezplatform-admin-ui/pull/1825 and https://github.com/ezsystems/ezplatform-admin-ui/pull/1819 - the selectors were changed https://github.com/ezsystems/ezplatform-admin-ui/pull/1825 and need to be adjusted for the tests to pass.
Failing build:
https://travis-ci.com/github/ezsystems/ezplatform-admin-ui/jobs/527374810
```
And I set "Name" to "Country field" for "Country" field                      # Ibexa\AdminUi\Behat\BrowserContext\ContentTypeContext::iSetFieldDefinitionData()
WebDriver\Exception\JavaScriptError: javascript error: Cannot read property 'click' of null
(Session info: chrome=90.0.4430.85)
```
> [Behat] Adjusted selectors to redesign

- src/bundle/Resources/views/parts/menu/top_menu_2nd_level.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-375
When working on IBX-375 we noticed there is a problem with 2nd level menu. Even though you set `extras.routes` on first level element and it matches, the second level menu won't be displayed unless there is a match on a child. In some cases you still want to display 2nd level menu, for example Page Builder submenu when there is no siteaccess match.
> IBX-375: Fixed setting 2nd menu level active

- src/lib/Behat/Component/Fields/RichText.php
| Tickets       | https://issues.ibexa.co/browse/IBX-93
Failing build:
https://travis-ci.com/github/ezsystems/ezplatform-page-builder/builds/233724638
You can see that this job fails:
https://travis-ci.com/github/ezsystems/ezplatform-page-builder/jobs/527021180
but this job passes:
https://travis-ci.com/github/ezsystems/ezplatform-page-builder/jobs/527021181
Even though they both include the same test (TextBlock test in Blocks.feature).
The difference is in setups: the second job has none related to Richtext, but the first one adds a custom …
> IBX-93: [Behat] Fixed calculating Richtext button positions

- src/bundle/Resources/public/scss/_inputs.scss
- src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-614
| Doc needed?   | ???
Textarea redesign.
> IBX-614: As an Editor, I want to see redesigned text area in all states

- src/bundle/Resources/config/default_parameters.yaml
- src/bundle/Resources/config/services/modules/content_tree.yaml
- src/lib/UI/Module/ContentTree/NodeFactory.php
Jira's issue: https://issues.ibexa.co/browse/IBX-704
requires: 
https://github.com/ezsystems/ezplatform-kernel/pull/215
https://github.com/ezsystems/ezplatform-solr-search-engine/pull/215
Children counts call to Solr can create an overhead for `load-subtree` calls. 
This PR adds Aggregation support for `NodeFactory` to speed it up when supported.
> IBX-704: Added aggregation support to NodeFactory

- src/lib/Behat/Component/Fields/RichText.php
| Tickets       | https://issues.ibexa.co/browse/IBX-93
Similar as in https://github.com/ezsystems/ezplatform-admin-ui/pull/1829, using standard Selenium actions fails when interacting with CKEditor - it's not stable enough.
```
And I set up block "Text" "Text" with default testing configuration                                                                # Ibexa\PageBuilder\Tests\Behat\Context\PageBuilderContext::addBlockWithDefaultTestingConfiguration()
Ibexa\Behat\Browser\Exception\ElementNotFoundException: Collection …
```
> IBX-93: [Behat] Switched to JS script for invoking CKEditor toolbar

- src/bundle/Resources/public/js/scripts/fieldType/base/base-field.js
- src/bundle/Resources/public/js/scripts/fieldType/base/base-preview-field.js
- src/bundle/Resources/public/js/scripts/fieldType/ezurl.js
- src/bundle/Resources/public/scss/_forms.scss
- src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
- src/bundle/Resources/public/scss/fieldType/edit/_ezurl.scss
- src/bundle/Resources/views/themes/admin/content/form_fields.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-644
> IBX-644: URL Field Type redesign

- src/lib/Behat/Page/RolesPage.php
JIRA: https://issues.ibexa.co/browse/IBX-835
This PR improves stability of Roles.feature tests; it seems that during role deletion behat is unable to select policy which is meant to be deleted. This policy, due to behat constraints (size of window in which tests are performed) is not visible on screen; to mitigate this problem mouseOver() function will be used. The idea is that by scrolling down it will be possible to see the desirable policy.
```
When I delete Role "Test Role edited"                               # Ibexa\AdminUi\Behat\BrowserContext\RolesContext::deleteRoleNamed()
Exception: element click intercepted: Element is not clickable at point (344, 994)
```
> [Behat] Fixed test stability during role deletion

- src/lib/Behat/Page/ContentTypeGroupPage.php
JIRA: https://issues.ibexa.co/browse/IBX-835
Similar PR: https://github.com/ezsystems/ezplatform-admin-ui/pull/1863
This PR improves tests stability during deletion of content type. MouseOver() function is used to scroll down so a certain element may be visible.
> [Behat] Fixed test stability during deletion of content type

- src/bundle/Resources/public/scss/_alerts.scss
- src/bundle/Resources/public/scss/_icons.scss
- src/bundle/Resources/views/themes/admin/account/settings/update_datetime_format.html.twig
- src/bundle/Resources/views/themes/admin/content/location_view.html.twig
- src/bundle/Resources/views/themes/admin/content/relation_unauthorized.html.twig
- src/bundle/Resources/views/themes/admin/content_type/part/nontranslatable_fields_disabled.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/alert/alert.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/preview_unavailable.html.twig
- src/bundle/Resources/views/themes/admin/ui/field_type/preview/content_fields.html.twig
- src/bundle/Resources/views/themes/admin/url_wildcard/list.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-901
- https://github.com/ezsystems/date-based-publisher/pull/237
- https://github.com/ezsystems/ezcommerce-admin-ui/pull/101
- https://github.com/ezsystems/ezplatform-page-builder/pull/819
- https://github.com/ezsystems/ezplatform-site-factory/pull/136
- https://github.com/ezsystems/ezplatform-version-comparison/pull/63
- https://github.com/ezsystems/ezplatform-icons/pull/10
Now we have a new twig template
```twig
{% include '@ezdesign/ui/component/alert/alert.html.twig' with {
type: …
```
> IBX-901: As an Editor, I want to see redesigned alerts

- src/bundle/Resources/views/themes/admin/content/location_view.html.twig
It's probably merge conflict resolving issue.
https://github.com/ezsystems/ezplatform-admin-ui/blob/dcec45ad8cb9e7e875db3276d6ae47222a54858a/src/bundle/Resources/views/themes/admin/content/location_view.html.twig#L95-L106
> Fixed wrong enclosing tag in location_view.html.twig

- src/bundle/Resources/public/js/scripts/admin.context.menu.js
| Tickets       | https://issues.ibexa.co/browse/IBX-939
Fixing js error when context menu does not have 'more' button
> IBX-939: Create attribute groups list for prodcut catalog

- src/bundle/Controller/ContentEditController.php
- src/bundle/Resources/config/routing.yaml
- src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
- src/lib/Event/CancelEditVersionDraftEvent.php
| Tickets       | https://issues.ibexa.co/browse/IBX-431
There cancel button (`X`) was a plain link and it was not possible to intercept and react to the action on the backend side.
> IBX-431: Allowed interception of canceling the draft version edit

- src/lib/Behat/Component/Fields/RichText.php
Test failure:
```
| TextBlock             | Text              |
Notice: Undefined offset: 2 in vendor/ezsystems/ezplatform-admin-ui/src/lib/Behat/Component/Fields/RichText.php line 109
```
Somewhere during the redesign the default layout of CKEditor widget changed. It used to look like this:
(the unordered list button is visible all the time).
Now it looks like this:
The buttons previously visible are now available only after the additional menu is expanded.
I've:
1) fixed adding unordere lists
2) adjusted the Embed …
> [Behat] Fixed Richtext button positions after widget redesign

- src/lib/Behat/Component/UserNotificationPopup.php
Example error on Travis:
https://app.travis-ci.com/ezsystems/ezplatform-workflow/builds/236969700?utm_source=slack&utm_medium=notification
```
And I go to user notification with details:                                       # Ibexa\AdminUi\Behat\BrowserContext\UserNotificationContext::iGoToUserNotificationWithDetails()
| Type                   | Description                               |
| Content review request | From: Creator Workflow Please have a look |
Notice: Undefined variable: type in …
```
> [Behat] Corrected error message for missing user notification

- src/bundle/Controller/TranslationController.php
- src/bundle/Resources/config/routing.yml
| Tickets       | [IBX-862](https://issues.ibexa.co/browse/IBX-862)
The `locationId`  parameter has been added to translate action in order for redirect after the translation to work properly.
> IBX-862: Fixed translation action originating from non-main Location

- src/bundle/Resources/public/js/scripts/admin.contenttype.relation.default.location.js
- src/bundle/Resources/translations/ezrepoforms_content_type.en.xliff
- src/bundle/Resources/views/admin/content_type/field_types.html.twig
| Tickets       | [IBX-808](https://issues.ibexa.co/browse/IBX-808)
| Bugfix?      | no
| Improvement? | yes
Excerpt from JIRA:
>Currently, after selecting "Starting Location" in ezobjectrelation settings, there is no way to reset it. This might get problematic when, for some reason, the initial content is not visible in UDW due to tree_root parameter usage or associated user permissions.
> IBX-808: As an Editor, I want to be able to reset starting location for ezobjectrelation FieldType

- src/bundle/Resources/public/scss/_dashboard.scss
- src/bundle/Resources/public/scss/_general.scss
- src/bundle/Resources/public/scss/_main-container.scss
- src/bundle/Resources/public/scss/ui/modules/sub-items-list/_grid.view.item.scss
- src/bundle/Resources/views/themes/admin/content/modal/draft_conflict.html.twig
- src/bundle/Resources/views/themes/admin/content/tab/versions/table.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/table/table.html.twig
- src/lib/Behat/Page/ObjectStateGroupPage.php
- src/lib/Behat/Page/SectionPage.php
| Tickets       | https://issues.ibexa.co/browse/IBX-963
https://github.com/ezsystems/ezplatform-page-builder/pull/827
> IBX-963: Buttons on Trash page are hidden on medium resolutions

- composer.json
- src/bundle/Controller/ContentOnTheFlyController.php
| Tickets       | https://issues.ibexa.co/browse/IBX-902
Fixed field groups in content on the fly edit
requires: https://github.com/ezsystems/ezplatform-content-forms/pull/46
> IBX-902: Fixed field groups in content on the fly edit

- src/bundle/Resources/encore/ez.js.config.js
- src/bundle/Resources/public/js/scripts/helpers/cookies.helper.js
- src/bundle/Resources/public/js/scripts/sidebar/main.menu.js
- src/bundle/Resources/public/scss/_main-menu.scss
- src/bundle/Resources/views/themes/admin/ui/menu/main_2nd_level.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-976
> IBX-976: Disabled transition for side menu after reload page

- features/standard/ContentTypeFields.feature
- src/bundle/Resources/public/js/scripts/admin.input.text.js
- src/bundle/Resources/public/js/scripts/core/dropdown.js
- src/bundle/Resources/public/scss/_dropdown.scss
- src/bundle/Resources/public/scss/_inputs.scss
- src/bundle/Resources/views/themes/admin/ui/component/dropdown.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/dropdown_item.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/input_text.html.twig
- src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-967
> IBX-967: As an Editor, I want to filter Dropdown items

- src/bundle/Controller/ContentViewController.php
- src/lib/Form/Type/ChoiceList/Loader/ContentEditTranslationChoiceLoader.php
- src/lib/Form/Type/Content/Translation/TranslationAddType.php
| Tickets       | [IBX-952](https://issues.ibexa.co/browse/IBX-952)
We should consider the `Location` we are actually in to load the required languages as the user might not have access to main `Location` but have access to secondary one.
Related `ezplatform-page-builder` PR: https://github.com/ezsystems/ezplatform-page-builder/pull/826.
> IBX-952: Added chosen Location to Translation Choice form

- src/bundle/Resources/public/js/scripts/sidebar/main.menu.js
| Tickets       | https://issues.ibexa.co/browse/IBX-1011
> IBX-1011: Fixing hide all tooltip after click in side menu

- src/bundle/Resources/views/themes/admin/content/edit/base.html.twig
- src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-954
Also makes `close_button` extensible.
> IBX-954: Fixed missing Close button redirection to cancel action

- src/bundle/Resources/public/js/scripts/fieldType/ezdate.js
| Tickets       | [IBX-964](https://issues.ibexa.co/browse/IBX-964)
| Doc needed?   |/no
> IBX-964: Added offset to timestamp

- .github/workflows/pr_check.yaml
| Tickets       | https://issues.ibexa.co/browse/IBX-754
| New feature?  | yes (CI)
This PR adds a new Github Action that verifies base branch for Pull Request for PHP packages.
1) I've decided to base this solution on the `branch-alias` property in composer.json, which exists in every branch in our packages and has a different value for each stable branch. 
2) At first I've experiemented with using the `checkout` action to get the file contents, but then I've decided it's better to get a single file instead of performing a (shallow) clone of the whole repo
3) …
> [CI] Added job for wrong target branch detection

- composer.json
- phpunit.xml
- tests/lib/REST/Input/ContentType/FieldDefinitionCreateTest.php
- tests/lib/REST/Input/ContentType/FieldDefinitionDeleteTest.php
- tests/lib/REST/Input/ContentType/FieldDefinitionReorderTest.php
Fixes wrong PHP namespace added in #1835.
> Fixed issues in test PHP namespace

- src/bundle/Resources/views/themes/admin/content/widget/content_create.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1023
> IBX-1023: Fixed instant filter input styles

- src/bundle/Resources/config/services/forms.yaml
| Tickets       | IBX-792
| Tests pass?   | ~yes/no~
Attempts to fix an issue that occurs irregularly, causing failure to compile service container due to loading of a new class (with new namespace) via `resource` declaration.
Error reported:
```
In FileLoader.php line 174:
Expected to find class "EzSystems\EzPlatformAdminUi\Form\Type\ContentType\FieldDefinitionsCollectionType" in file "/var/www/vendor/ezsystems/ezplatform-admin-ui/src/lib/Form/Type/ContentType/FieldDefinitionsCollectionType.php" while importing services from resource "../../../lib/Form/Type", …
```
> IBX-792: Fixed class using new namespace registered via resource

- src/lib/Behat/Component/Table/Table.php
This is a companion PR for https://github.com/ezsystems/BehatBundle/pull/212
Relying on exceptions to control flow of the application is a bad practice, in this case it stops us from using interactive debug in places where this code is used (it's detected as an error and interactive session kicks in).
This code works the same way, but does not rely on exceptions.
> [Behat] Removed logic based on exceptions in Table searching

- src/bundle/Resources/translations/content_type.en.xliff
- src/bundle/Resources/views/themes/admin/content_type/tab/view.html.twig
| Tests pass?   | N/A
Fixing a small typo in the expiation text below "Make content available even with missing translations" when viewing a content type: "avalable" replaced by "available".
> Fix "avalable" to "available"

- src/lib/Behat/BrowserContext/ContentTypeContext.php
- src/lib/Behat/Component/IbexaDropdown.php
- src/lib/Behat/Page/ContentTypeUpdatePage.php
There are two issues happening on Travis right now:
1) Commit: https://github.com/ezsystems/ezplatform-admin-ui/pull/2000/commits/f6a49b264c96a6496539cb3aaf86a7b873c9cc34
```
When I check "video" block in ezlandingpage field blocks section                                     # Ibexa\AdminUi\Behat\BrowserContext\ContentTypeContext::iCheckBlockInField()
Ibexa\Behat\Browser\Exception\TimeoutException: Transition has not started at all for element with CSS locator 'fieldDefinitionToggle': '.ibexa-collapse:nth-last-child(2) > div.ibexa-collapse__header > button:last-child:not([data-bs-target="#content_collapse"])'. Please make sure the condition is used on the correct element. Timeout value: 5 seconds. in vendor/ezsystems/behatbundle/src/lib/Browser/Element/BaseElement.php:59
Stack trace:
#0 …
```
> [Behat] Stability fixes

- src/lib/Behat/BusinessContext/AdminUpdateContext.php
- src/lib/Behat/PageElement/AdminUpdateForm.php
JIRA: https://issues.ibexa.co/browse/IBX-1289
Related PR: https://github.com/ezsystems/ezplatform-page-builder/pull/904
This is the backport of https://issues.ibexa.co/browse/IBX-1070 & https://issues.ibexa.co/browse/IBX-671.
> [Behat] IBX-1289 admin-ui backport
